define([], function () {
  return {
  "PropertyPaneDescription": "الوصف",
  "BasicGroupName": "اسم المجموعة",
  "DescriptionFieldLabel": "حقل الوصف",
  "SaveButton": "حفظ",
  "BackButton": "رجوع",
  "GetStartedLabel": "بدء الاستخدام",
  "AdminToolsLabel": "أدوات المسؤول",
  "ChampionLeaderBoardLabel": "لوحة المتصدرين للرواد",
  "AddMemberLabel": "إضافة عضو",
  "NominateMemberLabel": "ترشيح عضو",
  "DigitalBadgeLabel": "شارة رقمية",
  "TOTLabel": "دورة ألعاب الفِرق",
  "ChampionListLabel": "قائمة الرواد",
  "EventsListLabel": "قائمة الأحداث",
  "AdminTasksLabel": "مهام المسؤول",
  "ManageDigitalBadgesLabel": "إدارة الشارات الرقمية",
  "EnableTOTLabel": "تشغيل دورة ألعاب الفِرق",
  "AddMembersToolTip": "بدء إضافة الأعضاء بإضافة الأشخاص الذين ستتعاون معهم في...",
  "DigitalMembersToolTip": "الحصول على شارتك الرقمية واستخدامها على صورة ملف التعريف الخاص بك",
  "ChampionsListToolTip": "الوصول إلى قائمة الرواد",
  "EventsListToolTip": "الوصول إلى قائمة الأحداث",
  "EnableTOTToolTip": "تشغيل دورة ألعاب الفِرق",
  "ManageDigitalBadgesToolTip": "إدارة الشارات الرقمية",
  "WelcomeLabel": "مرحباً",
  "ManageAppLogoLabel": "إدارة شعار التطبيق",
  "ManageAppLogoToolTip": "إدارة شعار التطبيق",
  "AppLogoToolTip": "الصفحة الرئيسية",
  "MoreInfoToolTip": "مزيد من المعلومات",
  "SupportToolTip": "دعم",
  "FeedbackToolTip": "ملاحظات",
  "AdditionalResourcesHeaderLabel": "موارد إضافية:",
  "AdditionalResourcesContentLabel": "تركز مجموعة Microsoft Teams Customer Advocacy على تقديم حلول مثل تلك لتلهمك وتساعدك على تحقيق أهدافك. تابع وانضم من خلال هذه الموارد الأخرى لمعرفة المزيد منا ومن المجتمع:",
  "M365ChampionCommunityLinkLabel": "مجتمع رواد Microsoft 365",
  "DrivingAdoptionLinkLabel": "استخدام القيادة في Microsoft Technical Community",
  "CurrentVersionLabel": "الإصدار الحالي:",
  "LatestVersionLabel": "أحدث إصدار:",
  "CMPGitHubLinkLabel": "GitHub",
  "VisitLabel": "تفضل بزيارة صفحات النظام الأساسي لإدارة الرواد لمعرفة المزيد:",
  "OverviewLabel": "نظرة عامة ومعلومات حول",
  "MSAdoptionHubLinkLabel": "مركز اعتماد Microsoft",
  "DocumentationLabel": "الوثائق التقنية للحل والنظرة العامة المعمارية على",
  "AddMemberPageTitle": "إضافة عضو",
  "NominateMemberPageTitle": "ترشيح عضو",
  "PeoplePickerPlaceholder": "لإضافة عضو، الرجاء كتابة اسم العضو",
  "FocusAreaPlaceholder": "تحديد منطقة التركيز",
  "UserExistingMessage": "المستخدم رائد بالفعل!",
  "ChampionsListPageTitle": "قائمة الرواد",
  "UserNominatedMessage": "تم ترشيح المستخدم بنجاح!",
  "UserAddedMessage": "تمت إضافة المستخدم بنجاح!",
  "PeopleNameGridHeader": "اسم العضو",
  "SelectChampion": "تحديد الرائد",
  "SelectAll": "تحديد كل الرواد",
  "FocusAreaGridHeader": "منطقة التركيز",
  "CountryGridHeader": "البلد",
  "RegionLabel": "المنطقة",
  "StatusGridHeader": "الحالة",
  "ActionGridHeader": "إجراء",
  "ApproveButton": "موافقة",
  "RejectButton": "رفض",
  "NoChampionsMessage": "لا توجد طلبات معلقة في الوقت الحالي",
  "ChampionApprovedMessage": "تمت الموافقة على طلب (طلبات) الرائد.",
  "ChampionRejectedMessage": "تم رفض طلب (طلبات) الرائد.",
  "ProcessingSpinnerLabel": "تتمّ الآن المعالجة...",
  "DigitalBadgePageTitle": "شارة رقمية",
  "LoadingSpinnerLabel": "يتم الآن التحميل...",
  "LoadingDigitalBadgeLabel": "تحميل إطار الشارة الرقمية",
  "DigitalBadgeAppBannerAltText": "مشاركة أعضاء فريق Microsoft في مناقشة",
  "GroupGridHeader": "مجموعة",
  "ShowHideToggle": "إظهار/إخفاء حقول قائمة الأعضاء",
  "ToggleView": "تبديل",
  "SelectedFocusAreaLabel": "تم تحديد منطقة التركيز",
  "PreAcceptPageTitle": "المطالبة بالشارة الرقمية.",
  "PreAcceptDisclaimer": "<h2><span style='font-weight:bold;'>مرحباً بك في الأداة المساعدة للشارات الرقمية</span></h2>",
  "PreAcceptDisclaimer1": "كجزء من عضويتك في برنامج الأبطال، لقد حصلت على شارة رقمية! ستمكنك هذه الأداة المساعدة من \"<em>المطالبة</em>\" بشارتك الرقمية من خلال وضعها فوق صورة ملفك الشخصي الحالية.",
  "PreAcceptDisclaimer2": "يرجى ملاحظة أن هذا سيؤدي إلى تحديث صورة ملف التعريف الخاص بك عبر جميع Microsoft 365 (Exchange وTeams وSharePoint وما إلى ذلك).",
  "PreAcceptDisclaimer3": "إذا أردت، <span style='font-weight:bold'>ستتوفر لديك فرصة 'حفظ' نسخة من صورة ملف التعريف الموجودة الخاصة بك</span> بدون تراكب الشارة الرقمية في الخطوات التالية. الرجاء النقر فوق 'قبول' للمتابعة (قد ترى نافذة منبثقة مفتوحة ومطالبة بتسجيل الدخول).",
  "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>مرحبًا بك في الأداة المساعدة للشارة الرقمية</span>. كجزء من عضويتك في برنامج الرواد، يمكنك الحصول على شارة رقمية. ستمكنك هذه الأداة المساعدة من \"<em>المطالبة</em>\" بشاراتك الرقمية عن طريق تراكبها أعلى صورة ملف التعريف الموجودة. الرجاء ملاحظة أن هذا سيؤدي إلى تحديث صورة ملف التعريف الخاص بك عبر جميع Microsoft 365 (Exchange وTeams وSharePoint وغيرها)",
  "HowtoGetDigitalBadgeText": "كيفية الحصول على شارة الرائد",
  "MultipleBadgeMessage": "حدد شارة من القائمة أدناه. سيتم تطبيق الشارة المحددة على صورة ملف التعريف الخاص بك.",
  "NoBadgeMessage": "لم يتم العثور على شارات لك لتحديدها. الرجاء التحقق مع مسؤول التطبيق لديك.",
  "DigitalBadgeSubPageTitle": "إليك كيف ستبدو شارتك الرقمية!",
  "ProfileImageAlt": "صورة ملف التعريف الخاص بي المستخدمة عبر O365 وTeams وما إلى ذلك",
  "BadgeImageAlt": "جائزة على شكل ميدالية مع الحرف C في المنتصف تشير إلى أنني جزء من برنامج الرواد",
  "NoProfileImageAlt": "صورة ظلية لشخص ما، تشير إلى عدم استخدام صورة لملف التعريف حالياً على حسابك",
  "ApplyButtonText": "استخدام الصورة",
  "ApplyButtonAriaDescription": "بالنقر فوق هذا الزر، فإنك تمنح جزء الويب الخاص ببرنامج الرواد الإذن لتحديث صورة ملف التعريف نيابة عنك.",
  "ApplyButton": "تطبيق",
  "DownloadButtonText": "تنزيل",
  "DownloadButtonAriaDescription": "انقر لتنزيل صورة ملف التعريف الحالية الخاصة بك",
  "DownloadingButtonText": "يتم الآن التنزيل...",
  "DownloadedButtonText": "تم التنزيل",
  "DownloadedButtonSecondaryText": "يمكن العثور على صورة ملف التعريف الخاصة بك التي تم تنزيلها في مجلد التنزيلات الخاص بجهازك.",
  "DownloadButtonSecondaryText": "تنزيل صورة ملف التعريف الحالية",
  "PreApplyDisclaimer": "هذه معاينة لصورة ملف التعريف الجديدة بما في ذلك الشارة الرقمية. إذا كنت ترغب في تنزيل صورة ملف التعريف الحالية الخاصة بك قبل تطبيق الشارة الرقمية، فانقر فوق الرابط '<strong>تنزيل صورة ملف التعريف الحالية الخاصة بك</strong>'.",
  "PreApplyDisclaimer1": "سيؤدي النقر فوق \"تطبيق الصورة\" إلى تحديث صورة ملفك الشخصي في Microsoft 365 بهذه الصورة الجديدة. <strong>الرجاء ملاحظة أن هذا سيؤدي إلى تحديث صورة ملف التعريف الخاص بك عبر كافة Microsoft 365 ويتعذر إرجاعه من خلال هذه الصفحة</strong>.",
  "PreApplyDisclaimer2": "إذا كنت ترغب في تغيير الصورة مرة أخرى، يمكنك استخدام <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' id='linkToChangeProfileImage'>تطبيق Outlook على ويب</a>.",
  "NoProfileImageDescription": "إذا قمت بالفعل بإقران صورة بملف التعريف الخاص بك، ولا تزال ترى هذه الرسالة، فقد لا تكون صورتك متوفرة حتى الآن. الرجاء المحاولة مرة أخرى لاحقاً، أو الاتصال بمكتب المساعدة <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>helpdesk</a> في حالة استمرار عدم ظهورها بعد 24 ساعة.",
  "AcceptButtonText": "قبول",
  "AcceptButtonAriaDescription": "بالنقر فوق هذا الزر، فإنك تمنح جزء الويب الخاص ببرنامج الرواد الإذن لتحديث صورة ملف التعريف نيابة عنك.",
  "UnauthorizedText": "أنت غير مؤهل لبرنامج شارة الرائد في الوقت الحالي",
  "ApplySpinnerLabel": "يتم الآن استخدام صورة ملف تعريف جديدة على حسابك...",
  "DigitalBadgeSuccessMessage": "<strong>تهانينا!</strong> لقد نجحت في المطالبة بالشارة الرقمية الخاصة بك وتم تحديث صورة ملف التعريف الخاص بك. الرجاء الانتظار حتى 24 ساعة لرؤية التحديث منعكساً على جميع تطبيقات Microsoft 365 (بما في ذلك Teams).",
  "BadgePointsTooltip": "النقاط المطلوبة لإلغاء التأمين:",
  "CMPSideBarPointsLabel": "نقاط",
  "CMPSideBarGlobalRankLabel": "تصنيف عمومي",
  "CMPSideBarChampionsLabel": "الرواد",
  "FirstNameLabel": "الاسم الأول",
  "LastNameLabel": "الاسم الأخير",
  "EmailIDLabel": "معرّف البريد الإلكتروني",
  "BecomeChampionLabel": "كن رائداً",
  "ChampionSubmissionPendingLabel": "عمليات إرسال الرائد معلقة",
  "ChampionRequestSubmitSuccessMessage": "تم إرسال طلب الرائد بنجاح",
  "PivotHeaderGlobal": "عالمي",
  "PivotHeaderNearMe": "بالقرب مني",
  "PivotHeaderBySpeciality": "حسب الاختصاص",
  "NearMePlaceHolder": "تحديد بالقرب مني",
  "BySpecialityPlaceHolder": "تحديد حسب الاختصاص",
  "TopChampionsLabel": "أهم الرواد",
  "RecordsNotFound": "لم يتم العثور على السجلات",
  "EventTypeLabel": "نوع الحدث",
  "CountLabel": "عدد",
  "MyRankLabel": "تصنيفي",
  "SelectDate": "تحديد تاريخ",
  "NotesPlaceholder": "200 حرف كحد أقصى",
  "EventSubmissionPendingMessage": "تم إرسال الحدث (الأحداث) للحصول على الموافقة. سيتم منح النقاط بمجرد الموافقة على الحدث (الأحداث).",
  "EventsSubmissionSuccessMessage": "تم تسجيل الحدث (الأحداث) بنجاح.",
  "ViewDashBoardLabel": "عرض لوحة المعلومات",
  "DateofEventGridLabel": "تاريخ الحدث",
  "EventTypeGridLabel": "نوع",
  "RecordEventLabel": "تسجيل حدث",
  "MonthAndDateLabel": "الشهر والتاريخ",
  "EventTypeGridLabelPlaceHolder": "تحديد نوع الحدث",
  "EventTypeValidationMessage": "الرجاء تحديد نوع الحدث!",
  "CountValidationMessage": "يجب أن يكون العدد بين 1 و5",
  "EventsSubmitMessage": "عند الانتهاء من إضافة الأحداث، الرجاء النقر فوق الزر \"إرسال\" للحفظ.",
  "SubmitButton": "إرسال",
  "SearchLabel": "البحث عن أفضل الأبطال",
  "ActivitiesLabel": "أنشطة",
  "FocusAreaLabel": "منطقة التركيز",
  "ShowMoreLabel": "إظهار أكثر",
  "ViewActivitiesLabel": "إظهار الأنشطة",
  "ChatIconLabel": "دردشة",
  "RequestToCallLabel": "جدولة المزامنة",
  "EmailIconLabel": "إرسال بريد إلكتروني",
  "MeetupSubject": "1:1 (طلب الرائد)",
  "MeetupBody": "تخصيص بعض الوقت لمناقشة منطقة الرائد الخاصة بك والتعرف على المزيد!",
  "NoActivitiesinGridLabel": "لم يتم العثور على أي أنشطة!",
  "CreateTournamentPageTitle": "إنشاء دورة ألعاب",
  "CreateTournamentSuccessLabel": "تم إنشاء دورة الألعاب بنجاح.",
  "TournamentNameLabel": "اسم دورة الألعاب",
  "TournamentNamePlaceHolderLabel": "اسم دورة الألعاب (255 حرفاً كحد أقصى)",
  "TournamentNameErrorLabel": "اسم دورة الألعاب مطلوب.",
  "TournamentDescriptionLabel": "وصف دورة الألعاب",
  "TournamentDescPlaceHolderLabel": "وصف دورة الألعاب (500 حرف كحد أقصى)",
  "SelectTeamsActionsLabel": "تحديد إجراءات Teams:",
  "TeamsActionInfoToolTip": "حدد من إجراءات Teams المتوفرة أدناه لتضمينها في دورة الألعاب الجديدة. لإضافة إجراءات دورة ألعاب جديدة للاختيار من بينها، تفضل بزيارة إدارة إجراءات دورة الألعاب من أدوات المسؤول.",
  "ActionErrorLabel": "حدد إجراءً واحداً على الأقل لإنشاء دورة ألعاب.",
  "CreateTournamentButton": "إنشاء دورة ألعاب",
  "DuplicateTournamentNameError": "اسم دورة الألعاب موجود بالفعل. أدخل اسمًا آخر لدورة الألعاب.",
  "CreateTournamentsButton": "إنشاء دورات ألعاب",
  "SingleTournamentLabel": "دورة ألعاب فردية",
  "MultipleTournamentLabel": "دورات ألعاب متعددة",
  "MultiTournamentStep": "خطوة",
  "MultiTournamentStep1LinkLabel": "تنزيل القالب",
  "MultiTournamentStep1Text": "من نموذج تنسيق الملف",
  "MultiTournamentStep2": "أضف تفاصيل دورة الألعاب إلى الملف باتباع الإرشادات التالية",
  "MultiTournamentStep3": "تحميل الملف",
  "UploadFileButton": "تحميل ملف",
  "RemoveFileLabel": "إزالة ملف",
  "ImportSpinnerMessage": "يتم الآن إنشاء دورات ألعاب.....",
  "ErrorMsgTournamentList": "حدث خطأ أثناء إنشاء عنصر في قائمة دورات الألعاب. قم بتصحيح البيانات وحاول مرة أخرى.",
  "ErrorMsgActionsList": "حدث خطأ أثناء إنشاء عنصر في قائمة الإجراءات. قم بتصحيح البيانات وحاول مرة أخرى.",
  "ErrorMsgTournamentActionsList": "حدث خطأ أثناء إنشاء عنصر في قائمة إجراءات دورة الألعاب. قم بتصحيح البيانات وحاول مرة أخرى.",
  "LogMsgTournamentExists": "تم التخطي، بما أن دورة الألعاب",
  "LogMsgTournamentExists1": "موجودة بالفعل.",
  "LogMsgDone": "دورة ألعاب",
  "LogMsgDone1": "تم الإنشاء.",
  "LogMsgInvalidTournamentName": "تم التخطي، نظراً لأنه لا يحتوي على اسم دورة ألعاب صالح.",
  "LogMsgInvalidTemplate": "تم التخطي لأنه قالب غير صالح.",
  "LogMsgMultipleTournaments": "تم التخطي، نظراً لوجود أكثر من اسم واحد لدورة الألعاب.",
  "LogMsgBlankSheet": "تم التخطي، نظرا لأنه فارغ.",
  "LogProgress": " فيما يلي التقدم:",
  "ImportRule1": "عدم تعديل رؤوس الأعمدة في القالب",
  "ImportRule2": "عدم حذف الأعمدة الموجودة في القالب",
  "ImportRule3": "أدخل البيانات في جميع الأعمدة المطلوبة (*) المذكورة في القالب",
  "ImportRule4": "اتبع حد ونوع الأحرف المذكورين في القالب لكل عمود",
  "ImportRule5": "أدخل بيانات لدورة ألعاب واحدة فقط في كل ورقة وفقا لنموذج البيانات المقدمة",
  "ImportRule6": "يمكن إنشاء 10 دورات ألعاب فقط في المرة الواحدة",
  "ImportRule7": "تأكد من أن اسم دورة الألعاب فريد",
  "TOTBreadcrumbLabel": "دورة ألعاب الفِرق",
  "EnableTOTSuccessMessage": "تم تمكين دورة ألعاب الفِرق بنجاح. الرجاء تحديث التطبيق للمتابعة.",
  "EnableTOTSpinnerMessage": "ستستغرق هذه العملية بضع دقائق لتكتمل. الرجاء عدم التنقل بعيدا حتى تظهر الرسالة المكتملة بنجاح.",
  "TOTLeaderBoardPageTitle": "لوحة المتسابقين الأوائل",
  "TOTMyDashboardPageTitle": "لوحة المعلومات الخاصة بي",
  "ManageTournamentActionsToolTip": "الوصول إلى قائمة إجراءات دورة الألعاب",
  "ManageTournamentActionsLabel": "إدارة إجراءات دورة الألعاب",
  "ManageTournamentsLabel": "إدارة دورات الألعاب",
  "ManageAdminsToolTip": "الوصول إلى قائمة المسؤول",
  "ManageAdminsLabel": "إدارة المسؤولين",
  "QuickLinksLabel": "ارتباطات سريعة",
  "SpinnerListCreationMessage": "يتم الآن إعداد دورة ألعاب الفِرق...",
  "ManageTournamentsPageTitle": "إدارة دورات الألعاب",
  "ManageToTLabel1": "يمكن بدء دورات ألعاب متعددة في المرة الواحدة. اطّلع أدناه على دورات الألعاب النشطة الحالية، والقدرة على إكمال دورة الألعاب، بالإضافة إلى القدرة على بدء دورة ألعاب جديدة.",
  "ManageToTLabel2": "بمجرد بدء دورة ألعاب وإكمالها، لن تكون متوفرة للبدء مرة أخرى؛ ومع ذلك، يمكنك إنشاء دورة ألعاب جديدة باستخدام نفس الإجراءات إذا كنت ترغب في إكمال دورة ألعاب مماثلة.",
  "EndTournamentDialogMessage": "هل تريد بالتأكيد إكمال دورة الألعاب؟",
  "StartTournamentDialogMessage": "هل تريد بالتأكيد بدء دورة (دورات) ألعاب جديدة؟",
  "ConfirmLabel": "تأكيد",
  "YesButton": "نعم",
  "NoButton": "لا",
  "ActiveTournamentLabel": "دورات ألعاب نشطة",
  "EndTournamentButton": "إكمال دورة الألعاب",
  "StartTournamentHeaderLabel": "بدء دورة ألعاب",
  "NoTournamentMessage": "لم يتم العثور على أي دورات ألعاب. الرجاء معاودة التحقق لاحقاً.",
  "SelectTournamentMessage": "حدد دورة ألعاب واحدة على الأقل للبدء.",
  "SelectEndTournamentMessage": "حدد دورة ألعاب لإكمالها.",
  "StartTournamentButton": "بدء دورة (دورات) الألعاب",
  "EndTournamentSuccessMessage": "اكتملت دورة الألعاب بنجاح.",
  "EnableTournamentSuccessMessage": "بدأت دورة الألعاب بنجاح.",
  "CompleteTournamentSpinnerMessage": "يتم الآن إكمال دورة الألعاب...",
  "EnableTournamentSpinnerMessage": "يتم الآن تمكين دورة (دورات) الألعاب...",
  "SearchActiveTournaments": "بحث في دورات الألعاب النشطة",
  "SearchPendingTournaments": "ابحث في دورات الألعاب للبدء",
  "SelectAllLabel": "تحديد الكل",
  "NoSearchResults": "لا توجد نتائج مطابقة لبحثك.",
  "NoActiveParticipantsMessage": "لا يوجد أي مشاركين نشطين في الوقت الحالي. كن أول من يشارك في نشاط ويسجله من لوحة المعلومات!",
  "NoActiveTournamentMessage": "لا توجد دورات ألعاب نشطة في الوقت الحالي. الرجاء معاودة التحقق لاحقاً.",
  "TournamentLabel": "دورة ألعاب",
  "DescriptionLabel": "الوصف",
  "NoActiveParticipantsErrorMessage": "لا يوجد أي مشاركين نشطين في الوقت الحالي. كن أول من يقوم بالمشاركة وتسجيل نشاط من ",
  "PendingActionsLabel": "الإجراءات المعلقة",
  "PendingActionsSuccessMessage": "لا يوجد المزيد من الإجراءات المعلقة في دورة الألعاب هذه.",
  "SelectActionsErrorMessage": "حدد إجراء واحد على الأقل للمتابعة.",
  "FormSavingMessage": "يتم الآن حفظ تفاصيلك....",
  "CompletedActionsLabel": "الإجراءات المكتملة",
  "RankLabel": "تصنيف",
  "UserLabel": "مستخدم",
  "MyDashboardInfoIconMessage": "معرفة المزيد حول هذا الإجراء",
  "SelectTournamentPlaceHolder": "تحديد دورة ألعاب",
  "MyTournamentsLabel": "دورات الألعاب الخاصة بي",
  "OrLabel": "أو",
  "MyTournamentsTooltip": "دورات الألعاب النشطة التي شاركت فيها بالفعل",
  "PointsLabel": "نقاط",
  "TournamentRankLabel": "ترتيب دورة الألعاب",
  "ParticipantsLabel": "المشاركون",
  "TournamentReportsPageTitle": "تقرير دورات الألعاب",
  "TotalActivitiesLabel": "إجمالي الأنشطة",
  "TotalPointsLabel": "إجمالي النقاط",
  "TotalParticipantsLabel": "كل المشاركين",
  "TotalPercentageCompletionLabel": "% من إجمالي الاكتمال",
  "Top5ParticipantswithPointsLabel": "أهم 5 مشاركين بالنقاط",
  "Top5TournamentswithParticipantsLabel": "أفضل 5 دورات ألعاب مع المشاركين",
  "ParticipantsStatusLabel": "حالة المشاركين",
  "ParticipantsDetailsLabel": "تفاصيل المشاركين",
  "NameLabel": "الاسم",
  "PercentageTournamentCompletedLabel": "اكتملت دورة ألعاب بنسبة %",
  "ActivitiesCompletedLabel": "اكتملت الأنشطة",
  "NoRecordsinGridLabel": "لم يتم العثور على سجلات!",
  "SearchPlaceholder": "البحث باستخدام اسم المشارك",
  "NoCompletedTournamentsMessage": "لا توجد دورة ألعاب مكتملة في الوقت الحالي. الرجاء التحقق مرة أخرى لاحقًا.",
  "ReportsDropdownInfoIconText": "يمكن إنشاء التقرير لدورات الألعاب المكتملة فقط.",
  "RefreshIconInfoText": "انقر فوق تحديث لعرض أحدث البيانات",
  "EventApprovedMessage": "تمت الموافقة على حدث (أحداث) الرائد.",
  "EventRejectedMessage": "تم رفض حدث (أحداث) الرائد.",
  "SelectAllEvents": "تحديد كل الأحداث",
  "SelectEvent": "تحديد الحدث",
  "ChampionLabel": "الرائد",
  "EmailLabel": "البريد الإلكتروني",
  "EventLabel": "الحدث",
  "DateLabel": "التاريخ",
  "NotesLabel": "الملاحظات",
  "SuccessIcon": "أيقونه النجاح",
  "PendingEventsSearchboxPlaceholder": "بحث حسب الرائد / البريد الإلكتروني",
  "NoRecordsIcon": "أيقونة \"لا توجد سجلات\"",
  "NoPendingEventsLabel": "لا توجد أحداث معلقة في الوقت الحالي.",
  "ChampionActivitiesLabel": "أنشطة الرائد",
  "ManageConfigSettingsLabel": "إدارة إعدادات التكوين",
  "ApproveChampionSearchboxPlaceholder": "البحث حسب اسم العضو / البريد الإلكتروني",
  "EventsApprovalInfoIconTooltipContent": "سيتطلب تمكين هذا الخيار أن تتم الموافقة على عمليات إرسال الحدث من قبل البطل من قبل المسؤول. سيتم منح نقاط الأحداث بعد الموافقة فقط.",
  "ConfigSettingsSaved": "تم حفظ إعدادات التكوين.",
  "EventApprovalsEnableLabel": "تمكين موافقات حدث الرائد",
  "EventsSelectedLabel": "تم تحديد الحدث (الأحداث).",
  "ChampionsSelectedLabel": "تم تحديد الرائد (الرواد).",
  "ToggleLabelForMemberListColumns": "إظهار/إخفاء حقول قائمة الأعضاء",
  "TooltipContentForMemberListFieldsHeading": "إظهار/إخفاء حقول قائمة الأعضاء في جميع مكونات التطبيق أينما كان ذلك ممكنًا.",
  "ChampionReportLabel": "تقرير الأبطال",
  "ChampionReportToolTip": "تقرير الأبطال",
  "TotalChampionsLabel": "إجمالي الأبطال",
  "ClearButton": "مسح",
  "FilterbyDateLabel": "تصفية حسب التاريخ",
  "EventTypesHeading": "أنواع الأحداث",
  "NoEventsMessage": "لا توجد أي أحداث مكتملة في الوقت الحالي. الرجاء التحقق مرة أخرى لاحقا.",
  "NoEventsFoundMessage": "لم يتم العثور على أحداث!",
  "AppTitleLabel": "عنوان التطبيق",
  "AppTitleErrorLabel": "عنوان التطبيق مطلوب.",
  "AppTitlePlaceholderText": "30 حرفا كحد أقصى",
  "AppTitleInfoIconText": "سيظهر عنوان التطبيق في مقطع الرأس ومقاطع التنقل في التطبيق",
  "AboutContentLabel": "تم إنشاؤه مع أبطال المؤسسة / متخصصي الاستخدام في الاعتبار. تم تطوير هذا التطبيق من خلال مجتمع رائد Microsoft 365 لتقديم نظام أساسي للمساعدة في إنشاء مجتمعاتك والمحافظة عليها. بدءا بالإلهام من خلال التنفيذ في مساعدتك على تحقيق المزيد داخل مجتمعاتك!",
  "AboutHeaderLabel": "حول",
  "DashboardLabel": "لوحة المعلومات",
  "RemoveEventLabel": "إزالة الحدث",
  "AddEventLabel": "إضافة حدث",
  "EventChartLabel": "أهم 10 أحداث مع أنواع الأحداث",
  "FromLabel": "من",
  "ToLabel": "إلى",
  "AllTime": "طوال الوقت",
  "LastMonth": "الشهر الماضي",
  "Last3Months": "الأشهر الثلاثة الماضية",
  "Last6Months": "الأشهر الستة السابقة",
  "Last1Year": "آخر سنة",
  "SelectaCustomDate": "تحديد تاريخ مخصص",
  "championRecordsFoundLabel": "تم العثور على سجلات البطل",
  "digitalBadgeProfileAriaLabel": "فتح تطبيق Outlook على ويب في علامة تبويب مستعرض جديدة أو نافذة جديدة",
  "AddMemberAsAdminLabel": "إضافة عضو كمسؤول",
  "NoteValidationMessage": "يجب ألا تتجاوز الملاحظات 200 حرف",
  "CloseInfoPopoverButton": "إغلاق"
  }
});
