define([], function () {
  return {
    "AboutContentLabel": "تم إنشاء النظام الأساسي لإدارة الرواد لدينا مع مراعاة أخصائيي الاستخدام/ أبطال المؤسسة. تم تطوير هذا التطبيق من خلال مجتمع رواد Microsoft 365 لتقديم نظام أساسي للمساعدة في إنشاء مجتمعاتك والمحافظة عليها. بدءا بالإلهام من خلال التنفيذ في مساعدتك على تحقيق المزيد داخل مجتمعاتك!",
    "AboutHeaderLabel": "حول النظام الأساسي لإدارة الرواد (CMP):",
    "AcceptButtonAriaDescription": "بالنقر فوق هذا الزر، فإنك تمنح جزء الويب الخاص ببرنامج الرواد الإذن لتحديث صورة ملف التعريف نيابة عنك.",
    "AcceptButtonText": "قبول",
    "ActionErrorLabel": "حدد إجراءً واحدًا على الأقل لإنشاء دورة ألعاب.",
    "ActionGridHeader": "إجراء",
    "ActiveTournamentLabel": "دورات ألعاب نشطة",
    "ActivitiesCompletedLabel": "اكتملت الأنشطة",
    "ActivitiesLabel": "أنشطة",
    "AdditionalResourcesContentLabel": "تركز مجموعة Microsoft Teams Customer Advocacy على تقديم حلول مثل تلك لتلهمك وتساعدك على تحقيق أهدافك. تابع وانضم من خلال هذه الموارد الأخرى لمعرفة المزيد منا ومن المجتمع:",
    "AdditionalResourcesHeaderLabel": "موارد إضافية:",
    "AddMemberLabel": "إضافة عضو",
    "AddMemberPageTitle": "إضافة عضو",
    "AddMembersToolTip": "بدء إضافة الأعضاء بإضافة الأشخاص الذين ستتعاون معهم في...",
    "AdminTasksLabel": "مهام المسؤول",
    "AdminToolsLabel": "أدوات المسؤول",
    "AppHeaderTitleLabel": "النظام الأساسي لإدارة الرواد",
    "AppLogoToolTip": "الصفحة الرئيسية",
    "ApplyButton": "تطبيق",
    "ApplyButtonAriaDescription": "بالنقر فوق هذا الزر، فإنك تمنح جزء الويب الخاص ببرنامج الرواد الإذن لتحديث صورة ملف التعريف نيابة عنك.",
    "ApplyButtonText": "استخدام الصورة",
    "ApplySpinnerLabel": "يتم الآن استخدام صورة ملف تعريف جديدة على حسابك...",
    "ApproveButton": "موافقة",
    "ApproveChampionSearchboxPlaceholder": "البحث حسب اسم العضو / البريد الإلكتروني",
    "BackButton": "رجوع",
    "BadgeImageAlt": "جائزة على شكل ميدالية مع الحرف C في المنتصف تشير إلى أنني جزء من برنامج الرواد",
    "BadgePointsTooltip": "النقاط المطلوبة لإلغاء التأمين:",
    "BasicGroupName": "اسم المجموعة",
    "BecomeChampionLabel": "كن رائداً",
    "BySpecialityPlaceHolder": "تحديد حسب الاختصاص",
    "ChampionActivitiesLabel": "أنشطة الرائد",
    "ChampionApprovedMessage": "تمت الموافقة على طلب (طلبات) الرائد.",
    "ChampionLabel": "الرائد",
    "ChampionLeaderBoardLabel": "لوحة المتصدرين للرواد",
    "ChampionListLabel": "قائمة الرواد",
    "ChampionRejectedMessage": "تم رفض طلب (طلبات) الرائد.",
    "ChampionRequestSubmitSuccessMessage": "تم إرسال طلب الرائد بنجاح",
    "ChampionsListPageTitle": "قائمة الرواد",
    "ChampionsListToolTip": "الوصول إلى قائمة الرواد",
    "ChampionsSelectedLabel": "تم تحديد الرائد (الرواد).",
    "ChampionSubmissionPendingLabel": "عمليات إرسال الرائد معلقة",
    "ChatIconLabel": "دردشة",
    "CMPBreadcrumbLabel": "النظام الأساسي لإدارة الرواد",
    "CMPGitHubLinkLabel": "GitHub",
    "CMPSideBarChampionsLabel": "الرواد",
    "CMPSideBarGlobalRankLabel": "تصنيف عمومي",
    "CMPSideBarPointsLabel": "نقاط",
    "CompletedActionsLabel": "الإجراءات المكتملة",
    "CompleteTournamentSpinnerMessage": "يتم الآن إكمال دورة الألعاب...",
    "ConfigSettingsSaved": "تم حفظ إعدادات التكوين.",
    "ConfirmLabel": "تأكيد",
    "CountLabel": "عدد",
    "CountryGridHeader": "البلد",
    "CountryPlaceholder": "تحديد البلد",
    "CountValidationMessage": "يجب أن يكون العدد بين 1 و5",
    "CreateTournamentButton": "إنشاء دورة ألعاب",
    "CreateTournamentPageTitle": "إنشاء دورة ألعاب",
    "CreateTournamentsButton": "إنشاء دورات ألعاب",
    "CreateTournamentSuccessLabel": "تم إنشاء دورة الألعاب بنجاح.",
    "CurrentVersionLabel": "الإصدار الحالي:",
    "DateLabel": "التاريخ",
    "DateofEventGridLabel": "تاريخ الحدث",
    "DescriptionFieldLabel": "حقل الوصف",
    "DescriptionLabel": "الوصف",
    "DigitalBadgeAppBannerAltText": "مشاركة أعضاء فريق Microsoft في مناقشة",
    "DigitalBadgeLabel": "شارة رقمية",
    "DigitalBadgePageTitle": "شارة رقمية",
    "DigitalBadgeSubPageTitle": "إليك كيف ستبدو شارتك الرقمية!",
    "DigitalBadgeSuccessMessage": "<strong>تهانينا!</strong> لقد نجحت في المطالبة بالشارة الرقمية الخاصة بك وتم تحديث صورة ملف التعريف الخاص بك. الرجاء الانتظار حتى 24 ساعة لرؤية التحديث منعكساً على جميع تطبيقات Microsoft 365 (بما في ذلك Teams).",
    "DigitalMembersToolTip": "الحصول على شارتك الرقمية واستخدامها على صورة ملف التعريف الخاص بك",
    "DocumentationLabel": "الوثائق التقنية للحل والنظرة العامة المعمارية على",
    "DownloadButtonAriaDescription": "انقر لتنزيل صورة ملف التعريف الحالية الخاصة بك",
    "DownloadButtonSecondaryText": "تنزيل صورة ملف التعريف الحالية",
    "DownloadButtonText": "تنزيل",
    "DownloadedButtonSecondaryText": "يمكن العثور على صورة ملف التعريف الخاصة بك التي تم تنزيلها في مجلد التنزيلات الخاص بجهازك.",
    "DownloadedButtonText": "تم التنزيل",
    "DownloadingButtonText": "يتم الآن التنزيل...",
    "DrivingAdoptionLinkLabel": "استخدام القيادة في Microsoft Technical Community",
    "DuplicateTournamentNameError": "اسم دورة الألعاب موجود بالفعل. أدخل اسمًا آخر لدورة الألعاب.",
    "EmailIconLabel": "إرسال بريد إلكتروني",
    "EmailIDLabel": "معرّف البريد الإلكتروني",
    "EmailLabel": "البريد الإلكتروني",
    "EnableTOTLabel": "تشغيل دورة ألعاب الفِرق",
    "EnableTOTSpinnerMessage": "ستستغرق هذه العملية بضع دقائق لتكتمل. الرجاء عدم التنقل بعيدا حتى تظهر الرسالة المكتملة بنجاح.",
    "EnableTOTSuccessMessage": "تم تمكين دورة ألعاب الفِرق بنجاح. الرجاء تحديث التطبيق للمتابعة.",
    "EnableTOTToolTip": "تشغيل دورة ألعاب الفِرق",
    "EnableTournamentSpinnerMessage": "يتم الآن تمكين دورة (دورات) الألعاب...",
    "EnableTournamentSuccessMessage": "بدأت دورة الألعاب بنجاح.",
    "EndTournamentButton": "إكمال دورة الألعاب",
    "EndTournamentDialogMessage": "هل تريد بالتأكيد إكمال دورة الألعاب؟",
    "EndTournamentSuccessMessage": "اكتملت دورة الألعاب بنجاح.",
    "ErrorMsgActionsList": "حدث خطأ أثناء إنشاء عنصر في قائمة الإجراءات. قم بتصحيح البيانات وحاول مرة أخرى.",
    "ErrorMsgTournamentActionsList": "حدث خطأ أثناء إنشاء عنصر في قائمة إجراءات دورة الألعاب. قم بتصحيح البيانات وحاول مرة أخرى.",
    "ErrorMsgTournamentList": "حدث خطأ أثناء إنشاء عنصر في قائمة دورات الألعاب. قم بتصحيح البيانات وحاول مرة أخرى.",
    "EventApprovalsEnableLabel": "تمكين موافقات حدث الرائد",
    "EventApprovedMessage": "تمت الموافقة على حدث (أحداث) الرائد.",
    "EventLabel": "الحدث",
    "EventRejectedMessage": "تم رفض حدث (أحداث) الرائد.",
    "EventsApprovalInfoIconTooltipContent": "سيتطلب تمكين هذا الخيار أن تتم الموافقة على عمليات إرسال الحدث من قبل البطل من قبل المسؤول. سيتم منح نقاط الأحداث بعد الموافقة فقط.",
    "EventsListLabel": "قائمة الأحداث",
    "EventsListToolTip": "الوصول إلى قائمة الأحداث",
    "EventsSelectedLabel": "تم تحديد الحدث (الأحداث).",
    "EventsSubmissionSuccessMessage": "تم تسجيل الحدث (الأحداث) بنجاح.",
    "EventsSubmitMessage": "عند الانتهاء من إضافة الأحداث، الرجاء النقر فوق الزر \"إرسال\" للحفظ.",
    "EventsTrackListLabel": "قائمة تعقب الأحداث",
    "EventSubmissionPendingMessage": "تم إرسال الحدث (الأحداث) للحصول على الموافقة. سيتم منح النقاط بمجرد الموافقة على الحدث (الأحداث).",
    "EventTrackListToolTip": "الوصول إلى قائمة تعقب الأحداث",
    "EventTypeGridLabel": "نوع",
    "EventTypeGridLabelPlaceHolder": "تحديد نوع الحدث",
    "EventTypeLabel": "نوع الحدث",
    "EventTypeValidationMessage": "الرجاء تحديد نوع الحدث!",
    "FeedbackToolTip": "ملاحظات",
    "FirstNameLabel": "الاسم الأول",
    "FocusAreaGridHeader": "منطقة التركيز",
    "FocusAreaLabel": "منطقة التركيز",
    "FocusAreaPlaceholder": "تحديد منطقة التركيز",
    "FormSavingMessage": "يتم الآن حفظ تفاصيلك....",
    "GetStartedLabel": "بدء الاستخدام",
    "GroupGridHeader": "مجموعة",
    "GroupPlaceholder": "تحديد مجموعة",
    "HowtoGetDigitalBadgeText": "كيفية الحصول على شارة الرائد",
    "ImportRule1": "عدم تعديل رؤوس الأعمدة في القالب",
    "ImportRule2": "عدم حذف الأعمدة الموجودة في القالب",
    "ImportRule3": "أدخل البيانات في جميع الأعمدة المطلوبة (*) المذكورة في القالب",
    "ImportRule4": "اتبع حد ونوع الأحرف المذكورين في القالب لكل عمود",
    "ImportRule5": "أدخل بيانات لدورة ألعاب واحدة فقط في كل ورقة وفقا لنموذج البيانات المقدمة",
    "ImportRule6": "يمكن إنشاء 10 دورات ألعاب فقط في المرة الواحدة",
    "ImportRule7": "تأكد من أن اسم دورة الألعاب فريد",
    "ImportSpinnerMessage": "يتم الآن إنشاء دورات ألعاب.....",
    "LastNameLabel": "الاسم الأخير",
    "LatestVersionLabel": "أحدث إصدار:",
    "LoadingSpinnerLabel": "يتم الآن التحميل...",
    "LogMsgBlankSheet": "تم التخطي، نظرا لأنه فارغ.",
    "LogMsgDone": "دورة ألعاب",
    "LogMsgDone1": "تم الإنشاء.",
    "LogMsgInvalidTemplate": "تم التخطي لأنه قالب غير صالح.",
    "LogMsgInvalidTournamentName": "تم التخطي، نظراً لأنه لا يحتوي على اسم دورة ألعاب صالح.",
    "LogMsgMultipleTournaments": "تم التخطي، نظراً لوجود أكثر من اسم واحد لدورة الألعاب.",
    "LogMsgTournamentExists": "تم التخطي، بما أن دورة الألعاب",
    "LogMsgTournamentExists1": "موجودة بالفعل.",
    "LogProgress": " فيما يلي التقدم:",
    "M365ChampionCommunityLinkLabel": "مجتمع رواد Microsoft 365",
    "ManageAdminsLabel": "إدارة المسؤولين",
    "ManageAdminsToolTip": "الوصول إلى قائمة المسؤول",
    "ManageAppLogoLabel": "إدارة شعار التطبيق",
    "ManageAppLogoToolTip": "إدارة شعار التطبيق",
    "ManageConfigSettingsLabel": "إدارة إعدادات التكوين",
    "ManageDigitalBadgesLabel": "إدارة الشارات الرقمية",
    "ManageDigitalBadgesToolTip": "إدارة الشارات الرقمية",
    "ManageToTLabel1": "يمكن بدء دورات ألعاب متعددة في المرة الواحدة. اطّلع أدناه على دورات الألعاب النشطة الحالية، والقدرة على إكمال دورة الألعاب، بالإضافة إلى القدرة على بدء دورة ألعاب جديدة.",
    "ManageToTLabel2": "بمجرد بدء دورة ألعاب وإكمالها، لن تكون متوفرة للبدء مرة أخرى؛ ومع ذلك، يمكنك إنشاء دورة ألعاب جديدة باستخدام نفس الإجراءات إذا كنت ترغب في إكمال دورة ألعاب مماثلة.",
    "ManageTournamentActionsLabel": "إدارة إجراءات دورة الألعاب",
    "ManageTournamentActionsToolTip": "الوصول إلى قائمة إجراءات دورة الألعاب",
    "ManageTournamentsLabel": "إدارة دورات الألعاب",
    "ManageTournamentsPageTitle": "إدارة دورات الألعاب",
    "MeetupBody": "تخصيص بعض الوقت لمناقشة منطقة الرائد الخاصة بك والتعرف على المزيد!",
    "MeetupSubject": "1:1 (طلب الرائد)",
    "MonthAndDateLabel": "الشهر والتاريخ",
    "MoreInfoToolTip": "مزيد من المعلومات",
    "MSAdoptionHubLinkLabel": "مركز اعتماد Microsoft",
    "MultipleBadgeMessage": "حدد شارة من القائمة أدناه. سيتم تطبيق الشارة المحددة على صورة ملف التعريف الخاص بك.",
    "MultipleTournamentLabel": "دورات ألعاب متعددة",
    "MultiTournamentStep": "خطوة",
    "MultiTournamentStep1LinkLabel": "تنزيل القالب",
    "MultiTournamentStep1Text": "من نموذج تنسيق الملف",
    "MultiTournamentStep2": "أضف تفاصيل دورة الألعاب إلى الملف باتباع الإرشادات التالية",
    "MultiTournamentStep3": "تحميل الملف",
    "MyDashboardInfoIconMessage": "معرفة المزيد حول هذا الإجراء",
    "MyRankLabel": "تصنيفي",
    "MyTournamentsLabel": "دورات الألعاب الخاصة بي",
    "MyTournamentsTooltip": "دورات الألعاب النشطة التي شاركت فيها بالفعل",
    "NameLabel": "الاسم",
    "NearMePlaceHolder": "تحديد بالقرب مني",
    "NoActiveParticipantsErrorMessage": "لا يوجد أي مشاركين نشطين في الوقت الحالي. كن أول من يقوم بالمشاركة وتسجيل نشاط من ",
    "NoActiveParticipantsMessage": "لا يوجد أي مشاركين نشطين في الوقت الحالي. كن أول من يشارك في نشاط ويسجله من لوحة المعلومات!",
    "NoActiveTournamentMessage": "لا توجد دورات ألعاب نشطة في الوقت الحالي. الرجاء معاودة التحقق لاحقاً.",
    "NoActivitiesinGridLabel": "لم يتم العثور على أي أنشطة!",
    "NoBadgeMessage": "لم يتم العثور على شارات لك لتحديدها. الرجاء التحقق مع مسؤول التطبيق لديك.",
    "NoButton": "لا",
    "NoChampionsMessage": "لا توجد طلبات معلقة في الوقت الحالي",
    "NoCompletedTournamentsMessage": "لا توجد دورة ألعاب مكتملة في الوقت الحالي. الرجاء التحقق مرة أخرى لاحقًا.",
    "NominateMemberLabel": "ترشيح عضو",
    "NominateMemberPageTitle": "ترشيح عضو",
    "NoPendingEventsLabel": "لا توجد أحداث معلقة في الوقت الحالي.",
    "NoProfileImageAlt": "صورة ظلية لشخص ما، تشير إلى عدم استخدام صورة لملف التعريف حالياً على حسابك",
    "NoProfileImageDescription": "إذا قمت بالفعل بإقران صورة بملف التعريف الخاص بك، ولا تزال ترى هذه الرسالة، فقد لا تكون صورتك متوفرة حتى الآن. الرجاء المحاولة مرة أخرى لاحقاً، أو الاتصال بمكتب المساعدة <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>helpdesk</a> في حالة استمرار عدم ظهورها بعد 24 ساعة.",
    "NoRecordsIcon": "أيقونة \"لا توجد سجلات\"",
    "NoRecordsinGridLabel": "لم يتم العثور على سجلات!",
    "NoSearchResults": "لا توجد نتائج مطابقة لبحثك.",
    "NotesLabel": "الملاحظات",
    "NotesPlaceholder": "200 حرف كحد أقصى",
    "NoTournamentMessage": "لم يتم العثور على أي دورات ألعاب. الرجاء معاودة التحقق لاحقاً.",
    "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>مرحبًا بك في الأداة المساعدة للشارة الرقمية</span>. كجزء من عضويتك في برنامج الرواد، يمكنك الحصول على شارة رقمية. ستمكنك هذه الأداة المساعدة من \"<em>المطالبة</em>\" بشاراتك الرقمية عن طريق تراكبها أعلى صورة ملف التعريف الموجودة. الرجاء ملاحظة أن هذا سيؤدي إلى تحديث صورة ملف التعريف الخاص بك عبر جميع Microsoft 365 (Exchange وTeams وSharePoint وغيرها)",
    "OrLabel": "أو",
    "OverviewLabel": "نظرة عامة ومعلومات حول",
    "ParticipantsDetailsLabel": "تفاصيل المشاركين",
    "ParticipantsLabel": "المشاركون",
    "ParticipantsStatusLabel": "حالة المشاركين",
    "PendingActionsLabel": "الإجراءات المعلقة",
    "PendingActionsSuccessMessage": "لا يوجد المزيد من الإجراءات المعلقة في دورة الألعاب هذه.",
    "PendingEventsSearchboxPlaceholder": "بحث حسب الرائد / البريد الإلكتروني",
    "PeopleNameGridHeader": "اسم العضو",
    "PeoplePickerPlaceholder": "لإضافة عضو، الرجاء كتابة اسم العضو",
    "PercentageTournamentCompletedLabel": "اكتملت دورة ألعاب بنسبة %",
    "PivotHeaderBySpeciality": "حسب الاختصاص",
    "PivotHeaderGlobal": "عالمي",
    "PivotHeaderNearMe": "بالقرب مني",
    "PointsLabel": "نقاط",
    "PreAcceptDisclaimer": "<span style='font-weight:bold;'>مرحبًا بك في الأداة المساعدة للشارة الرقمية</span> <br/><br/> <span>، لقد حصلت على شارة رقمية كجزء من عضويتك في برنامج الرواد. ستمكنك هذه الأداة المساعدة من \"<em>المطالبة</em>\" بشاراتك الرقمية عن طريق تراكبها أعلى صورة ملف التعريف الموجودة. <br/><br/> الرجاء العلم بأن هذا سيؤدي إلى تحديث صورة ملف التعريف الخاص بك عبر جميع Microsoft 365 (Exchange وTeams وSharePoint وغيرها).</span>",
    "PreAcceptDisclaimer2": "إذا أردت، <span style='font-weight:bold;'>ستتوفر لديك فرصة 'حفظ' نسخة من صورة ملف التعريف الموجودة الخاصة بك</span> بدون تراكب الشارة الرقمية في الخطوات التالية. الرجاء النقر فوق ’قبول‘ للمتابعة (قد ترى إطارا منبثقا مفتوحاً ومطالبة بتسجيل الدخول).",
    "PreAcceptPageTitle": "المطالبة بالشارة الرقمية.",
    "PreApplyDisclaimer": "هذه معاينة لصورة ملف التعريف الجديدة بما في ذلك الشارة الرقمية. إذا كنت ترغب في تنزيل صورة ملف التعريف الحالية الخاصة بك قبل تطبيق الشارة الرقمية، فانقر فوق الرابط '<strong>تنزيل صورة ملف التعريف الحالية الخاصة بك</strong>'<br />",
    "PreApplyDisclaimer1": "<br />سيؤدي النقر فوق 'تطبيق الصورة' إلى تحديث صورة ملف التعريف Microsoft 365 بهذه الصورة الجديدة. <strong>الرجاء ملاحظة أن هذا سيؤدي إلى تحديث صورة ملف التعريف الخاص بك عبر كافة Microsoft 365 ويتعذر إرجاعه من خلال هذه الصفحة</strong>. <br/><br/>إذا كنت ترغب في تغيير صورتك مرة أخرى، يمكنك استخدام <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' aria-label='Open the Outlook web application in a new browser tab or window'>Outlook web application</a>.",
    "ProcessingSpinnerLabel": "تتمّ الآن المعالجة...",
    "ProfileImageAlt": "صورة ملف التعريف الخاص بي المستخدمة عبر O365 وTeams وما إلى ذلك",
    "PropertyPaneDescription": "الوصف",
    "QuickLinksLabel": "ارتباطات سريعة",
    "RankLabel": "تصنيف",
    "RecordEventLabel": "تسجيل حدث",
    "RecordsNotFound": "لم يتم العثور على السجلات",
    "RefreshIconInfoText": "انقر فوق تحديث لعرض أحدث البيانات",
    "RegionGridHeader": "المنطقة",
    "RegionLabel": "المنطقة",
    "RegionPlaceholder": "حدد المنطقة",
    "RejectButton": "رفض",
    "RemoveFileLabel": "إزالة ملف",
    "ReportsDropdownInfoIconText": "يمكن إنشاء التقرير لدورات الألعاب المكتملة فقط.",
    "RequestToCallLabel": "طلب اتصال هاتفي",
    "SaveButton": "حفظ",
    "SearchActiveTournaments": "بحث في دورات الألعاب النشطة",
    "SearchLabel": "بحث",
    "SearchPendingTournaments": "ابحث في دورات الألعاب للبدء",
    "SearchPlaceholder": "البحث باستخدام اسم المشارك",
    "SelectActionsErrorMessage": "حدد إجراء واحد على الأقل للمتابعة.",
    "SelectAll": "تحديد كل الرواد",
    "SelectAllEvents": "تحديد كل الأحداث",
    "SelectAllLabel": "تحديد الكل",
    "SelectChampion": "تحديد الرائد",
    "SelectDate": "تحديد تاريخ",
    "SelectEndTournamentMessage": "حدد دورة ألعاب لإكمالها.",
    "SelectEvent": "تحديد الحدث",
    "SelectTeamsActionsLabel": "تحديد إجراءات Teams:",
    "SelectTournamentMessage": "حدد دورة ألعاب واحدة على الأقل للبدء.",
    "SelectTournamentPlaceHolder": "تحديد دورة ألعاب",
    "ShowMoreLabel": "إظهار أكثر",
    "SingleTournamentLabel": "دورة ألعاب فردية",
    "SpinnerListCreationMessage": "يتم الآن إعداد دورة ألعاب الفِرق...",
    "StartTournamentButton": "بدء دورة (دورات) الألعاب",
    "StartTournamentDialogMessage": "هل تريد بالتأكيد بدء دورة (دورات) ألعاب جديدة؟",
    "StartTournamentHeaderLabel": "بدء دورة ألعاب",
    "StatusGridHeader": "الحالة",
    "SubmitButton": "إرسال",
    "SuccessIcon": "أيقونه النجاح",
    "SupportToolTip": "دعم",
    "TeamsActionInfoToolTip": "حدد من إجراءات Teams المتوفرة أدناه لتضمينها في دورة الألعاب الجديدة. لإضافة إجراءات دورة ألعاب جديدة للاختيار من بينها، تفضل بزيارة إدارة إجراءات دورة الألعاب من أدوات المسؤول.",
    "ToggleLabelForMemberListColumns": "إظهار/إخفاء حقول قائمة الأعضاء",
    "TooltipContentForMemberListFieldsHeading": "إظهار/إخفاء حقول قائمة الأعضاء في جميع مكونات التطبيق أينما كان ذلك ممكنًا.",
    "Top5ParticipantswithPointsLabel": "أهم 5 مشاركين بالنقاط",
    "Top5TournamentswithParticipantsLabel": "أفضل 5 دورات ألعاب مع المشاركين",
    "TopChampionsLabel": "أهم الرواد",
    "TotalActivitiesLabel": "إجمالي الأنشطة",
    "TotalParticipantsLabel": "كل المشاركين",
    "TotalPercentageCompletionLabel": "% من إجمالي الاكتمال",
    "TotalPointsLabel": "إجمالي النقاط",
    "TOTBreadcrumbLabel": "دورة ألعاب الفِرق",
    "TOTLabel": "دورة ألعاب الفِرق",
    "TOTLeaderBoardPageTitle": "لوحة المتسابقين الأوائل",
    "TOTMyDashboardPageTitle": "لوحة المعلومات الخاصة بي",
    "TournamentDescPlaceHolderLabel": "وصف دورة الألعاب (500 حرف كحد أقصى)",
    "TournamentDescriptionLabel": "وصف دورة الألعاب",
    "TournamentLabel": "دورة ألعاب",
    "TournamentNameErrorLabel": "اسم دورة الألعاب مطلوب.",
    "TournamentNameLabel": "اسم دورة الألعاب",
    "TournamentNamePlaceHolderLabel": "اسم دورة الألعاب (255 حرفاً كحد أقصى)",
    "TournamentRankLabel": "ترتيب دورة الألعاب",
    "TournamentReportsPageTitle": "تقرير دورات الألعاب",
    "UnauthorizedText": "أنت غير مؤهل لبرنامج شارة الرائد في الوقت الحالي",
    "UploadFileButton": "تحميل ملف",
    "UserAddedMessage": "تمت إضافة المستخدم بنجاح!",
    "UserExistingMessage": "المستخدم رائد بالفعل!",
    "UserLabel": "مستخدم",
    "UserNominatedMessage": "تم ترشيح المستخدم بنجاح!",
    "ViewActivitiesLabel": "إظهار الأنشطة",
    "ViewDashBoardLabel": "عرض لوحة المعلومات",
    "VisitLabel": "تفضل بزيارة صفحات النظام الأساسي لإدارة الرواد لمعرفة المزيد:",
    "WelcomeLabel": "مرحباً",
    "YesButton": "نعم",
  }
});