define([], function () {
  return {
    "AboutContentLabel": "was created with organizational Champions / Adoption Specialists in mind. Hearing from the Microsoft 365 Champion Community this app was developed to deliver a platform to help create and sustain your own communities. Starting with inspiration through execution in helping you achieve more within your own communities!",
    "AboutHeaderLabel": "About the",
    "AcceptButtonAriaDescription": "By clicking this button you're giving the Champions Program web part permission to update your profile picture on your behalf.",
    "AcceptButtonText": "Accept",
    "ActionErrorLabel": "Select at least one action to create a tournament.",
    "ActionGridHeader": "Action",
    "ActiveTournamentLabel": "Active Tournaments",
    "ActivitiesCompletedLabel": "Activities Completed",
    "ActivitiesLabel": "Activities",
    "AddEventLabel": "Add Event",
    "AdditionalResourcesContentLabel": "The Microsoft Teams Customer Advocacy Group is focused on delivering solutions like these to inspire and help you achieve your goals. Follow and join in through these other resources to learn more from us and the community:",
    "AdditionalResourcesHeaderLabel": "Additional Resources:",
    "AddMemberLabel": "Add Member",
    "AddMemberPageTitle": "Add Member",
    "AddMembersToolTip": "Adding Members Start adding the people you will collaborate with in your...",
    "AdminTasksLabel": "Admin Tasks",
    "AdminToolsLabel": "Admin Tools",
    "AllTime": "All Time",
    "AppLogoToolTip": "Home",
    "ApplyButton": "Apply",
    "ApplyButtonAriaDescription": "By clicking this button you're giving the Champions Program web part permission to update your profile picture on your behalf.",
    "ApplyButtonText": "Apply image",
    "ApplySpinnerLabel": "Applying new profile image to your account...",
    "ApproveButton": "Approve",
    "ApproveChampionSearchboxPlaceholder": "Search by Member Name / Email",
    "AppTitleErrorLabel": "App Title is required.",
    "AppTitleInfoIconText": "The App title will appear in the header section and breadcrumb sections of the app",
    "AppTitleLabel": "App Title",
    "AppTitlePlaceholderText": "Max 30 Characters",
    "BackButton": "Back",
    "BadgeImageAlt": "Medal-shaped award with the letter C in the middle signifying I am a part of the Champions Program",
    "BadgePointsTooltip": "Points required to unlock:",
    "BasicGroupName": "Group Name",
    "BecomeChampionLabel": "Become a Champion",
    "BySpecialityPlaceHolder": "Select By Specialty",
    "ChampionActivitiesLabel": "Champion Activities",
    "ChampionApprovedMessage": "Champion Request(s) Approved.",
    "ChampionLabel": "Champion",
    "ChampionLeaderBoardLabel": "Champion LeaderBoard",
    "ChampionListLabel": "Champions List",
    "championRecordsFoundLabel": "Champion records found",
    "ChampionRejectedMessage": "Champion Request(s) Rejected.",
    "ChampionReportLabel": "Champions Report",
    "ChampionReportToolTip": "Champions Report",
    "ChampionRequestSubmitSuccessMessage": "Champion request submission successful",
    "ChampionsListPageTitle": "Champions List",
    "ChampionsListToolTip": "Accessing Champions List",
    "ChampionsSelectedLabel": "Champion(s) selected.",
    "ChampionSubmissionPendingLabel": "Champion submission pending",
    "ChatIconLabel": "Chat",
    "ClearButton": "Clear",
    "CMPGitHubLinkLabel": "GitHub",
    "CMPSideBarChampionsLabel": "Champions",
    "CMPSideBarGlobalRankLabel": "Global Rank",
    "CMPSideBarPointsLabel": "Points",
    "CompletedActionsLabel": "Completed Actions",
    "CompleteTournamentSpinnerMessage": "Completing Tournament...",
    "ConfigSettingsSaved": "Config settings saved.",
    "ConfirmLabel": "Confirm",
    "CountLabel": "Count",
    "CountryGridHeader": "Country",
    "CountValidationMessage": "Count should be between 1 and 5",
    "CreateTournamentButton": "Create Tournament",
    "CreateTournamentPageTitle": "Create Tournament",
    "CreateTournamentsButton": "Create Tournaments",
    "CreateTournamentSuccessLabel": "Tournament created successfully.",
    "CurrentVersionLabel": "Current Version:",
    "DashboardLabel": "Dashboard",
    "DateLabel": "Date",
    "DateofEventGridLabel": "Date of Event",
    "DescriptionFieldLabel": "Description Field",
    "DescriptionLabel": "Description",
    "DigitalBadgeAppBannerAltText": "Microsoft team members engaging in a discussion",
    "DigitalBadgeLabel": "Digital Badge",
    "DigitalBadgePageTitle": "Digital Badge",
    "digitalBadgeProfileAriaLabel": "Open the Outlook web application in a new browser tab or window",
    "DigitalBadgeSubPageTitle": "Here's how your digital badge will look!",
    "DigitalBadgeSuccessMessage": "<strong>Congratulations!</strong> You have successfully claimed your digital badge and your profile picture has been updated. Please allow up to 24 hours to see the update reflected across all Microsoft 365 applications (including Teams).",
    "DigitalMembersToolTip": "Get your digital badge and apply it to your profile image",
    "DocumentationLabel": "Solution technical documentation and architectural overview on",
    "DownloadButtonAriaDescription": "Click to download your current profile image",
    "DownloadButtonSecondaryText": "Download your current profile image",
    "DownloadButtonText": "Download",
    "DownloadedButtonSecondaryText": "Your downloaded profile image can be found in your device's Downloads folder.",
    "DownloadedButtonText": "Downloaded",
    "DownloadingButtonText": "Downloading...",
    "DrivingAdoptionLinkLabel": "Driving Adoption on the Microsoft Technical Community",
    "DuplicateTournamentNameError": "Tournament name already exists. Enter another name for tournament.",
    "EmailIconLabel": "Send an Email",
    "EmailIDLabel": "Email Id",
    "EmailLabel": "Email",
    "EnableTOTLabel": "Enable Tournament of Teams",
    "EnableTOTSpinnerMessage": "This process will take a few moments to complete. Please do not navigate away until you see the completed successfully message.",
    "EnableTOTSuccessMessage": "Tournament of Teams has been enabled successfully. Please refresh the app to continue.",
    "EnableTOTToolTip": "Enable Tournament of Teams",
    "EnableTournamentSpinnerMessage": "Enabling Tournament(s)...",
    "EnableTournamentSuccessMessage": "Tournament(s) started successfully.",
    "EndTournamentButton": "Complete Tournament",
    "EndTournamentDialogMessage": "Are you sure want to complete the tournament?",
    "EndTournamentSuccessMessage": "Tournament completed successfully.",
    "ErrorMsgActionsList": "An error occurred while creating an item in Actions list. Correct the data and try again.",
    "ErrorMsgTournamentActionsList": "An error occured while creating an item in Tournament Actions list. Correct the data and try again.",
    "ErrorMsgTournamentList": "An error occured while creating an item in Tournaments list. Correct the data and try again.",
    "EventApprovalsEnableLabel": "Enable Champion Event Approvals",
    "EventApprovedMessage": "Champion Event(s) Approved.",
    "EventChartLabel": "Top 10 Events with Event Types",
    "EventLabel": "Event",
    "EventRejectedMessage": "Champion Event(s) Rejected.",
    "EventsApprovalInfoIconTooltipContent": "Enabling this option will require the event submissions by champions to be approved by an admin. The points for the events will be awarded only after the approval.",
    "EventsListLabel": "Events List",
    "EventsListToolTip": "Accessing Events List",
    "EventsSelectedLabel": "Event(s) selected.",
    "EventsSubmissionSuccessMessage": "Event(s) recorded successfully.",
    "EventsSubmitMessage": "When you are done adding events, please click on Submit button to save.",
    "EventSubmissionPendingMessage": "Event(s) submitted for approval. Points will be awarded once the event(s) are approved.",
    "EventTypeGridLabel": "Type",
    "EventTypeGridLabelPlaceHolder": "Select Event Type",
    "EventTypeLabel": "Event Type",
    "EventTypesHeading": "Event Types",
    "EventTypeValidationMessage": "Please select event type!",
    "FeedbackToolTip": "Feedback",
    "FilterbyDateLabel": "Filter by Date",
    "FirstNameLabel": "First Name",
    "FocusAreaGridHeader": "Focus Area",
    "FocusAreaLabel": "Focus Area",
    "FocusAreaPlaceholder": "Select Focus Area",
    "FormSavingMessage": "Saving your details....",
    "FromLabel": "From",
    "GetStartedLabel": "Get Started",
    "GroupGridHeader": "Group",
    "HowtoGetDigitalBadgeText": "How to get Champion Badge",
    "ImportRule1": "Do not modify the column headers in the template",
    "ImportRule2": "Do not delete the columns in the template",
    "ImportRule3": "Enter data in all the required(*) columns mentioned in the template",
    "ImportRule4": "Follow the character limit and type mentioned in the template for each column",
    "ImportRule5": "Enter data for only 1 tournament in each sheet as per the sample data provided",
    "ImportRule6": "Only 10 tournaments can be created at a time",
    "ImportRule7": "Ensure the Tournament Name is unique",
    "ImportSpinnerMessage": "Creating tournaments.....",
    "Last1Year": "Last 1 Year",
    "Last3Months": "Last 3 Months",
    "Last6Months": "Last 6 Months",
    "LastMonth": "Last Month",
    "LastNameLabel": "Last Name",
    "LatestVersionLabel": "Latest Version:",
    "LoadingDigitalBadgeLabel": "Digital badge frame loading",
    "LoadingSpinnerLabel": "Loading...",
    "LogMsgBlankSheet": "Skipped, since it is blank.",
    "LogMsgDone": "Tournament",
    "LogMsgDone1": "created.",
    "LogMsgInvalidTemplate": "Skipped, since it is not a valid template.",
    "LogMsgInvalidTournamentName": "Skipped, since it doesn't have a valid Tournament Name.",
    "LogMsgMultipleTournaments": "Skipped, since it has more than one Tournament Name.",
    "LogMsgTournamentExists": "Skipped, since the tournament",
    "LogMsgTournamentExists1": "already exists.",
    "LogProgress": " Below is the progress:",
    "M365ChampionCommunityLinkLabel": "Microsoft 365 Champion Community",
    "ManageAdminsLabel": "Manage Admins",
    "ManageAdminsToolTip": "Accessing Admin List",
    "ManageAppLogoLabel": "Manage App Logo",
    "ManageAppLogoToolTip": "Manage App Logo",
    "ManageConfigSettingsLabel": "Manage Config Settings",
    "ManageDigitalBadgesLabel": "Manage Digital Badges",
    "ManageDigitalBadgesToolTip": "Manage Digital Badges",
    "ManageToTLabel1": "Multiple tournaments can be started at a time. See below for the current active tournaments, ability to complete the tournament, as well as the ability to start a new tournament.",
    "ManageToTLabel2": "Once a tournament has been started and completed it will not be available to start again; however, you can create a new tournament using the same actions if you would like to complete a similar tournament!",
    "ManageTournamentActionsLabel": "Manage Tournament Actions",
    "ManageTournamentActionsToolTip": "Accessing Tournament Actions List",
    "ManageTournamentsLabel": "Manage Tournaments",
    "ManageTournamentsPageTitle": "Manage Tournaments",
    "MeetupBody": "Setting aside time to discuss your champion area and learn more!",
    "MeetupSubject": "1:1 (Champion Request)",
    "MonthAndDateLabel": "Month and Date",
    "MoreInfoToolTip": "More Info",
    "MSAdoptionHubLinkLabel": "Microsoft Adoption Hub",
    "MultipleBadgeMessage": "Select a badge from the below list. Selected badge will be applied on your profile picture.",
    "MultipleTournamentLabel": "Multiple Tournaments",
    "MultiTournamentStep": "Step",
    "MultiTournamentStep1LinkLabel": "Download Template",
    "MultiTournamentStep1Text": " of sample file format",
    "MultiTournamentStep2": "Add tournament details to the file by following the guidelines",
    "MultiTournamentStep3": "Upload the file",
    "MyDashboardInfoIconMessage": "Find out more about this action",
    "MyRankLabel": "My Rank",
    "MyTournamentsLabel": "My Tournaments",
    "MyTournamentsTooltip": "Active tournaments that you have participated in already",
    "NameLabel": "Name",
    "NearMePlaceHolder": "Select Near Me",
    "NoActiveParticipantsErrorMessage": "There are no active participants at the moment. Be the first to participate and log an activity from ",
    "NoActiveParticipantsMessage": "There are no active participants at the moment. Be the first to participate and log an activity from My Dashboard!",
    "NoActiveTournamentMessage": "No active tournaments at the moment. Please check back later.",
    "NoActivitiesinGridLabel": "No Activities found!",
    "NoBadgeMessage": "No badges found for you to select. Please check with your App Administrator.",
    "NoButton": "No",
    "NoChampionsMessage": "No pending requests at this time",
    "NoCompletedTournamentsMessage": "There is no completed tournament at the moment. Please check back later.",
    "NoEventsFoundMessage": "No Events found!",
    "NoEventsMessage": "There is no completed events at the moment. Please check back later.",
    "NominateMemberLabel": "Nominate Member",
    "NominateMemberPageTitle": "Nominate Member",
    "NoPendingEventsLabel": "No pending events at this time.",
    "NoProfileImageAlt": "Silhouette of a person, signifying no profile image is currently applied to your account",
    "NoProfileImageDescription": "If you have already associated a picture with your profile, and you’re still seeing this message, your picture might not be available yet. Please try again later, or contact the <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>helpdesk</a> if it still doesn’t show up after 24 hours.",
    "NoRecordsIcon": "No Records Icon",
    "NoRecordsinGridLabel": "No Records found!",
    "NoSearchResults": "No results matching your search.",
    "NotesLabel": "Notes",
    "NotesPlaceholder": "Max 200 characters",
    "NoTournamentMessage": "No tournaments found. Please check back later.",
    "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>Welcome to the digital badge utility</span>. As part of your membership of the Champions Program, you can earn a digital badge! This utility will enable you to '<em>claim</em>' your digital badge by overlaying it on top of your existing profile picture. Please note that this will update your profile picture across all of Microsoft 365 (Exchange, Teams, SharePoint, etc.)",
    "OrLabel": "OR",
    "OverviewLabel": "Overview & Information on our",
    "ParticipantsDetailsLabel": "Participants Details",
    "ParticipantsLabel": "Participants",
    "ParticipantsStatusLabel": "Participants Status",
    "PendingActionsLabel": "Pending Actions",
    "PendingActionsSuccessMessage": "There are no more pending actions in this tournament.",
    "PendingEventsSearchboxPlaceholder": "Search by Champion / Email",
    "PeopleNameGridHeader": "Member Name",
    "PeoplePickerPlaceholder": "For Adding a member please type member name",
    "PercentageTournamentCompletedLabel": "% Tournament Completed",
    "PivotHeaderBySpeciality": "By Specialty",
    "PivotHeaderGlobal": "Global",
    "PivotHeaderNearMe": "Near Me",
    "PointsLabel": "Points",
    "PreAcceptDisclaimer": "<h2><span style='font-weight:bold;'>Welcome to the digital badge utility</span></h2>",
    "PreAcceptDisclaimer1": "As part of your membership to the Champions Program, you have earned a digital badge! This utility will enable you to '<em>claim</em>' your digital badge by overlaying it on top of your existing profile picture.",
    "PreAcceptDisclaimer2": "Please note that this will update your profile picture across all of Microsoft 365 (Exchange, Teams, SharePoint, etc).",
    "PreAcceptDisclaimer3": "If desired, <span style='font-weight:bold;'>you will have an opportunity to 'save' a copy of your existing profile picture</span> without the digital badge overlay in the succeeding steps. Please click ‘Accept’ to continue (you might see a pop-up open and prompt for sign-in).",
    "PreAcceptPageTitle": "Claim your digital badge!",
    "PreApplyDisclaimer": "This is a preview of your new profile picture including the digital badge. If you wish to download your existing profile picture prior to applying the digital badge, click on the '<strong>Download your current profile image</strong>' link.",
    "PreApplyDisclaimer1": "Clicking 'Apply Image' will update your Microsoft 365 profile picture with this new image. <strong>Please note this will update your profile picture across all of Microsoft 365 and cannot be reverted through this page</strong>.",
    "PreApplyDisclaimer2": "If you'd like to change your picture back, you can use the <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' id='linkToChangeProfileImage'>Outlook web application</a>.",
    "ProcessingSpinnerLabel": "Processing...",
    "ProfileImageAlt": "My profile image used across O365, Teams, etc",
    "PropertyPaneDescription": "Description",
    "QuickLinksLabel": "Quick Links",
    "RankLabel": "Rank",
    "RecordEventLabel": "Record Event",
    "RecordsNotFound": "Records Not Found",
    "RefreshIconInfoText": "Click refresh to see latest data",
    "RegionLabel": "Region",
    "RejectButton": "Reject",
    "RemoveEventLabel": "Remove Event",
    "RemoveFileLabel": "Remove File",
    "ReportsDropdownInfoIconText": "Report can be generated only for completed tournaments.",
    "RequestToCallLabel": "Schedule a sync",
    "SaveButton": "Save",
    "SearchActiveTournaments": "Search active tournaments",
    "SearchLabel": "Search Top Champions",
    "SearchPendingTournaments": "Search tournaments to start",
    "SearchPlaceholder": "Search by Participant's Name",
    "SelectActionsErrorMessage": "Select atleast one action to proceed.",
    "SelectaCustomDate": "Select a Custom Date",
    "SelectAllChampions": "Select All Champions",
    "SelectAllEvents": "Select All Events",
    "SelectAllLabel": "Select All",
    "SelectChampion": "Select Champion",
    "SelectDate": "Select a date",
    "SelectedFocusAreaLabel": "Focus area selected",
    "SelectEndTournamentMessage": "Select a tournament to complete.",
    "SelectEvent": "Select Event",
    "SelectTeamsActionsLabel": "Select Teams Actions:",
    "SelectTournamentMessage": "Select atleast one tournament to start.",
    "SelectTournamentPlaceHolder": "Select Tournament",
    "ShowHideToggle": "Show/Hide Member List Fields",
    "ShowMoreLabel": "Show More",
    "SingleTournamentLabel": "Single Tournament",
    "SpinnerListCreationMessage": "Setting up Tournament of Teams...",
    "StartTournamentButton": "Start Tournament(s)",
    "StartTournamentDialogMessage": "Are you sure want to start the new tournament(s)?",
    "StartTournamentHeaderLabel": "Start Tournament",
    "StatusGridHeader": "Status",
    "SubmitButton": "Submit",
    "SuccessIcon": "Success Icon",
    "SupportToolTip": "Support",
    "TeamsActionInfoToolTip": "Select from the below available Teams actions to include in the new tournament. To add new tournament actions to choose from, visit the Manage Tournament Actions from the Admin Tools.",
    "ToggleLabelForMemberListColumns": "Show/Hide Member List Fields",
    "ToggleView": "toggle",
    "ToLabel": "To",
    "TooltipContentForMemberListFieldsHeading": "Show/hide member list fields in all the components of the app wherever applicable.",
    "Top5ParticipantswithPointsLabel": "Top 5 Participants with Points",
    "Top5TournamentswithParticipantsLabel": "Top 5 Tournaments with Participants",
    "TopChampionsLabel": "Top Champions",
    "TotalActivitiesLabel": "Total Activities",
    "TotalChampionsLabel": "Total Champions",
    "TotalParticipantsLabel": "Total Participants",
    "TotalPercentageCompletionLabel": "% of Total Completion",
    "TotalPointsLabel": "Total Points",
    "TOTBreadcrumbLabel": "Tournament of Teams",
    "TOTLabel": "Tournament of Teams",
    "TOTLeaderBoardPageTitle": "Leader Board",
    "TOTMyDashboardPageTitle": "My Dashboard",
    "TournamentDescPlaceHolderLabel": "Tournament Description(Max 500 characters)",
    "TournamentDescriptionLabel": "Tournament Description",
    "TournamentLabel": "Tournament",
    "TournamentNameErrorLabel": "Tournament Name is required.",
    "TournamentNameLabel": "Tournament Name",
    "TournamentNamePlaceHolderLabel": "Tournament Name(Max 255 characters)",
    "TournamentRankLabel": "Tournament Rank",
    "TournamentReportsPageTitle": "Tournaments Report",
    "UnauthorizedText": "You are not qualified for Champion Badge Program at this time",
    "UploadFileButton": "Upload File",
    "UserAddedMessage": "User Added Successfully!",
    "UserExistingMessage": "User Already a Champion!",
    "UserLabel": "User",
    "UserNominatedMessage": "User Nominated Successfully!",
    "ViewActivitiesLabel": "View Activities",
    "ViewDashBoardLabel": "View Dashboard",
    "VisitLabel": "Visit the Champion Management Platform pages to learn more:",
    "WelcomeLabel": "Welcome",
    "YesButton": "Yes"
  }
});
