define([], function () {
  return {
    "AboutContentLabel": "Nuestra Plataforma de administración de expertos se creó teniendo en cuenta los expertos de la organización / los especialistas en adopción. Al escuchar a la Comunidad de expertos de Microsoft 365, esta aplicación se desarrolló para ofrecer una plataforma que ayude a crear y mantener tus propias comunidades. Partiendo de la inspiración y a través de la ejecución podemos ayudarte a conseguir más en tus propias comunidades.",
    "AboutHeaderLabel": "Acerca de la Plataforma de administración de expertos (CMP):",
    "AcceptButtonAriaDescription": "Al hacer clic en este botón, concederás permiso al elemento web del Programa De Expertos para actualizar la imagen de perfil en tu nombre.",
    "AcceptButtonText": "Aceptar",
    "ActionErrorLabel": "Selecciona al menos una acción para crear un torneo.",
    "ActionGridHeader": "Acción",
    "ActiveTournamentLabel": "Torneos activos",
    "ActivitiesCompletedLabel": "Actividades completadas",
    "ActivitiesLabel": "Actividades",
    "AdditionalResourcesContentLabel": "El grupo de atención al cliente de Microsoft Teams se centra en ofrecer soluciones como estas para inspirarte y ayudarte a alcanzar tus objetivos. Sigue y únete a estos otros recursos para obtener más información de nosotros y de la comunidad:",
    "AdditionalResourcesHeaderLabel": "Recursos adicionales:",
    "AddMemberLabel": "Añadir miembro",
    "AddMemberPageTitle": "Añadir miembro",
    "AddMembersToolTip": "Agregar miembros: empieza a agregar a las personas con las que colaborarás en tu...",
    "AdminTasksLabel": "Tareas de administración",
    "AdminToolsLabel": "Herramientas de administración",
    "AppHeaderTitleLabel": "Plataforma de administración de expertos",
    "AppLogoToolTip": "Inicio",
    "ApplyButton": "Aplicar",
    "ApplyButtonAriaDescription": "Al hacer clic en este botón, concederás permiso al elemento web del Programa De Expertos para actualizar la imagen de perfil en tu nombre.",
    "ApplyButtonText": "Aplicar imagen",
    "ApplySpinnerLabel": "Aplicando la nueva imagen de perfil a su cuenta...",
    "ApproveButton": "Aprobar",
    "ApproveChampionSearchboxPlaceholder": "Buscar por nombre de miembro o correo electrónico",
    "BackButton": "Atrás",
    "BadgeImageAlt": "Premio en forma de medalla con la letra C en el medio que significa que forme parte del Programa De Expertos",
    "BadgePointsTooltip": "Puntos necesarios para desbloquear:",
    "BasicGroupName": "Nombre de grupo",
    "BecomeChampionLabel": "Conviértete en un experto",
    "BySpecialityPlaceHolder": "Seleccionar por especialidad",
    "ChampionActivitiesLabel": "Actividades de experto",
    "ChampionApprovedMessage": "Solicitud(es) de experto aprobadas.",
    "ChampionLabel": "Experto",
    "ChampionLeaderBoardLabel": "Marcador de campeones",
    "ChampionListLabel": "Lista de expertos",
    "ChampionRejectedMessage": "Solicitud(es) de experto rechazadas.",
    "ChampionRequestSubmitSuccessMessage": "Envío de solicitud de experto correcto",
    "ChampionsListPageTitle": "Lista de expertos",
    "ChampionsListToolTip": "Acceso a la lista de expertos",
    "ChampionsSelectedLabel": "Expero(s) seleccionado(s).",
    "ChampionSubmissionPendingLabel": "Admisión de experto pendiente",
    "ChatIconLabel": "Chat",
    "CMPBreadcrumbLabel": "Plataforma de administración de expertos",
    "CMPGitHubLinkLabel": "GitHub",
    "CMPSideBarChampionsLabel": "Expertos",
    "CMPSideBarGlobalRankLabel": "Clasificación global",
    "CMPSideBarPointsLabel": "Puntos",
    "CompletedActionsLabel": "Acciones completadas",
    "CompleteTournamentSpinnerMessage": "Completando torneo...",
    "ConfigSettingsSaved": "Configuración guardada.",
    "ConfirmLabel": "Confirmar",
    "CountLabel": "Recuento",
    "CountryGridHeader": "País o región",
    "CountryPlaceholder": "Seleccionar país o región",
    "CountValidationMessage": "El recuento debe estar comprendido entre 1 y 5",
    "CreateTournamentButton": "Crear torneo",
    "CreateTournamentPageTitle": "Crear torneo",
    "CreateTournamentsButton": "Crear torneos",
    "CreateTournamentSuccessLabel": "El torneo se creó correctamente.",
    "CurrentVersionLabel": "Versión actual:",
    "DateLabel": "Fecha",
    "DateofEventGridLabel": "Fecha del evento",
    "DescriptionFieldLabel": "Campo Descripción",
    "DescriptionLabel": "Descripción",
    "DigitalBadgeAppBannerAltText": "Los miembros del equipo de Microsoft participan en una discusión",
    "DigitalBadgeLabel": "Distintivo digital",
    "DigitalBadgePageTitle": "Distintivo digital",
    "DigitalBadgeSubPageTitle": "Este es el aspecto que tendrá tu insignia digital.",
    "DigitalBadgeSuccessMessage": "<strong>Enhorabuena.</strong> Has solicitado correctamente tu distintivo digital y se ha actualizado tu imagen de perfil. Espera hasta 24 horas para ver la actualización reflejada en todas las aplicaciones de Microsoft 365 (incluido Teams).",
    "DigitalMembersToolTip": "Obtener el distintivo digital y aplicarlo a la imagen de perfil",
    "DocumentationLabel": "Documentación técnica de la solución e información general sobre la arquitectura en",
    "DownloadButtonAriaDescription": "Haz clic para descargar la imagen de perfil actual",
    "DownloadButtonSecondaryText": "Descargar la imagen de perfil actual",
    "DownloadButtonText": "Descargar",
    "DownloadedButtonSecondaryText": "La imagen de perfil descargada se encuentra en la carpeta Descargas del dispositivo.",
    "DownloadedButtonText": "Descargado",
    "DownloadingButtonText": "Descargando...",
    "DrivingAdoptionLinkLabel": "Impulsar la adopción en Microsoft Technical Community",
    "DuplicateTournamentNameError": "El nombre del torneo ya existe. Escribe otro nombre para el torneo.",
    "EmailIconLabel": "Enviar correo electrónico",
    "EmailIDLabel": "Id. de correo electrónico",
    "EmailLabel": "Correo electrónico",
    "EnableTOTLabel": "Habilitar torneo de equipos",
    "EnableTOTSpinnerMessage": "Este proceso tardará unos minutos en completarse. No salga de la página hasta que vea el mensaje completado correctamente.",
    "EnableTOTSuccessMessage": "El torneo de equipos se ha habilitado correctamente. Actualice la aplicación para continuar.",
    "EnableTOTToolTip": "Habilitar torneo de equipos",
    "EnableTournamentSpinnerMessage": "Habilitando torneo(s)...",
    "EnableTournamentSuccessMessage": "Los torneos se iniciaron correctamente.",
    "EndTournamentButton": "Completar torneo",
    "EndTournamentDialogMessage": "¿Estás seguro de que quieres completar el torneo?",
    "EndTournamentSuccessMessage": "El torneo se completó correctamente.",
    "ErrorMsgActionsList": "Error al crear un elemento en la lista acciones. Corrija los datos e inténtelo de nuevo.",
    "ErrorMsgTournamentActionsList": "Error al crear un elemento en la lista de acciones del torneo. Corrija los datos e inténtelo de nuevo.",
    "ErrorMsgTournamentList": "Error al crear un elemento en la lista de torneos. Corrija los datos e inténtelo de nuevo.",
    "EventApprovalsEnableLabel": "Habilitar aprobaciones de eventos de experto",
    "EventApprovedMessage": "Eventos de experto aprobados.",
    "EventLabel": "Evento",
    "EventRejectedMessage": "Evento(s) de experto rechazado(s).",
    "EventsApprovalInfoIconTooltipContent": "Si habilitas esta opción, será necesario que los expertos aprueben los envíos de eventos. Los puntos de los eventos se concederán solo después de la aprobación.",
    "EventsListLabel": "Lista de eventos",
    "EventsListToolTip": "Acceso a la lista de eventos",
    "EventsSelectedLabel": "Evento(s) seleccionado(s).",
    "EventsSubmissionSuccessMessage": "Evento(s) registrado(s) correctamente.",
    "EventsSubmitMessage": "Cuando hayas terminado de agregar eventos, haz clic en el botón Enviar para guardar.",
    "EventsTrackListLabel": "Lista de seguimiento de eventos",
    "EventSubmissionPendingMessage": "Eventos enviados para aprobación. Los puntos se concederán una vez que se aprueben los eventos.",
    "EventTrackListToolTip": "Acceso a la lista de seguimiento de eventos",
    "EventTypeGridLabel": "Tipo",
    "EventTypeGridLabelPlaceHolder": "Seleccionar tipo de evento",
    "EventTypeLabel": "Tipo de evento",
    "EventTypeValidationMessage": "Selecciona el tipo de evento.",
    "FeedbackToolTip": "Comentarios",
    "FirstNameLabel": "Nombre",
    "FocusAreaGridHeader": "Área de enfoque",
    "FocusAreaLabel": "Área de enfoque",
    "FocusAreaPlaceholder": "Seleccionar área de enfoque",
    "FormSavingMessage": "Guardando los detalles...",
    "GetStartedLabel": "Introducción",
    "GroupGridHeader": "Grupo",
    "GroupPlaceholder": "Seleccionar grupo",
    "HowtoGetDigitalBadgeText": "Cómo obtener la insignia de experto",
    "ImportRule1": "No modificar los encabezados de columna de la plantilla",
    "ImportRule2": "No eliminar las columnas de la plantilla",
    "ImportRule3": "Escribe los datos en todas las columnas requeridas(*) mencionadas en la plantilla.",
    "ImportRule4": "Seguir el límite de caracteres y el tipo mencionado en la plantilla para cada columna",
    "ImportRule5": "Escribe los datos de un solo torneo por cada hoja según los datos de ejemplo proporcionados",
    "ImportRule6": "Solo se pueden crear diez torneos a la vez",
    "ImportRule7": "Asegúrate de que el nombre del torneo es único",
    "ImportSpinnerMessage": "Creando torneos......",
    "LastNameLabel": "Apellidos",
    "LatestVersionLabel": "Versión más reciente:",
    "LoadingSpinnerLabel": "Cargando...",
    "LogMsgBlankSheet": "Omitido, ya que está en blanco.",
    "LogMsgDone": "Torneo",
    "LogMsgDone1": "creado.",
    "LogMsgInvalidTemplate": "Omitido, ya que no es una plantilla válida.",
    "LogMsgInvalidTournamentName": "Omitido, ya que no tiene un nombre de torneo válido.",
    "LogMsgMultipleTournaments": "Omitido, ya que tiene más de un nombre de torneo.",
    "LogMsgTournamentExists": "Omitido, porque el torneo",
    "LogMsgTournamentExists1": "ya existe.",
    "LogProgress": " A continuación se muestra el progreso:",
    "M365ChampionCommunityLinkLabel": "Comunidad de expertos de Microsoft 365",
    "ManageAdminsLabel": "Administrar administradores",
    "ManageAdminsToolTip": "Acceso a la lista de administradores",
    "ManageAppLogoLabel": "Administrar logotipo de la aplicación",
    "ManageAppLogoToolTip": "Administrar logotipo de la aplicación",
    "ManageConfigSettingsLabel": "Administrar valores de configuración",
    "ManageDigitalBadgesLabel": "Administrar distintivos digitales",
    "ManageDigitalBadgesToolTip": "Administrar distintivos digitales",
    "ManageToTLabel1": "Se pueden iniciar varios torneos a la vez. Consulta a continuación los torneos que están activos, la capacidad de completar el torneo, así como la capacidad de iniciar un nuevo torneo.",
    "ManageToTLabel2": "Una vez que se haya iniciado y completado un torneo, no estará disponible para empezarlo de nuevo. Sin embargo, podrás crear un nuevo torneo con las mismas acciones si quieres completar un torneo similar.",
    "ManageTournamentActionsLabel": "Administrar acciones del torneo",
    "ManageTournamentActionsToolTip": "Acceso a la lista de acciones del torneo",
    "ManageTournamentsLabel": "Administrar torneos",
    "ManageTournamentsPageTitle": "Administrar torneos",
    "MeetupBody": "Reserva tiempo para hablar de tu área de experto y obtener más información.",
    "MeetupSubject": "1:1 (Solicitud de experto)",
    "MonthAndDateLabel": "Mes y fecha",
    "MoreInfoToolTip": "Más información",
    "MSAdoptionHubLinkLabel": "Centro de adopción de Microsoft",
    "MultipleBadgeMessage": "Seleccione un distintivo de la lista siguiente. El distintivo seleccionado se aplicará a la imagen de perfil.",
    "MultipleTournamentLabel": "Torneos múltiples",
    "MultiTournamentStep": "Paso",
    "MultiTournamentStep1LinkLabel": "Descargar plantilla",
    "MultiTournamentStep1Text": " de formato de archivo de ejemplo",
    "MultiTournamentStep2": "Agrega los detalles del torneo al archivo siguiendo las directrices",
    "MultiTournamentStep3": "Cargar el archivo",
    "MyDashboardInfoIconMessage": "Más información acerca de esta acción",
    "MyRankLabel": "Mi clasificación",
    "MyTournamentsLabel": "Mis torneos",
    "MyTournamentsTooltip": "Torneos activos en los que ya has participado",
    "NameLabel": "Nombre",
    "NearMePlaceHolder": "Seleccionar Cerca de mí",
    "NoActiveParticipantsErrorMessage": "No hay participantes activos en este momento. Sea el primero en participar y registrar una actividad desde ",
    "NoActiveParticipantsMessage": "No hay participantes activos en este momento. Sea el primero en participar y registrar una actividad desde Mi panel.",
    "NoActiveTournamentMessage": "No hay torneos activos en este momento. Vuelve a comprobarlo más tarde.",
    "NoActivitiesinGridLabel": "No se encontraron actividades.",
    "NoBadgeMessage": "No se encontraron insignias para seleccionar. Compruébalo con el administrador de la aplicación.",
    "NoButton": "No",
    "NoChampionsMessage": "No hay solicitudes pendientes en este momento",
    "NoCompletedTournamentsMessage": "No hay ningún torneo completado en este momento. Vuelve a comprobarlo más tarde.",
    "NominateMemberLabel": "Miembro designado",
    "NominateMemberPageTitle": "Miembro designado",
    "NoPendingEventsLabel": "No hay eventos pendientes en este momento.",
    "NoProfileImageAlt": "Silueta de una persona, que indica que no hay ninguna imagen de perfil aplicada actualmente a tu cuenta",
    "NoProfileImageDescription": "Si ya has asociado una imagen a tu perfil y sigues viendo este mensaje, es posible que la imagen aún no esté disponible. Vuelve a intentarlo más tarde o ponte en contacto con el <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>servicio de asistencia</a> si sigue sin aparecer después de 24 horas.",
    "NoRecordsIcon": "Icono Sin registros",
    "NoRecordsinGridLabel": "No se encontraron registros.",
    "NoSearchResults": "No hay resultados que coincidan con la búsqueda.",
    "NotesLabel": "Notas",
    "NotesPlaceholder": "200 caracteres como máximo",
    "NoTournamentMessage": "No se han encontraron torneos. Vuelve a comprobarlo más tarde.",
    "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>Te damos la bienvenida a la utilidad de distintivo digital</span>. Como parte de tu suscripción al Programa De Expertos, puedes ganar un distintivo digital. Esta utilidad te permitirá \"<em>reclamar</em>\" el distintivo digital superponiéndolo sobre la imagen de perfil existente. Ten en cuenta que se actualizará la imagen de perfil en todo Microsoft 365 (Exchange, Teams, SharePoint, etc.).",
    "OrLabel": "O",
    "OverviewLabel": "Información general e información sobre nuestro",
    "ParticipantsDetailsLabel": "Detalles de los participantes",
    "ParticipantsLabel": "Participantes",
    "ParticipantsStatusLabel": "Estado de los participantes",
    "PendingActionsLabel": "Acciones pendientes",
    "PendingActionsSuccessMessage": "No hay más acciones pendientes en este torneo.",
    "PendingEventsSearchboxPlaceholder": "Buscar por experto o correo electrónico",
    "PeopleNameGridHeader": "Nombre del miembro",
    "PeoplePickerPlaceholder": "Para agregar un miembro, escribe el nombre del miembro",
    "PercentageTournamentCompletedLabel": "% de torneo completado",
    "PivotHeaderBySpeciality": "Por especialidad",
    "PivotHeaderGlobal": "Global",
    "PivotHeaderNearMe": "Cerca de mí",
    "PointsLabel": "Puntos",
    "PreAcceptDisclaimer": "<span style='font-weight:bold;'>Te damos la bienvenida a la utilidad de distintivo digital</span> <br/><br/> <span>Como parte de tu suscripción al Programa De Expertos, has ganado un distintivo digital. Esta utilidad te permitirá \"<em>reclamar</em>\" el distintivo digital superponiéndolo sobre la imagen de perfil existente. <br/><br/> Ten en cuenta que se actualizará la imagen de perfil en todo Microsoft 365 (Exchange, Teams, SharePoint, etc.).</span>",
    "PreAcceptDisclaimer2": "Si lo deseas, <span style='font-weight:bold;'>tendrás la oportunidad de \"guardar\" una copia de la imagen de perfil existente</span> sin la superposición del distintivo digital en los pasos siguientes. Haga clic en \"Aceptar\" para continuar (es posible que se abra una ventana emergente que le pida que inicie sesión).",
    "PreAcceptPageTitle": "Reclama tu distintivo digital.",
    "PreApplyDisclaimer": "Esta es una vista previa de la nueva imagen de perfil, incluida el distintivo digital. Si deseas descargar la imagen de perfil existente antes de aplicar el distintivo digital, haz clic en el vínculo \"'<strong>Descargar la imagen de perfil actual\"</strong>.<br />",
    "PreApplyDisclaimer1": "<br />Al hacer clic en \"Aplicar imagen\", se actualizará la imagen de perfil de Microsoft 365 con esta nueva imagen. <strong>Ten en cuenta que se actualizará la imagen de perfil en todo Microsoft 365 y no se puede revertir a través de esta página</strong>. <br/><br/>Si quieres volver a cambiar la imagen, puedes usar la <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' aria-label='Open the Outlook web application in a new browser tab or window'>aplicación web de Outlook</a>.",
    "ProcessingSpinnerLabel": "Procesando...",
    "ProfileImageAlt": "Mi imagen de perfil usada en O365, Teams, etc.",
    "PropertyPaneDescription": "Descripción",
    "QuickLinksLabel": "Enlaces rápidos",
    "RankLabel": "Clasificación",
    "RecordEventLabel": "Registrar evento",
    "RecordsNotFound": "Registros no encontrados",
    "RefreshIconInfoText": "Haz clic en Actualizar para ver los datos más recientes",
    "RegionGridHeader": "Región",
    "RegionLabel": "Región",
    "RegionPlaceholder": "Selecciona la región",
    "RejectButton": "Rechazar",
    "RemoveFileLabel": "Quitar archivo",
    "ReportsDropdownInfoIconText": "El informe solo se puede generar para torneos completados.",
    "RequestToCallLabel": "Solicitud de llamada",
    "SaveButton": "Guardar",
    "SearchActiveTournaments": "Buscar torneos activos",
    "SearchLabel": "Buscar",
    "SearchPendingTournaments": "Buscar torneos para empezar",
    "SearchPlaceholder": "Buscar por nombre de participante",
    "SelectActionsErrorMessage": "Seleccione al menos una acción para continuar.",
    "SelectAll": "Seleccionar todos los expertos",
    "SelectAllEvents": "Seleccionar todos los eventos",
    "SelectAllLabel": "Seleccionar todo",
    "SelectChampion": "Seleccionar experto",
    "SelectDate": "Seleccione una fecha",
    "SelectEndTournamentMessage": "Selecciona un torneo para completarlo.",
    "SelectEvent": "Seleccionar evento",
    "SelectTeamsActionsLabel": "Seleccionar acciones de Teams:",
    "SelectTournamentMessage": "Selecciona al menos un torneo para empezar.",
    "SelectTournamentPlaceHolder": "Seleccionar torneo",
    "ShowMoreLabel": "Mostrar más",
    "SingleTournamentLabel": "Torneo único",
    "SpinnerListCreationMessage": "Configurando el torneo de equipos...",
    "StartTournamentButton": "Iniciar torneo",
    "StartTournamentDialogMessage": "¿Estás seguro de que quieres iniciar el nuevo torneo?",
    "StartTournamentHeaderLabel": "Iniciar torneo",
    "StatusGridHeader": "Estado",
    "SubmitButton": "Enviar",
    "SuccessIcon": "Icono Acción correcta",
    "SupportToolTip": "Asistencia",
    "TeamsActionInfoToolTip": "Selecciona entre las siguientes acciones de Teams disponibles para incluirlas en el nuevo torneo. Para agregar nuevas acciones de torneo entre las que poder elegir, visita Administrar acciones del torneo desde las herramientas de Administración.",
    "ToggleLabelForMemberListColumns": "Mostrar u ocultar campos de lista de miembros",
    "TooltipContentForMemberListFieldsHeading": "Muestra u oculta los campos de la lista de miembros en todos los componentes de la aplicación cuando corresponda.",
    "Top5ParticipantswithPointsLabel": "5 participantes principales con puntos",
    "Top5TournamentswithParticipantsLabel": "5 torneos principales con participantes",
    "TopChampionsLabel": "Principales expertos",
    "TotalActivitiesLabel": "Total de actividades",
    "TotalParticipantsLabel": "Total de participantes",
    "TotalPercentageCompletionLabel": "% de finalización total",
    "TotalPointsLabel": "Total de puntos",
    "TOTBreadcrumbLabel": "Torneo de equipos",
    "TOTLabel": "Torneo de equipos",
    "TOTLeaderBoardPageTitle": "Panel de clasificación",
    "TOTMyDashboardPageTitle": "Mi panel",
    "TournamentDescPlaceHolderLabel": "Descripción del torneo (máximo 500 caracteres)",
    "TournamentDescriptionLabel": "Descripción del torneo",
    "TournamentLabel": "Torneo",
    "TournamentNameErrorLabel": "Se requiere el nombre del torneo.",
    "TournamentNameLabel": "Nombre del torneo",
    "TournamentNamePlaceHolderLabel": "Nombre del torneo (máximo 255 caracteres)",
    "TournamentRankLabel": "Clasificación del torneo",
    "TournamentReportsPageTitle": "Informe de torneos",
    "UnauthorizedText": "No está cualificado para el Programa Distintivo de experto en este momento",
    "UploadFileButton": "Subir archivo",
    "UserAddedMessage": "El usuario se ha añadido correctamente.",
    "UserExistingMessage": "El usuario ya es un experto.",
    "UserLabel": "Usuario",
    "UserNominatedMessage": "El usuario se ha designado correctamente.",
    "ViewActivitiesLabel": "Ver actividades",
    "ViewDashBoardLabel": "Ver panel",
    "VisitLabel": "Visita las páginas de la Plataforma de administración de expertos para obtener más información:",
    "WelcomeLabel": "Bienvenido",
    "YesButton": "Sí",
  }
});