define([], function () {
  return {
  "PropertyPaneDescription": "Description",
  "BasicGroupName": "Nom du groupe",
  "DescriptionFieldLabel": "Champ de description",
  "SaveButton": "Enregistrer",
  "BackButton": "Précédent",
  "GetStartedLabel": "Prise en main",
  "AdminToolsLabel": "Outils d’administration",
  "ChampionLeaderBoardLabel": "Classement des champions",
  "AddMemberLabel": "Ajouter un membre",
  "NominateMemberLabel": "Désigner un membre",
  "DigitalBadgeLabel": "Badge numérique",
  "TOTLabel": "Tournoi des équipes",
  "ChampionListLabel": "Liste des champions",
  "EventsListLabel": "Liste d‘événements",
  "AdminTasksLabel": "Tâches d’administration",
  "ManageDigitalBadgesLabel": "Gérer les badges numériques",
  "EnableTOTLabel": "Activer le tournoi des équipes",
  "AddMembersToolTip": "L’ajout de membres commence à ajouter des personnes avec lesquelles vous collaborerez dans votre...",
  "DigitalMembersToolTip": "Obtenez votre badge numérique et appliquez-le à votre image de profil",
  "ChampionsListToolTip": "Accès à la liste des champions",
  "EventsListToolTip": "Accès à la liste des événements",
  "EnableTOTToolTip": "Activer le tournoi des équipes",
  "ManageDigitalBadgesToolTip": "Gérer les badges numériques",
  "WelcomeLabel": "Bienvenue",
  "ManageAppLogoLabel": "Gérer le logo de l’application",
  "ManageAppLogoToolTip": "Gérer le logo de l’application",
  "AppLogoToolTip": "Accueil",
  "MoreInfoToolTip": "Plus d'informations",
  "SupportToolTip": "Support",
  "FeedbackToolTip": "Commentaires",
  "AdditionalResourcesHeaderLabel": "Ressources Supplémentaires :",
  "AdditionalResourcesContentLabel": "Le groupe de promotion client Microsoft Teams se concentre sur la fourniture de solutions telles que celles-ci pour vous inspirez et vous aider à atteindre vos objectifs. Suivez ces autres ressources et rejoignez-les pour en savoir plus sur nous et la communauté :",
  "M365ChampionCommunityLinkLabel": "Communauté des champions Microsoft 365",
  "DrivingAdoptionLinkLabel": "Adoption de la conduite sur la Microsoft Technical Community",
  "CurrentVersionLabel": "Version actuelle :",
  "LatestVersionLabel": "Dernière version :",
  "CMPGitHubLinkLabel": "GitHub",
  "VisitLabel": "Visitez les pages de la plateforme de gestion des champions pour en savoir plus :",
  "OverviewLabel": "Vue d’ensemble et informations sur notre",
  "MSAdoptionHubLinkLabel": "Hub d’adoption de Microsoft",
  "DocumentationLabel": "Documentation technique de la solution et vue d’ensemble architecturale sur",
  "AddMemberPageTitle": "Ajouter un membre",
  "NominateMemberPageTitle": "Désigner un membre",
  "PeoplePickerPlaceholder": "Pour ajouter un membre, tapez le nom du membre",
  "FocusAreaPlaceholder": "Sélectionner une zone de focus",
  "UserExistingMessage": "L’utilisateur est déjà un champion !",
  "ChampionsListPageTitle": "Liste des champions",
  "UserNominatedMessage": "L’utilisateur a été correctement désigné !",
  "UserAddedMessage": "L’utilisateur a été correctement ajouté !",
  "PeopleNameGridHeader": "Nom du membre",
  "SelectChampion": "Sélectionner un champion",
  "SelectAll": "Sélectionner tous les champions",
  "FocusAreaGridHeader": "Zone de focus",
  "CountryGridHeader": "Pays",
  "RegionLabel": "Région",
  "StatusGridHeader": "État",
  "ActionGridHeader": "Action",
  "ApproveButton": "Approuver",
  "RejectButton": "Rejeter",
  "NoChampionsMessage": "Aucune demande en attente pour l’instant",
  "ChampionApprovedMessage": "Demande(s) de champion approuvée.",
  "ChampionRejectedMessage": "Demande(s) de champion rejetée.",
  "ProcessingSpinnerLabel": "Traitement en cours...",
  "DigitalBadgePageTitle": "Badge numérique",
  "LoadingSpinnerLabel": "Chargement est en cours... Merci de patienter.",
  "LoadingDigitalBadgeLabel": "Chargement du cadre du badge numérique",
  "DigitalBadgeAppBannerAltText": "Membres de l’équipe Microsoft s’engagent dans une discussion",
  "GroupGridHeader": "Groupe",
  "ShowHideToggle": "Afficher/masquer les champs de liste de membres",
  "ToggleView": "basculer",
  "SelectedFocusAreaLabel": "Zone de mise au point sélectionnée",
  "PreAcceptPageTitle": "Demandez votre badge numérique !",
  "PreAcceptDisclaimer": "<h2><span style='font-weight:bold;'>Bienvenue dans l’utilitaire de badge numérique</span></h2>",
  "PreAcceptDisclaimer1": "Dans le cadre de votre adhésion au Programme des champions, vous avez gagné un badge numérique ! Cet utilitaire vous permet de « <em>réclamer</em> » votre badge numérique en le superposant à votre image de profil existante.",
  "PreAcceptDisclaimer2": "Notez que cette opération mettra à jour votre photo de profil sur l’ensemble des Microsoft 365 (Exchange, Teams, SharePoint, etc.).",
  "PreAcceptDisclaimer3": "Si vous le souhaitez, <span style='font-weight:bold'>vous aurez la possibilité d’enregistrer une copie de votre image de profil existante</span> sans la superposition du badge numérique dans les étapes suivantes. Cliquez sur « Accepter » pour continuer (vous pouvez voir une fenêtre contextuelle ouverte et demander une connexion).",
  "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>Bienvenue dans l’utilitaire de badge numérique</span>. Dans le cadre de votre abonnement au programme Champions, vous pouvez gagner un badge numérique ! Cet utilitaire vous permet de « <em>demander</em> » votre badge numérique en la superposant en haut de votre photo de profil existante. Notez que cette opération mettra à jour votre image de profil sur l’ensemble de Microsoft 365 (Exchange, Teams, SharePoint, etc.)",
  "HowtoGetDigitalBadgeText": "Comment obtenir un badge de champion",
  "MultipleBadgeMessage": "Sélectionnez un badge dans la liste ci-dessous. Le badge sélectionné sera appliqué à votre photo de profil.",
  "NoBadgeMessage": "Aucun badge à sélectionner n’a été trouvé. Veuillez vérifier auprès de votre administrateur d’application.",
  "DigitalBadgeSubPageTitle": "Voici à quoi ressemblera votre badge numérique !",
  "ProfileImageAlt": "Mon image de profil utilisée dans O365, Teams, etc.",
  "BadgeImageAlt": "Trophée en forme de médaille avec la lettre C au milieu, ce qui signifie que je fais partie du Programme des champions",
  "NoProfileImageAlt": "Silhouette d’une personne, signe qu’aucune image de profil n’est actuellement appliquée à votre compte",
  "ApplyButtonText": "Appliquer une image",
  "ApplyButtonAriaDescription": "En cliquant sur ce bouton, vous autorisez le composant WebPart programme Champions à mettre à jour votre photo de profil en votre nom.",
  "ApplyButton": "Appliquer",
  "DownloadButtonText": "Télécharger",
  "DownloadButtonAriaDescription": "Cliquez pour télécharger votre image de profil actuelle",
  "DownloadingButtonText": "Téléchargement en cours...",
  "DownloadedButtonText": "Téléchargé",
  "DownloadedButtonSecondaryText": "L’image de votre profil téléchargée se trouve dans le dossier Téléchargements de votre appareil.",
  "DownloadButtonSecondaryText": "Télécharger votre image de profil actuelle",
  "PreApplyDisclaimer": "Il s’agit d’un aperçu de votre nouvelle photo de profil, notamment le badge numérique.  Si vous souhaitez télécharger votre photo de profil existante avant d’appliquer le badge numérique, cliquez sur le lien '<strong>Télécharger votre image de profil actuelle</strong>'.",
  "PreApplyDisclaimer1": "Cliquez sur Appliquer l’image pour mettre à jour votre image de profil Microsoft 365 avec cette nouvelle image. <strong> Notez que cette opération mettra à jour votre image de profil sur l’ensemble des Microsoft 365 et ne pourra pas être rétablie via cette page</strong>.",
  "PreApplyDisclaimer2": "Si vous souhaitez rétablir votre image, vous pouvez utiliser l’ <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' id='linkToChangeProfileImage'> Application web Outlook</a>.",
  "NoProfileImageDescription": "Si vous avez déjà associé une image à votre profil et que vous voyez toujours ce message, votre image n’est peut-être pas encore disponible. Réessayez plus tard ou contactez le <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>support technique</a> s’il n’apparaît toujours pas après 24 heures.",
  "AcceptButtonText": "Accepter",
  "AcceptButtonAriaDescription": "En cliquant sur ce bouton, vous autorisez le composant WebPart programme Champions à mettre à jour votre photo de profil en votre nom.",
  "UnauthorizedText": "Vous n’êtes pas qualifié pour le programme de badge des champions pour l’instant",
  "ApplySpinnerLabel": "Application en cours d’une nouvelle image de profil à votre compte...",
  "DigitalBadgeSuccessMessage": "<strong>Félicitations !</strong> Vous avez demandé votre badge numérique et votre photo de profil a été mise à jour. Veuillez patienter jusqu’à 24 heures pour voir la mise à jour reflétée dans toutes les applications Microsoft 365 (y compris Teams).",
  "BadgePointsTooltip": "Points requis pour déverrouiller :",
  "CMPSideBarPointsLabel": "Points",
  "CMPSideBarGlobalRankLabel": "Rang global",
  "CMPSideBarChampionsLabel": "Champions",
  "FirstNameLabel": "Prénom",
  "LastNameLabel": "Nom",
  "EmailIDLabel": "ID de l’adresse de courrier électronique",
  "BecomeChampionLabel": "Devenez un champion",
  "ChampionSubmissionPendingLabel": "Soumission du champion en attente",
  "ChampionRequestSubmitSuccessMessage": "Soumission de la demande de champion réussie",
  "PivotHeaderGlobal": "Global",
  "PivotHeaderNearMe": "Près de moi",
  "PivotHeaderBySpeciality": "Par spécialité",
  "NearMePlaceHolder": "Sélectionner près de moi",
  "BySpecialityPlaceHolder": "Sélectionner par spécialisation",
  "TopChampionsLabel": "Meilleurs champions",
  "RecordsNotFound": "Enregistrements non trouvés",
  "EventTypeLabel": "Type d'événement",
  "CountLabel": "Nombre",
  "MyRankLabel": "Mon rang",
  "SelectDate": "Sélectionnez une date",
  "NotesPlaceholder": "200 caractères maximum",
  "EventSubmissionPendingMessage": "Événement(s) soumis(s) pour approbation. Les points sont attribués une fois que les événements sont approuvés.",
  "EventsSubmissionSuccessMessage": "Événement(s) enregistré(s).",
  "ViewDashBoardLabel": "Afficher le tableau de bord",
  "DateofEventGridLabel": "Date de l’événement",
  "EventTypeGridLabel": "Type",
  "RecordEventLabel": "Enregistrer un événement",
  "MonthAndDateLabel": "Mois et jour",
  "EventTypeGridLabelPlaceHolder": "Sélectionner le type d’événement",
  "EventTypeValidationMessage": "Sélectionnez le type d’événement !",
  "CountValidationMessage": "Le nombre doit être compris entre 1 et 5",
  "EventsSubmitMessage": "Lorsque vous avez terminé d’ajouter des événements, cliquez sur le bouton Envoyer pour enregistrer.",
  "SubmitButton": "Soumettre",
  "SearchLabel": "Rechercher les meilleurs champions",
  "ActivitiesLabel": "Activités",
  "FocusAreaLabel": "Zone de focus",
  "ShowMoreLabel": "Afficher plus",
  "ViewActivitiesLabel": "Afficher les activités",
  "ChatIconLabel": "Conversation",
  "RequestToCallLabel": "Planifier une synchronisation",
  "EmailIconLabel": "Envoyer un message électronique",
  "MeetupSubject": "1:1 (Demande de champion)",
  "MeetupBody": "Réservez du temps pour discuter de votre zone de champion et en savoir plus !",
  "NoActivitiesinGridLabel": "Aucune activité trouvée !",
  "CreateTournamentPageTitle": "Créer un tournoi",
  "CreateTournamentSuccessLabel": "Le tournoi a été correctement créé.",
  "TournamentNameLabel": "Nom du tournoi",
  "TournamentNamePlaceHolderLabel": "Nom du tournoi (255 caractères max.)",
  "TournamentNameErrorLabel": "Le nom du tournoi est obligatoire.",
  "TournamentDescriptionLabel": "Description du tournoi",
  "TournamentDescPlaceHolderLabel": "Description du tournoi : (500 caractères maximum)",
  "SelectTeamsActionsLabel": "Sélectionner les actions Teams :",
  "TeamsActionInfoToolTip": "Sélectionnez parmi les actions Teams disponibles ci-dessous à inclure dans le nouveau tournoi. Pour ajouter de nouvelles actions de tournoi parmi les suivantes, visitez la section Gérer les actions du tournoi à partir des outils d’administration.",
  "ActionErrorLabel": "Sélectionnez au moins une action pour créer un tournoi.",
  "CreateTournamentButton": "Créer un tournoi",
  "DuplicateTournamentNameError": "Le nom du tournoi existe déjà. Entrez un autre nom pour le tournoi.",
  "CreateTournamentsButton": "Créer des tournois",
  "SingleTournamentLabel": "Tournoi unique",
  "MultipleTournamentLabel": "Plusieurs tournois",
  "MultiTournamentStep": "Étape",
  "MultiTournamentStep1LinkLabel": "Télécharger un modèle",
  "MultiTournamentStep1Text": " de format du fichier d’exemple",
  "MultiTournamentStep2": "Ajouter les détails du tournoi au fichier en suivant les instructions",
  "MultiTournamentStep3": "Télécharger le fichier",
  "UploadFileButton": "Charger un fichier",
  "RemoveFileLabel": "Supprimer le fichier",
  "ImportSpinnerMessage": "Création en cours de tournois.....",
  "ErrorMsgTournamentList": "Une erreur s’est produite lors de la création d’un élément dans la liste des tournois. Corrigez les données et réessayez.",
  "ErrorMsgActionsList": "Une erreur s’est produite lors de la création d’un élément dans la liste Actions. Corrigez les données et réessayez.",
  "ErrorMsgTournamentActionsList": "Une erreur s’est produite lors de la création d’un élément dans la liste d’actions du tournoi. Corrigez les données et réessayez.",
  "LogMsgTournamentExists": "Ignoré, car le tournoi",
  "LogMsgTournamentExists1": "existe déjà.",
  "LogMsgDone": "Tournoi",
  "LogMsgDone1": "date de création.",
  "LogMsgInvalidTournamentName": "Ignoré, car il n’a pas de nom de tournoi valide.",
  "LogMsgInvalidTemplate": "Ignoré, car il ne s’agit pas d’un modèle valide.",
  "LogMsgMultipleTournaments": "Ignoré, car il possède plusieurs noms de tournoi.",
  "LogMsgBlankSheet": "Ignoré, car il est vide.",
  "LogProgress": " Voici la progression :",
  "ImportRule1": "Ne pas modifier les en-têtes de colonne dans le modèle",
  "ImportRule2": "Ne pas supprimer des colonnes du modèle",
  "ImportRule3": "Entrer des données dans toutes les colonnes obligatoires (*) mentionnées dans le modèle",
  "ImportRule4": "Suivre la limite de caractères et le type mentionné dans le modèle pour chaque colonne",
  "ImportRule5": "Entrez les données d’un seul tournoi dans chaque feuille en fonction des exemples de données fournis",
  "ImportRule6": "Seuls 10 tournois peuvent être créés à la fois",
  "ImportRule7": "Vérifiez que le nom du tournoi est unique",
  "TOTBreadcrumbLabel": "Tournoi des équipes",
  "EnableTOTSuccessMessage": "Le tournoi des équipes a été activé. Actualisez l’application pour continuer.",
  "EnableTOTSpinnerMessage": "L’exécution de ce processus prendra quelques instants. Ne quittez pas l’application tant que le message n’est pas terminé.",
  "TOTLeaderBoardPageTitle": "Tableau d’honneur",
  "TOTMyDashboardPageTitle": "Mon tableau de bord",
  "ManageTournamentActionsToolTip": "Accès à la liste des actions du tournoi",
  "ManageTournamentActionsLabel": "Gérer les actions du tournoi",
  "ManageTournamentsLabel": "Gérer les tournois",
  "ManageAdminsToolTip": "Accès à la liste des administrateurs",
  "ManageAdminsLabel": "Gérer les administrateurs",
  "QuickLinksLabel": "Liens rapides",
  "SpinnerListCreationMessage": "Configuration en cours du tournoi des équipes...",
  "ManageTournamentsPageTitle": "Gérer les tournois",
  "ManageToTLabel1": "Vous pouvez démarrer plusieurs tournois à la fois. Consultez ci-dessous les tournois actifs actuels, la possibilité de terminer le tournoi, ainsi que la possibilité de démarrer un nouveau tournoi.",
  "ManageToTLabel2": "Une fois qu’un tournoi a été démarré et terminé, il ne sera plus disponible pour recommencer ; toutefois, vous pouvez créer un tournoi à l’aide des mêmes actions si vous souhaitez terminer un tournoi similaire !",
  "EndTournamentDialogMessage": "Voulez-vous vraiment terminer le tournoi ?",
  "StartTournamentDialogMessage": "Voulez-vous vraiment démarrer le ou les nouveaux tournois ?",
  "ConfirmLabel": "Confirmer",
  "YesButton": "Oui",
  "NoButton": "Non",
  "ActiveTournamentLabel": "Tournois actifs",
  "EndTournamentButton": "Terminer un tournoi",
  "StartTournamentHeaderLabel": "Démarrer le tournoi",
  "NoTournamentMessage": "Aucun tournoi trouvé. Réessayer plus tard.",
  "SelectTournamentMessage": "Sélectionnez au moins un tournoi pour commencer.",
  "SelectEndTournamentMessage": "Sélectionnez un tournoi à terminer.",
  "StartTournamentButton": "Démarrer le(s) tournoi(s)",
  "EndTournamentSuccessMessage": "Le tournoi s’est correctement terminé.",
  "EnableTournamentSuccessMessage": "Le(s) tournoi(s) ont démarré avec succès.",
  "CompleteTournamentSpinnerMessage": "Fin du tournoi...",
  "EnableTournamentSpinnerMessage": "Activation du ou des tournois...",
  "SearchActiveTournaments": "Rechercher dans les tournois actifs",
  "SearchPendingTournaments": "Rechercher dans les tournois pour commencer",
  "SelectAllLabel": "Sélectionner tout",
  "NoSearchResults": "Aucun résultat ne correspond à votre recherche.",
  "NoActiveParticipantsMessage": "Il n’y a aucun participant actif pour le moment. Soyez le premier à participer et à enregistrer une activité à partir de Mon tableau de bord !",
  "NoActiveTournamentMessage": "Aucun tournoi actif pour le moment. Veuillez réessayer plus tard.",
  "TournamentLabel": "Tournoi",
  "DescriptionLabel": "Description",
  "NoActiveParticipantsErrorMessage": "Il n’y a aucun participant actif pour le moment. Soyez le premier à participer et à enregistrer une activité à partir de ",
  "PendingActionsLabel": "Actions en attente",
  "PendingActionsSuccessMessage": "Il n’y a plus d’actions en attente dans ce tournoi.",
  "SelectActionsErrorMessage": "Sélectionnez au moins une action pour continuer.",
  "FormSavingMessage": "Enregistrement en cours de vos détails....",
  "CompletedActionsLabel": "Actions terminées.",
  "RankLabel": "Classement",
  "UserLabel": "Utilisateur",
  "MyDashboardInfoIconMessage": "En savoir plus sur cette action",
  "SelectTournamentPlaceHolder": "Sélectionner un tournoi",
  "MyTournamentsLabel": "Mes tournois",
  "OrLabel": "OU",
  "MyTournamentsTooltip": "Tournois actifs auxquels vous avez déjà participé",
  "PointsLabel": "Points",
  "TournamentRankLabel": "Classement du tournoi",
  "ParticipantsLabel": "Participants",
  "TournamentReportsPageTitle": "Rapport sur les tournois",
  "TotalActivitiesLabel": "Nombre total d’activités",
  "TotalPointsLabel": "Nombre total de points",
  "TotalParticipantsLabel": "Nombre total de participants",
  "TotalPercentageCompletionLabel": "% de l’achèvement total",
  "Top5ParticipantswithPointsLabel": "5 premiers participants avec points",
  "Top5TournamentswithParticipantsLabel": "Top 5 des tournois avec des participants",
  "ParticipantsStatusLabel": "État des participants",
  "ParticipantsDetailsLabel": "Détails des participants",
  "NameLabel": "Nom",
  "PercentageTournamentCompletedLabel": "Pourcentage du tournoi terminé",
  "ActivitiesCompletedLabel": "Activités terminées",
  "NoRecordsinGridLabel": "Nous n’avons trouvé aucun enregistrement.",
  "SearchPlaceholder": "Rechercher par nom de participant",
  "NoCompletedTournamentsMessage": "Aucun tournoi n’est terminé pour le moment. Veuillez réessayer plus tard.",
  "ReportsDropdownInfoIconText": "Le rapport ne peut être généré que pour les tournois terminés.",
  "RefreshIconInfoText": "Cliquez sur Actualiser pour afficher les données les plus récentes",
  "EventApprovedMessage": "Événement(s) champion(s) approuvé(s).",
  "EventRejectedMessage": "Événement(s) champion(s) rejeté(s).",
  "SelectAllEvents": "Sélectionner tous les événements",
  "SelectEvent": "Sélectionner un événement",
  "ChampionLabel": "Champion",
  "EmailLabel": "E-mail",
  "EventLabel": "Événement",
  "DateLabel": "Date",
  "NotesLabel": "Notes",
  "SuccessIcon": "Icône de réussite",
  "PendingEventsSearchboxPlaceholder": "Rechercher par champion/e-mail",
  "NoRecordsIcon": "Icône Aucun enregistrement",
  "NoPendingEventsLabel": "Aucun événement en attente pour l’instant.",
  "ChampionActivitiesLabel": "Activités du champion",
  "ManageConfigSettingsLabel": "Gérer les paramètres de configuration",
  "ApproveChampionSearchboxPlaceholder": "Rechercher par nom de membre/e-mail",
  "EventsApprovalInfoIconTooltipContent": "L’activation de cette option nécessite que les soumissions d’événements par les champions soient approuvées par un administrateur. Les points pour les événements ne seront attribués qu’après l’approbation.",
  "ConfigSettingsSaved": "Paramètres de configuration enregistrés.",
  "EventApprovalsEnableLabel": "Activer les approbations d’événements champion",
  "EventsSelectedLabel": "Événement(s) sélectionné(s).",
  "ChampionsSelectedLabel": "Champion(s) sélectionné(s).",
  "ToggleLabelForMemberListColumns": "Afficher/masquer les champs de liste de membres",
  "TooltipContentForMemberListFieldsHeading": "Afficher/masquer les champs de liste de membres dans tous les composants de l’application, le cas échéant.",
  "ChampionReportLabel": "Rapport sur les champions",
  "ChampionReportToolTip": "Rapport sur les champions",
  "TotalChampionsLabel": "Total Champions",
  "ClearButton": "Effacer",
  "FilterbyDateLabel": "Filtrer par date",
  "EventTypesHeading": "Types d’événements",
  "NoEventsMessage": "Aucun événement n’est terminé pour le moment. Veuillez réessayer plus tard.",
  "NoEventsFoundMessage": "Événements introuvables !",
  "AppTitleLabel": "Titre de l’application",
  "AppTitleErrorLabel": "Le titre de l’application est obligatoire.",
  "AppTitlePlaceholderText": "30 caractères maximum",
  "AppTitleInfoIconText": "Le titre de l’application apparaîtra dans la section d’en-tête et les sections de barre de navigation de l’application",
  "AboutContentLabel": "a été créé avec les champions de l’organisation et les spécialistes de l’adoption à l’esprit. À l’écoute de la communauté Microsoft 365 Champion, cette application a été développée pour fournir une plateforme permettant de créer et de soutenir vos propres communautés. Commencez par l’inspiration grâce à l’exécution pour vous aider à gagner en ressources au sein de vos propres communautés !",
  "AboutHeaderLabel": "À propos du",
  "DashboardLabel": "Tableau de bord",
  "RemoveEventLabel": "Supprimer l’événement",
  "AddEventLabel": "Ajouter un événement",
  "EventChartLabel": "Top 10 des événements avec des types d’événements",
  "FromLabel": "De",
  "ToLabel": "À",
  "AllTime": "Tout l’historique",
  "LastMonth": "Le mois dernier",
  "Last3Months": "3 derniers mois",
  "Last6Months": "6 derniers mois",
  "Last1Year": "Année dernière",
  "SelectaCustomDate": "Sélectionner une date personnalisée",
  "championRecordsFoundLabel": "Enregistrements de champion trouvés",
  "digitalBadgeProfileAriaLabel": "Ouvrir l’application web Outlook dans un nouvel onglet ou une nouvelle fenêtre de navigateur",
  "AddMemberAsAdminLabel": "Ajouter un membre en tant qu’administrateur",
  "NoteValidationMessage": "Les notes ne doivent pas dépasser 200 caractères",
  "CloseInfoPopoverButton": "Fermer"
  }
});
