define([], function () {
    return {
      "PropertyPaneDescription": "Description",
      "BasicGroupName": "Nom du groupe",
      "DescriptionFieldLabel": "Champ de description",
      "CMPBreadcrumbLabel": "Plateforme de gestion des champions",
      "SaveButton": "Enregistrer",
      "BackButton": "Précédent",
      "GetStartedLabel": "Prise en main",
      "AdminToolsLabel": "Outils d’administration",
      "ChampionLeaderBoardLabel": "Classement des champions",
      "AddMemberLabel": "Ajouter un membre",
      "NominateMemberLabel": "Désigner un membre",
      "DigitalBadgeLabel": "Badge numérique",
      "TOTLabel": "Tournoi de Teams",
      "ChampionListLabel": "Liste des champions",
      "EventsListLabel": "Liste d‘événements",
      "EventsTrackListLabel": "Liste de suivi des événements",
      "ManageApprovalsLabel": "Gérer les approbations",
      "ManageDigitalBadgesLabel": "Gérer les badges numériques",
      "EnableTOTLabel": "Activer le tournoi de Teams",
      "AddMembersToolTip": "L’ajout de membres commence à ajouter des personnes avec lesquelles vous collaborerez dans votre...",
      "DigitalMembersToolTip": "Obtenez votre badge numérique et appliquez-le à votre image de profil",
      "ChampionsListToolTip": "Accès à la liste des champions",
      "EventsListToolTip": "Accès à la liste des événements",
      "EventTrackListToolTip": "Accès à la liste du suivi des événements",
      "ManageApprovalToolTip": "Approuver le champion",
      "EnableTOTToolTip": "Activer le tournoi de Teams",
      "ManageDigitalBadgesToolTip": "Gérer les badges numériques",
      "WelcomeLabel": "Bienvenue",
      "ManageAppLogoLabel": "Gérer le logo de l’application",
      "ManageAppLogoToolTip": "Gérer le logo de l’application",
      "AppHeaderTitleLabel": "Plateforme de gestion des champions",
      "AppLogoToolTip": "Accueil",
      "MoreInfoToolTip": "Plus d'informations",
      "SupportToolTip": "Support",
      "FeedbackToolTip": "Commentaires",
      "AboutHeaderLabel": "À propos de la Plateforme de gestion des champions (CMP) :",
      "AboutContentLabel": "Notre plateforme de gestion des champions a été créée avec à l’esprit les spécialistes de l’adoption et les champions de l’organisation. Après avoir recueilli les commentaires de la Communauté des champions Microsoft 365, cette application a été créée pour fournir une plateforme vous permettant de créer et supporter vos propres communautés. Commencez par l’inspiration grâce à l’exécution pour vous aider à gagner en productivité au sein de vos propres communautés !",
      "AdditionalResourcesHeaderLabel": "Ressources Supplémentaires :",
      "AdditionalResourcesContentLabel": "Le groupe de promotion client Microsoft Teams se concentre sur la fourniture de solutions telles que celles-ci pour vous inspirez et vous aider à atteindre vos objectifs. Suivez ces autres ressources et rejoignez-les pour en savoir plus sur nous et la communauté :",
      "M365ChampionCommunityLinkLabel": "Communauté des champions Microsoft 365",
      "DrivingAdoptionLinkLabel": "Adoption de la conduite sur la Microsoft Technical Community",
      "CurrentVersionLabel": "Version actuelle :",
      "LatestVersionLabel": "Dernière version :",
      "CMPGitHubLinkLabel": "GitHub",
      "VisitLabel": "Visitez les pages de la plateforme de gestion des champions pour en savoir plus :",
      "OverviewLabel": "Vue d’ensemble et informations sur notre",
      "MSAdoptionHubLinkLabel": "Microsoft Adoption Hub",
      "DocumentationLabel": "Documentation technique de la solution et vue d’ensemble architecturale sur",
      "AddMemberPageTitle": "Ajouter un membre",
      "NominateMemberPageTitle": "Désigner un membre",
      "PeoplePickerPlaceholder": "Pour ajouter un membre, tapez le nom du membre",
      "RegionPlaceholder": "Sélectionnez une région",
      "CountryPlaceholder": "Sélectionner un pays",
      "GroupPlaceholder": "Sélectionner un groupe",
      "FocusAreaPlaceholder": "Sélectionner une zone de focus",
      "UserExistingMessage": "L’utilisateur est déjà un champion !",
      "ChampionsListPageTitle": "Liste des champions",
      "UserNominatedMessage": "L’utilisateur a été correctement désigné !",
      "UserAddedMessage": "L’utilisateur a été correctement ajouté !",
      "PeopleNameGridHeader": "Nom du membre",
      "Select": "Sélectionner",
      "SelectAll": "Sélectionner tout",
      "RegionGridHeader": "Région",
      "CountryGridHeader": "Pays",
      "GroupGridHeader": "Groupe",
      "FocusAreaGridHeader": "Zone de focus",
      "StatusGridHeader": "État",
      "ManageApprovalsPageTitle": "Gérer les approbations",
      "ActionGridHeader": "Action",
      "ApproveButton": "Approuver",
      "RejectButton": "Rejeter",
      "NoChampionsMessage": "Aucune demande en attente pour l’instant",
      "ChampionApprovedMessage": "Demande(s) de champion approuvée!",
      "ChampionRejectedMessage": "Demande(s) de champion rejetée!",
      "ProcessingSpinnerLabel": "Traitement en cours...",
      "DigitalBadgePageTitle": "Badge numérique",
      "LoadingSpinnerLabel": "Chargement est en cours... Merci de patienter.",
      "DigitalBadgeAppBannerAltText": "Membres de l’équipe Microsoft s’engagent dans une discussion",
      "PreAcceptPageTitle": "Demandez votre badge numérique !",
      "PreAcceptDisclaimer": "<span style='font-weight:bold;'>Bienvenue dans l’utilitaire de badge numérique</span> <br/><br/> <span>Dans le cadre de votre abonnement au programme Champions, vous avez gagné un badge numérique ! Cet utilitaire vous permet de « <em>demander</em> » votre badge numérique en la superposant en haut de votre photo de profil existante. <br/><br/> Notez que cette opération mettra à jour votre image de profil sur l’ensemble de Microsoft 365 (Exchange, Teams, SharePoint, etc.).</span>",
      "PreAcceptDisclaimer2": "Si vous le souhaitez, <span style='font-weight:bold;'>vous aurez la possibilité d’enregistrer une copie de votre image de profil existante</span> sans la superposition du badge numérique dans les étapes suivantes. Cliquez sur « Accepter » pour continuer (vous pouvez voir une fenêtre contextuelle ouverte et demander une connexion).",
      "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>Bienvenue dans l’utilitaire de badge numérique</span>. Dans le cadre de votre abonnement au programme Champions, vous pouvez gagner un badge numérique ! Cet utilitaire vous permet de « <em>demander</em> » votre badge numérique en la superposant en haut de votre photo de profil existante. Notez que cette opération mettra à jour votre image de profil sur l’ensemble de Microsoft 365 (Exchange, Teams, SharePoint, etc.)",
      "HowtoGetDigitalBadgeText": "Comment obtenir un badge de champion",
      "MultipleBadgeMessage": "Sélectionnez un badge dans la liste ci-dessous. Le badge sélectionné sera appliqué à votre photo de profil.",
      "NoBadgeMessage": "Aucun badge à sélectionner n’a été trouvé. Veuillez vérifier auprès de votre administrateur d’application.",
      "DigitalBadgeSubPageTitle": "Voici à quoi ressemblera votre badge numérique !",
      "ProfileImageAlt": "Mon image de profil utilisée dans O365, Teams, etc.",
      "BadgeImageAlt": "Trophée en forme de médaille avec la lettre C au milieu, ce qui signifie que je fais partie du Programme des champions",
      "NoProfileImageAlt": "Silhouette d’une personne, signe qu’aucune image de profil n’est actuellement appliquée à votre compte",
      "ApplyButtonText": "Appliquer une image",
      "ApplyButtonAriaDescription": "En cliquant sur ce bouton, vous autorisez le composant WebPart programme Champions à mettre à jour votre photo de profil en votre nom.",
      "ApplyButton": "Appliquer",
      "DownloadButtonText": "Télécharger",
      "DownloadButtonAriaDescription": "Cliquez pour télécharger votre image de profil actuelle",
      "DownloadingButtonText": "Téléchargement en cours...",
      "DownloadedButtonText": "Téléchargé",
      "DownloadedButtonSecondaryText": "L’image de votre profil téléchargée se trouve dans le dossier Téléchargements de votre appareil.",
      "DownloadButtonSecondaryText": "Télécharger votre image de profil actuelle",
      "PreApplyDisclaimer": "Il s’agit d’un aperçu de votre nouvelle photo de profil, notamment le badge numérique. Si vous souhaitez télécharger votre photo de profil existante avant d’appliquer le badge numérique, cliquez sur le lien '<strong>Télécharger votre image de profil actuelle</strong>'.<br />",
      "PreApplyDisclaimer1": "<br />En cliquant sur « Appliquer l’image », vous mettrez à jour votre image de profil Microsoft 365 avec cette nouvelle image. <strong>Veuillez noter que cette opération va mettre à jour votre image de profil sur l’ensemble de Microsoft 365 et ne peut pas être rétablie via cette page</strong>. <br/><br/>Si vous souhaitez rétablir votre image, vous pouvez utiliser l’<a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' aria-label='Open the Outlook web application in a new browser tab or window'>application web Outlook</a>.",
      "NoProfileImageDescription": "Si vous avez déjà associé une image à votre profil et que vous voyez toujours ce message, votre image n’est peut-être pas encore disponible. Réessayez plus tard ou contactez le <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>support technique</a> s’il n’apparaît toujours pas après 24 heures.",
      "AcceptButtonText": "Accepter",
      "AcceptButtonAriaDescription": "En cliquant sur ce bouton, vous autorisez le composant WebPart programme Champions à mettre à jour votre photo de profil en votre nom.",
      "UnauthorizedText": "Vous n’êtes pas qualifié pour le programme de badge des champions pour l’instant",
      "ApplySpinnerLabel": "Application en cours d’une nouvelle image de profil à votre compte...",
      "DigitalBadgeSuccessMessage": "<strong>Félicitations !</strong> Vous avez demandé votre badge numérique et votre photo de profil a été mise à jour. Veuillez patienter jusqu’à 24 heures pour voir la mise à jour reflétée dans toutes les applications Microsoft 365 (y compris Teams).",
      "CMPSideBarPointsLabel": "Points",
      "CMPSideBarGlobalRankLabel": "Rang global",
      "CMPSideBarChampionsLabel": "Champions",
      "FirstNameLabel": "Prénom",
      "LastNameLabel": "Nom",
      "EmailIDLabel": "ID de l’adresse de courrier électronique",
      "BecomeChampionLabel": "Devenez un champion",
      "ChampionSubmissionPendingLabel": "Soumission du champion en attente",
      "ChampionRequestSubmitSuccessMessage": "Soumission de la demande de champion réussie",
      "PivotHeaderGlobal": "Global",
      "PivotHeaderNearMe": "Près de moi",
      "PivotHeaderBySpeciality": "Par spécialité",
      "NearMePlaceHolder": "Sélectionner près de moi",
      "BySpecialityPlaceHolder": "Sélectionner par spécialisation",
      "TopChampionsLabel": "Meilleurs champions",
      "RecordsNotFound": "Enregistrements non trouvés",
      "EventTypeLabel": "Type d'événement",
      "CountLabel": "Nombre",
      "MyRankLabel": "Mon rang",
      "ViewDashBoardLabel": "Afficher le tableau de bord",
      "DateofEventGridLabel": "Date de l’événement",
      "EventTypeGridLabel": "Type",
      "RecordEventLabel": "Enregistrer un événement",
      "MonthAndDateLabel": "Mois et jour",
      "EventTypeGridLabelPlaceHolder": "Sélectionner le type d’événement",
      "EventTypeValidationMessage": "Sélectionnez le type d’événement !",
      "CountValidationMessage": "Le nombre doit être compris entre 1 et 5",
      "EventsSubmitMessage": "Lorsque vous avez terminé d’ajouter des événements, cliquez sur le bouton Envoyer pour enregistrer.",
      "SubmitButton": "Soumettre",
      "SearchLabel": "Recherche",
      "ActivitiesLabel": "Activités",
      "RegionLabel": "Région",
      "FocusAreaLabel": "Zone de focus",
      "ShowMoreLabel": "Afficher plus",
      "ViewActivitiesLabel": "Afficher les activités",
      "ChatIconLabel": "Conversation",
      "RequestToCallLabel": "Demander à passer un appel",
      "EmailIconLabel": "Envoyer un message électronique",
      "MeetupSubject": "1:1 (Demande de champion)",
      "MeetupBody": "Réservez du temps pour discuter de votre zone de champion et en savoir plus !",
      "NoActivitiesinGridLabel": "Aucune activité trouvée !",
      "CreateTournamentPageTitle": "Créer un tournoi",
      "CreateTournamentSuccessLabel": "Le tournoi a été correctement créé.",
      "TournamentNameLabel": "Nom du tournoi",
      "TournamentNamePlaceHolderLabel": "Nom du tournoi (255 caractères max.)",
      "TournamentNameErrorLabel": "Le nom du tournoi est obligatoire.",
      "TournamentDescriptionLabel": "Description du tournoi",
      "TournamentDescPlaceHolderLabel": "Description du tournoi : (500 caractères maximum)",
      "SelectTeamsActionsLabel": "Sélectionner les actions Teams :",
      "TeamsActionInfoToolTip": "Sélectionnez parmi les actions Teams disponibles ci-dessous à inclure dans le nouveau tournoi. Pour ajouter de nouvelles actions de tournoi parmi les suivantes, visitez la section Gérer les actions du tournoi à partir des outils d’administration.",
      "ActionErrorLabel": "Sélectionnez au moins une action pour créer un tournoi.",
      "CreateTournamentButton": "Créer un tournoi",
      "DuplicateTournamentNameError": "Le nom du tournoi existe déjà. Entrez un autre nom pour le tournoi.",
      "CreateTournamentsButton": "Créer des tournois",
      "SingleTournamentLabel": "Tournoi unique",
      "MultipleTournamentLabel": "Plusieurs tournois",
      "MultiTournamentStep": "Étape",
      "MultiTournamentStep1LinkLabel": "Télécharger un modèle",
      "MultiTournamentStep1Text": " de format du fichier d’exemple",
      "MultiTournamentStep2": "Ajouter les détails du tournoi au fichier en suivant les instructions",
      "MultiTournamentStep3": "Télécharger le fichier",
      "UploadFileButton": "Charger un fichier",
      "RemoveFileLabel": "Supprimer le fichier",
      "ImportSpinnerMessage": "Création en cours de tournois.....",
      "ErrorMsgTournamentList": "Une erreur s’est produite lors de la création d’un élément dans la liste des tournois. Corrigez les données et réessayez.",
      "ErrorMsgActionsList": "Une erreur s’est produite lors de la création d’un élément dans la liste Actions. Corrigez les données et réessayez.",
      "ErrorMsgTournamentActionsList": "Une erreur s’est produite lors de la création d’un élément dans la liste d’actions du tournoi. Corrigez les données et réessayez.",
      "LogMsgTournamentExists": "Ignoré, car le tournoi",
      "LogMsgTournamentExists1": "existe déjà.",
      "LogMsgDone": "Tournoi",
      "LogMsgDone1": "date de création.",
      "LogMsgInvalidTournamentName": "Ignoré, car il n’a pas de nom de tournoi valide.",
      "LogMsgInvalidTemplate": "Ignoré, car il ne s’agit pas d’un modèle valide.",
      "LogMsgMultipleTournaments": "Ignoré, car il possède plusieurs noms de tournoi.",
      "LogMsgBlankSheet": "Ignoré, car il est vide.",
      "LogProgress": " Voici la progression :",
      "ImportRule1": "Ne pas modifier les en-têtes de colonne dans le modèle",
      "ImportRule2": "Ne pas supprimer des colonnes du modèle",
      "ImportRule3": "Entrer des données dans toutes les colonnes obligatoires (*) mentionnées dans le modèle",
      "ImportRule4": "Suivre la limite de caractères et le type mentionné dans le modèle pour chaque colonne",
      "ImportRule5": "Entrez les données d’un seul tournoi dans chaque feuille en fonction des exemples de données fournis",
      "ImportRule6": "Seuls 10 tournois peuvent être créés à la fois",
      "ImportRule7": "Vérifiez que le nom du tournoi est unique",
      "TOTBreadcrumbLabel": "Tournoi de Teams",
      "EnableTOTSuccessMessage": "Le tournoi de Teams a été activé. Actualisez l’application pour continuer.",
      "EnableTOTSpinnerMessage": "L’exécution de ce processus prendra quelques instants. Ne quittez pas l’application tant que le message n’est pas terminé.",
      "TOTLeaderBoardPageTitle": "Tableau d’honneur",
      "TOTMyDashboardPageTitle": "Mon tableau de bord",
      "ManageTournamentActionsToolTip": "Accès à la liste des actions du tournoi",
      "ManageTournamentActionsLabel": "Gérer les actions du tournoi",
      "ManageTournamentsLabel": "Gérer les tournois",
      "ManageAdminsToolTip": "Accès à la liste des administrateurs",
      "ManageAdminsLabel": "Gérer les administrateurs",
      "QuickLinksLabel": "Liens rapides",
      "SpinnerListCreationMessage": "Configuration en cours du tournoi de Teams...",
      "ManageTournamentsPageTitle": "Gérer les tournois",
      "ManageToTLabel1": "Vous pouvez démarrer plusieurs tournois à la fois. Consultez ci-dessous les tournois actifs actuels, la possibilité de terminer le tournoi, ainsi que la possibilité de démarrer un nouveau tournoi.",
      "ManageToTLabel2": "Une fois qu’un tournoi a été démarré et terminé, il ne sera plus disponible pour recommencer ; toutefois, vous pouvez créer un tournoi à l’aide des mêmes actions si vous souhaitez terminer un tournoi similaire !",
      "EndTournamentDialogMessage": "Voulez-vous vraiment terminer le tournoi ?",
      "StartTournamentDialogMessage": "Voulez-vous vraiment démarrer le ou les nouveaux tournois ?",
      "ConfirmLabel": "Confirmer",
      "YesButton": "Oui",
      "NoButton": "Non",
      "ActiveTournamentLabel": "Tournois actifs",
      "EndTournamentButton": "Terminer un tournoi",
      "StartTournamentHeaderLabel": "Démarrer le tournoi",
      "NoTournamentMessage": "Aucun tournoi trouvé. Réessayer plus tard.",
      "SelectTournamentMessage": "Sélectionnez au moins un tournoi pour commencer.",
      "SelectEndTournamentMessage": "Sélectionnez un tournoi à terminer.",
      "StartTournamentButton": "Démarrer le(s) tournoi(s)",
      "EndTournamentSuccessMessage": "Le tournoi s’est correctement terminé.",
      "EnableTournamentSuccessMessage": "Le(s) tournoi(s) ont démarré avec succès.",
      "CompleteTournamentSpinnerMessage": "Fin du tournoi...",
      "EnableTournamentSpinnerMessage": "Activation du ou des tournois...",
      "SearchActiveTournaments": "Rechercher dans les tournois actifs",
      "SearchPendingTournaments": "Rechercher dans les tournois pour commencer",
      "SelectAllLabel": "Sélectionner tout",
      "NoSearchResults": "Aucun résultat ne correspond à votre recherche.",
      "NoActiveParticipantsMessage": "Il n’y a aucun participant actif pour le moment. Soyez le premier à participer et à enregistrer une activité à partir de Mon tableau de bord !",
      "NoActiveTournamentMessage": "Aucun tournoi actif pour le moment. Veuillez réessayer plus tard.",
      "TournamentLabel": "Tournoi",
      "DescriptionLabel": "Description",
      "NoActiveParticipantsErrorMessage": "Il n’y a aucun participant actif pour le moment. Soyez le premier à participer et à enregistrer une activité à partir de ",
      "PendingActionsLabel": "Actions en attente",
      "PendingActionsSuccessMessage": "Il n’y a plus d’actions en attente dans ce tournoi.",
      "SelectActionsErrorMessage": "Sélectionnez au moins une action pour continuer.",
      "FormSavingMessage": "Enregistrement en cours de vos détails....",
      "CompletedActionsLabel": "Actions terminées.",
      "RankLabel": "Classement",
      "UserLabel": "Utilisateur",
      "MyDashboardInfoIconMessage": "En savoir plus sur cette action",
      "SelectTournamentPlaceHolder": "Sélectionner un tournoi",
      "MyTournamentsLabel": "Mes tournois",
      "OrLabel": "OU",
      "MyTournamentsTooltip": "Tournois actifs auxquels vous avez déjà participé",
      "PointsLabel": "Points",
      "TournamentRankLabel": "Classement du tournoi",
      "ParticipantsLabel": "Participants",
      "TournamentReportsPageTitle": "Rapport sur les tournois",
      "TotalActivitiesLabel": "Nombre total d’activités",
      "TotalPointsLabel": "Nombre total de points",
      "TotalParticipantsLabel": "Nombre total de participants",
      "TotalPercentageCompletionLabel": "% de l’achèvement total",
      "Top5ParticipantswithPointsLabel": "5 premiers participants avec points",
      "Top5TournamentswithParticipantsLabel": "Top 5 des tournois avec des participants",
      "ParticipantsStatusLabel": "État des participants",
      "ParticipantsDetailsLabel": "Détails des participants",
      "NameLabel": "Nom",
      "PercentageTournamentCompletedLabel": "Pourcentage du tournoi terminé",
      "ActivitiesCompletedLabel": "Activités terminées",
      "NoRecordsinGridLabel": "Nous n’avons trouvé aucun enregistrement.",
      "SearchPlaceholder": "Rechercher par nom de participant",
      "NoCompletedTournamentsMessage": "Aucun tournoi n’est terminé pour le moment. Veuillez réessayer plus tard.",
      "ReportsDropdownInfoIconText": "Le rapport ne peut être généré que pour les tournois terminés.",
      "RefreshIconInfoText": "Cliquez sur Actualiser pour afficher les données les plus récentes"
    }

});