define([], function () {
  return {
    "AboutContentLabel": "Notre plateforme de gestion des champions a été créée avec à l’esprit les spécialistes de l’adoption et les champions de l’organisation. Après avoir recueilli les commentaires de la Communauté des champions Microsoft 365, cette application a été créée pour fournir une plateforme vous permettant de créer et supporter vos propres communautés. Commencez par l’inspiration grâce à l’exécution pour vous aider à gagner en productivité au sein de vos propres communautés !",
    "AboutHeaderLabel": "À propos de la Plateforme de gestion des champions (CMP) :",
    "AcceptButtonAriaDescription": "En cliquant sur ce bouton, vous autorisez le composant WebPart programme Champions à mettre à jour votre photo de profil en votre nom.",
    "AcceptButtonText": "Accepter",
    "ActionErrorLabel": "Sélectionnez au moins une action pour créer un tournoi.",
    "ActionGridHeader": "Action",
    "ActiveTournamentLabel": "Tournois actifs",
    "ActivitiesCompletedLabel": "Activités terminées",
    "ActivitiesLabel": "Activités",
    "AdditionalResourcesContentLabel": "Le groupe de promotion client Microsoft Teams se concentre sur la fourniture de solutions telles que celles-ci pour vous inspirez et vous aider à atteindre vos objectifs. Suivez ces autres ressources et rejoignez-les pour en savoir plus sur nous et la communauté :",
    "AdditionalResourcesHeaderLabel": "Ressources Supplémentaires :",
    "AddMemberLabel": "Ajouter un membre",
    "AddMemberPageTitle": "Ajouter un membre",
    "AddMembersToolTip": "L’ajout de membres commence à ajouter des personnes avec lesquelles vous collaborerez dans votre...",
    "AdminTasksLabel": "Tâches d’administration",
    "AdminToolsLabel": "Outils d’administration",
    "AppHeaderTitleLabel": "Plateforme de gestion des champions",
    "AppLogoToolTip": "Accueil",
    "ApplyButton": "Appliquer",
    "ApplyButtonAriaDescription": "En cliquant sur ce bouton, vous autorisez le composant WebPart programme Champions à mettre à jour votre photo de profil en votre nom.",
    "ApplyButtonText": "Appliquer une image",
    "ApplySpinnerLabel": "Application en cours d’une nouvelle image de profil à votre compte...",
    "ApproveButton": "Approuver",
    "ApproveChampionSearchboxPlaceholder": "Rechercher par nom de membre/e-mail",
    "BackButton": "Précédent",
    "BadgeImageAlt": "Trophée en forme de médaille avec la lettre C au milieu, ce qui signifie que je fais partie du Programme des champions",
    "BadgePointsTooltip": "Points requis pour déverrouiller :",
    "BasicGroupName": "Nom du groupe",
    "BecomeChampionLabel": "Devenez un champion",
    "BySpecialityPlaceHolder": "Sélectionner par spécialisation",
    "ChampionActivitiesLabel": "Activités du champion",
    "ChampionApprovedMessage": "Demande(s) de champion approuvée.",
    "ChampionLabel": "Champion",
    "ChampionLeaderBoardLabel": "Classement des champions",
    "ChampionListLabel": "Liste des champions",
    "ChampionRejectedMessage": "Demande(s) de champion rejetée.",
    "ChampionRequestSubmitSuccessMessage": "Soumission de la demande de champion réussie",
    "ChampionsListPageTitle": "Liste des champions",
    "ChampionsListToolTip": "Accès à la liste des champions",
    "ChampionsSelectedLabel": "Champion(s) sélectionné(s).",
    "ChampionSubmissionPendingLabel": "Soumission du champion en attente",
    "ChatIconLabel": "Conversation",
    "CMPBreadcrumbLabel": "Plateforme de gestion des champions",
    "CMPGitHubLinkLabel": "GitHub",
    "CMPSideBarChampionsLabel": "Champions",
    "CMPSideBarGlobalRankLabel": "Rang global",
    "CMPSideBarPointsLabel": "Points",
    "CompletedActionsLabel": "Actions terminées.",
    "CompleteTournamentSpinnerMessage": "Fin du tournoi...",
    "ConfigSettingsSaved": "Paramètres de configuration enregistrés.",
    "ConfirmLabel": "Confirmer",
    "CountLabel": "Nombre",
    "CountryGridHeader": "Pays",
    "CountryPlaceholder": "Sélectionner un pays",
    "CountValidationMessage": "Le nombre doit être compris entre 1 et 5",
    "CreateTournamentButton": "Créer un tournoi",
    "CreateTournamentPageTitle": "Créer un tournoi",
    "CreateTournamentsButton": "Créer des tournois",
    "CreateTournamentSuccessLabel": "Le tournoi a été correctement créé.",
    "CurrentVersionLabel": "Version actuelle :",
    "DateLabel": "Date",
    "DateofEventGridLabel": "Date de l’événement",
    "DescriptionFieldLabel": "Champ de description",
    "DescriptionLabel": "Description",
    "DigitalBadgeAppBannerAltText": "Membres de l’équipe Microsoft s’engagent dans une discussion",
    "DigitalBadgeLabel": "Badge numérique",
    "DigitalBadgePageTitle": "Badge numérique",
    "DigitalBadgeSubPageTitle": "Voici à quoi ressemblera votre badge numérique !",
    "DigitalBadgeSuccessMessage": "<strong>Félicitations !</strong> Vous avez demandé votre badge numérique et votre photo de profil a été mise à jour. Veuillez patienter jusqu’à 24 heures pour voir la mise à jour reflétée dans toutes les applications Microsoft 365 (y compris Teams).",
    "DigitalMembersToolTip": "Obtenez votre badge numérique et appliquez-le à votre image de profil",
    "DocumentationLabel": "Documentation technique de la solution et vue d’ensemble architecturale sur",
    "DownloadButtonAriaDescription": "Cliquez pour télécharger votre image de profil actuelle",
    "DownloadButtonSecondaryText": "Télécharger votre image de profil actuelle",
    "DownloadButtonText": "Télécharger",
    "DownloadedButtonSecondaryText": "L’image de votre profil téléchargée se trouve dans le dossier Téléchargements de votre appareil.",
    "DownloadedButtonText": "Téléchargé",
    "DownloadingButtonText": "Téléchargement en cours...",
    "DrivingAdoptionLinkLabel": "Adoption de la conduite sur la Microsoft Technical Community",
    "DuplicateTournamentNameError": "Le nom du tournoi existe déjà. Entrez un autre nom pour le tournoi.",
    "EmailIconLabel": "Envoyer un message électronique",
    "EmailIDLabel": "ID de l’adresse de courrier électronique",
    "EmailLabel": "E-mail",
    "EnableTOTLabel": "Activer le tournoi des équipes",
    "EnableTOTSpinnerMessage": "L’exécution de ce processus prendra quelques instants. Ne quittez pas l’application tant que le message n’est pas terminé.",
    "EnableTOTSuccessMessage": "Le tournoi des équipes a été activé. Actualisez l’application pour continuer.",
    "EnableTOTToolTip": "Activer le tournoi des équipes",
    "EnableTournamentSpinnerMessage": "Activation du ou des tournois...",
    "EnableTournamentSuccessMessage": "Le(s) tournoi(s) ont démarré avec succès.",
    "EndTournamentButton": "Terminer un tournoi",
    "EndTournamentDialogMessage": "Voulez-vous vraiment terminer le tournoi ?",
    "EndTournamentSuccessMessage": "Le tournoi s’est correctement terminé.",
    "ErrorMsgActionsList": "Une erreur s’est produite lors de la création d’un élément dans la liste Actions. Corrigez les données et réessayez.",
    "ErrorMsgTournamentActionsList": "Une erreur s’est produite lors de la création d’un élément dans la liste d’actions du tournoi. Corrigez les données et réessayez.",
    "ErrorMsgTournamentList": "Une erreur s’est produite lors de la création d’un élément dans la liste des tournois. Corrigez les données et réessayez.",
    "EventApprovalsEnableLabel": "Activer les approbations d’événements champion",
    "EventApprovedMessage": "Événement(s) champion(s) approuvé(s).",
    "EventLabel": "Événement",
    "EventRejectedMessage": "Événement(s) champion(s) rejeté(s).",
    "EventsApprovalInfoIconTooltipContent": "L’activation de cette option nécessite que les soumissions d’événements par les champions soient approuvées par un administrateur. Les points pour les événements ne seront attribués qu’après l’approbation.",
    "EventsListLabel": "Liste d‘événements",
    "EventsListToolTip": "Accès à la liste des événements",
    "EventsSelectedLabel": "Événement(s) sélectionné(s).",
    "EventsSubmissionSuccessMessage": "Événement(s) enregistré(s).",
    "EventsSubmitMessage": "Lorsque vous avez terminé d’ajouter des événements, cliquez sur le bouton Envoyer pour enregistrer.",
    "EventsTrackListLabel": "Liste de suivi des événements",
    "EventSubmissionPendingMessage": "Événement(s) soumis(s) pour approbation. Les points sont attribués une fois que les événements sont approuvés.",
    "EventTrackListToolTip": "Accès à la liste du suivi des événements",
    "EventTypeGridLabel": "Type",
    "EventTypeGridLabelPlaceHolder": "Sélectionner le type d’événement",
    "EventTypeLabel": "Type d'événement",
    "EventTypeValidationMessage": "Sélectionnez le type d’événement !",
    "FeedbackToolTip": "Commentaires",
    "FirstNameLabel": "Prénom",
    "FocusAreaGridHeader": "Zone de focus",
    "FocusAreaLabel": "Zone de focus",
    "FocusAreaPlaceholder": "Sélectionner une zone de focus",
    "FormSavingMessage": "Enregistrement en cours de vos détails....",
    "GetStartedLabel": "Prise en main",
    "GroupGridHeader": "Groupe",
    "GroupPlaceholder": "Sélectionner un groupe",
    "HowtoGetDigitalBadgeText": "Comment obtenir un badge de champion",
    "ImportRule1": "Ne pas modifier les en-têtes de colonne dans le modèle",
    "ImportRule2": "Ne pas supprimer des colonnes du modèle",
    "ImportRule3": "Entrer des données dans toutes les colonnes obligatoires (*) mentionnées dans le modèle",
    "ImportRule4": "Suivre la limite de caractères et le type mentionné dans le modèle pour chaque colonne",
    "ImportRule5": "Entrez les données d’un seul tournoi dans chaque feuille en fonction des exemples de données fournis",
    "ImportRule6": "Seuls 10 tournois peuvent être créés à la fois",
    "ImportRule7": "Vérifiez que le nom du tournoi est unique",
    "ImportSpinnerMessage": "Création en cours de tournois.....",
    "LastNameLabel": "Nom",
    "LatestVersionLabel": "Dernière version :",
    "LoadingSpinnerLabel": "Chargement est en cours... Merci de patienter.",
    "LogMsgBlankSheet": "Ignoré, car il est vide.",
    "LogMsgDone": "Tournoi",
    "LogMsgDone1": "date de création.",
    "LogMsgInvalidTemplate": "Ignoré, car il ne s’agit pas d’un modèle valide.",
    "LogMsgInvalidTournamentName": "Ignoré, car il n’a pas de nom de tournoi valide.",
    "LogMsgMultipleTournaments": "Ignoré, car il possède plusieurs noms de tournoi.",
    "LogMsgTournamentExists": "Ignoré, car le tournoi",
    "LogMsgTournamentExists1": "existe déjà.",
    "LogProgress": " Voici la progression :",
    "M365ChampionCommunityLinkLabel": "Communauté des champions Microsoft 365",
    "ManageAdminsLabel": "Gérer les administrateurs",
    "ManageAdminsToolTip": "Accès à la liste des administrateurs",
    "ManageAppLogoLabel": "Gérer le logo de l’application",
    "ManageAppLogoToolTip": "Gérer le logo de l’application",
    "ManageConfigSettingsLabel": "Gérer les paramètres de configuration",
    "ManageDigitalBadgesLabel": "Gérer les badges numériques",
    "ManageDigitalBadgesToolTip": "Gérer les badges numériques",
    "ManageToTLabel1": "Vous pouvez démarrer plusieurs tournois à la fois. Consultez ci-dessous les tournois actifs actuels, la possibilité de terminer le tournoi, ainsi que la possibilité de démarrer un nouveau tournoi.",
    "ManageToTLabel2": "Une fois qu’un tournoi a été démarré et terminé, il ne sera plus disponible pour recommencer ; toutefois, vous pouvez créer un tournoi à l’aide des mêmes actions si vous souhaitez terminer un tournoi similaire !",
    "ManageTournamentActionsLabel": "Gérer les actions du tournoi",
    "ManageTournamentActionsToolTip": "Accès à la liste des actions du tournoi",
    "ManageTournamentsLabel": "Gérer les tournois",
    "ManageTournamentsPageTitle": "Gérer les tournois",
    "MeetupBody": "Réservez du temps pour discuter de votre zone de champion et en savoir plus !",
    "MeetupSubject": "1:1 (Demande de champion)",
    "MonthAndDateLabel": "Mois et jour",
    "MoreInfoToolTip": "Plus d'informations",
    "MSAdoptionHubLinkLabel": "Hub d’adoption de Microsoft",
    "MultipleBadgeMessage": "Sélectionnez un badge dans la liste ci-dessous. Le badge sélectionné sera appliqué à votre photo de profil.",
    "MultipleTournamentLabel": "Plusieurs tournois",
    "MultiTournamentStep": "Étape",
    "MultiTournamentStep1LinkLabel": "Télécharger un modèle",
    "MultiTournamentStep1Text": " de format du fichier d’exemple",
    "MultiTournamentStep2": "Ajouter les détails du tournoi au fichier en suivant les instructions",
    "MultiTournamentStep3": "Télécharger le fichier",
    "MyDashboardInfoIconMessage": "En savoir plus sur cette action",
    "MyRankLabel": "Mon rang",
    "MyTournamentsLabel": "Mes tournois",
    "MyTournamentsTooltip": "Tournois actifs auxquels vous avez déjà participé",
    "NameLabel": "Nom",
    "NearMePlaceHolder": "Sélectionner près de moi",
    "NoActiveParticipantsErrorMessage": "Il n’y a aucun participant actif pour le moment. Soyez le premier à participer et à enregistrer une activité à partir de ",
    "NoActiveParticipantsMessage": "Il n’y a aucun participant actif pour le moment. Soyez le premier à participer et à enregistrer une activité à partir de Mon tableau de bord !",
    "NoActiveTournamentMessage": "Aucun tournoi actif pour le moment. Veuillez réessayer plus tard.",
    "NoActivitiesinGridLabel": "Aucune activité trouvée !",
    "NoBadgeMessage": "Aucun badge à sélectionner n’a été trouvé. Veuillez vérifier auprès de votre administrateur d’application.",
    "NoButton": "Non",
    "NoChampionsMessage": "Aucune demande en attente pour l’instant",
    "NoCompletedTournamentsMessage": "Aucun tournoi n’est terminé pour le moment. Veuillez réessayer plus tard.",
    "NominateMemberLabel": "Désigner un membre",
    "NominateMemberPageTitle": "Désigner un membre",
    "NoPendingEventsLabel": "Aucun événement en attente pour l’instant.",
    "NoProfileImageAlt": "Silhouette d’une personne, signe qu’aucune image de profil n’est actuellement appliquée à votre compte",
    "NoProfileImageDescription": "Si vous avez déjà associé une image à votre profil et que vous voyez toujours ce message, votre image n’est peut-être pas encore disponible. Réessayez plus tard ou contactez le <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>support technique</a> s’il n’apparaît toujours pas après 24 heures.",
    "NoRecordsIcon": "Icône Aucun enregistrement",
    "NoRecordsinGridLabel": "Nous n’avons trouvé aucun enregistrement.",
    "NoSearchResults": "Aucun résultat ne correspond à votre recherche.",
    "NotesLabel": "Notes",
    "NotesPlaceholder": "200 caractères maximum",
    "NoTournamentMessage": "Aucun tournoi trouvé. Réessayer plus tard.",
    "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>Bienvenue dans l’utilitaire de badge numérique</span>. Dans le cadre de votre abonnement au programme Champions, vous pouvez gagner un badge numérique ! Cet utilitaire vous permet de « <em>demander</em> » votre badge numérique en la superposant en haut de votre photo de profil existante. Notez que cette opération mettra à jour votre image de profil sur l’ensemble de Microsoft 365 (Exchange, Teams, SharePoint, etc.)",
    "OrLabel": "OU",
    "OverviewLabel": "Vue d’ensemble et informations sur notre",
    "ParticipantsDetailsLabel": "Détails des participants",
    "ParticipantsLabel": "Participants",
    "ParticipantsStatusLabel": "État des participants",
    "PendingActionsLabel": "Actions en attente",
    "PendingActionsSuccessMessage": "Il n’y a plus d’actions en attente dans ce tournoi.",
    "PendingEventsSearchboxPlaceholder": "Rechercher par champion/e-mail",
    "PeopleNameGridHeader": "Nom du membre",
    "PeoplePickerPlaceholder": "Pour ajouter un membre, tapez le nom du membre",
    "PercentageTournamentCompletedLabel": "Pourcentage du tournoi terminé",
    "PivotHeaderBySpeciality": "Par spécialité",
    "PivotHeaderGlobal": "Global",
    "PivotHeaderNearMe": "Près de moi",
    "PointsLabel": "Points",
    "PreAcceptDisclaimer": "<span style='font-weight:bold;'>Bienvenue dans l’utilitaire de badge numérique</span> <br/><br/> <span>Dans le cadre de votre abonnement au programme Champions, vous avez gagné un badge numérique ! Cet utilitaire vous permet de « <em>demander</em> » votre badge numérique en la superposant en haut de votre photo de profil existante. <br/><br/> Notez que cette opération mettra à jour votre image de profil sur l’ensemble de Microsoft 365 (Exchange, Teams, SharePoint, etc.).</span>",
    "PreAcceptDisclaimer2": "Si vous le souhaitez, <span style='font-weight:bold;'>vous aurez la possibilité d’enregistrer une copie de votre image de profil existante</span> sans la superposition du badge numérique dans les étapes suivantes. Cliquez sur « Accepter » pour continuer (vous pouvez voir une fenêtre contextuelle ouverte et demander une connexion).",
    "PreAcceptPageTitle": "Demandez votre badge numérique !",
    "PreApplyDisclaimer": "Il s’agit d’un aperçu de votre nouvelle photo de profil, notamment le badge numérique. Si vous souhaitez télécharger votre photo de profil existante avant d’appliquer le badge numérique, cliquez sur le lien '<strong>Télécharger votre image de profil actuelle</strong>'.<br />",
    "PreApplyDisclaimer1": "<br />En cliquant sur « Appliquer l’image », vous mettrez à jour votre image de profil Microsoft 365 avec cette nouvelle image. <strong>Veuillez noter que cette opération va mettre à jour votre image de profil sur l’ensemble de Microsoft 365 et ne peut pas être rétablie via cette page</strong>. <br/><br/>Si vous souhaitez rétablir votre image, vous pouvez utiliser l’<a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' aria-label='Open the Outlook web application in a new browser tab or window'>application web Outlook</a>.",
    "ProcessingSpinnerLabel": "Traitement en cours...",
    "ProfileImageAlt": "Mon image de profil utilisée dans O365, Teams, etc.",
    "PropertyPaneDescription": "Description",
    "QuickLinksLabel": "Liens rapides",
    "RankLabel": "Classement",
    "RecordEventLabel": "Enregistrer un événement",
    "RecordsNotFound": "Enregistrements non trouvés",
    "RefreshIconInfoText": "Cliquez sur Actualiser pour afficher les données les plus récentes",
    "RegionGridHeader": "Région",
    "RegionLabel": "Région",
    "RegionPlaceholder": "Sélectionnez une région",
    "RejectButton": "Rejeter",
    "RemoveFileLabel": "Supprimer le fichier",
    "ReportsDropdownInfoIconText": "Le rapport ne peut être généré que pour les tournois terminés.",
    "RequestToCallLabel": "Demander à passer un appel",
    "SaveButton": "Enregistrer",
    "SearchActiveTournaments": "Rechercher dans les tournois actifs",
    "SearchLabel": "Recherche",
    "SearchPendingTournaments": "Rechercher dans les tournois pour commencer",
    "SearchPlaceholder": "Rechercher par nom de participant",
    "SelectActionsErrorMessage": "Sélectionnez au moins une action pour continuer.",
    "SelectAll": "Sélectionner tous les champions",
    "SelectAllEvents": "Sélectionner tous les événements",
    "SelectAllLabel": "Sélectionner tout",
    "SelectChampion": "Sélectionner un champion",
    "SelectDate": "Sélectionnez une date",
    "SelectEndTournamentMessage": "Sélectionnez un tournoi à terminer.",
    "SelectEvent": "Sélectionner un événement",
    "SelectTeamsActionsLabel": "Sélectionner les actions Teams :",
    "SelectTournamentMessage": "Sélectionnez au moins un tournoi pour commencer.",
    "SelectTournamentPlaceHolder": "Sélectionner un tournoi",
    "ShowMoreLabel": "Afficher plus",
    "SingleTournamentLabel": "Tournoi unique",
    "SpinnerListCreationMessage": "Configuration en cours du tournoi des équipes...",
    "StartTournamentButton": "Démarrer le(s) tournoi(s)",
    "StartTournamentDialogMessage": "Voulez-vous vraiment démarrer le ou les nouveaux tournois ?",
    "StartTournamentHeaderLabel": "Démarrer le tournoi",
    "StatusGridHeader": "État",
    "SubmitButton": "Soumettre",
    "SuccessIcon": "Icône de réussite",
    "SupportToolTip": "Support",
    "TeamsActionInfoToolTip": "Sélectionnez parmi les actions Teams disponibles ci-dessous à inclure dans le nouveau tournoi. Pour ajouter de nouvelles actions de tournoi parmi les suivantes, visitez la section Gérer les actions du tournoi à partir des outils d’administration.",
    "ToggleLabelForMemberListColumns": "Afficher/masquer les champs de liste de membres",
    "TooltipContentForMemberListFieldsHeading": "Afficher/masquer les champs de liste de membres dans tous les composants de l’application, le cas échéant.",
    "Top5ParticipantswithPointsLabel": "5 premiers participants avec points",
    "Top5TournamentswithParticipantsLabel": "Top 5 des tournois avec des participants",
    "TopChampionsLabel": "Meilleurs champions",
    "TotalActivitiesLabel": "Nombre total d’activités",
    "TotalParticipantsLabel": "Nombre total de participants",
    "TotalPercentageCompletionLabel": "% de l’achèvement total",
    "TotalPointsLabel": "Nombre total de points",
    "TOTBreadcrumbLabel": "Tournoi des équipes",
    "TOTLabel": "Tournoi des équipes",
    "TOTLeaderBoardPageTitle": "Tableau d’honneur",
    "TOTMyDashboardPageTitle": "Mon tableau de bord",
    "TournamentDescPlaceHolderLabel": "Description du tournoi : (500 caractères maximum)",
    "TournamentDescriptionLabel": "Description du tournoi",
    "TournamentLabel": "Tournoi",
    "TournamentNameErrorLabel": "Le nom du tournoi est obligatoire.",
    "TournamentNameLabel": "Nom du tournoi",
    "TournamentNamePlaceHolderLabel": "Nom du tournoi (255 caractères max.)",
    "TournamentRankLabel": "Classement du tournoi",
    "TournamentReportsPageTitle": "Rapport sur les tournois",
    "UnauthorizedText": "Vous n’êtes pas qualifié pour le programme de badge des champions pour l’instant",
    "UploadFileButton": "Charger un fichier",
    "UserAddedMessage": "L’utilisateur a été correctement ajouté !",
    "UserExistingMessage": "L’utilisateur est déjà un champion !",
    "UserLabel": "Utilisateur",
    "UserNominatedMessage": "L’utilisateur a été correctement désigné !",
    "ViewActivitiesLabel": "Afficher les activités",
    "ViewDashBoardLabel": "Afficher le tableau de bord",
    "VisitLabel": "Visitez les pages de la plateforme de gestion des champions pour en savoir plus :",
    "WelcomeLabel": "Bienvenue",
    "YesButton": "Oui",
  }
});