define([], function () {
    return {
      "PropertyPaneDescription": "תיאור",
      "BasicGroupName": "שם קבוצה",
      "DescriptionFieldLabel": "שדה תיאור",
      "CMPBreadcrumbLabel": "פלטפורמת ניהול אלופים",
      "SaveButton": "שמור",
      "BackButton": "הקודם",
      "GetStartedLabel": "תחילת העבודה",
      "AdminToolsLabel": "כלי מנהל מערכת",
      "ChampionLeaderBoardLabel": "טבלת המובילים של אלוף",
      "AddMemberLabel": "הוספת חבר",
      "NominateMemberLabel": "הגשת מועמדות של חבר",
      "DigitalBadgeLabel": "תג דיגיטלי",
      "TOTLabel": "טורניר של Teams",
      "ChampionListLabel": "רשימת אלופים",
      "EventsListLabel": "רשימת אירועים",
      "EventsTrackListLabel": "רשימת מעקב אחר אירועים",
      "ManageApprovalsLabel": "ניהול אישורים",
      "ManageDigitalBadgesLabel": "נהל תגים דיגיטליים",
      "EnableTOTLabel": "הפוך טורניר של Teams לזמין",
      "AddMembersToolTip": "הוספת חברים - התחל להוסיף את האנשים שאיתם תשתף פעולה ב...",
      "DigitalMembersToolTip": "קבל את התג הדיגיטלי שלך והחל אותו על תמונת הפרופיל שלך",
      "ChampionsListToolTip": "גישה לרשימת האלופים",
      "EventsListToolTip": "גישה לרשימת האירועים",
      "EventTrackListToolTip": "גישה לרשימת מעקב אחר אירועים",
      "ManageApprovalToolTip": "אשר אלוף",
      "EnableTOTToolTip": "הפוך טורניר של Teams לזמין",
      "ManageDigitalBadgesToolTip": "נהל תגים דיגיטליים",
      "WelcomeLabel": "ברוך הבא",
      "ManageAppLogoLabel": "נהל סמל של יישום",
      "ManageAppLogoToolTip": "נהל סמל של יישום",
      "AppHeaderTitleLabel": "פלטפורמת ניהול אלופים",
      "AppLogoToolTip": "בית",
      "MoreInfoToolTip": "מידע נוסף",
      "SupportToolTip": "תמיכה",
      "FeedbackToolTip": "משוב",
      "AboutHeaderLabel": "אודות פלטפורמת ניהול האלופים (CMP):",
      "AboutContentLabel": "פלטפורמת ניהול האלופים שלנו נוצרה תוך מחשבה על אלופים ארגוניים / מומחי אימוץ. בהשראת קהילת האלופים של Microsoft 365, יישום זה פותח כדי להעניק פלטפורמה שתתמוך ביצירה ותחזוק של קהילות משל עצמך. החל מהשראה ועד ביצוע - עוזרים לכם להשיג יותר בקהילות שלכם!",
      "AdditionalResourcesHeaderLabel": "משאבים נוספים:",
      "AdditionalResourcesContentLabel": "קבוצת התמיכה ללקוחות Microsoft Teams מתמקדת באספקת פתרונות כגון אלה כדי לעורר השראה וכדי לסייע לך בהשגת מטרותיך. עקוב אחר משאבים אחרים אלה והצטרף אליהם כדי לקבל מידע נוסף מאיתנו ומקהילה:",
      "M365ChampionCommunityLinkLabel": "קהילת האלופים של Microsoft 365",
      "DrivingAdoptionLinkLabel": "קידום של אימוץ בקהילת Microsoft Technical Community",
      "CurrentVersionLabel": "הגירסה הנוכחית:",
      "LatestVersionLabel": "הגירסה העדכנית ביותר:",
      "CMPGitHubLinkLabel": "GitHub",
      "VisitLabel": "בקר בדפי פלטפורמת ניהול האלופים כדי לקבל מידע נוסף:",
      "OverviewLabel": "מידע ומבט כולל על",
      "MSAdoptionHubLinkLabel": "מרכז האימוץ של Microsoft",
      "DocumentationLabel": "תיעוד טכני של פתרון וסקירה ארכיטקטונית של",
      "AddMemberPageTitle": "הוספת חבר",
      "NominateMemberPageTitle": "הגשת מועמדות של חבר",
      "PeoplePickerPlaceholder": "להוספת חבר, הקלד שם של חבר",
      "RegionPlaceholder": "בחירת אזור",
      "CountryPlaceholder": "בחר מדינה/אזור",
      "GroupPlaceholder": "בחירת קבוצה",
      "FocusAreaPlaceholder": "בחר אזור מיקוד",
      "UserExistingMessage": "המשתמש כבר אלוף!",
      "ChampionsListPageTitle": "רשימת אלופים",
      "UserNominatedMessage": "מומעדות המשתמש הוגשה בהצלחה!",
      "UserAddedMessage": "המשתמש נוסף בהצלחה!",
      "PeopleNameGridHeader": "שם חבר",
      "Select": "בחר",
      "SelectAll": "בחר הכל",
      "RegionGridHeader": "אזור",
      "CountryGridHeader": "מדינה",
      "GroupGridHeader": "קבוצה",
      "FocusAreaGridHeader": "אזור התמקדות",
      "StatusGridHeader": "מצב",
      "ManageApprovalsPageTitle": "ניהול אישורים",
      "ActionGridHeader": "פעולה",
      "ApproveButton": "אשר",
      "RejectButton": "דחה",
      "NoChampionsMessage": "אין בקשות ממתינות בשלב זה",
      "ChampionApprovedMessage": "בקשות האלופים אושרו!",
      "ChampionRejectedMessage": "בקשות האלופים נדחו!",
      "ProcessingSpinnerLabel": "מעבד...",
      "DigitalBadgePageTitle": "תג דיגיטלי",
      "LoadingSpinnerLabel": "טעינה...",
      "DigitalBadgeAppBannerAltText": "חברי צוות של Microsoft מנהלים בדיון",
      "PreAcceptPageTitle": "קבל את התג הדיגיטלי שלך!",
      "PreAcceptDisclaimer": "<span style='font-weight:bold;'>ברוך הבא לשירות התגים הדיגיטליים</span> <br/><br/> <span>כחלק מחברותך בתוכנית האלופים, זכית בתג דיגיטלי! שירות זה יאפשר לך '<em>לתבוע בעלות</em>' על התג הדיגיטלי על-ידי הוספה שלו לתמונת הפרופיל הקיימת שלך. <br/><br/> שים לב שפעולה זו תעדכן את תמונת הפרופיל שלך בכל Microsoft 365‏ (Exchange‏, Teams‏, SharePoint וכו').</span>",
      "PreAcceptDisclaimer2": "אם תרצה, <span style='font-weight:bold;'>תהיה לך אפשרות 'לשמור' העתק של תמונות הפרופיל הקיימת שלך</span>ללא התוספת של התג הדיגיטלי בשלבים הבאים. לחץ על 'קבל' כדי להמשיך (ייתכן שייפתח חלון מוקפץ ויבקש להירשם).",
      "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>ברוך הבא לשירות התגים הדיגיטליים</span>. כחלק מחברותך בתוכנית האלופים, תוכל לזכות בתג דיגיטלי! שירות זה יאפשר לך '<em>לתבוע בעלות</em>' על התג הדיגיטלי על-ידי הוספה שלו לתמונת הפרופיל הקיימת שלך. שים לב שפעולה זו תעדכן את תמונת הפרופיל שלך בכל Microsoft 365‏ (Exchange‏, Teams‏, SharePoint וכו').",
      "HowtoGetDigitalBadgeText": "כיצד זוכים בתג אלוף",
      "MultipleBadgeMessage": "בחר תג מהרשימה שלהלן. התג שנבחר יוחל על תמונת הפרופיל שלך.",
      "NoBadgeMessage": "לא נמצאו תגים שתוכל לבחור. בדוק עם מנהל היישום.",
      "DigitalBadgeSubPageTitle": "כך התג הדיגיטלי שלך ייראה!",
      "ProfileImageAlt": "הפרופיל שלי תמונה הנמצאת בשימוש ברחבי O365, Teams וכן הלאה",
      "BadgeImageAlt": "פרס בצורת מדליה עם האות C במרכז מציין שאני חלק מתוכנית האלופים",
      "NoProfileImageAlt": "צללית של אדם המציינת היעדר של תמונת פרופיל מוחלת כעת בחשבונך",
      "ApplyButtonText": "החל תמונה",
      "ApplyButtonAriaDescription": "בלחיצה על לחצן זה אתה מעניק ל- Web Part של תוכנית האלופים הרשאה לעדכן את תמונת הפרופיל שלך בשמך.",
      "ApplyButton": "החל",
      "DownloadButtonText": "הורד",
      "DownloadButtonAriaDescription": "לחץ כדי להוריד את תמונת הפרופיל הנוכחית שלך",
      "DownloadingButtonText": "מוריד...",
      "DownloadedButtonText": "הורד",
      "DownloadedButtonSecondaryText": "ניתן למצוא את תמונת הפרופיל שהורדת בתיקיה 'הורדות' במכשיר שלך.",
      "DownloadButtonSecondaryText": "הורד את תמונת הפרופיל הנוכחית שלך",
      "PreApplyDisclaimer": "זוהי תצוגה מקדימה של תמונת הפרופיל שלך בתוספת התג הדיגיטלי. אם ברצונך להוריד את תמונת הפרופיל הקיימת לפני הוספת התג הדיגיטלי, לחץ על הקישור '<strong>הורד את תמונת הפרופיל הנוכחית שלך image</strong>'.<br />",
      "PreApplyDisclaimer1": "<br />לחיצה על 'החל תמונה' תעדכן את תמונת הפרופיל שלך ב- Microsoft 365 בתמונה חדשה זו. <strong>שים לב שפעולה זו תעדכן את תמונת הפרופיל שלך בכל Microsoft 365 ולא ניתן לבטל אותה דרך דף זה</strong>. <br/><br/>אם ברצונך לחזור לתמונה הישנה, תוכל להשתמש ב <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' aria-label='Open the Outlook web application in a new browser tab or window'>אפליקציית Outlook לאינטרנט</a>.",
      "NoProfileImageDescription": "אם לפרופיל שלך כבר משויכת תמונה, והודעה זו עדיין מוצגת, ייתכן שהתמונה שלך עדיין לא זמינה. נסה שוב מאוחר יותר, או פנה ל<a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>צוות התמיכה</a> אם היא לא תופיע לאחר 24 שעות.",
      "AcceptButtonText": "קבל",
      "AcceptButtonAriaDescription": "בלחיצה על לחצן זה אתה מעניק ל- Web Part של תוכנית האלופים הרשאה לעדכן את תמונת הפרופיל שלך בשמך.",
      "UnauthorizedText": "אינך עומד בדרישות עבור תוכנית תג 'אלוף' בשלב זה",
      "ApplySpinnerLabel": "מחיל תמונת פרופיל חדשה בחשבון שלך...",
      "DigitalBadgeSuccessMessage": "<strong>ברכותינו!</strong> אספת בהצלחה את התג הדיגיטלי שלך ותמונת הפרופיל שלך עודכנה. יש להמתין עד 24 שעות עד להשתקפות של העדכון בכל יישומי Microsoft 365 (כולל Teams).",
      "CMPSideBarPointsLabel": "נקודות",
      "CMPSideBarGlobalRankLabel": "דירוג כללי",
      "CMPSideBarChampionsLabel": "אלופים",
      "FirstNameLabel": "שם פרטי",
      "LastNameLabel": "שם משפחה",
      "EmailIDLabel": "מזהה דואר אלקטרוני",
      "BecomeChampionLabel": "הפוך לאלוף",
      "ChampionSubmissionPendingLabel": "הגשת אלוף בהמתנה",
      "ChampionRequestSubmitSuccessMessage": "הגשה של בקשת אלוף הצליחה",
      "PivotHeaderGlobal": "כללי",
      "PivotHeaderNearMe": "בקרבתי",
      "PivotHeaderBySpeciality": "לפי התמחות",
      "NearMePlaceHolder": "בחר בקרבתי",
      "BySpecialityPlaceHolder": "בחר לפי תחום התמחות",
      "TopChampionsLabel": "אלופים מובילים",
      "RecordsNotFound": "רשומות לא נמצאו",
      "EventTypeLabel": "סוג אירוע",
      "CountLabel": "ספירה",
      "MyRankLabel": "הדירוג שלי",
      "ViewDashBoardLabel": "הצג לוח מחוונים",
      "DateofEventGridLabel": "תאריך האירוע",
      "EventTypeGridLabel": "סוג",
      "RecordEventLabel": "הקלט אירוע",
      "MonthAndDateLabel": "חודש ותאריך",
      "EventTypeGridLabelPlaceHolder": "בחר סוג אירוע",
      "EventTypeValidationMessage": "בחר סוג אירוע.",
      "CountValidationMessage": "המספר צריך להיות בין 1 ל- 5",
      "EventsSubmitMessage": "כשתסיים להוסיף אירועים, לחץ על לחצן 'שלח' כדי לשמור.",
      "SubmitButton": "שלח",
      "SearchLabel": "חפש",
      "ActivitiesLabel": "פעילויות",
      "RegionLabel": "אזור",
      "FocusAreaLabel": "אזור התמקדות",
      "ShowMoreLabel": "הצג עוד",
      "ViewActivitiesLabel": "הצג פעילויות",
      "ChatIconLabel": "שוחח בצ'אט",
      "RequestToCallLabel": "בקשה לבצע שיחה",
      "EmailIconLabel": "שלח דואר אלקטרוני",
      "MeetupSubject": "אחד על אחד (בקשת אלוף)",
      "MeetupBody": "הקדשת זמן לדיון באזור האלופים שלך ולקבלת מידע נוסף!",
      "NoActivitiesinGridLabel": "לא נמצאו פעילויות.",
      "CreateTournamentPageTitle": "צור טורניר",
      "CreateTournamentSuccessLabel": "הטורניר נוצר בהצלחה.",
      "TournamentNameLabel": "שם הטורניר",
      "TournamentNamePlaceHolderLabel": "שם הטורניר (255 תווים לכל היותר)",
      "TournamentNameErrorLabel": "נדרש שם של הטורניר.",
      "TournamentDescriptionLabel": "תיאור הטורניר",
      "TournamentDescPlaceHolderLabel": "תיאור של הטורניר (500 תווים לכל היותר)",
      "SelectTeamsActionsLabel": "בחר פעולות Teams:",
      "TeamsActionInfoToolTip": "בחר מבין פעולות Teams הזמינות להלן כדי לכלול בטורניר החדש. כדי להוסיף פעולות טורניר חדשות למבחר, בקר במקטע 'נהל פעולות טורניר' ב'כלי מנהל מערכת'.",
      "ActionErrorLabel": "בחר פעולה אחת לפחות ליצירת טורניר.",
      "CreateTournamentButton": "צור טורניר",
      "DuplicateTournamentNameError": "שם הטורניר כבר קיים. הזן שם אחר עבור הטורניר.",
      "CreateTournamentsButton": "צור טורנירים",
      "SingleTournamentLabel": "טורניר יחיד",
      "MultipleTournamentLabel": "טורנירים מרובים",
      "MultiTournamentStep": "שלב",
      "MultiTournamentStep1LinkLabel": "הורד תבנית",
      "MultiTournamentStep1Text": " מתבנית של קובץ לדוגמה",
      "MultiTournamentStep2": "הוסף פרטי טורניר לקובץ על-ידי ביצוע ההנחיות",
      "MultiTournamentStep3": "העלה את הקובץ",
      "UploadFileButton": "העלה קובץ",
      "RemoveFileLabel": "הסר קובץ",
      "ImportSpinnerMessage": "יוצר טורנירים.....",
      "ErrorMsgTournamentList": "אירעה שגיאה בעת יצירת פריט ברשימת הטורנירים. תקן את הנתונים ונסה שוב.",
      "ErrorMsgActionsList": "אירעה שגיאה בעת יצירת פריט ברשימת הפעולות. תקן את הנתונים ונסה שוב.",
      "ErrorMsgTournamentActionsList": "אירעה שגיאה בעת יצירת פריט ברשימת פעולות הטורניר. תקן את הנתונים ונסה שוב.",
      "LogMsgTournamentExists": "המערכת דילגה, מאחר שהטורניר",
      "LogMsgTournamentExists1": "כבר קיים.",
      "LogMsgDone": "טורניר",
      "LogMsgDone1": "נוצר.",
      "LogMsgInvalidTournamentName": "המערכת דילגה על כך, מאחר שאין לו שם טורניר חוקי.",
      "LogMsgInvalidTemplate": "המערכת דילגה על כך, מאחר שזו אינה תבנית חוקית.",
      "LogMsgMultipleTournaments": "המערכת דילגה על כך, מאחר שהיא כוללת יותר לשם טורניר אחד.",
      "LogMsgBlankSheet": "המערכת דילגה על פריט זה מכיוון שהוא ריק.",
      "LogProgress": " להלן ההתקדמות:",
      "ImportRule1": "אל תשנה את כותרות העמודות בתבנית",
      "ImportRule2": "אל תמחק את העמודות בתבנית",
      "ImportRule3": "הזן נתונים בכל העמודות הדרושות(*) המוזכרות בתבנית",
      "ImportRule4": "עקוב אחר מגבלת התווים והקלד המוזכר בתבנית עבור כל עמודה",
      "ImportRule5": "הזן נתונים עבור טורניר אחד בלבד בכל גיליון, כמו בנתונים לדוגמה",
      "ImportRule6": "ניתן ליצור 10 טורנירים בלבד בכל פעם",
      "ImportRule7": "ודא ששם הטורניר ייחודי",
      "TOTBreadcrumbLabel": "טורניר של Teams",
      "EnableTOTSuccessMessage": "הטורניר של Teams הפך לזמין בהצלחה. רענן את האפליקציה כדי להמשיך.",
      "EnableTOTSpinnerMessage": "תהליך זה יימשך מספר רגעים. אל תנווט החוצה עד שתראה את ההודעה שהושלמה בהצלחה.",
      "TOTLeaderBoardPageTitle": "טבלת המובילים",
      "TOTMyDashboardPageTitle": "לוח המחוונים שלי",
      "ManageTournamentActionsToolTip": "גישה לרשימת פעולות הטורניר",
      "ManageTournamentActionsLabel": "ניהול פעולות טורניר",
      "ManageTournamentsLabel": "נהל טורנירים",
      "ManageAdminsToolTip": "גישה לרשימת מנהל מערכת",
      "ManageAdminsLabel": "נהל מנהלי מערכת",
      "QuickLinksLabel": "קישורים מהירים",
      "SpinnerListCreationMessage": "מגדיר את טורניר Teams...",
      "ManageTournamentsPageTitle": "נהל טורנירים",
      "ManageToTLabel1": "ניתן להתחיל מספר טורנירים בכל פעם. עיין להלן לקבלת מידע על הטורנירים הפעילים הנוכחיים, היכולת להשלים את הטורניר, וכן על היכולת להתחיל טורניר חדש.",
      "ManageToTLabel2": "לאחר התחלה והשלמה של טורניר, לא יהיה ניתן להתחיל אותו מחדש. עם זאת, תוכל ליצור טורניר חדש באותה דרך אם ברצונך להשלים טורניר דומה!",
      "EndTournamentDialogMessage": "האם אתה בטוח שברצונך להשלים את הטורניר?",
      "StartTournamentDialogMessage": "האם אתה בטוח שברצונך להתחיל את הטורנירים החדשים?",
      "ConfirmLabel": "אשר",
      "YesButton": "כן",
      "NoButton": "לא",
      "ActiveTournamentLabel": "טורנירים פעילים",
      "EndTournamentButton": "השלם טורניר",
      "StartTournamentHeaderLabel": "התחל טורניר",
      "NoTournamentMessage": "לא נמצאו טורנירים. בדוק שוב מאוחר יותר.",
      "SelectTournamentMessage": "בחר טורניר אחד לפחות כדי להתחיל.",
      "SelectEndTournamentMessage": "בחר טורניר לסיום.",
      "StartTournamentButton": "התחל טורנירים",
      "EndTournamentSuccessMessage": "הטורניר הושלם בהצלחה.",
      "EnableTournamentSuccessMessage": "הטורנירים התחילו בהצלחה.",
      "CompleteTournamentSpinnerMessage": "משלים טורניר...",
      "EnableTournamentSpinnerMessage": "מפעיל טורנירים...",
      "SearchActiveTournaments": "חפש טורנירים פעילים",
      "SearchPendingTournaments": "חפש טורנירים כדי להתחיל",
      "SelectAllLabel": "בחר הכל",
      "NoSearchResults": "אין תוצאות התואמות לחיפוש שלך.",
      "NoActiveParticipantsMessage": "אין משתתפים פעילים כרגע. היה הראשון להשתתף ולרשום פעילות ב'לוח המחוונים שלי'!",
      "NoActiveTournamentMessage": "אין טורנירים פעילים כרגע. בדוק שוב מאוחר יותר.",
      "TournamentLabel": "טורניר",
      "DescriptionLabel": "תיאור",
      "NoActiveParticipantsErrorMessage": "אין משתתפים פעילים כרגע. היה הראשון להשתתף ולרשום פעילות מאת ",
      "PendingActionsLabel": "פעולות בהמתנה",
      "PendingActionsSuccessMessage": "אין עוד פעולות ממתינות בטורניר זה.",
      "SelectActionsErrorMessage": "בחר פעולה אחת לפחות כדי להמשיך.",
      "FormSavingMessage": "שומר את הפרטים שלך....",
      "CompletedActionsLabel": "פעולות שהושלמו",
      "RankLabel": "דרגה",
      "UserLabel": "משתמש",
      "MyDashboardInfoIconMessage": "קבל פרטים נוספים אודות פעולה זו",
      "SelectTournamentPlaceHolder": "בחר טורניר",
      "MyTournamentsLabel": "הטורנירים שלי",
      "OrLabel": "או",
      "MyTournamentsTooltip": "טורנירים פעילים שכבר השתתפת בהם",
      "PointsLabel": "נקודות",
      "TournamentRankLabel": "דירוג הטורניר",
      "ParticipantsLabel": "משתתפים",
      "TournamentReportsPageTitle": "דוח טורנירים",
      "TotalActivitiesLabel": "סך כל הפעילויות",
      "TotalPointsLabel": "סה\"כ נקודות",
      "TotalParticipantsLabel": "כל המשתתפים",
      "TotalPercentageCompletionLabel": "% מההשלמה הכוללת",
      "Top5ParticipantswithPointsLabel": "חמשת המשתתפים המובילים עם נקודות",
      "Top5TournamentswithParticipantsLabel": "חמשת הטורנירים המובילים עם משתתפים",
      "ParticipantsStatusLabel": "מצב המשתתפים",
      "ParticipantsDetailsLabel": "פרטי המשתתפים",
      "NameLabel": "שם",
      "PercentageTournamentCompletedLabel": "% מהטורניר הושלמו",
      "ActivitiesCompletedLabel": "פעילויות שהושלמו",
      "NoRecordsinGridLabel": "לא נמצאו רשומות.",
      "SearchPlaceholder": "חפש לפי כינוי של משתתף",
      "NoCompletedTournamentsMessage": "אין טורניר שהושלם כרגע. בדוק שוב מאוחר יותר.",
      "ReportsDropdownInfoIconText": "ניתן ליצור דוח רק עבור טורנירים שהושלמו.",
      "RefreshIconInfoText": "לחץ על 'רענן' כדי לראות את הנתונים העדכניים ביותר"
    }

});