define([], function () {
  return {
  "PropertyPaneDescription": "תיאור",
  "BasicGroupName": "שם קבוצה",
  "DescriptionFieldLabel": "שדה תיאור",
  "SaveButton": "שמור",
  "BackButton": "הקודם",
  "GetStartedLabel": "תחילת העבודה",
  "AdminToolsLabel": "כלי מנהל מערכת",
  "ChampionLeaderBoardLabel": "טבלת המובילים של אלוף",
  "AddMemberLabel": "הוספת חבר",
  "NominateMemberLabel": "הגשת מועמדות של חבר",
  "DigitalBadgeLabel": "תג דיגיטלי",
  "TOTLabel": "טורניר צוותים",
  "ChampionListLabel": "רשימת אלופים",
  "EventsListLabel": "רשימת אירועים",
  "AdminTasksLabel": "משימות מנהל מערכת",
  "ManageDigitalBadgesLabel": "נהל תגים דיגיטליים",
  "EnableTOTLabel": "הפוך טורניר צוותים לזמין",
  "AddMembersToolTip": "הוספת חברים - התחל להוסיף את האנשים שאיתם תשתף פעולה ב...",
  "DigitalMembersToolTip": "קבל את התג הדיגיטלי שלך והחל אותו על תמונת הפרופיל שלך",
  "ChampionsListToolTip": "גישה לרשימת האלופים",
  "EventsListToolTip": "גישה לרשימת האירועים",
  "EnableTOTToolTip": "הפוך טורניר צוותים לזמין",
  "ManageDigitalBadgesToolTip": "נהל תגים דיגיטליים",
  "WelcomeLabel": "ברוך הבא",
  "ManageAppLogoLabel": "נהל סמל של יישום",
  "ManageAppLogoToolTip": "נהל סמל של יישום",
  "AppLogoToolTip": "בית",
  "MoreInfoToolTip": "מידע נוסף",
  "SupportToolTip": "תמיכה",
  "FeedbackToolTip": "משוב",
  "AdditionalResourcesHeaderLabel": "משאבים נוספים:",
  "AdditionalResourcesContentLabel": "קבוצת התמיכה ללקוחות Microsoft Teams מתמקדת באספקת פתרונות כגון אלה כדי לעורר השראה וכדי לסייע לך בהשגת מטרותיך. עקוב אחר משאבים אחרים אלה והצטרף אליהם כדי לקבל מידע נוסף מאיתנו ומקהילה:",
  "M365ChampionCommunityLinkLabel": "קהילת האלופים של Microsoft 365",
  "DrivingAdoptionLinkLabel": "קידום של אימוץ בקהילת Microsoft Technical Community",
  "CurrentVersionLabel": "הגירסה הנוכחית:",
  "LatestVersionLabel": "הגירסה העדכנית ביותר:",
  "CMPGitHubLinkLabel": "GitHub",
  "VisitLabel": "בקר בדפי פלטפורמת ניהול האלופים כדי לקבל מידע נוסף:",
  "OverviewLabel": "מידע ומבט כולל על",
  "MSAdoptionHubLinkLabel": "מרכז ההטמעה של Microsoft",
  "DocumentationLabel": "תיעוד טכני של פתרון וסקירה ארכיטקטונית של",
  "AddMemberPageTitle": "הוספת חבר",
  "NominateMemberPageTitle": "הגשת מועמדות של חבר",
  "PeoplePickerPlaceholder": "להוספת חבר, הקלד שם של חבר",
  "FocusAreaPlaceholder": "בחר אזור מיקוד",
  "UserExistingMessage": "המשתמש כבר אלוף!",
  "ChampionsListPageTitle": "רשימת אלופים",
  "UserNominatedMessage": "מומעדות המשתמש הוגשה בהצלחה!",
  "UserAddedMessage": "המשתמש נוסף בהצלחה!",
  "PeopleNameGridHeader": "שם חבר",
  "SelectChampion": "בחר אלוף",
  "SelectAll": "בחר את כל האלופים",
  "FocusAreaGridHeader": "אזור התמקדות",
  "CountryGridHeader": "מדינה",
  "RegionLabel": "אזור",
  "StatusGridHeader": "מצב",
  "ActionGridHeader": "פעולה",
  "ApproveButton": "אשר",
  "RejectButton": "דחה",
  "NoChampionsMessage": "אין בקשות ממתינות בשלב זה",
  "ChampionApprovedMessage": "בקשתות האלופים אושרו.",
  "ChampionRejectedMessage": "בקשות האלופים נדחו.",
  "ProcessingSpinnerLabel": "מעבד...",
  "DigitalBadgePageTitle": "תג דיגיטלי",
  "LoadingSpinnerLabel": "טעינה...",
  "LoadingDigitalBadgeLabel": "מסגרת התג הדיגיטלי נטענת",
  "DigitalBadgeAppBannerAltText": "חברי צוות של Microsoft מנהלים בדיון",
  "GroupGridHeader": "קבוצה",
  "ShowHideToggle": "הצג/הסתר שדות של רשימת חברים",
  "ToggleView": "החלפת מצב",
  "SelectedFocusAreaLabel": "אזור המיקוד שנבחר",
  "PreAcceptPageTitle": "קבל את התג הדיגיטלי שלך!",
  "PreAcceptDisclaimer": "<h2>‏‏‎<span style='font-weight:bold;'>‎ברוך הבא לכלי השירות של התג הדיגיטלי</span></h2>",
  "PreAcceptDisclaimer1": "כחלק מחברותך בתוכנית Champions Program, זכית בתג דיגיטלי! כלי שירות זה יאפשר לך '<em>לממש</em>' את התג הדיגיטלי שלך על-ידי קביעתו כשכבת-על מעל תמונת הפרופיל הקיימת.",
  "PreAcceptDisclaimer2": "שים לב שתמונה זו תעדכן את תמונת הפרופיל שלך בכל Microsoft 365 (Exchange, Teams, SharePoint וכן הלאה).",
  "PreAcceptDisclaimer3": "אם תרצה, <span style='font-weight:bold'>תהיה לך הזדמנות ’לשמור’ העתק של תמונות הפרופיל הקיימת שלך</span> ללא שכבת-על של תג דיגיטלי בשלבים הבאים. לחץ על 'קבל' כדי להמשיך (ייתכן שתראה חלון מוקפץ פתוח ותתבקש להיכנס).",
  "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>ברוך הבא לשירות התגים הדיגיטליים</span>. כחלק מחברותך בתוכנית האלופים, תוכל לזכות בתג דיגיטלי! שירות זה יאפשר לך '<em>לתבוע בעלות</em>' על התג הדיגיטלי על-ידי הוספה שלו לתמונת הפרופיל הקיימת שלך. שים לב שפעולה זו תעדכן את תמונת הפרופיל שלך בכל Microsoft 365 (Exchange, Teams, SharePoint וכו').",
  "HowtoGetDigitalBadgeText": "כיצד זוכים בתג אלוף",
  "MultipleBadgeMessage": "בחר תג מהרשימה שלהלן. התג שנבחר יוחל על תמונת הפרופיל שלך.",
  "NoBadgeMessage": "לא נמצאו תגים שתוכל לבחור. בדוק עם מנהל היישום.",
  "DigitalBadgeSubPageTitle": "כך התג הדיגיטלי שלך ייראה!",
  "ProfileImageAlt": "הפרופיל שלי תמונה הנמצאת בשימוש ברחבי O365, Teams וכן הלאה",
  "BadgeImageAlt": "פרס בצורת מדליה עם האות C במרכז מציין שאני חלק מתוכנית האלופים",
  "NoProfileImageAlt": "צללית של אדם המציינת היעדר של תמונת פרופיל מוחלת כעת בחשבונך",
  "ApplyButtonText": "החל תמונה",
  "ApplyButtonAriaDescription": "בלחיצה על לחצן זה אתה מעניק ל- Web Part של תוכנית האלופים הרשאה לעדכן את תמונת הפרופיל שלך בשמך.",
  "ApplyButton": "החל",
  "DownloadButtonText": "הורד",
  "DownloadButtonAriaDescription": "לחץ כדי להוריד את תמונת הפרופיל הנוכחית שלך",
  "DownloadingButtonText": "מוריד...",
  "DownloadedButtonText": "הורד",
  "DownloadedButtonSecondaryText": "ניתן למצוא את תמונת הפרופיל שהורדת בתיקיה 'הורדות' במכשיר שלך.",
  "DownloadButtonSecondaryText": "הורד את תמונת הפרופיל הנוכחית שלך",
  "PreApplyDisclaimer": "זוהי תצוגה מקדימה של תמונת הפרופיל החדשה שלך, כולל התג הדיגיטלי. אם ברצונך להוריד את תמונת הפרופיל הקיימת לפני הוספת התג הדיגיטלי, לחץ על הקישור '<strong>הורד את תמונת הפרופיל הנוכחית שלך image‎‏</strong>'.",
  "PreApplyDisclaimer1": "לחיצה על ‘החל תמונה‘ תעדכן את תמונת הפרופיל שלך ב- Microsoft 365 בתמונה חדשה. <strong>שים לב שפעולה זו תעדכן את תמונת הפרופיל שלך בכל Microsoft 365 ולא תהיה אפשרות לבטל אותה דרך דף זה</strong>.",
  "PreApplyDisclaimer2": "אם ברצונך לחזור לתמונה הקודמת, באפשרותך להשתמש <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' id='linkToChangeProfileImage'>באפליקציית האינטרנט של Outlook</a>.",
  "NoProfileImageDescription": "אם לפרופיל שלך כבר משויכת תמונה, והודעה זו עדיין מוצגת, ייתכן שהתמונה שלך עדיין לא זמינה. נסה שוב מאוחר יותר, או פנה ל<a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>צוות התמיכה</a> אם היא לא תופיע לאחר 24 שעות.",
  "AcceptButtonText": "קבל",
  "AcceptButtonAriaDescription": "בלחיצה על לחצן זה אתה מעניק ל- Web Part של תוכנית האלופים הרשאה לעדכן את תמונת הפרופיל שלך בשמך.",
  "UnauthorizedText": "אינך עומד בדרישות עבור תוכנית תג 'אלוף' בשלב זה",
  "ApplySpinnerLabel": "מחיל תמונת פרופיל חדשה בחשבון שלך...",
  "DigitalBadgeSuccessMessage": "<strong>ברכותינו!</strong> אספת בהצלחה את התג הדיגיטלי שלך ותמונת הפרופיל שלך עודכנה. יש להמתין עד 24 שעות עד להשתקפות של העדכון בכל יישומי Microsoft 365 (כולל Teams).",
  "BadgePointsTooltip": "נקודות נדרשות לביטול נעילה:",
  "CMPSideBarPointsLabel": "נקודות",
  "CMPSideBarGlobalRankLabel": "דירוג כללי",
  "CMPSideBarChampionsLabel": "אלופים",
  "FirstNameLabel": "שם פרטי",
  "LastNameLabel": "שם משפחה",
  "EmailIDLabel": "מזהה דואר אלקטרוני",
  "BecomeChampionLabel": "הפוך לאלוף",
  "ChampionSubmissionPendingLabel": "הגשת אלוף בהמתנה",
  "ChampionRequestSubmitSuccessMessage": "הגשה של בקשת אלוף הצליחה",
  "PivotHeaderGlobal": "כללי",
  "PivotHeaderNearMe": "בקרבתי",
  "PivotHeaderBySpeciality": "לפי התמחות",
  "NearMePlaceHolder": "בחר בקרבתי",
  "BySpecialityPlaceHolder": "בחר לפי תחום התמחות",
  "TopChampionsLabel": "אלופים מובילים",
  "RecordsNotFound": "רשומות לא נמצאו",
  "EventTypeLabel": "סוג אירוע",
  "CountLabel": "ספירה",
  "MyRankLabel": "הדירוג שלי",
  "SelectDate": "בחר תאריך",
  "NotesPlaceholder": "200 תווים לכל היותר",
  "EventSubmissionPendingMessage": "אירועים שנשלחו לאישור. נקודות יוענקו ברגע שהאירועים יאושרו.",
  "EventsSubmissionSuccessMessage": "אירועים נרשמו בהצלחה.",
  "ViewDashBoardLabel": "הצג לוח מחוונים",
  "DateofEventGridLabel": "תאריך האירוע",
  "EventTypeGridLabel": "סוג",
  "RecordEventLabel": "הקלט אירוע",
  "MonthAndDateLabel": "חודש ותאריך",
  "EventTypeGridLabelPlaceHolder": "בחר סוג אירוע",
  "EventTypeValidationMessage": "בחר סוג אירוע.",
  "CountValidationMessage": "המספר צריך להיות בין 1 ל- 5",
  "EventsSubmitMessage": "כשתסיים להוסיף אירועים, לחץ על לחצן 'שלח' כדי לשמור.",
  "SubmitButton": "שלח",
  "SearchLabel": "חפש אלופים מובילים",
  "ActivitiesLabel": "פעילויות",
  "FocusAreaLabel": "אזור התמקדות",
  "ShowMoreLabel": "הצג עוד",
  "ViewActivitiesLabel": "הצג פעילויות",
  "ChatIconLabel": "שוחח בצ'אט",
  "RequestToCallLabel": "תזמון סינכרון",
  "EmailIconLabel": "שלח דואר אלקטרוני",
  "MeetupSubject": "אחד על אחד (בקשת אלוף)",
  "MeetupBody": "הקדשת זמן לדיון באזור האלופים שלך ולקבלת מידע נוסף!",
  "NoActivitiesinGridLabel": "לא נמצאו פעילויות.",
  "CreateTournamentPageTitle": "צור טורניר",
  "CreateTournamentSuccessLabel": "הטורניר נוצר בהצלחה.",
  "TournamentNameLabel": "שם הטורניר",
  "TournamentNamePlaceHolderLabel": "שם הטורניר (255 תווים לכל היותר)",
  "TournamentNameErrorLabel": "נדרש שם של הטורניר.",
  "TournamentDescriptionLabel": "תיאור הטורניר",
  "TournamentDescPlaceHolderLabel": "תיאור של הטורניר (500 תווים לכל היותר)",
  "SelectTeamsActionsLabel": "בחר פעולות Teams:",
  "TeamsActionInfoToolTip": "בחר מבין פעולות צוותים הזמינות להלן כדי לכלול בטורניר החדש. כדי להוסיף פעולות טורניר חדשות למבחר, בקר במקטע 'נהל פעולות טורניר' ב'כלי מנהל מערכת'.",
  "ActionErrorLabel": "בחר פעולה אחת לפחות לשם יצירת טורניר.",
  "CreateTournamentButton": "צור טורניר",
  "DuplicateTournamentNameError": "שם הטורניר כבר קיים. הזן שם אחר עבור הטורניר.",
  "CreateTournamentsButton": "צור טורנירים",
  "SingleTournamentLabel": "טורניר יחיד",
  "MultipleTournamentLabel": "טורנירים מרובים",
  "MultiTournamentStep": "שלב",
  "MultiTournamentStep1LinkLabel": "הורד תבנית",
  "MultiTournamentStep1Text": " מתבנית של קובץ לדוגמה",
  "MultiTournamentStep2": "הוסף פרטי טורניר לקובץ על-ידי ביצוע ההנחיות",
  "MultiTournamentStep3": "העלה את הקובץ",
  "UploadFileButton": "העלה קובץ",
  "RemoveFileLabel": "הסר קובץ",
  "ImportSpinnerMessage": "יוצר טורנירים.....",
  "ErrorMsgTournamentList": "אירעה שגיאה בעת יצירת פריט ברשימת הטורנירים. תקן את הנתונים ונסה שוב.",
  "ErrorMsgActionsList": "אירעה שגיאה בעת יצירת פריט ברשימת הפעולות. תקן את הנתונים ונסה שוב.",
  "ErrorMsgTournamentActionsList": "אירעה שגיאה בעת יצירת פריט ברשימת פעולות הטורניר. תקן את הנתונים ונסה שוב.",
  "LogMsgTournamentExists": "המערכת דילגה, מאחר שהטורניר",
  "LogMsgTournamentExists1": "כבר קיים.",
  "LogMsgDone": "טורניר",
  "LogMsgDone1": "נוצר.",
  "LogMsgInvalidTournamentName": "המערכת דילגה על כך, מאחר שאין לו שם טורניר חוקי.",
  "LogMsgInvalidTemplate": "המערכת דילגה על כך, מאחר שזו אינה תבנית חוקית.",
  "LogMsgMultipleTournaments": "המערכת דילגה על כך, מאחר שהיא כוללת יותר לשם טורניר אחד.",
  "LogMsgBlankSheet": "המערכת דילגה על פריט זה מכיוון שהוא ריק.",
  "LogProgress": " להלן ההתקדמות:",
  "ImportRule1": "אל תשנה את כותרות העמודות בתבנית",
  "ImportRule2": "אל תמחק את העמודות בתבנית",
  "ImportRule3": "הזן נתונים בכל העמודות הדרושות(*) המוזכרות בתבנית",
  "ImportRule4": "עקוב אחר מגבלת התווים והקלד המוזכר בתבנית עבור כל עמודה",
  "ImportRule5": "הזן נתונים עבור טורניר אחד בלבד בכל גיליון, כמו בנתונים לדוגמה",
  "ImportRule6": "ניתן ליצור 10 טורנירים בלבד בכל פעם",
  "ImportRule7": "ודא ששם הטורניר ייחודי",
  "TOTBreadcrumbLabel": "טורניר צוותים",
  "EnableTOTSuccessMessage": "טורניר צוותים הפך לזמין בהצלחה. רענן את האפליקציה כדי להמשיך.",
  "EnableTOTSpinnerMessage": "תהליך זה יימשך מספר רגעים. אל תנווט החוצה עד שתראה את ההודעה שהושלמה בהצלחה.",
  "TOTLeaderBoardPageTitle": "טבלת המובילים",
  "TOTMyDashboardPageTitle": "לוח המחוונים שלי",
  "ManageTournamentActionsToolTip": "גישה לרשימת פעולות הטורניר",
  "ManageTournamentActionsLabel": "ניהול פעולות טורניר",
  "ManageTournamentsLabel": "נהל טורנירים",
  "ManageAdminsToolTip": "גישה לרשימת מנהל מערכת",
  "ManageAdminsLabel": "נהל מנהלי מערכת",
  "QuickLinksLabel": "קישורים מהירים",
  "SpinnerListCreationMessage": "מגדיר את טורניר צוותים...",
  "ManageTournamentsPageTitle": "נהל טורנירים",
  "ManageToTLabel1": "ניתן להתחיל מספר טורנירים בכל פעם. עיין להלן לקבלת מידע על הטורנירים הפעילים הנוכחיים, היכולת להשלים את הטורניר, וכן על היכולת להתחיל טורניר חדש.",
  "ManageToTLabel2": "לאחר התחלה והשלמה של טורניר, לא יהיה ניתן להתחיל אותו מחדש. עם זאת, תוכל ליצור טורניר חדש באותה דרך אם ברצונך להשלים טורניר דומה!",
  "EndTournamentDialogMessage": "האם אתה בטוח שברצונך להשלים את הטורניר?",
  "StartTournamentDialogMessage": "האם אתה בטוח שברצונך להתחיל את הטורנירים החדשים?",
  "ConfirmLabel": "אשר",
  "YesButton": "כן",
  "NoButton": "לא",
  "ActiveTournamentLabel": "טורנירים פעילים",
  "EndTournamentButton": "השלם טורניר",
  "StartTournamentHeaderLabel": "התחל טורניר",
  "NoTournamentMessage": "לא נמצאו טורנירים. בדוק שוב מאוחר יותר.",
  "SelectTournamentMessage": "בחר טורניר אחד לפחות כדי להתחיל.",
  "SelectEndTournamentMessage": "בחר טורניר לסיום.",
  "StartTournamentButton": "התחל טורנירים",
  "EndTournamentSuccessMessage": "הטורניר הושלם בהצלחה.",
  "EnableTournamentSuccessMessage": "הטורנירים התחילו בהצלחה.",
  "CompleteTournamentSpinnerMessage": "משלים טורניר...",
  "EnableTournamentSpinnerMessage": "מפעיל טורנירים...",
  "SearchActiveTournaments": "חפש טורנירים פעילים",
  "SearchPendingTournaments": "חפש טורנירים כדי להתחיל",
  "SelectAllLabel": "בחר הכל",
  "NoSearchResults": "אין תוצאות התואמות לחיפוש שלך.",
  "NoActiveParticipantsMessage": "אין משתתפים פעילים כרגע. היה הראשון להשתתף ולרשום פעילות ב'לוח המחוונים שלי'!",
  "NoActiveTournamentMessage": "אין טורנירים פעילים כרגע. בדוק שוב מאוחר יותר.",
  "TournamentLabel": "טורניר",
  "DescriptionLabel": "תיאור",
  "NoActiveParticipantsErrorMessage": "אין משתתפים פעילים כרגע. היה הראשון להשתתף ולרשום פעילות מאת ",
  "PendingActionsLabel": "פעולות בהמתנה",
  "PendingActionsSuccessMessage": "אין עוד פעולות ממתינות בטורניר זה.",
  "SelectActionsErrorMessage": "בחר פעולה אחת לפחות כדי להמשיך.",
  "FormSavingMessage": "שומר את הפרטים שלך....",
  "CompletedActionsLabel": "פעולות שהושלמו",
  "RankLabel": "דרגה",
  "UserLabel": "משתמש",
  "MyDashboardInfoIconMessage": "קבל פרטים נוספים אודות פעולה זו",
  "SelectTournamentPlaceHolder": "בחר טורניר",
  "MyTournamentsLabel": "הטורנירים שלי",
  "OrLabel": "או",
  "MyTournamentsTooltip": "טורנירים פעילים שכבר השתתפת בהם",
  "PointsLabel": "נקודות",
  "TournamentRankLabel": "דירוג הטורניר",
  "ParticipantsLabel": "משתתפים",
  "TournamentReportsPageTitle": "דוח טורנירים",
  "TotalActivitiesLabel": "סך כל הפעילויות",
  "TotalPointsLabel": "סה\"כ נקודות",
  "TotalParticipantsLabel": "כל המשתתפים",
  "TotalPercentageCompletionLabel": "% מההשלמה הכוללת",
  "Top5ParticipantswithPointsLabel": "חמשת המשתתפים המובילים עם נקודות",
  "Top5TournamentswithParticipantsLabel": "חמשת הטורנירים המובילים עם משתתפים",
  "ParticipantsStatusLabel": "מצב המשתתפים",
  "ParticipantsDetailsLabel": "פרטי המשתתפים",
  "NameLabel": "שם",
  "PercentageTournamentCompletedLabel": "% מהטורניר הושלמו",
  "ActivitiesCompletedLabel": "פעילויות שהושלמו",
  "NoRecordsinGridLabel": "לא נמצאו רשומות.",
  "SearchPlaceholder": "חפש לפי כינוי של משתתף",
  "NoCompletedTournamentsMessage": "אין טורניר שהושלם כרגע. בדוק שוב מאוחר יותר.",
  "ReportsDropdownInfoIconText": "ניתן ליצור דוח רק עבור טורנירים שהושלמו.",
  "RefreshIconInfoText": "לחץ על 'רענן' כדי לראות את הנתונים העדכניים ביותר",
  "EventApprovedMessage": "אירועי האלופים אושרו.",
  "EventRejectedMessage": "אירועי האלופים נדחו.",
  "SelectAllEvents": "בחר את כל האירועים",
  "SelectEvent": "בחר אירוע",
  "ChampionLabel": "אלוף",
  "EmailLabel": "דואר אלקטרוני",
  "EventLabel": "אירוע",
  "DateLabel": "תאריך",
  "NotesLabel": "הערות",
  "SuccessIcon": "סמל 'הצלחה'",
  "PendingEventsSearchboxPlaceholder": "חפש לפי אלוף / דואר אלקטרוני",
  "NoRecordsIcon": "סמל 'אין רשומות'",
  "NoPendingEventsLabel": "אין אירועים ממתינים בשלב זה.",
  "ChampionActivitiesLabel": "פעילויות אלופים",
  "ManageConfigSettingsLabel": "נהל הגדרות תצורה",
  "ApproveChampionSearchboxPlaceholder": "חפש לפי שם/דואר אלקטרוני של חבר",
  "EventsApprovalInfoIconTooltipContent": "הפיכת אפשרות זו לזמינה תדרוש אישור של מנהל מערכת לבקשות אירוע שאלופים מגישים. הנקודות עבור האירועים יוענקו רק לאחר האישור.",
  "ConfigSettingsSaved": "הגדרות תצורה נשמרו.",
  "EventApprovalsEnableLabel": "הפוך אישורי אירוע אלופים לזמינים",
  "EventsSelectedLabel": "אירועים שנבחרו.",
  "ChampionsSelectedLabel": "אלופים שנבחרו.",
  "ToggleLabelForMemberListColumns": "הצג/הסתר שדות של רשימת חברים",
  "TooltipContentForMemberListFieldsHeading": "הצג/הסתר שדות רשימת חברים בכל הרכיבים של האפליקציה בכל מקום שבו ישים.",
  "ChampionReportLabel": "דוח אלופים",
  "ChampionReportToolTip": "דוח אלופים",
  "TotalChampionsLabel": "סה\"כ אלופים",
  "ClearButton": "נקה",
  "FilterbyDateLabel": "סנן לפי תאריך",
  "EventTypesHeading": "סוגי אירועים",
  "NoEventsMessage": "אין אירועים שהושלמו כרגע. בדוק שוב מאוחר יותר.",
  "NoEventsFoundMessage": "לא נמצאו אירועים!",
  "AppTitleLabel": "כותרת האפליקציה",
  "AppTitleErrorLabel": "נדרשת כותרת אפליקציה.",
  "AppTitlePlaceholderText": "30 תווים לכל היותר",
  "AppTitleInfoIconText": "כותרת האפליקציה תופיע במקטע הכותרת ובקטעי שביל הניווט של האפליקציה",
  "AboutContentLabel": "נוצרה במחשבה על אלופים ארגוניים/מומחי אימוץ. בהשראת קהילת האלופים של Microsoft 365, יישום זה פותח כדי להעניק פלטפורמה שתתמוך ביצירה ובתחזוקה של קהילות משלך. מרגע ההשראה ובמהלך הביצוע - עוזרים לכם להשיג יותר בקהילות שלך!",
  "AboutHeaderLabel": "אודות",
  "DashboardLabel": "לוח מחוונים",
  "RemoveEventLabel": "הסרת אירוע",
  "AddEventLabel": "הוספת אירוע",
  "EventChartLabel": "10 האירועים המובילים עם סוגי אירועים",
  "FromLabel": "החל",
  "ToLabel": "עד",
  "AllTime": "בכל הזמנים",
  "LastMonth": "מחודש שעבר",
  "Last3Months": "ב-3 החודשים האחרונים",
  "Last6Months": "ב- 6 החודשים האחרונים",
  "Last1Year": "בשנה האחרונה",
  "SelectaCustomDate": "בחר תאריך מותאם אישית",
  "championRecordsFoundLabel": "נמצאו רשומות אלופים",
  "digitalBadgeProfileAriaLabel": "פתח את אפליקציית האינטרנט של Outlook בכרטיסיה חדשה או בחלון דפדפן חדש",
  "AddMemberAsAdminLabel": "הוסף חבר כמנהל מערכת",
  "NoteValidationMessage": "הערות לא צריכות לחרוג מ- 200 תווים",
  "CloseInfoPopoverButton": "סגור"
  }
});
