define([], function () {
  return {
    "AboutContentLabel": "נוצרה במחשבה על אלופים ארגוניים/מומחי אימוץ. בהשראת קהילת האלופים של Microsoft 365, יישום זה פותח כדי להעניק פלטפורמה שתתמוך ביצירה ובתחזוקה של קהילות משלך. מרגע ההשראה ובמהלך הביצוע - עוזרים לכם להשיג יותר בקהילות שלך!",
    "AboutHeaderLabel": "אודות",
    "AcceptButtonAriaDescription": "בלחיצה על לחצן זה אתה מעניק ל- Web Part של תוכנית האלופים הרשאה לעדכן את תמונת הפרופיל שלך בשמך.",
    "AcceptButtonText": "קבל",
    "ActionErrorLabel": "בחר פעולה אחת לפחות לשם יצירת טורניר.",
    "ActionGridHeader": "פעולה",
    "ActiveTournamentLabel": "טורנירים פעילים",
    "ActivitiesCompletedLabel": "פעילויות שהושלמו",
    "ActivitiesLabel": "פעילויות",
    "AddEventLabel": "הוספת אירוע",
    "AdditionalResourcesContentLabel": "קבוצת התמיכה ללקוחות Microsoft Teams מתמקדת באספקת פתרונות כגון אלה כדי לעורר השראה וכדי לסייע לך בהשגת מטרותיך. עקוב אחר משאבים אחרים אלה והצטרף אליהם כדי לקבל מידע נוסף מאיתנו ומקהילה:",
    "AdditionalResourcesHeaderLabel": "משאבים נוספים:",
    "AddMemberLabel": "הוספת חבר",
    "AddMemberPageTitle": "הוספת חבר",
    "AddMembersToolTip": "הוספת חברים - התחל להוסיף את האנשים שאיתם תשתף פעולה ב...",
    "AdminTasksLabel": "משימות מנהל מערכת",
    "AdminToolsLabel": "כלי מנהל מערכת",
    "AllTime": "בכל הזמנים",
    "AppLogoToolTip": "בית",
    "ApplyButton": "החל",
    "ApplyButtonAriaDescription": "בלחיצה על לחצן זה אתה מעניק ל- Web Part של תוכנית האלופים הרשאה לעדכן את תמונת הפרופיל שלך בשמך.",
    "ApplyButtonText": "החל תמונה",
    "ApplySpinnerLabel": "מחיל תמונת פרופיל חדשה בחשבון שלך...",
    "ApproveButton": "אשר",
    "ApproveChampionSearchboxPlaceholder": "חפש לפי שם/דואר אלקטרוני של חבר",
    "AppTitleErrorLabel": "נדרשת כותרת אפליקציה.",
    "AppTitleInfoIconText": "כותרת האפליקציה תופיע במקטע הכותרת ובקטעי שביל הניווט של האפליקציה",
    "AppTitleLabel": "כותרת האפליקציה",
    "AppTitlePlaceholderText": "30 תווים לכל היותר",
    "BackButton": "הקודם",
    "BadgeImageAlt": "פרס בצורת מדליה עם האות C במרכז מציין שאני חלק מתוכנית האלופים",
    "BadgePointsTooltip": "נקודות נדרשות לביטול נעילה:",
    "BasicGroupName": "שם קבוצה",
    "BecomeChampionLabel": "הפוך לאלוף",
    "BySpecialityPlaceHolder": "בחר לפי תחום התמחות",
    "ChampionActivitiesLabel": "פעילויות אלופים",
    "ChampionApprovedMessage": "בקשתות האלופים אושרו.",
    "ChampionLabel": "אלוף",
    "ChampionLeaderBoardLabel": "טבלת המובילים של אלוף",
    "ChampionListLabel": "רשימת אלופים",
    "championRecordsFoundLabel": "נמצאו רשומות אלופים",
    "ChampionRejectedMessage": "בקשות האלופים נדחו.",
    "ChampionReportLabel": "דוח אלופים",
    "ChampionReportToolTip": "דוח אלופים",
    "ChampionRequestSubmitSuccessMessage": "הגשה של בקשת אלוף הצליחה",
    "ChampionsListPageTitle": "רשימת אלופים",
    "ChampionsListToolTip": "גישה לרשימת האלופים",
    "ChampionsSelectedLabel": "אלופים שנבחרו.",
    "ChampionSubmissionPendingLabel": "הגשת אלוף בהמתנה",
    "ChatIconLabel": "שוחח בצ'אט",
    "ClearButton": "נקה",
    "CMPGitHubLinkLabel": "GitHub",
    "CMPSideBarChampionsLabel": "אלופים",
    "CMPSideBarGlobalRankLabel": "דירוג כללי",
    "CMPSideBarPointsLabel": "נקודות",
    "CompletedActionsLabel": "פעולות שהושלמו",
    "CompleteTournamentSpinnerMessage": "משלים טורניר...",
    "ConfigSettingsSaved": "הגדרות תצורה נשמרו.",
    "ConfirmLabel": "אשר",
    "CountLabel": "ספירה",
    "CountryGridHeader": "מדינה",
    "CountValidationMessage": "המספר צריך להיות בין 1 ל- 5",
    "CreateTournamentButton": "צור טורניר",
    "CreateTournamentPageTitle": "צור טורניר",
    "CreateTournamentsButton": "צור טורנירים",
    "CreateTournamentSuccessLabel": "הטורניר נוצר בהצלחה.",
    "CurrentVersionLabel": "הגירסה הנוכחית:",
    "DashboardLabel": "לוח מחוונים",
    "DateLabel": "תאריך",
    "DateofEventGridLabel": "תאריך האירוע",
    "DescriptionFieldLabel": "שדה תיאור",
    "DescriptionLabel": "תיאור",
    "DigitalBadgeAppBannerAltText": "חברי צוות של Microsoft מנהלים בדיון",
    "DigitalBadgeLabel": "תג דיגיטלי",
    "DigitalBadgePageTitle": "תג דיגיטלי",
    "digitalBadgeProfileAriaLabel": "פתח את אפליקציית האינטרנט של Outlook בכרטיסיה חדשה או בחלון דפדפן חדש",
    "DigitalBadgeSubPageTitle": "כך התג הדיגיטלי שלך ייראה!",
    "DigitalBadgeSuccessMessage": "<strong>ברכותינו!</strong> אספת בהצלחה את התג הדיגיטלי שלך ותמונת הפרופיל שלך עודכנה. יש להמתין עד 24 שעות עד להשתקפות של העדכון בכל יישומי Microsoft 365 (כולל Teams).",
    "DigitalMembersToolTip": "קבל את התג הדיגיטלי שלך והחל אותו על תמונת הפרופיל שלך",
    "DocumentationLabel": "תיעוד טכני של פתרון וסקירה ארכיטקטונית של",
    "DownloadButtonAriaDescription": "לחץ כדי להוריד את תמונת הפרופיל הנוכחית שלך",
    "DownloadButtonSecondaryText": "הורד את תמונת הפרופיל הנוכחית שלך",
    "DownloadButtonText": "הורד",
    "DownloadedButtonSecondaryText": "ניתן למצוא את תמונת הפרופיל שהורדת בתיקיה 'הורדות' במכשיר שלך.",
    "DownloadedButtonText": "הורד",
    "DownloadingButtonText": "מוריד...",
    "DrivingAdoptionLinkLabel": "קידום של אימוץ בקהילת Microsoft Technical Community",
    "DuplicateTournamentNameError": "שם הטורניר כבר קיים. הזן שם אחר עבור הטורניר.",
    "EmailIconLabel": "שלח דואר אלקטרוני",
    "EmailIDLabel": "מזהה דואר אלקטרוני",
    "EmailLabel": "דואר אלקטרוני",
    "EnableTOTLabel": "הפוך טורניר צוותים לזמין",
    "EnableTOTSpinnerMessage": "תהליך זה יימשך מספר רגעים. אל תנווט החוצה עד שתראה את ההודעה שהושלמה בהצלחה.",
    "EnableTOTSuccessMessage": "טורניר צוותים הפך לזמין בהצלחה. רענן את האפליקציה כדי להמשיך.",
    "EnableTOTToolTip": "הפוך טורניר צוותים לזמין",
    "EnableTournamentSpinnerMessage": "מפעיל טורנירים...",
    "EnableTournamentSuccessMessage": "הטורנירים התחילו בהצלחה.",
    "EndTournamentButton": "השלם טורניר",
    "EndTournamentDialogMessage": "האם אתה בטוח שברצונך להשלים את הטורניר?",
    "EndTournamentSuccessMessage": "הטורניר הושלם בהצלחה.",
    "ErrorMsgActionsList": "אירעה שגיאה בעת יצירת פריט ברשימת הפעולות. תקן את הנתונים ונסה שוב.",
    "ErrorMsgTournamentActionsList": "אירעה שגיאה בעת יצירת פריט ברשימת פעולות הטורניר. תקן את הנתונים ונסה שוב.",
    "ErrorMsgTournamentList": "אירעה שגיאה בעת יצירת פריט ברשימת הטורנירים. תקן את הנתונים ונסה שוב.",
    "EventApprovalsEnableLabel": "הפוך אישורי אירוע אלופים לזמינים",
    "EventApprovedMessage": "אירועי האלופים אושרו.",
    "EventChartLabel": "10 האירועים המובילים עם סוגי אירועים",
    "EventLabel": "אירוע",
    "EventRejectedMessage": "אירועי האלופים נדחו.",
    "EventsApprovalInfoIconTooltipContent": "הפיכת אפשרות זו לזמינה תדרוש אישור של מנהל מערכת לבקשות אירוע שאלופים מגישים. הנקודות עבור האירועים יוענקו רק לאחר האישור.",
    "EventsListLabel": "רשימת אירועים",
    "EventsListToolTip": "גישה לרשימת האירועים",
    "EventsSelectedLabel": "אירועים שנבחרו.",
    "EventsSubmissionSuccessMessage": "אירועים נרשמו בהצלחה.",
    "EventsSubmitMessage": "כשתסיים להוסיף אירועים, לחץ על לחצן 'שלח' כדי לשמור.",
    "EventSubmissionPendingMessage": "אירועים שנשלחו לאישור. נקודות יוענקו ברגע שהאירועים יאושרו.",
    "EventTypeGridLabel": "סוג",
    "EventTypeGridLabelPlaceHolder": "בחר סוג אירוע",
    "EventTypeLabel": "סוג אירוע",
    "EventTypesHeading": "סוגי אירועים",
    "EventTypeValidationMessage": "בחר סוג אירוע.",
    "FeedbackToolTip": "משוב",
    "FilterbyDateLabel": "סנן לפי תאריך",
    "FirstNameLabel": "שם פרטי",
    "FocusAreaGridHeader": "אזור התמקדות",
    "FocusAreaLabel": "אזור התמקדות",
    "FocusAreaPlaceholder": "בחר אזור מיקוד",
    "FormSavingMessage": "שומר את הפרטים שלך....",
    "FromLabel": "החל",
    "GetStartedLabel": "תחילת העבודה",
    "GroupGridHeader": "קבוצה",
    "HowtoGetDigitalBadgeText": "כיצד זוכים בתג אלוף",
    "ImportRule1": "אל תשנה את כותרות העמודות בתבנית",
    "ImportRule2": "אל תמחק את העמודות בתבנית",
    "ImportRule3": "הזן נתונים בכל העמודות הדרושות(*) המוזכרות בתבנית",
    "ImportRule4": "עקוב אחר מגבלת התווים והקלד המוזכר בתבנית עבור כל עמודה",
    "ImportRule5": "הזן נתונים עבור טורניר אחד בלבד בכל גיליון, כמו בנתונים לדוגמה",
    "ImportRule6": "ניתן ליצור 10 טורנירים בלבד בכל פעם",
    "ImportRule7": "ודא ששם הטורניר ייחודי",
    "ImportSpinnerMessage": "יוצר טורנירים.....",
    "Last1Year": "בשנה האחרונה",
    "Last3Months": "ב-3 החודשים האחרונים",
    "Last6Months": "ב- 6 החודשים האחרונים",
    "LastMonth": "מחודש שעבר",
    "LastNameLabel": "שם משפחה",
    "LatestVersionLabel": "הגירסה העדכנית ביותר:",
    "LoadingDigitalBadgeLabel": "מסגרת התג הדיגיטלי נטענת",
    "LoadingSpinnerLabel": "טעינה...",
    "LogMsgBlankSheet": "המערכת דילגה על פריט זה מכיוון שהוא ריק.",
    "LogMsgDone": "טורניר",
    "LogMsgDone1": "נוצר.",
    "LogMsgInvalidTemplate": "המערכת דילגה על כך, מאחר שזו אינה תבנית חוקית.",
    "LogMsgInvalidTournamentName": "המערכת דילגה על כך, מאחר שאין לו שם טורניר חוקי.",
    "LogMsgMultipleTournaments": "המערכת דילגה על כך, מאחר שהיא כוללת יותר לשם טורניר אחד.",
    "LogMsgTournamentExists": "המערכת דילגה, מאחר שהטורניר",
    "LogMsgTournamentExists1": "כבר קיים.",
    "LogProgress": " להלן ההתקדמות:",
    "M365ChampionCommunityLinkLabel": "קהילת האלופים של Microsoft 365",
    "ManageAdminsLabel": "נהל מנהלי מערכת",
    "ManageAdminsToolTip": "גישה לרשימת מנהל מערכת",
    "ManageAppLogoLabel": "נהל סמל של יישום",
    "ManageAppLogoToolTip": "נהל סמל של יישום",
    "ManageConfigSettingsLabel": "נהל הגדרות תצורה",
    "ManageDigitalBadgesLabel": "נהל תגים דיגיטליים",
    "ManageDigitalBadgesToolTip": "נהל תגים דיגיטליים",
    "ManageToTLabel1": "ניתן להתחיל מספר טורנירים בכל פעם. עיין להלן לקבלת מידע על הטורנירים הפעילים הנוכחיים, היכולת להשלים את הטורניר, וכן על היכולת להתחיל טורניר חדש.",
    "ManageToTLabel2": "לאחר התחלה והשלמה של טורניר, לא יהיה ניתן להתחיל אותו מחדש. עם זאת, תוכל ליצור טורניר חדש באותה דרך אם ברצונך להשלים טורניר דומה!",
    "ManageTournamentActionsLabel": "ניהול פעולות טורניר",
    "ManageTournamentActionsToolTip": "גישה לרשימת פעולות הטורניר",
    "ManageTournamentsLabel": "נהל טורנירים",
    "ManageTournamentsPageTitle": "נהל טורנירים",
    "MeetupBody": "הקדשת זמן לדיון באזור האלופים שלך ולקבלת מידע נוסף!",
    "MeetupSubject": "אחד על אחד (בקשת אלוף)",
    "MonthAndDateLabel": "חודש ותאריך",
    "MoreInfoToolTip": "מידע נוסף",
    "MSAdoptionHubLinkLabel": "מרכז ההטמעה של Microsoft",
    "MultipleBadgeMessage": "בחר תג מהרשימה שלהלן. התג שנבחר יוחל על תמונת הפרופיל שלך.",
    "MultipleTournamentLabel": "טורנירים מרובים",
    "MultiTournamentStep": "שלב",
    "MultiTournamentStep1LinkLabel": "הורד תבנית",
    "MultiTournamentStep1Text": " מתבנית של קובץ לדוגמה",
    "MultiTournamentStep2": "הוסף פרטי טורניר לקובץ על-ידי ביצוע ההנחיות",
    "MultiTournamentStep3": "העלה את הקובץ",
    "MyDashboardInfoIconMessage": "קבל פרטים נוספים אודות פעולה זו",
    "MyRankLabel": "הדירוג שלי",
    "MyTournamentsLabel": "הטורנירים שלי",
    "MyTournamentsTooltip": "טורנירים פעילים שכבר השתתפת בהם",
    "NameLabel": "שם",
    "NearMePlaceHolder": "בחר בקרבתי",
    "NoActiveParticipantsErrorMessage": "אין משתתפים פעילים כרגע. היה הראשון להשתתף ולרשום פעילות מאת ",
    "NoActiveParticipantsMessage": "אין משתתפים פעילים כרגע. היה הראשון להשתתף ולרשום פעילות ב'לוח המחוונים שלי'!",
    "NoActiveTournamentMessage": "אין טורנירים פעילים כרגע. בדוק שוב מאוחר יותר.",
    "NoActivitiesinGridLabel": "לא נמצאו פעילויות.",
    "NoBadgeMessage": "לא נמצאו תגים שתוכל לבחור. בדוק עם מנהל היישום.",
    "NoButton": "לא",
    "NoChampionsMessage": "אין בקשות ממתינות בשלב זה",
    "NoCompletedTournamentsMessage": "אין טורניר שהושלם כרגע. בדוק שוב מאוחר יותר.",
    "NoEventsFoundMessage": "לא נמצאו אירועים!",
    "NoEventsMessage": "אין אירועים שהושלמו כרגע. בדוק שוב מאוחר יותר.",
    "NominateMemberLabel": "הגשת מועמדות של חבר",
    "NominateMemberPageTitle": "הגשת מועמדות של חבר",
    "NoPendingEventsLabel": "אין אירועים ממתינים בשלב זה.",
    "NoProfileImageAlt": "צללית של אדם המציינת היעדר של תמונת פרופיל מוחלת כעת בחשבונך",
    "NoProfileImageDescription": "אם לפרופיל שלך כבר משויכת תמונה, והודעה זו עדיין מוצגת, ייתכן שהתמונה שלך עדיין לא זמינה. נסה שוב מאוחר יותר, או פנה ל<a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>צוות התמיכה</a> אם היא לא תופיע לאחר 24 שעות.",
    "NoRecordsIcon": "סמל 'אין רשומות'",
    "NoRecordsinGridLabel": "לא נמצאו רשומות.",
    "NoSearchResults": "אין תוצאות התואמות לחיפוש שלך.",
    "NotesLabel": "הערות",
    "NotesPlaceholder": "200 תווים לכל היותר",
    "NoTournamentMessage": "לא נמצאו טורנירים. בדוק שוב מאוחר יותר.",
    "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>ברוך הבא לשירות התגים הדיגיטליים</span>. כחלק מחברותך בתוכנית האלופים, תוכל לזכות בתג דיגיטלי! שירות זה יאפשר לך '<em>לתבוע בעלות</em>' על התג הדיגיטלי על-ידי הוספה שלו לתמונת הפרופיל הקיימת שלך. שים לב שפעולה זו תעדכן את תמונת הפרופיל שלך בכל Microsoft 365 (Exchange, Teams, SharePoint וכו').",
    "OrLabel": "או",
    "OverviewLabel": "מידע ומבט כולל על",
    "ParticipantsDetailsLabel": "פרטי המשתתפים",
    "ParticipantsLabel": "משתתפים",
    "ParticipantsStatusLabel": "מצב המשתתפים",
    "PendingActionsLabel": "פעולות בהמתנה",
    "PendingActionsSuccessMessage": "אין עוד פעולות ממתינות בטורניר זה.",
    "PendingEventsSearchboxPlaceholder": "חפש לפי אלוף / דואר אלקטרוני",
    "PeopleNameGridHeader": "שם חבר",
    "PeoplePickerPlaceholder": "להוספת חבר, הקלד שם של חבר",
    "PercentageTournamentCompletedLabel": "% מהטורניר הושלמו",
    "PivotHeaderBySpeciality": "לפי התמחות",
    "PivotHeaderGlobal": "כללי",
    "PivotHeaderNearMe": "בקרבתי",
    "PointsLabel": "נקודות",
    "PreAcceptDisclaimer": "<h2>‏‏‎<span style='font-weight:bold;'>‎ברוך הבא לכלי השירות של התג הדיגיטלי</span></h2>",
    "PreAcceptDisclaimer1": "כחלק מחברותך בתוכנית Champions Program, זכית בתג דיגיטלי! כלי שירות זה יאפשר לך '<em>לממש</em>' את התג הדיגיטלי שלך על-ידי קביעתו כשכבת-על מעל תמונת הפרופיל הקיימת.",
    "PreAcceptDisclaimer2": "שים לב שתמונה זו תעדכן את תמונת הפרופיל שלך בכל Microsoft 365 (Exchange, Teams, SharePoint וכן הלאה).",
    "PreAcceptDisclaimer3": "אם תרצה, <span style='font-weight:bold'>תהיה לך הזדמנות ’לשמור’ העתק של תמונות הפרופיל הקיימת שלך</span> ללא שכבת-על של תג דיגיטלי בשלבים הבאים. לחץ על 'קבל' כדי להמשיך (ייתכן שתראה חלון מוקפץ פתוח ותתבקש להיכנס).",
    "PreAcceptPageTitle": "קבל את התג הדיגיטלי שלך!",
    "PreApplyDisclaimer": "זוהי תצוגה מקדימה של תמונת הפרופיל החדשה שלך, כולל התג הדיגיטלי. אם ברצונך להוריד את תמונת הפרופיל הקיימת לפני הוספת התג הדיגיטלי, לחץ על הקישור '<strong>הורד את תמונת הפרופיל הנוכחית שלך image‎‏</strong>'.",
    "PreApplyDisclaimer1": "לחיצה על ‘החל תמונה‘ תעדכן את תמונת הפרופיל שלך ב- Microsoft 365 בתמונה חדשה. <strong>שים לב שפעולה זו תעדכן את תמונת הפרופיל שלך בכל Microsoft 365 ולא תהיה אפשרות לבטל אותה דרך דף זה</strong>.",
    "PreApplyDisclaimer2": "אם ברצונך לחזור לתמונה הקודמת, באפשרותך להשתמש <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' id='linkToChangeProfileImage'>באפליקציית האינטרנט של Outlook</a>.",
    "ProcessingSpinnerLabel": "מעבד...",
    "ProfileImageAlt": "הפרופיל שלי תמונה הנמצאת בשימוש ברחבי O365, Teams וכן הלאה",
    "PropertyPaneDescription": "תיאור",
    "QuickLinksLabel": "קישורים מהירים",
    "RankLabel": "דרגה",
    "RecordEventLabel": "הקלט אירוע",
    "RecordsNotFound": "רשומות לא נמצאו",
    "RefreshIconInfoText": "לחץ על 'רענן' כדי לראות את הנתונים העדכניים ביותר",
    "RegionLabel": "אזור",
    "RejectButton": "דחה",
    "RemoveEventLabel": "הסרת אירוע",
    "RemoveFileLabel": "הסר קובץ",
    "ReportsDropdownInfoIconText": "ניתן ליצור דוח רק עבור טורנירים שהושלמו.",
    "RequestToCallLabel": "תזמון סינכרון",
    "SaveButton": "שמור",
    "SearchActiveTournaments": "חפש טורנירים פעילים",
    "SearchLabel": "חפש אלופים מובילים",
    "SearchPendingTournaments": "חפש טורנירים כדי להתחיל",
    "SearchPlaceholder": "חפש לפי כינוי של משתתף",
    "SelectActionsErrorMessage": "בחר פעולה אחת לפחות כדי להמשיך.",
    "SelectaCustomDate": "בחר תאריך מותאם אישית",
    "SelectAll": "בחר את כל האלופים",
    "SelectAllEvents": "בחר את כל האירועים",
    "SelectAllLabel": "בחר הכל",
    "SelectChampion": "בחר אלוף",
    "SelectDate": "בחר תאריך",
    "SelectedFocusAreaLabel": "אזור המיקוד שנבחר",
    "SelectEndTournamentMessage": "בחר טורניר לסיום.",
    "SelectEvent": "בחר אירוע",
    "SelectTeamsActionsLabel": "בחר פעולות Teams:",
    "SelectTournamentMessage": "בחר טורניר אחד לפחות כדי להתחיל.",
    "SelectTournamentPlaceHolder": "בחר טורניר",
    "ShowHideToggle": "הצג/הסתר שדות של רשימת חברים",
    "ShowMoreLabel": "הצג עוד",
    "SingleTournamentLabel": "טורניר יחיד",
    "SpinnerListCreationMessage": "מגדיר את טורניר צוותים...",
    "StartTournamentButton": "התחל טורנירים",
    "StartTournamentDialogMessage": "האם אתה בטוח שברצונך להתחיל את הטורנירים החדשים?",
    "StartTournamentHeaderLabel": "התחל טורניר",
    "StatusGridHeader": "מצב",
    "SubmitButton": "שלח",
    "SuccessIcon": "סמל 'הצלחה'",
    "SupportToolTip": "תמיכה",
    "TeamsActionInfoToolTip": "בחר מבין פעולות צוותים הזמינות להלן כדי לכלול בטורניר החדש. כדי להוסיף פעולות טורניר חדשות למבחר, בקר במקטע 'נהל פעולות טורניר' ב'כלי מנהל מערכת'.",
    "ToggleLabelForMemberListColumns": "הצג/הסתר שדות של רשימת חברים",
    "ToggleView": "החלפת מצב",
    "ToLabel": "עד",
    "TooltipContentForMemberListFieldsHeading": "הצג/הסתר שדות רשימת חברים בכל הרכיבים של האפליקציה בכל מקום שבו ישים.",
    "Top5ParticipantswithPointsLabel": "חמשת המשתתפים המובילים עם נקודות",
    "Top5TournamentswithParticipantsLabel": "חמשת הטורנירים המובילים עם משתתפים",
    "TopChampionsLabel": "אלופים מובילים",
    "TotalActivitiesLabel": "סך כל הפעילויות",
    "TotalChampionsLabel": "סה\"כ אלופים",
    "TotalParticipantsLabel": "כל המשתתפים",
    "TotalPercentageCompletionLabel": "% מההשלמה הכוללת",
    "TotalPointsLabel": "סה\"כ נקודות",
    "TOTBreadcrumbLabel": "טורניר צוותים",
    "TOTLabel": "טורניר צוותים",
    "TOTLeaderBoardPageTitle": "טבלת המובילים",
    "TOTMyDashboardPageTitle": "לוח המחוונים שלי",
    "TournamentDescPlaceHolderLabel": "תיאור של הטורניר (500 תווים לכל היותר)",
    "TournamentDescriptionLabel": "תיאור הטורניר",
    "TournamentLabel": "טורניר",
    "TournamentNameErrorLabel": "נדרש שם של הטורניר.",
    "TournamentNameLabel": "שם הטורניר",
    "TournamentNamePlaceHolderLabel": "שם הטורניר (255 תווים לכל היותר)",
    "TournamentRankLabel": "דירוג הטורניר",
    "TournamentReportsPageTitle": "דוח טורנירים",
    "UnauthorizedText": "אינך עומד בדרישות עבור תוכנית תג 'אלוף' בשלב זה",
    "UploadFileButton": "העלה קובץ",
    "UserAddedMessage": "המשתמש נוסף בהצלחה!",
    "UserExistingMessage": "המשתמש כבר אלוף!",
    "UserLabel": "משתמש",
    "UserNominatedMessage": "מומעדות המשתמש הוגשה בהצלחה!",
    "ViewActivitiesLabel": "הצג פעילויות",
    "ViewDashBoardLabel": "הצג לוח מחוונים",
    "VisitLabel": "בקר בדפי פלטפורמת ניהול האלופים כדי לקבל מידע נוסף:",
    "WelcomeLabel": "ברוך הבא",
    "YesButton": "כן"
  }
});
