define([], function () {
    return {
      "PropertyPaneDescription": "説明",
      "BasicGroupName": "グループ名",
      "DescriptionFieldLabel": "説明フィールド",
      "CMPBreadcrumbLabel": "チャンピオン管理プラットフォーム",
      "SaveButton": "保存",
      "BackButton": "戻る",
      "GetStartedLabel": "開始",
      "AdminToolsLabel": "管理ツール",
      "ChampionLeaderBoardLabel": "チャンピオンのランキング",
      "AddMemberLabel": "メンバーを追加",
      "NominateMemberLabel": "メンバーの推薦",
      "DigitalBadgeLabel": "デジタル バッジ",
      "TOTLabel": "Teams のトーナメント",
      "ChampionListLabel": "チャンピオン リスト",
      "EventsListLabel": "イベント リスト",
      "EventsTrackListLabel": "イベント追跡リスト",
      "ManageApprovalsLabel": "承認の管理",
      "ManageDigitalBadgesLabel": "デジタル バッジの管理",
      "EnableTOTLabel": "Teams のトーナメントを有効にする",
      "AddMembersToolTip": "メンバーの追加: 共同作業を行うユーザーの追加を開始します...",
      "DigitalMembersToolTip": "デジタル バッジを取得して、プロフィール画像に適用します",
      "ChampionsListToolTip": "チャンピオン リストにアクセスしています",
      "EventsListToolTip": "イベント リストにアクセスしています",
      "EventTrackListToolTip": "イベント追跡リストにアクセスしています",
      "ManageApprovalToolTip": "チャンピオンの承認",
      "EnableTOTToolTip": "Teams のトーナメントを有効にする",
      "ManageDigitalBadgesToolTip": "デジタル バッジの管理",
      "WelcomeLabel": "ようこそ",
      "ManageAppLogoLabel": "アプリのロゴを管理する",
      "ManageAppLogoToolTip": "アプリのロゴを管理する",
      "AppHeaderTitleLabel": "チャンピオン管理プラットフォーム",
      "AppLogoToolTip": "ホーム",
      "MoreInfoToolTip": "詳細",
      "SupportToolTip": "サポート",
      "FeedbackToolTip": "フィードバック",
      "AboutHeaderLabel": "チャンピオン管理プラットフォーム (CMP) について:",
      "AboutContentLabel": "チャンピオン管理プラットフォームは、組織のチャンピオン/導入スペシャリストを念頭に置いて作成されました。このアプリは、Microsoft 365 チャンピオン コミュニティからの意見を聞き、独自のコミュニティの作成と維持に役立つプラットフォームを提供するために開発されました。実行を通じてインスピレーションを得て、自分のコミュニティ内でより多くの成果を上げるのに役立ちます。",
      "AdditionalResourcesHeaderLabel": "追加リソース:",
      "AdditionalResourcesContentLabel": "Microsoft Teams Customer Advocacy Group は、目標の達成を促し、支援するために、このようなソリューションを提供することに重点を置いています。これらの他のリソースをフォローして参加し、私たちとコミュニティからさらに学びましょう。",
      "M365ChampionCommunityLinkLabel": "Microsoft 365 チャンピオン コミュニティ",
      "DrivingAdoptionLinkLabel": "Microsoft Technical Community での導入の促進",
      "CurrentVersionLabel": "現在のバージョン:",
      "LatestVersionLabel": "最新バージョン",
      "CMPGitHubLinkLabel": "GitHub",
      "VisitLabel": "詳細については、チャンピオン管理プラットフォームのページにアクセスしてください。",
      "OverviewLabel": "概要と情報",
      "MSAdoptionHubLinkLabel": "Microsoft Adoption Hub",
      "DocumentationLabel": "ソリューションの技術ドキュメントとアーキテクチャの概要",
      "AddMemberPageTitle": "メンバーを追加",
      "NominateMemberPageTitle": "メンバーの推薦",
      "PeoplePickerPlaceholder": "メンバーを追加するには、メンバー名を入力してください",
      "RegionPlaceholder": "地域の選択",
      "CountryPlaceholder": "国を選択",
      "GroupPlaceholder": "グループを選択する",
      "FocusAreaPlaceholder": "フォーカス領域の選択",
      "UserExistingMessage": "ユーザーは既にチャンピオンです!",
      "ChampionsListPageTitle": "チャンピオン リスト",
      "UserNominatedMessage": "ユーザーが正常に推薦されました。",
      "UserAddedMessage": "ユーザーが正常に追加されました。",
      "PeopleNameGridHeader": "メンバー名",
      "Select": "選択",
      "SelectAll": "すべて選択",
      "RegionGridHeader": "地域",
      "CountryGridHeader": "国",
      "GroupGridHeader": "グループ",
      "FocusAreaGridHeader": "フォーカス領域",
      "StatusGridHeader": "状態",
      "ManageApprovalsPageTitle": "承認の管理",
      "ActionGridHeader": "操作",
      "ApproveButton": "承認",
      "RejectButton": "拒否",
      "NoChampionsMessage": "現時点では保留中の要求はありません",
      "ChampionApprovedMessage": "チャンピオンの要求が承認されました。",
      "ChampionRejectedMessage": "チャンピオンの要求が拒否されました。",
      "ProcessingSpinnerLabel": "処理中...",
      "DigitalBadgePageTitle": "デジタル バッジ",
      "LoadingSpinnerLabel": "読み込んでいます...",
      "DigitalBadgeAppBannerAltText": "ディスカッションに参加している Microsoft チーム メンバー",
      "PreAcceptPageTitle": "デジタル バッジを要求してください!",
      "PreAcceptDisclaimer": "<span style='font-weight:bold;'>デジタル バッジ ユーティリティへようこそ</span> <br/><br/> <span>チャンピオンズ プログラムのメンバーシップの一環として、デジタル バッジを獲得しました。このユーティリティを使用すると、既存のプロフィール写真の上にデジタル バッジを重ねて、デジタル バッジを '<em>請求</em>' することができます。<br/><br/> これにより、すべての Microsoft 365 (Exchange、Teams、SharePoint など) でプロフィール写真が更新されることに注意してください。</span>",
      "PreAcceptDisclaimer2": "必要に応じて、<span style='font-weight:bold;'>次の手順でデジタル バッジのオーバーレイを使用せずに、既存のプロフィール写真のコピーを [保存] する機会があります</span>。[同意する] をクリックして続行してください (ポップアップが開き、サインインを求めるプロンプトが表示される場合があります)。",
      "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>デジタル バッジ ユーティリティへようこそ</span>。チャンピオンズ プログラムのメンバーシップの一環として、デジタル バッジを獲得しました。このユーティリティを使用すると、既存のプロフィール写真の上にデジタル バッジを重ねて、デジタル バッジを '<em>請求</em>' することができます。これにより、すべての Microsoft 365 (Exchange、Teams、SharePoint など) でプロフィール写真が更新されることに注意してください。",
      "HowtoGetDigitalBadgeText": "チャンピオン バッジを取得する方法",
      "MultipleBadgeMessage": "下の一覧からバッジを選択してください。選択したバッジはプロフィール画像に適用されます。",
      "NoBadgeMessage": "選択するバッジが見つかりません。アプリ管理者に確認してください。",
      "DigitalBadgeSubPageTitle": "デジタル バッジの外観は次のとおりです。",
      "ProfileImageAlt": "O365、Teams などで使用されるプロファイル画像",
      "BadgeImageAlt": "中央に文字 C が付いたメダルの形をした賞です。私はチャンピオン プログラムの一部です",
      "NoProfileImageAlt": "プロフィール画像が現在アカウントに適用されていないことを示す人物のシルエット",
      "ApplyButtonText": "イメージの適用",
      "ApplyButtonAriaDescription": "このボタンをクリックすると、Champions Program の Web パーツに、あなたに代わってプロフィール写真を更新するアクセス許可が与えられます。",
      "ApplyButton": "適用",
      "DownloadButtonText": "ダウンロード",
      "DownloadButtonAriaDescription": "クリックして現在のプロフィール画像をダウンロードします",
      "DownloadingButtonText": "ダウンロードしています...",
      "DownloadedButtonText": "ダウンロード完了",
      "DownloadedButtonSecondaryText": "ダウンロードしたプロフィール画像は、デバイスのダウンロード フォルダーにあります。",
      "DownloadButtonSecondaryText": "現在のプロフィール画像をダウンロード",
      "PreApplyDisclaimer": "これは、デジタル バッジを含む新しいプロフィール写真のプレビューです。デジタル バッジを適用する前に既存のプロフィール写真をダウンロードする場合は、<strong>[現在のプロフィール画像をダウンロードする]</strong> リンクをクリックしてください。<br />",
      "PreApplyDisclaimer1": "<br />[画像の適用] をクリックすると、Microsoft 365 のプロフィール写真がこの新しい画像で更新されます。<strong>これにより、Microsoft 365 全体でプロフィール写真が更新され、このページから元に戻すことはできないので注意してください</strong>。<br/><br/>写真を元に戻したい場合は、<a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' aria-label='Open the Outlook web application in a new browser tab or window'>Outlook web application</a> を使用できます。",
      "NoProfileImageDescription": "既に写真をプロフィールに関連付けていて、まだこのメッセージが表示されている場合は、写真がまだ利用できない可能性があります。後でもう一度やり直すか、24 時間経過しても表示されない場合は <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>helpdesk</a> に連絡してください。",
      "AcceptButtonText": "承諾",
      "AcceptButtonAriaDescription": "このボタンをクリックすると、Champions Program の Web パーツに、あなたに代わってプロフィール写真を更新するアクセス許可が与えられます。",
      "UnauthorizedText": "現在、チャンピオン バッジ プログラムの資格はありません。",
      "ApplySpinnerLabel": "新しいプロフィール画像をアカウントに適用しています...",
      "DigitalBadgeSuccessMessage": "<strong>おめでとうございます!</strong> デジタル バッジの申請に成功し、プロフィール写真が更新されました。すべての Microsoft 365 アプリケーション (Teams を含む) に更新が反映されるまで、最大 24 時間かかります。",
      "CMPSideBarPointsLabel": "得点",
      "CMPSideBarGlobalRankLabel": "グローバル ランク",
      "CMPSideBarChampionsLabel": "チャンピオン",
      "FirstNameLabel": "名",
      "LastNameLabel": "姓",
      "EmailIDLabel": "メール ID",
      "BecomeChampionLabel": "チャンピオンになる",
      "ChampionSubmissionPendingLabel": "チャンピオンの申請が保留中です",
      "ChampionRequestSubmitSuccessMessage": "チャンピオン要求の送信に成功しました",
      "PivotHeaderGlobal": "グローバル",
      "PivotHeaderNearMe": "近くにいる",
      "PivotHeaderBySpeciality": "専門分野",
      "NearMePlaceHolder": "近くを選択",
      "BySpecialityPlaceHolder": "専門分野で選択する",
      "TopChampionsLabel": "上位のチャンピオン",
      "RecordsNotFound": "検出されなかったレコード",
      "EventTypeLabel": "イベントの種類",
      "CountLabel": "カウント",
      "MyRankLabel": "自分のランク",
      "ViewDashBoardLabel": "ダッシュボードを表示",
      "DateofEventGridLabel": "イベントの日付",
      "EventTypeGridLabel": "型",
      "RecordEventLabel": "イベントの記録",
      "MonthAndDateLabel": "月と日",
      "EventTypeGridLabelPlaceHolder": "イベントの種類の選択",
      "EventTypeValidationMessage": "イベントの種類を選択してください!",
      "CountValidationMessage": "数は 1 から 5 の間でなければなりません",
      "EventsSubmitMessage": "イベントの追加が完了したら、[送信] ボタンをクリックして保存してください。",
      "SubmitButton": "送信",
      "SearchLabel": "検索",
      "ActivitiesLabel": "アクティビティ",
      "RegionLabel": "地域",
      "FocusAreaLabel": "フォーカス領域",
      "ShowMoreLabel": "詳細表示",
      "ViewActivitiesLabel": "アクティビティの表示",
      "ChatIconLabel": "チャット",
      "RequestToCallLabel": "通話の要求",
      "EmailIconLabel": "電子メール メッセージの送信",
      "MeetupSubject": "1:1 (チャンピオンの要求)",
      "MeetupBody": "チャンピオン分野について話し合い、詳細を確認する時間を確保しましょう!",
      "NoActivitiesinGridLabel": "アクティビティが見つかりません!",
      "CreateTournamentPageTitle": "トーナメントを作成",
      "CreateTournamentSuccessLabel": "トーナメントが正常に作成されました。",
      "TournamentNameLabel": "トーナメント名",
      "TournamentNamePlaceHolderLabel": "トーナメント名 (最大 255 文字)",
      "TournamentNameErrorLabel": "トーナメント名が必要です。",
      "TournamentDescriptionLabel": "トーナメントの説明",
      "TournamentDescPlaceHolderLabel": "トーナメントの説明 (最大 500 文字)",
      "SelectTeamsActionsLabel": "Teams アクションの選択:",
      "TeamsActionInfoToolTip": "以下の利用可能なチーム アクションから選択して、新しいトーナメントに含めます。選択する新しいトーナメント アクションを追加するには、管理ツールから [トーナメント アクションの管理] にアクセスします。",
      "ActionErrorLabel": "トーナメントを作成するには、少なくとも 1 つのアクションを選択してください。",
      "CreateTournamentButton": "トーナメントを作成",
      "DuplicateTournamentNameError": "トーナメント名は既に存在します。トーナメントの別の名前を入力してください。",
      "CreateTournamentsButton": "トーナメントの作成",
      "SingleTournamentLabel": "単一のトーナメント",
      "MultipleTournamentLabel": "複数のトーナメント",
      "MultiTournamentStep": "ステップ",
      "MultiTournamentStep1LinkLabel": "テンプレートをダウンロード",
      "MultiTournamentStep1Text": " サンプル ファイル形式の",
      "MultiTournamentStep2": "ガイドラインに従って、トーナメントの詳細をファイルに追加します",
      "MultiTournamentStep3": "ファイルをアップロード",
      "UploadFileButton": "ファイルのアップロード",
      "RemoveFileLabel": "ファイルの削除",
      "ImportSpinnerMessage": "トーナメントを作成しています.....",
      "ErrorMsgTournamentList": "トーナメント リストにアイテムを作成中にエラーが発生しました。データを修正して、もう一度お試しください。",
      "ErrorMsgActionsList": "アクションの一覧にアイテムを作成中にエラーが発生しました。データを修正して、もう一度お試しください。",
      "ErrorMsgTournamentActionsList": "トーナメント アクションリストにアイテムを作成中にエラーが発生しました。データを修正して、もう一度お試しください。",
      "LogMsgTournamentExists": "トーナメントが既に存在するため、スキップされました",
      "LogMsgTournamentExists1": "既に存在します。",
      "LogMsgDone": "トーナメント",
      "LogMsgDone1": "作成されました。",
      "LogMsgInvalidTournamentName": "有効なトーナメント名がないため、スキップされました。",
      "LogMsgInvalidTemplate": "有効なテンプレートではないため、スキップされました。",
      "LogMsgMultipleTournaments": "複数のトーナメント名があるため、スキップされました。",
      "LogMsgBlankSheet": "空白のため、スキップされました。",
      "LogProgress": " 進捗状況は次のとおりです。",
      "ImportRule1": "テンプレートの列ヘッダーを変更しない",
      "ImportRule2": "テンプレート内の列を削除しない",
      "ImportRule3": "テンプレートに記載されているすべての必須 (*) 列にデータを入力してください",
      "ImportRule4": "各列のテンプレートに記載されている文字数制限と種類に従ってください",
      "ImportRule5": "提供されたサンプル データに従って、各シートに 1 つのトーナメントのみのデータを入力します",
      "ImportRule6": "一度に作成できるトーナメントは 10 個のみです",
      "ImportRule7": "トーナメント名が一意であることを確認してください",
      "TOTBreadcrumbLabel": "Teams のトーナメント",
      "EnableTOTSuccessMessage": "Teams のトーナメントが正常に有効になりました。続行するには、アプリを更新してください。",
      "EnableTOTSpinnerMessage": "このプロセスが完了するまでにしばらく時間がかかります。正常に完了したメッセージが表示されるまで、移動しないでください。",
      "TOTLeaderBoardPageTitle": "リーダー ボード",
      "TOTMyDashboardPageTitle": "自分のダッシュボード",
      "ManageTournamentActionsToolTip": "トーナメント アクション リストにアクセスしています",
      "ManageTournamentActionsLabel": "トーナメント アクションの管理",
      "ManageTournamentsLabel": "トーナメントの管理",
      "ManageAdminsToolTip": "管理リストにアクセスしています",
      "ManageAdminsLabel": "管理者の管理",
      "QuickLinksLabel": "クイック リンク",
      "SpinnerListCreationMessage": "Teams のトーナメントを設定しています...",
      "ManageTournamentsPageTitle": "トーナメントの管理",
      "ManageToTLabel1": "一度に複数のトーナメントを開始できます。現在アクティブなトーナメント、トーナメントを完了する機能、および新しいトーナメントを開始する機能については、以下を参照してください。",
      "ManageToTLabel2": "トーナメントが開始されて完了すると、再開することはできなくなります。ただし、同様のトーナメントを完了したい場合は、同じアクションを使用して新しいトーナメントを作成できます。",
      "EndTournamentDialogMessage": "トーナメントを完了しますか?",
      "StartTournamentDialogMessage": "新しいトーナメントを始めますか?",
      "ConfirmLabel": "確認",
      "YesButton": "はい",
      "NoButton": "いいえ",
      "ActiveTournamentLabel": "アクティブなトーナメント",
      "EndTournamentButton": "トーナメントを完了する",
      "StartTournamentHeaderLabel": "トーナメントを開始する",
      "NoTournamentMessage": "トーナメントが見つかりません。後でもう一度ご確認ください。",
      "SelectTournamentMessage": "開始するトーナメントを少なくとも 1 つ選択してください。",
      "SelectEndTournamentMessage": "完了するトーナメントを選択します。",
      "StartTournamentButton": "トーナメントを開始する",
      "EndTournamentSuccessMessage": "トーナメントが正常に完了しました。",
      "EnableTournamentSuccessMessage": "トーナメントが正常に開始されました。",
      "CompleteTournamentSpinnerMessage": "トーナメントを完了しています...",
      "EnableTournamentSpinnerMessage": "トーナメントを有効にしています...",
      "SearchActiveTournaments": "アクティブなトーナメントを検索する",
      "SearchPendingTournaments": "開始するトーナメントを検索する",
      "SelectAllLabel": "すべて選択",
      "NoSearchResults": "検索に一致する結果がありません。",
      "NoActiveParticipantsMessage": "現在、アクティブな参加者はいません。最初に参加し、自分のダッシュボードからアクティビティをログに記録してください!",
      "NoActiveTournamentMessage": "現在、アクティブなトーナメントはありません。後でもう一度ご確認ください。",
      "TournamentLabel": "トーナメント",
      "DescriptionLabel": "説明",
      "NoActiveParticipantsErrorMessage": "現在、アクティブな参加者はいません。最初に参加し、アクティビティをログに記録してください ",
      "PendingActionsLabel": "保留中のアクション",
      "PendingActionsSuccessMessage": "このトーナメントにはこれ以上保留中のアクションはありません。",
      "SelectActionsErrorMessage": "続行するには、少なくとも 1 つのアクションを選択してください。",
      "FormSavingMessage": "詳細を保存しています...",
      "CompletedActionsLabel": "完了したアクション",
      "RankLabel": "ランク",
      "UserLabel": "ユーザー",
      "MyDashboardInfoIconMessage": "このアクションの詳細をご覧ください",
      "SelectTournamentPlaceHolder": "トーナメントの選択",
      "MyTournamentsLabel": "トーナメント",
      "OrLabel": "OR",
      "MyTournamentsTooltip": "既に参加しているアクティブなトーナメント",
      "PointsLabel": "得点",
      "TournamentRankLabel": "トーナメント ランク",
      "ParticipantsLabel": "参加者",
      "TournamentReportsPageTitle": "トーナメント レポート",
      "TotalActivitiesLabel": "アクティビティの合計",
      "TotalPointsLabel": "合計得点",
      "TotalParticipantsLabel": "合計参加者数",
      "TotalPercentageCompletionLabel": "完了の合計に対する割合",
      "Top5ParticipantswithPointsLabel": "ポイントを持つ上位 5 人の参加者",
      "Top5TournamentswithParticipantsLabel": "参加者がいる上位 5 つのトーナメント",
      "ParticipantsStatusLabel": "参加者の状態",
      "ParticipantsDetailsLabel": "参加者の詳細",
      "NameLabel": "名前",
      "PercentageTournamentCompletedLabel": "トーナメント完了の割合",
      "ActivitiesCompletedLabel": "アクティビティが完了しました",
      "NoRecordsinGridLabel": "レコードが見つかりません!",
      "SearchPlaceholder": "参加者の名前で検索する",
      "NoCompletedTournamentsMessage": "現在、完了したトーナメントはありません。後でもう一度ご確認ください。",
      "ReportsDropdownInfoIconText": "レポートは、完了したトーナメントについてのみ生成できます。",
      "RefreshIconInfoText": "最新のデータを表示するには、[更新] をクリックします"
    }

});