define([], function () {
  return {
    "AboutContentLabel": "チャンピオン管理プラットフォームは、組織のチャンピオン/導入スペシャリストを念頭に置いて作成されました。このアプリは、Microsoft 365 チャンピオン コミュニティからの意見を聞き、独自のコミュニティの作成と維持に役立つプラットフォームを提供するために開発されました。実行を通じてインスピレーションを得て、自分のコミュニティ内でより多くの成果を上げるのに役立ちます。",
    "AboutHeaderLabel": "チャンピオン管理プラットフォーム (CMP) について:",
    "AcceptButtonAriaDescription": "このボタンをクリックすると、チャンピオン プログラムの Web パーツに、あなたに代わってプロフィール写真を更新するアクセス許可が与えられます。",
    "AcceptButtonText": "承諾",
    "ActionErrorLabel": "トーナメントを作成するには、少なくとも 1 つのアクションを選択してください。",
    "ActionGridHeader": "操作",
    "ActiveTournamentLabel": "アクティブなトーナメント",
    "ActivitiesCompletedLabel": "アクティビティが完了しました",
    "ActivitiesLabel": "アクティビティ",
    "AdditionalResourcesContentLabel": "Microsoft Teams Customer Advocacy Group は、目標の達成を促し、支援するために、このようなソリューションを提供することに重点を置いています。これらの他のリソースをフォローして参加し、私たちとコミュニティからさらに学びましょう。",
    "AdditionalResourcesHeaderLabel": "追加リソース:",
    "AddMemberLabel": "メンバーを追加",
    "AddMemberPageTitle": "メンバーを追加",
    "AddMembersToolTip": "メンバーの追加: 共同作業を行うユーザーの追加を開始します...",
    "AdminTasksLabel": "管理タスク",
    "AdminToolsLabel": "管理ツール",
    "AppHeaderTitleLabel": "チャンピオン管理プラットフォーム",
    "AppLogoToolTip": "ホーム",
    "ApplyButton": "適用",
    "ApplyButtonAriaDescription": "このボタンをクリックすると、チャンピオン プログラムの Web パーツに、あなたに代わってプロフィール写真を更新するアクセス許可が与えられます。",
    "ApplyButtonText": "イメージの適用",
    "ApplySpinnerLabel": "新しいプロフィール画像をアカウントに適用しています...",
    "ApproveButton": "承認",
    "ApproveChampionSearchboxPlaceholder": "メンバー名/メールで検索",
    "BackButton": "戻る",
    "BadgeImageAlt": "中央に文字 C が付いたメダルの形をした賞です。私はチャンピオン プログラムの一部です",
    "BadgePointsTooltip": "ロック解除に必要なポイント:",
    "BasicGroupName": "グループ名",
    "BecomeChampionLabel": "チャンピオンになる",
    "BySpecialityPlaceHolder": "専門分野で選択する",
    "ChampionActivitiesLabel": "チャンピオン アクティビティ",
    "ChampionApprovedMessage": "チャンピオンの要求が承認されました。",
    "ChampionLabel": "チャンピオン",
    "ChampionLeaderBoardLabel": "チャンピオン ランキング",
    "ChampionListLabel": "チャンピオン リスト",
    "ChampionRejectedMessage": "チャンピオンの要求が拒否されました。",
    "ChampionRequestSubmitSuccessMessage": "チャンピオン要求の送信に成功しました",
    "ChampionsListPageTitle": "チャンピオン リスト",
    "ChampionsListToolTip": "チャンピオン リストにアクセスしています",
    "ChampionsSelectedLabel": "チャンピオンが選択されました。",
    "ChampionSubmissionPendingLabel": "チャンピオンの申請が保留中です",
    "ChatIconLabel": "チャット",
    "CMPBreadcrumbLabel": "チャンピオン管理プラットフォーム",
    "CMPGitHubLinkLabel": "GitHub",
    "CMPSideBarChampionsLabel": "チャンピオン",
    "CMPSideBarGlobalRankLabel": "グローバル ランク",
    "CMPSideBarPointsLabel": "得点",
    "CompletedActionsLabel": "完了したアクション",
    "CompleteTournamentSpinnerMessage": "トーナメントを完了しています...",
    "ConfigSettingsSaved": "構成設定が保存されました。",
    "ConfirmLabel": "確認",
    "CountLabel": "カウント",
    "CountryGridHeader": "国",
    "CountryPlaceholder": "国を選択",
    "CountValidationMessage": "数は 1 から 5 の間でなければなりません",
    "CreateTournamentButton": "トーナメントを作成",
    "CreateTournamentPageTitle": "トーナメントを作成",
    "CreateTournamentsButton": "トーナメントの作成",
    "CreateTournamentSuccessLabel": "トーナメントが正常に作成されました。",
    "CurrentVersionLabel": "現在のバージョン:",
    "DateLabel": "日付",
    "DateofEventGridLabel": "イベントの日付",
    "DescriptionFieldLabel": "説明フィールド",
    "DescriptionLabel": "説明",
    "DigitalBadgeAppBannerAltText": "ディスカッションに参加している Microsoft チーム メンバー",
    "DigitalBadgeLabel": "デジタル バッジ",
    "DigitalBadgePageTitle": "デジタル バッジ",
    "DigitalBadgeSubPageTitle": "デジタル バッジの外観は次のとおりです。",
    "DigitalBadgeSuccessMessage": "<strong>おめでとうございます!</strong> デジタル バッジの申請に成功し、プロフィール写真が更新されました。すべての Microsoft 365 アプリケーション (Teams を含む) に更新が反映されるまで、最大 24 時間かかります。",
    "DigitalMembersToolTip": "デジタル バッジを取得して、プロフィール画像に適用します",
    "DocumentationLabel": "ソリューションの技術ドキュメントとアーキテクチャの概要",
    "DownloadButtonAriaDescription": "クリックして現在のプロフィール画像をダウンロードします",
    "DownloadButtonSecondaryText": "現在のプロフィール画像をダウンロード",
    "DownloadButtonText": "ダウンロード",
    "DownloadedButtonSecondaryText": "ダウンロードしたプロフィール画像は、デバイスのダウンロード フォルダーにあります。",
    "DownloadedButtonText": "ダウンロード完了",
    "DownloadingButtonText": "ダウンロードしています...",
    "DrivingAdoptionLinkLabel": "Microsoft Technical Community での導入の促進",
    "DuplicateTournamentNameError": "トーナメント名は既に存在します。トーナメントの別の名前を入力してください。",
    "EmailIconLabel": "電子メール メッセージの送信",
    "EmailIDLabel": "メール ID",
    "EmailLabel": "メール",
    "EnableTOTLabel": "Teams のトーナメントを有効にする",
    "EnableTOTSpinnerMessage": "このプロセスが完了するまでにしばらく時間がかかります。正常に完了したメッセージが表示されるまで、移動しないでください。",
    "EnableTOTSuccessMessage": "Teams のトーナメントが正常に有効になりました。続行するには、アプリを更新してください。",
    "EnableTOTToolTip": "Teams のトーナメントを有効にする",
    "EnableTournamentSpinnerMessage": "トーナメントを有効にしています...",
    "EnableTournamentSuccessMessage": "トーナメントが正常に開始されました。",
    "EndTournamentButton": "トーナメントを完了する",
    "EndTournamentDialogMessage": "トーナメントを完了しますか?",
    "EndTournamentSuccessMessage": "トーナメントが正常に完了しました。",
    "ErrorMsgActionsList": "アクションの一覧にアイテムを作成中にエラーが発生しました。データを修正して、もう一度お試しください。",
    "ErrorMsgTournamentActionsList": "トーナメント アクションリストにアイテムを作成中にエラーが発生しました。データを修正して、もう一度お試しください。",
    "ErrorMsgTournamentList": "トーナメント リストにアイテムを作成中にエラーが発生しました。データを修正して、もう一度お試しください。",
    "EventApprovalsEnableLabel": "チャンピオン イベントの承認を有効にする",
    "EventApprovedMessage": "チャンピオン イベントが承認されました。",
    "EventLabel": "イベント",
    "EventRejectedMessage": "チャンピオン イベントが拒否されました。",
    "EventsApprovalInfoIconTooltipContent": "このオプションを有効にすると、チャンピオンによるイベント送信が管理者によって承認される必要があります。イベントのポイントは承認後にのみ付与されます。",
    "EventsListLabel": "イベント リスト",
    "EventsListToolTip": "イベント リストにアクセスしています",
    "EventsSelectedLabel": "イベントが選択されました。",
    "EventsSubmissionSuccessMessage": "イベントが正常に記録されました。",
    "EventsSubmitMessage": "イベントの追加が完了したら、[送信] ボタンをクリックして保存してください。",
    "EventsTrackListLabel": "イベント追跡リスト",
    "EventSubmissionPendingMessage": "承認のために送信されたイベント。ポイントは、イベントが承認されると付与されます。",
    "EventTrackListToolTip": "イベント追跡リストにアクセスしています",
    "EventTypeGridLabel": "型",
    "EventTypeGridLabelPlaceHolder": "イベントの種類の選択",
    "EventTypeLabel": "イベントの種類",
    "EventTypeValidationMessage": "イベントの種類を選択してください!",
    "FeedbackToolTip": "フィードバック",
    "FirstNameLabel": "名",
    "FocusAreaGridHeader": "フォーカス領域",
    "FocusAreaLabel": "フォーカス領域",
    "FocusAreaPlaceholder": "フォーカス領域の選択",
    "FormSavingMessage": "詳細を保存しています...",
    "GetStartedLabel": "開始",
    "GroupGridHeader": "グループ",
    "GroupPlaceholder": "グループを選択する",
    "HowtoGetDigitalBadgeText": "チャンピオン バッジを取得する方法",
    "ImportRule1": "テンプレートの列ヘッダーを変更しない",
    "ImportRule2": "テンプレート内の列を削除しない",
    "ImportRule3": "テンプレートに記載されているすべての必須 (*) 列にデータを入力してください",
    "ImportRule4": "各列のテンプレートに記載されている文字数制限と種類に従ってください",
    "ImportRule5": "提供されたサンプル データに従って、各シートに 1 つのトーナメントのみのデータを入力します",
    "ImportRule6": "一度に作成できるトーナメントは 10 個のみです",
    "ImportRule7": "トーナメント名が一意であることを確認してください",
    "ImportSpinnerMessage": "トーナメントを作成しています.....",
    "LastNameLabel": "姓",
    "LatestVersionLabel": "最新バージョン",
    "LoadingSpinnerLabel": "読み込んでいます...",
    "LogMsgBlankSheet": "空白のため、スキップされました。",
    "LogMsgDone": "トーナメント",
    "LogMsgDone1": "作成されました。",
    "LogMsgInvalidTemplate": "有効なテンプレートではないため、スキップされました。",
    "LogMsgInvalidTournamentName": "有効なトーナメント名がないため、スキップされました。",
    "LogMsgMultipleTournaments": "複数のトーナメント名があるため、スキップされました。",
    "LogMsgTournamentExists": "トーナメントが既に存在するため、スキップされました",
    "LogMsgTournamentExists1": "既に存在します。",
    "LogProgress": " 進捗状況は次のとおりです。",
    "M365ChampionCommunityLinkLabel": "Microsoft 365 チャンピオン コミュニティ",
    "ManageAdminsLabel": "管理者の管理",
    "ManageAdminsToolTip": "管理リストにアクセスしています",
    "ManageAppLogoLabel": "アプリのロゴを管理する",
    "ManageAppLogoToolTip": "アプリのロゴを管理する",
    "ManageConfigSettingsLabel": "構成設定の管理",
    "ManageDigitalBadgesLabel": "デジタル バッジの管理",
    "ManageDigitalBadgesToolTip": "デジタル バッジの管理",
    "ManageToTLabel1": "一度に複数のトーナメントを開始できます。現在アクティブなトーナメント、トーナメントを完了する機能、および新しいトーナメントを開始する機能については、以下を参照してください。",
    "ManageToTLabel2": "トーナメントが開始されて完了すると、再開することはできなくなります。ただし、同様のトーナメントを完了したい場合は、同じアクションを使用して新しいトーナメントを作成できます。",
    "ManageTournamentActionsLabel": "トーナメント アクションの管理",
    "ManageTournamentActionsToolTip": "トーナメント アクション リストにアクセスしています",
    "ManageTournamentsLabel": "トーナメントの管理",
    "ManageTournamentsPageTitle": "トーナメントの管理",
    "MeetupBody": "チャンピオン分野について話し合い、詳細を確認する時間を確保しましょう!",
    "MeetupSubject": "1:1 (チャンピオンの要求)",
    "MonthAndDateLabel": "月と日",
    "MoreInfoToolTip": "詳細",
    "MSAdoptionHubLinkLabel": "Microsoft 導入ハブ",
    "MultipleBadgeMessage": "下の一覧からバッジを選択してください。選択したバッジはプロフィール画像に適用されます。",
    "MultipleTournamentLabel": "複数のトーナメント",
    "MultiTournamentStep": "ステップ",
    "MultiTournamentStep1LinkLabel": "テンプレートをダウンロード",
    "MultiTournamentStep1Text": " サンプル ファイル形式の",
    "MultiTournamentStep2": "ガイドラインに従って、トーナメントの詳細をファイルに追加します",
    "MultiTournamentStep3": "ファイルをアップロード",
    "MyDashboardInfoIconMessage": "このアクションの詳細をご覧ください",
    "MyRankLabel": "自分のランク",
    "MyTournamentsLabel": "トーナメント",
    "MyTournamentsTooltip": "既に参加しているアクティブなトーナメント",
    "NameLabel": "名前",
    "NearMePlaceHolder": "近くを選択",
    "NoActiveParticipantsErrorMessage": "現在、アクティブな参加者はいません。最初に参加し、アクティビティをログに記録してください ",
    "NoActiveParticipantsMessage": "現在、アクティブな参加者はいません。最初に参加し、自分のダッシュボードからアクティビティをログに記録してください!",
    "NoActiveTournamentMessage": "現在、アクティブなトーナメントはありません。後でもう一度ご確認ください。",
    "NoActivitiesinGridLabel": "アクティビティが見つかりません!",
    "NoBadgeMessage": "選択するバッジが見つかりません。アプリ管理者に確認してください。",
    "NoButton": "いいえ",
    "NoChampionsMessage": "現時点では保留中の要求はありません",
    "NoCompletedTournamentsMessage": "現在、完了したトーナメントはありません。後でもう一度ご確認ください。",
    "NominateMemberLabel": "メンバーの推薦",
    "NominateMemberPageTitle": "メンバーの推薦",
    "NoPendingEventsLabel": "現時点で保留中のイベントはありません。",
    "NoProfileImageAlt": "プロフィール画像が現在アカウントに適用されていないことを示す人物のシルエット",
    "NoProfileImageDescription": "既に写真をプロフィールに関連付けていて、まだこのメッセージが表示されている場合は、写真がまだ利用できない可能性があります。後でもう一度やり直すか、24 時間経過しても表示されない場合は <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>helpdesk</a> に連絡してください。",
    "NoRecordsIcon": "記録なしアイコン",
    "NoRecordsinGridLabel": "レコードが見つかりません!",
    "NoSearchResults": "検索に一致する結果がありません。",
    "NotesLabel": "メモ",
    "NotesPlaceholder": "最大 200 文字",
    "NoTournamentMessage": "トーナメントが見つかりません。後でもう一度ご確認ください。",
    "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>デジタル バッジ ユーティリティへようこそ</span>。チャンピオン プログラムのメンバーシップの一環として、デジタル バッジを獲得しました。このユーティリティを使用すると、既存のプロフィール写真の上にデジタル バッジを重ねて、デジタル バッジを '<em>請求</em>' することができます。これにより、すべての Microsoft 365 (Exchange、Teams、SharePoint など) でプロフィール写真が更新されることに注意してください。",
    "OrLabel": "OR",
    "OverviewLabel": "概要と情報",
    "ParticipantsDetailsLabel": "参加者の詳細",
    "ParticipantsLabel": "参加者",
    "ParticipantsStatusLabel": "参加者の状態",
    "PendingActionsLabel": "保留中のアクション",
    "PendingActionsSuccessMessage": "このトーナメントにはこれ以上保留中のアクションはありません。",
    "PendingEventsSearchboxPlaceholder": "チャンピオン/メールで検索",
    "PeopleNameGridHeader": "メンバー名",
    "PeoplePickerPlaceholder": "メンバーを追加するには、メンバー名を入力してください",
    "PercentageTournamentCompletedLabel": "トーナメント完了の割合",
    "PivotHeaderBySpeciality": "専門分野",
    "PivotHeaderGlobal": "グローバル",
    "PivotHeaderNearMe": "近くにいる",
    "PointsLabel": "得点",
    "PreAcceptDisclaimer": "<span style='font-weight:bold;'>デジタル バッジ ユーティリティへようこそ</span> <br/><br/> <span>チャンピオン プログラムのメンバーシップの一環として、デジタル バッジを獲得しました。このユーティリティを使用すると、既存のプロフィール写真の上にデジタル バッジを重ねて、デジタル バッジを '<em>請求</em>' することができます。<br/><br/> これにより、すべての Microsoft 365 (Exchange、Teams、SharePoint など) でプロフィール写真が更新されることに注意してください。</span>",
    "PreAcceptDisclaimer2": "必要に応じて、<span style='font-weight:bold;'>次の手順でデジタル バッジのオーバーレイを使用せずに、既存のプロフィール写真のコピーを [保存] する機会があります</span>。[同意する] をクリックして続行してください (ポップアップが開き、サインインを求めるプロンプトが表示される場合があります)。",
    "PreAcceptPageTitle": "デジタル バッジを要求してください!",
    "PreApplyDisclaimer": "これは、デジタル バッジを含む新しいプロフィール写真のプレビューです。デジタル バッジを適用する前に既存のプロフィール写真をダウンロードする場合は、<strong>[現在のプロフィール画像をダウンロードする]</strong> リンクをクリックしてください。<br />",
    "PreApplyDisclaimer1": "<br />[画像の適用] をクリックすると、Microsoft 365 のプロフィール写真がこの新しい画像で更新されます。<strong>これにより、Microsoft 365 全体でプロフィール写真が更新され、このページから元に戻すことはできないので注意してください</strong>。<br/><br/>写真を元に戻したい場合は、<a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' aria-label='Open the Outlook web application in a new browser tab or window'>Outlook web application</a> を使用できます。",
    "ProcessingSpinnerLabel": "処理中...",
    "ProfileImageAlt": "O365、Teams などで使用されるプロファイル画像",
    "PropertyPaneDescription": "説明",
    "QuickLinksLabel": "クイック リンク",
    "RankLabel": "ランク",
    "RecordEventLabel": "イベントの記録",
    "RecordsNotFound": "検出されなかったレコード",
    "RefreshIconInfoText": "最新のデータを表示するには、[更新] をクリックします",
    "RegionGridHeader": "地域",
    "RegionLabel": "地域",
    "RegionPlaceholder": "地域の選択",
    "RejectButton": "拒否",
    "RemoveFileLabel": "ファイルの削除",
    "ReportsDropdownInfoIconText": "レポートは、完了したトーナメントについてのみ生成できます。",
    "RequestToCallLabel": "通話の要求",
    "SaveButton": "保存",
    "SearchActiveTournaments": "アクティブなトーナメントを検索する",
    "SearchLabel": "検索",
    "SearchPendingTournaments": "開始するトーナメントを検索する",
    "SearchPlaceholder": "参加者の名前で検索する",
    "SelectActionsErrorMessage": "続行するには、少なくとも 1 つのアクションを選択してください。",
    "SelectAll": "すべてのチャンピオンを選択",
    "SelectAllEvents": "すべてのイベントを選択",
    "SelectAllLabel": "すべて選択",
    "SelectChampion": "チャンピオンの選択",
    "SelectDate": "日付を選択",
    "SelectEndTournamentMessage": "完了するトーナメントを選択します。",
    "SelectEvent": "イベントの選択",
    "SelectTeamsActionsLabel": "Teams アクションの選択:",
    "SelectTournamentMessage": "開始するトーナメントを少なくとも 1 つ選択してください。",
    "SelectTournamentPlaceHolder": "トーナメントの選択",
    "ShowMoreLabel": "詳細表示",
    "SingleTournamentLabel": "単一のトーナメント",
    "SpinnerListCreationMessage": "Teams のトーナメントを設定しています...",
    "StartTournamentButton": "トーナメントを開始する",
    "StartTournamentDialogMessage": "新しいトーナメントを始めますか?",
    "StartTournamentHeaderLabel": "トーナメントを開始する",
    "StatusGridHeader": "状態",
    "SubmitButton": "送信",
    "SuccessIcon": "成功アイコン",
    "SupportToolTip": "サポート",
    "TeamsActionInfoToolTip": "以下の利用可能なチーム アクションから選択して、新しいトーナメントに含めます。選択する新しいトーナメント アクションを追加するには、管理ツールから [トーナメント アクションの管理] にアクセスします。",
    "ToggleLabelForMemberListColumns": "メンバー リスト フィールドの表示/非表示",
    "TooltipContentForMemberListFieldsHeading": "該当する場合は、アプリのすべてのコンポーネントのメンバー リスト フィールドの表示/非表示を切り替えます。",
    "Top5ParticipantswithPointsLabel": "ポイントを持つ上位 5 人の参加者",
    "Top5TournamentswithParticipantsLabel": "参加者がいる上位 5 つのトーナメント",
    "TopChampionsLabel": "上位のチャンピオン",
    "TotalActivitiesLabel": "アクティビティの合計",
    "TotalParticipantsLabel": "合計参加者数",
    "TotalPercentageCompletionLabel": "完了の合計に対する割合",
    "TotalPointsLabel": "合計得点",
    "TOTBreadcrumbLabel": "Teams のトーナメント",
    "TOTLabel": "Teams のトーナメント",
    "TOTLeaderBoardPageTitle": "リーダー ボード",
    "TOTMyDashboardPageTitle": "自分のダッシュボード",
    "TournamentDescPlaceHolderLabel": "トーナメントの説明 (最大 500 文字)",
    "TournamentDescriptionLabel": "トーナメントの説明",
    "TournamentLabel": "トーナメント",
    "TournamentNameErrorLabel": "トーナメント名が必要です。",
    "TournamentNameLabel": "トーナメント名",
    "TournamentNamePlaceHolderLabel": "トーナメント名 (最大 255 文字)",
    "TournamentRankLabel": "トーナメント ランク",
    "TournamentReportsPageTitle": "トーナメント レポート",
    "UnauthorizedText": "現在、チャンピオン バッジ プログラムの資格はありません。",
    "UploadFileButton": "ファイルのアップロード",
    "UserAddedMessage": "ユーザーが正常に追加されました。",
    "UserExistingMessage": "ユーザーは既にチャンピオンです!",
    "UserLabel": "ユーザー",
    "UserNominatedMessage": "ユーザーが正常に推薦されました。",
    "ViewActivitiesLabel": "アクティビティの表示",
    "ViewDashBoardLabel": "ダッシュボードを表示",
    "VisitLabel": "詳細については、チャンピオン管理プラットフォームのページにアクセスしてください。",
    "WelcomeLabel": "ようこそ",
    "YesButton": "はい",
  }
});