define([], function () {
  return {
    "AboutContentLabel": "챔피언 관리 플랫폼은 조직의 챔피언/채택 전문가를 염두에 두고 제작되었습니다. Microsoft 365 챔피언 커뮤니티의 의견을 반영하여 개발된 이 앱은 자체 커뮤니티를 만들고 유지하는 데 도움이 되는 플랫폼을 제공합니다. 자체 커뮤니티 내에서 더 많은 목표를 달성하는 데 도움이 되는 실행을 통해 영감을 얻은 상태로 시작하세요!",
    "AboutHeaderLabel": "CMP(챔피언 관리 플랫폼) 정보:",
    "AcceptButtonAriaDescription": "이 버튼을 클릭하면 챔피언십 프로그램 웹 파트에 사용자 대신 프로필 사진을 업데이트할 수 있는 권한이 부여됩니다.",
    "AcceptButtonText": "수락",
    "ActionErrorLabel": "토너먼트를 만들려면 하나 이상의 작업을 선택하세요.",
    "ActionGridHeader": "액션",
    "ActiveTournamentLabel": "활성 토너먼트",
    "ActivitiesCompletedLabel": "작업 완료됨",
    "ActivitiesLabel": "활동",
    "AdditionalResourcesContentLabel": "Microsoft Teams 고객 지지 그룹은 주로 이와 같은 솔루션을 제공하여 목표를 달성하기 위한 동기를 부여하고 도움을 주는 일을 합니다. 이러한 기타 리소스를 통해 팔로우하고 가입하여 당사와 당사 커뮤니티에게서 더 많은 도움을 받으세요.",
    "AdditionalResourcesHeaderLabel": "추가 리소스:",
    "AddMemberLabel": "구성원 추가",
    "AddMemberPageTitle": "구성원 추가",
    "AddMembersToolTip": "구성원 추가 작업에서 공동 작업할 사용자 추가 시작...",
    "AdminTasksLabel": "관리 작업",
    "AdminToolsLabel": "관리 도구",
    "AppHeaderTitleLabel": "챔피언 관리 플랫폼",
    "AppLogoToolTip": "홈",
    "ApplyButton": "적용",
    "ApplyButtonAriaDescription": "이 버튼을 클릭하면 챔피언십 프로그램 웹 파트에 사용자 대신 프로필 사진을 업데이트할 수 있는 권한이 부여됩니다.",
    "ApplyButtonText": "이미지 적용",
    "ApplySpinnerLabel": "계정에 새 프로필 이미지를 적용하는 중...",
    "ApproveButton": "승인",
    "ApproveChampionSearchboxPlaceholder": "구성원 이름/전자 메일로 검색",
    "BackButton": "뒤로",
    "BadgeImageAlt": "가운데에 C라는 문자가 있는 메달 모양 상은 챔피언십 프로그램에 참여 중임을 나타냅니다.",
    "BadgePointsTooltip": "잠금 해제에 필요한 포인트:",
    "BasicGroupName": "그룹 이름",
    "BecomeChampionLabel": "챔피언 되기",
    "BySpecialityPlaceHolder": "전문 분야별 선택",
    "ChampionActivitiesLabel": "챔피언 활동",
    "ChampionApprovedMessage": "챔피언 요청이 승인되었습니다.",
    "ChampionLabel": "챔피언",
    "ChampionLeaderBoardLabel": "챔피언 순위표",
    "ChampionListLabel": "챔피언 목록",
    "ChampionRejectedMessage": "챔피언 요청이 거부되었습니다.",
    "ChampionRequestSubmitSuccessMessage": "챔피언 요청 제출 성공",
    "ChampionsListPageTitle": "챔피언 목록",
    "ChampionsListToolTip": "챔피언 목록에 액세스하는 중",
    "ChampionsSelectedLabel": "챔피언을 선택했습니다.",
    "ChampionSubmissionPendingLabel": "챔피언 제출 보류 중",
    "ChatIconLabel": "채팅",
    "CMPBreadcrumbLabel": "챔피언 관리 플랫폼",
    "CMPGitHubLinkLabel": "GitHub",
    "CMPSideBarChampionsLabel": "챔피언",
    "CMPSideBarGlobalRankLabel": "글로벌 순위",
    "CMPSideBarPointsLabel": "점수",
    "CompletedActionsLabel": "완료된 액션",
    "CompleteTournamentSpinnerMessage": "토너먼트 완료 중...",
    "ConfigSettingsSaved": "구성 설정이 저장되었습니다.",
    "ConfirmLabel": "확인",
    "CountLabel": "수",
    "CountryGridHeader": "국가",
    "CountryPlaceholder": "국가 선택",
    "CountValidationMessage": "수는 1에서 5 사이여야 합니다.",
    "CreateTournamentButton": "토너먼트 만들기",
    "CreateTournamentPageTitle": "토너먼트 만들기",
    "CreateTournamentsButton": "토너먼트 만들기",
    "CreateTournamentSuccessLabel": "토너먼트를 만들었습니다.",
    "CurrentVersionLabel": "현재 버전:",
    "DateLabel": "날짜",
    "DateofEventGridLabel": "이벤트 날짜",
    "DescriptionFieldLabel": "설명 필드",
    "DescriptionLabel": "설명",
    "DigitalBadgeAppBannerAltText": "토론에 참여하는 Microsoft 팀 구성원",
    "DigitalBadgeLabel": "디지털 배지",
    "DigitalBadgePageTitle": "디지털 배지",
    "DigitalBadgeSubPageTitle": "디지털 배지의 모양은 다음과 같습니다!",
    "DigitalBadgeSuccessMessage": "<strong>축하드려요!</strong> 디지털 배지를 클레임하고 프로필 사진을 업데이트했습니다. Teams를 비롯한 모든 Microsoft 365 응용 프로그램에서 반영된 업데이트를 확인하려면 최대 24시간을 기다려주세요.",
    "DigitalMembersToolTip": "디지털 배지를 가져와 프로필 이미지에 적용",
    "DocumentationLabel": "솔루션 기술 설명서 및 아키텍처 개요",
    "DownloadButtonAriaDescription": "클릭해서 현재 프로필 이미지를 다운로드",
    "DownloadButtonSecondaryText": "현재 프로필 이미지 다운로드",
    "DownloadButtonText": "다운로드",
    "DownloadedButtonSecondaryText": "다운로드한 프로필 이미지는 장치의 다운로드 폴더에서 찾을 수 있습니다.",
    "DownloadedButtonText": "다운로드됨",
    "DownloadingButtonText": "다운로드 중...",
    "DrivingAdoptionLinkLabel": "Microsoft Technical Community에서 채택 추진",
    "DuplicateTournamentNameError": "토너먼트 이름이 이미 존재합니다. 토너먼트의 다른 이름을 입력하세요.",
    "EmailIconLabel": "전자 메일 보내기",
    "EmailIDLabel": "전자 메일 ID",
    "EmailLabel": "메일",
    "EnableTOTLabel": "팀 토너먼트 사용",
    "EnableTOTSpinnerMessage": "이 프로세스를 완료하는 데 몇 분 정도 걸립니다. 완료된 성공적으로 완료된 메시지가 표시될 때까지 다른 곳으로 이동하지 마세요.",
    "EnableTOTSuccessMessage": "팀 토너먼트를 사용하도록 설정했습니다. 계속하려면 앱을 새로 고치세요.",
    "EnableTOTToolTip": "팀 토너먼트 사용",
    "EnableTournamentSpinnerMessage": "토너먼트를 사용하도록 설정하는 중...",
    "EnableTournamentSuccessMessage": "토너먼트가 시작되었습니다.",
    "EndTournamentButton": "토너먼트 완료",
    "EndTournamentDialogMessage": "토너먼트를 완료할까요?",
    "EndTournamentSuccessMessage": "토너먼트를 완료했습니다.",
    "ErrorMsgActionsList": "작업 목록에서 항목을 만드는 동안 오류가 발생했습니다. 데이터를 수정하고 다시 시도하세요.",
    "ErrorMsgTournamentActionsList": "토너먼트 작업 목록에 항목을 만드는 동안 오류가 발생했습니다. 데이터를 수정하고 다시 시도하세요.",
    "ErrorMsgTournamentList": "토너먼트 목록에 항목을 만드는 동안 오류가 발생했습니다. 데이터를 수정하고 다시 시도하세요.",
    "EventApprovalsEnableLabel": "챔피언 이벤트 승인 사용",
    "EventApprovedMessage": "챔피언 이벤트가 승인되었습니다.",
    "EventLabel": "이벤트",
    "EventRejectedMessage": "챔피언 이벤트가 거부되었습니다.",
    "EventsApprovalInfoIconTooltipContent": "이 옵션을 사용하도록 설정하려면 챔피언의 이벤트 제출이 관리자의 승인을 받아야 합니다. 이벤트의 포인트는 승인 후에만 부여됩니다.",
    "EventsListLabel": "이벤트 목록",
    "EventsListToolTip": "이벤트 목록에 액세스하는 중",
    "EventsSelectedLabel": "이벤트가 선택되었습니다.",
    "EventsSubmissionSuccessMessage": "이벤트가 성공적으로 기록되었습니다.",
    "EventsSubmitMessage": "이벤트 추가가 완료되면 [제출] 버튼을 클릭하여 저장하세요.",
    "EventsTrackListLabel": "이벤트 트랙킹 목록",
    "EventSubmissionPendingMessage": "승인을 위해 제출된 이벤트입니다. 이벤트가 승인되면 포인트가 지급됩니다.",
    "EventTrackListToolTip": "이벤트 트랙킹 목록에 액세스하는 중",
    "EventTypeGridLabel": "유형",
    "EventTypeGridLabelPlaceHolder": "이벤트 유형 선택",
    "EventTypeLabel": "이벤트 유형",
    "EventTypeValidationMessage": "이벤트 유형을 선택하세요!",
    "FeedbackToolTip": "피드백",
    "FirstNameLabel": "이름",
    "FocusAreaGridHeader": "포커스 영역",
    "FocusAreaLabel": "포커스 영역",
    "FocusAreaPlaceholder": "포커스 영역 선택",
    "FormSavingMessage": "세부 정보를 저장하는 중...",
    "GetStartedLabel": "시작",
    "GroupGridHeader": "그룹",
    "GroupPlaceholder": "그룹 선택",
    "HowtoGetDigitalBadgeText": "챔피언 배지를 받는 방법",
    "ImportRule1": "템플릿의 열 머리글 수정 안 함",
    "ImportRule2": "템플릿의 열을 삭제하지 않음",
    "ImportRule3": "템플릿에 언급된 모든 필수(*) 열에 데이터 입력",
    "ImportRule4": "각 열이 템플릿에 언급된 문자 제한 및 형식을 따릅니다.",
    "ImportRule5": "제공된 샘플 데이터에 따라 각 시트에 1개의 토너먼트에 대한 데이터만 입력하세요.",
    "ImportRule6": "한 번에 10개의 토너먼트만 만들 수 있습니다.",
    "ImportRule7": "토너먼트 이름이 고유한지 확인하세요.",
    "ImportSpinnerMessage": "토너먼트를 만드는 중.....",
    "LastNameLabel": "성",
    "LatestVersionLabel": "최신 버전:",
    "LoadingSpinnerLabel": "로드 중...",
    "LogMsgBlankSheet": "비어 있으므로 건너뛰었습니다.",
    "LogMsgDone": "토너먼트",
    "LogMsgDone1": "만들어졌습니다.",
    "LogMsgInvalidTemplate": "올바른 템플릿이 아니므로 건너뛰었습니다.",
    "LogMsgInvalidTournamentName": "유효한 토너먼트 이름이 없으므로 건너뛰었습니다.",
    "LogMsgMultipleTournaments": "토너먼트 이름이 두 개 이상 있으므로 건너뛰었습니다.",
    "LogMsgTournamentExists": "토너먼트로 인해 건너뜀",
    "LogMsgTournamentExists1": "이미 있습니다.",
    "LogProgress": "진행률은 다음과 같습니다.",
    "M365ChampionCommunityLinkLabel": "Microsoft 365 챔피언 커뮤니티",
    "ManageAdminsLabel": "관리자 관리",
    "ManageAdminsToolTip": "관리 목록에 액세스하는 중",
    "ManageAppLogoLabel": "앱 로고 관리",
    "ManageAppLogoToolTip": "Manage App Logo",
    "ManageConfigSettingsLabel": "구성 설정 관리",
    "ManageDigitalBadgesLabel": "디지털 배지 관리",
    "ManageDigitalBadgesToolTip": "디지털 배지 관리",
    "ManageToTLabel1": "한 번에 여러 토너먼트를 시작할 수 있습니다. 현재 활성 토너먼트, 토너먼트 완료 기능 및 새 토너먼트 시작 기능은 아래를 참조하세요.",
    "ManageToTLabel2": "토너먼트가 시작되고 완료되면 다시 시작할 수 없습니다. 그러나 유사한 토너먼트를 완료하려는 경우 동일한 작업을 사용하여 새 토너먼트를 만들 수 있습니다!",
    "ManageTournamentActionsLabel": "토너먼트 작업 관리",
    "ManageTournamentActionsToolTip": "토너먼트 작업 목록에 액세스",
    "ManageTournamentsLabel": "토너먼트 관리",
    "ManageTournamentsPageTitle": "토너먼트 관리",
    "MeetupBody": "챔피언 지역에 대해 토론하고 자세히 알아볼 시간을 마련해 주세요!",
    "MeetupSubject": "1:1(챔피언 요청)",
    "MonthAndDateLabel": "월 및 일",
    "MoreInfoToolTip": "자세한 정보",
    "MSAdoptionHubLinkLabel": "Microsoft 채택 허브",
    "MultipleBadgeMessage": "아래 목록에서 배지를 선택하세요. 선택한 배지가 프로필 사진에 적용됩니다.",
    "MultipleTournamentLabel": "여러 토너먼트",
    "MultiTournamentStep": "단계",
    "MultiTournamentStep1LinkLabel": "템플릿 다운로드",
    "MultiTournamentStep1Text": "샘플 파일 형식",
    "MultiTournamentStep2": "지침에 따라 토너먼트 세부 정보를 파일에 추가",
    "MultiTournamentStep3": "파일 업로드",
    "MyDashboardInfoIconMessage": "이 액션에 대해 자세히 알아보기",
    "MyRankLabel": "내 순위",
    "MyTournamentsLabel": "내 토너먼트",
    "MyTournamentsTooltip": "이미 참가한 활성 토너먼트",
    "NameLabel": "이름",
    "NearMePlaceHolder": "내 근처에 있는 항목 선택",
    "NoActiveParticipantsErrorMessage": "현재 활성 참가자가 없습니다. 가장 먼저 참여하여 활동을 기록해 보세요. ",
    "NoActiveParticipantsMessage": "현재 활성 참가자가 없습니다. 가장 먼저 내 대시보드에 참여하고 활동을 기록해 보세요!",
    "NoActiveTournamentMessage": "현재 활성 토너먼트가 없습니다. 나중에 다시 확인하세요.",
    "NoActivitiesinGridLabel": "활동을 찾을 수 없습니다!",
    "NoBadgeMessage": "선택할 배지를 찾을 수 없습니다. 앱 관리자에게 문의하세요.",
    "NoButton": "아니요",
    "NoChampionsMessage": "현재 보류 중인 요청이 없습니다.",
    "NoCompletedTournamentsMessage": "현재 완료된 토너먼트가 없습니다. 나중에 다시 확인해 주세요.",
    "NominateMemberLabel": "구성원 추천",
    "NominateMemberPageTitle": "구성원 추천",
    "NoPendingEventsLabel": "현재 보류 중인 이벤트가 없습니다.",
    "NoProfileImageAlt": "현재 계정에 적용된 프로필 이미지가 없음을 나타내는 사람의 실루엣",
    "NoProfileImageDescription": "사진을 프로필과 이미 연결했으나 이 메시지가 계속 표시되는 경우 사진을 아직 사용할 수 없을 수 있습니다. 나중에 다시 시도하거나, 24시간 후에도 계속 사진이 표시되지 않으면 <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>지원팀</a>에 문의하세요.",
    "NoRecordsIcon": "레코드 없음 아이콘",
    "NoRecordsinGridLabel": "발견된 레코드가 없습니다!",
    "NoSearchResults": "검색과 일치하는 결과가 없습니다.",
    "NotesLabel": "메모",
    "NotesPlaceholder": "최대 200자",
    "NoTournamentMessage": "토너먼트를 찾을 수 없습니다. 나중에 다시 확인하세요.",
    "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>디지털 배지 유틸리티에 오신 것을 환영합니다</span>. 챔피언 프로그램 멤버십의 일부로 디지털 배지를 획득할 수 있습니다! 이 유틸리티를 사용하면 기존 프로필 사진 위에 디지털 배지를 오버레이하여 '<em>클레임</em>'할 수 있습니다. 이렇게 하면 모든 Microsoft 365(Exchange, Teams, SharePoint 등)에서 프로필 사진이 업데이트됩니다.",
    "OrLabel": "또는",
    "OverviewLabel": "개요 및 정보",
    "ParticipantsDetailsLabel": "참가자 세부 정보",
    "ParticipantsLabel": "참가자",
    "ParticipantsStatusLabel": "참가자 상태",
    "PendingActionsLabel": "보류 중인 액션",
    "PendingActionsSuccessMessage": "이 토너먼트에는 더 이상 보류 중인 작업이 없습니다.",
    "PendingEventsSearchboxPlaceholder": "챔피언/메일로 검색",
    "PeopleNameGridHeader": "구성원 이름",
    "PeoplePickerPlaceholder": "구성원을 추가하려면 구성원 이름을 입력하세요.",
    "PercentageTournamentCompletedLabel": "토너먼트 완료 %",
    "PivotHeaderBySpeciality": "전문 분야별",
    "PivotHeaderGlobal": "글로벌",
    "PivotHeaderNearMe": "내 근처",
    "PointsLabel": "점수",
    "PreAcceptDisclaimer": "<span style='font-weight:bold;'>디지털 배지 유틸리티에 오신 것을 환영합니다</span> <br/><br/> <span>챔피언 프로그램 멤버십의 일환으로 디지털 배지를 획득하셨습니다! 이 유틸리티를 사용하면 기존 프로필 사진 위에 디지털 배지를 오버레이하여 '<em>클레임</em>'할 수 있습니다. <br/><br/> 이렇게 하면 모든 Microsoft 365(Exchange, Teams, SharePoint 등)에서 프로필 사진이 업데이트됩니다.</span>",
    "PreAcceptDisclaimer2": "원하는 경우 다음 단계에서 디지털 배지 오버레이 없이 <span style='font-weight:bold;'>기존 프로필 사진 복사본을 ‘저장’</span>할 수 있습니다. ‘수락’을 클릭하여 계속하세요(팝업이 열리고 로그인하라는 메시지가 표시될 수 있습니다).",
    "PreAcceptPageTitle": "디지털 배지를 클레임하세요!",
    "PreApplyDisclaimer": "디지털 배지를 포함한 새 프로필 사진의 미리 보기입니다. 디지털 배지를 적용하기 전에 기존 프로필 사진을 다운로드하려면 '<strong> 현재 프로필 이미지 다운로드</strong>' 링크를 클릭하세요.<br />",
    "PreApplyDisclaimer1": "<br />'이미지 적용'을 클릭하면 Microsoft 365 프로필 사진이 이 새 이미지로 업데이트됩니다. <strong>이렇게 하면 모든 Microsoft 365 프로필 사진이 업데이트되며 이 페이지를 통해 되돌릴 수 없습니다</strong>. <br/><br/>사진을 다시 변경하려면 <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' aria-label='Open the Outlook web application in a new browser tab or window'>Outlook 웹 응용 프로그램</a>을 사용할 수 있습니다.",
    "ProcessingSpinnerLabel": "처리 중...",
    "ProfileImageAlt": "O365, Teams 등에서 사용되는 내 프로필 이미지",
    "PropertyPaneDescription": "설명",
    "QuickLinksLabel": "빠른 링크",
    "RankLabel": "순위",
    "RecordEventLabel": "이벤트 레코드",
    "RecordsNotFound": "레코드를 찾지 못함",
    "RefreshIconInfoText": "새로 고침을 클릭하여 최신 데이터 보기",
    "RegionGridHeader": "지역",
    "RegionLabel": "지역",
    "RegionPlaceholder": "지역 선택",
    "RejectButton": "거부",
    "RemoveFileLabel": "파일 제거",
    "ReportsDropdownInfoIconText": "보고서는 완료된 토너먼트에 대해서만 생성할 수 있습니다.",
    "RequestToCallLabel": "통화 요청",
    "SaveButton": "저장",
    "SearchActiveTournaments": "활성 토너먼트 검색",
    "SearchLabel": "검색",
    "SearchPendingTournaments": "시작할 토너먼트 검색",
    "SearchPlaceholder": "참가자 이름으로 검색",
    "SelectActionsErrorMessage": "계속하려면 액션을 하나 이상 선택하세요.",
    "SelectAll": "모든 챔피언 선택",
    "SelectAllEvents": "모든 이벤트 선택",
    "SelectAllLabel": "모두 선택",
    "SelectChampion": "챔피언 선택",
    "SelectDate": "날짜 선택",
    "SelectEndTournamentMessage": "완료할 토너먼트를 선택하세요.",
    "SelectEvent": "이벤트 선택",
    "SelectTeamsActionsLabel": "Teams 액션 선택:",
    "SelectTournamentMessage": "시작할 토너먼트를 하나 이상 선택하세요.",
    "SelectTournamentPlaceHolder": "토너먼트 선택",
    "ShowMoreLabel": "더 보기",
    "SingleTournamentLabel": "단일 토너먼트",
    "SpinnerListCreationMessage": "팀 토너먼트 설정 중...",
    "StartTournamentButton": "토너먼트 시작",
    "StartTournamentDialogMessage": "새 토너먼트를 시작할까요?",
    "StartTournamentHeaderLabel": "토너먼트 시작",
    "StatusGridHeader": "상태",
    "SubmitButton": "제출",
    "SuccessIcon": "성공 아이콘",
    "SupportToolTip": "지원",
    "TeamsActionInfoToolTip": "아래의 사용 가능한 팀 작업에서 새 토너먼트에 포함할 작업을 선택하세요. 선택할 새 토너먼트 작업을 추가하려면 관리 도구에서 토너먼트 작업 관리를 방문하세요.",
    "ToggleLabelForMemberListColumns": "멤버 목록 필드 표시/숨기기",
    "TooltipContentForMemberListFieldsHeading": "해당하는 경우 앱의 모든 구성 요소에 구성원 목록 필드를 표시하거나 숨깁니다.",
    "Top5ParticipantswithPointsLabel": "점수 포함 상위 5명 참가자",
    "Top5TournamentswithParticipantsLabel": "참가자 포함 상위 5개 토너먼트",
    "TopChampionsLabel": "상위 챔피언",
    "TotalActivitiesLabel": "활동 합계",
    "TotalParticipantsLabel": "참가자 합계",
    "TotalPercentageCompletionLabel": "총 완료율(%)",
    "TotalPointsLabel": "점수 합계",
    "TOTBreadcrumbLabel": "팀 토너먼트",
    "TOTLabel": "팀 토너먼트",
    "TOTLeaderBoardPageTitle": "순위표",
    "TOTMyDashboardPageTitle": "내 대시보드",
    "TournamentDescPlaceHolderLabel": "토너먼트 설명(최대 500자)",
    "TournamentDescriptionLabel": "토너먼트 설명",
    "TournamentLabel": "토너먼트",
    "TournamentNameErrorLabel": "토너먼트 이름이 필요합니다.",
    "TournamentNameLabel": "토너먼트 이름",
    "TournamentNamePlaceHolderLabel": "토너먼트 이름(최대 255자)",
    "TournamentRankLabel": "토너먼트 순위",
    "TournamentReportsPageTitle": "토너먼트 보고서",
    "UnauthorizedText": "지금은 챔피언십 배지 프로그램에 참여할 자격이 없습니다.",
    "UploadFileButton": "파일 업로드",
    "UserAddedMessage": "사용자를 추가했습니다!",
    "UserExistingMessage": "사용자가 이미 챔피언입니다!",
    "UserLabel": "사용자",
    "UserNominatedMessage": "사용자를 추천했습니다!",
    "ViewActivitiesLabel": "활동 보기",
    "ViewDashBoardLabel": "대시보드 보기",
    "VisitLabel": "자세히 알아보려면 챔피언 관리 플랫폼 페이지를 방문하세요.",
    "WelcomeLabel": "시작",
    "YesButton": "예",
  }
});