define([], function () {
    return {
      "PropertyPaneDescription": "설명",
      "BasicGroupName": "그룹 이름",
      "DescriptionFieldLabel": "설명 필드",
      "CMPBreadcrumbLabel": "챔피언십 관리 플랫폼",
      "SaveButton": "저장",
      "BackButton": "뒤로",
      "GetStartedLabel": "시작",
      "AdminToolsLabel": "관리 도구",
      "ChampionLeaderBoardLabel": "챔피언 순위표",
      "AddMemberLabel": "구성원 추가",
      "NominateMemberLabel": "구성원 추천",
      "DigitalBadgeLabel": "디지털 배지",
      "TOTLabel": "Teams 토너먼트",
      "ChampionListLabel": "챔피언 목록",
      "EventsListLabel": "이벤트 목록",
      "EventsTrackListLabel": "이벤트 트랙킹 목록",
      "ManageApprovalsLabel": "승인 관리",
      "ManageDigitalBadgesLabel": "디지털 배지 관리",
      "EnableTOTLabel": "Teams 토너먼트 사용",
      "AddMembersToolTip": "구성원 추가 작업에서 공동 작업할 사용자 추가 시작...",
      "DigitalMembersToolTip": "디지털 배지를 가져와 프로필 이미지에 적용",
      "ChampionsListToolTip": "챔피언 목록에 액세스하는 중",
      "EventsListToolTip": "이벤트 목록에 액세스하는 중",
      "EventTrackListToolTip": "이벤트 트랙킹 목록에 액세스하는 중",
      "ManageApprovalToolTip": "챔피언 승인",
      "EnableTOTToolTip": "Teams 토너먼트 사용",
      "ManageDigitalBadgesToolTip": "디지털 배지 관리",
      "WelcomeLabel": "시작",
      "ManageAppLogoLabel": "앱 로고 관리",
      "ManageAppLogoToolTip": "Manage App Logo",
      "AppHeaderTitleLabel": "챔피언십 관리 플랫폼",
      "AppLogoToolTip": "홈",
      "MoreInfoToolTip": "자세한 정보",
      "SupportToolTip": "지원",
      "FeedbackToolTip": "피드백",
      "AboutHeaderLabel": "CMP(챔피언십 관리 플랫폼) 정보:",
      "AboutContentLabel": "챔피언십 관리 플랫폼은 조직 챔피언/채택 전문가를 염두에 두고 제작되었습니다. Microsoft 365 챔피언 커뮤니티의 의견을 반영하여 개발된 이 앱은 자체 커뮤니티를 만들고 유지하는 데 도움이 되는 플랫폼을 제공합니다. 자체 커뮤니티 내에서 더욱더 많은 목표를 달성할 수 있도록 실행을 통해 영감을 불러일으키세요!",
      "AdditionalResourcesHeaderLabel": "추가 리소스:",
      "AdditionalResourcesContentLabel": "Microsoft Teams 고객 지지 그룹은 주로 이와 같은 솔루션을 제공하여 목표를 달성하기 위한 동기를 부여하고 도움을 주는 일을 합니다. 이러한 기타 리소스를 통해 팔로우하고 가입하여 당사와 당사 커뮤니티에게서 더 많은 도움을 받으세요.",
      "M365ChampionCommunityLinkLabel": "Microsoft 365 챔피언 커뮤니티",
      "DrivingAdoptionLinkLabel": "Microsoft Technical Community에서 채택 추진",
      "CurrentVersionLabel": "현재 버전:",
      "LatestVersionLabel": "최신 버전:",
      "CMPGitHubLinkLabel": "GitHub",
      "VisitLabel": "자세히 알아보려면 챔피언 관리 플랫폼 페이지를 방문하세요.",
      "OverviewLabel": "개요 및 정보",
      "MSAdoptionHubLinkLabel": "Microsoft 채택 허브",
      "DocumentationLabel": "솔루션 기술 설명서 및 아키텍처 개요",
      "AddMemberPageTitle": "구성원 추가",
      "NominateMemberPageTitle": "구성원 추천",
      "PeoplePickerPlaceholder": "구성원을 추가하려면 구성원 이름을 입력하세요.",
      "RegionPlaceholder": "지역 선택",
      "CountryPlaceholder": "국가 선택",
      "GroupPlaceholder": "그룹 선택",
      "FocusAreaPlaceholder": "포커스 영역 선택",
      "UserExistingMessage": "사용자가 이미 챔피언입니다!",
      "ChampionsListPageTitle": "챔피언 목록",
      "UserNominatedMessage": "사용자를 추천했습니다!",
      "UserAddedMessage": "사용자를 추가했습니다!",
      "PeopleNameGridHeader": "구성원 이름",
      "Select": "선택",
      "SelectAll": "모두 선택",
      "RegionGridHeader": "지역",
      "CountryGridHeader": "국가",
      "GroupGridHeader": "그룹",
      "FocusAreaGridHeader": "포커스 영역",
      "StatusGridHeader": "상태",
      "ManageApprovalsPageTitle": "승인 관리",
      "ActionGridHeader": "액션",
      "ApproveButton": "승인",
      "RejectButton": "거부",
      "NoChampionsMessage": "현재 보류 중인 요청이 없습니다.",
      "ChampionApprovedMessage": "챔피언 요청이 승인되었습니다.",
      "ChampionRejectedMessage": "챔피언 요청이 거부되었습니다.",
      "ProcessingSpinnerLabel": "처리 중...",
      "DigitalBadgePageTitle": "디지털 배지",
      "LoadingSpinnerLabel": "로드 중...",
      "DigitalBadgeAppBannerAltText": "토론에 참여하는 Microsoft 팀 구성원",
      "PreAcceptPageTitle": "디지털 배지를 클레임하세요!",
      "PreAcceptDisclaimer": "<span style='font-weight:bold;'>디지털 배지 유틸리티에 오신 것을 환영합니다.</span> <br/><br/> <span>챔피언 프로그램 멤버십의 일환으로 디지털 배지를 획득하셨습니다! 이 유틸리티를 사용하면 기존 프로필 사진 위에 디지털 배지를 오버레이하여 '<em>클레임</em>'할 수 있습니다. <br/><br/> 이렇게 하면 모든 Microsoft 365(Exchange, Teams, SharePoint 등)에서 프로필 사진이 업데이트됩니다.</span>",
      "PreAcceptDisclaimer2": "원하는 경우 다음 단계에서 디지털 배지 오버레이 없이 <span style='font-weight:bold;'>기존 프로필 사진 복사본을 ‘저장’할 수 있습니다.</span> ‘수락’을 클릭하여 계속하세요(팝업이 열리고 로그인하라는 메시지가 표시될 수 있습니다).",
      "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>디지털 배지 유틸리티에 오신 것을 환영합니다</span>. Champions Program 멤버십의 일부로 디지털 배지를 획득할 수 있습니다! 이 유틸리티를 사용하면 기존 프로필 사진 위에 디지털 배지를 오버레이하여 '<em>클레임</em>'할 수 있습니다. 이렇게 하면 모든 Microsoft 365(Exchange, Teams, SharePoint 등)에서 프로필 사진이 업데이트됩니다.",
      "HowtoGetDigitalBadgeText": "챔피언 배지를 받는 방법",
      "MultipleBadgeMessage": "아래 목록에서 배지를 선택하세요. 선택한 배지가 프로필 사진에 적용됩니다.",
      "NoBadgeMessage": "선택할 배지를 찾을 수 없습니다. 앱 관리자에게 문의하세요.",
      "DigitalBadgeSubPageTitle": "디지털 배지의 모양은 다음과 같습니다!",
      "ProfileImageAlt": "O365, Teams 등에서 사용되는 내 프로필 이미지",
      "BadgeImageAlt": "가운데에 C라는 문자가 있는 메달 모양 상은 챔피언십 프로그램에 참여 중이라는 것을 나타냅니다.",
      "NoProfileImageAlt": "현재 계정에 적용된 프로필 이미지가 없음을 나타내는 사람의 실루엣",
      "ApplyButtonText": "이미지 적용",
      "ApplyButtonAriaDescription": "이 버튼을 클릭하면 챔피언십 프로그램 웹 파트에 사용자 대신 프로필 사진을 업데이트할 수 있는 권한이 부여됩니다.",
      "ApplyButton": "적용",
      "DownloadButtonText": "다운로드",
      "DownloadButtonAriaDescription": "클릭해서 현재 프로필 이미지를 다운로드",
      "DownloadingButtonText": "다운로드 중...",
      "DownloadedButtonText": "다운로드됨",
      "DownloadedButtonSecondaryText": "다운로드한 프로필 이미지는 장치의 다운로드 폴더에서 찾을 수 있습니다.",
      "DownloadButtonSecondaryText": "현재 프로필 이미지 다운로드",
      "PreApplyDisclaimer": "디지털 배지를 포함한 새 프로필 사진의 미리 보기입니다. 디지털 배지를 적용하기 전에 기존 프로필 사진을 다운로드하려면 '<strong> 현재 프로필 이미지 다운로드</strong>' 링크를 클릭하세요.<br />",
      "PreApplyDisclaimer1": "<br />'이미지 적용'을 클릭하면 Microsoft 365 프로필 사진이 이 새 이미지로 업데이트됩니다. <strong>이렇게 하면 모든 Microsoft 365 프로필 사진이 업데이트되며 이 페이지를 통해 되돌릴 수 없습니다</strong>. <br/><br/>사진을 다시 변경하려면 <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' aria-label='Open the Outlook web application in a new browser tab or window'>Outlook 웹 응용 프로그램</a>을 사용할 수 있습니다.",
      "NoProfileImageDescription": "사진을 프로필과 이미 연결했으나 이 메시지가 계속 표시되는 경우 사진을 아직 사용할 수 없을 수 있습니다. 나중에 다시 시도하거나, 24시간 후에도 계속 사진이 표시되지 않으면 <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>지원팀</a>에 문의하세요.",
      "AcceptButtonText": "수락",
      "AcceptButtonAriaDescription": "이 버튼을 클릭하면 챔피언십 프로그램 웹 파트에 사용자 대신 프로필 사진을 업데이트할 수 있는 권한이 부여됩니다.",
      "UnauthorizedText": "지금은 챔피언십 배지 프로그램에 참여할 자격이 없습니다.",
      "ApplySpinnerLabel": "계정에 새 프로필 이미지를 적용하는 중...",
      "DigitalBadgeSuccessMessage": "<strong>축하드려요!</strong> 디지털 배지를 클레임하고 프로필 사진을 업데이트했습니다. Teams를 비롯한 모든 Microsoft 365 애플리케이션에서 반영된 업데이트를 보려면 최대 24시간을 기다려주세요.",
      "CMPSideBarPointsLabel": "점수",
      "CMPSideBarGlobalRankLabel": "글로벌 순위",
      "CMPSideBarChampionsLabel": "챔피언",
      "FirstNameLabel": "이름",
      "LastNameLabel": "성",
      "EmailIDLabel": "전자 메일 ID",
      "BecomeChampionLabel": "챔피언 되기",
      "ChampionSubmissionPendingLabel": "챔피언 제출 보류 중",
      "ChampionRequestSubmitSuccessMessage": "챔피언 요청 제출 성공",
      "PivotHeaderGlobal": "글로벌",
      "PivotHeaderNearMe": "내 근처",
      "PivotHeaderBySpeciality": "전문 분야별",
      "NearMePlaceHolder": "내 근처에 있는 항목 선택",
      "BySpecialityPlaceHolder": "전문 분야별 선택",
      "TopChampionsLabel": "상위 챔피언",
      "RecordsNotFound": "레코드를 찾지 못함",
      "EventTypeLabel": "이벤트 유형",
      "CountLabel": "수",
      "MyRankLabel": "내 순위",
      "ViewDashBoardLabel": "대시보드 보기",
      "DateofEventGridLabel": "이벤트 날짜",
      "EventTypeGridLabel": "유형",
      "RecordEventLabel": "이벤트 레코드",
      "MonthAndDateLabel": "월 및 일",
      "EventTypeGridLabelPlaceHolder": "이벤트 유형 선택",
      "EventTypeValidationMessage": "이벤트 유형을 선택하세요!",
      "CountValidationMessage": "수는 1에서 5 사이여야 합니다.",
      "EventsSubmitMessage": "이벤트 추가가 완료되면 [제출] 버튼을 클릭하여 저장하세요.",
      "SubmitButton": "제출",
      "SearchLabel": "검색",
      "ActivitiesLabel": "활동",
      "RegionLabel": "지역",
      "FocusAreaLabel": "포커스 영역",
      "ShowMoreLabel": "더 보기",
      "ViewActivitiesLabel": "활동 보기",
      "ChatIconLabel": "채팅",
      "RequestToCallLabel": "통화 요청",
      "EmailIconLabel": "전자 메일 보내기",
      "MeetupSubject": "1:1(챔피언 요청)",
      "MeetupBody": "챔피언 지역에 대해 토론하고 자세히 알아볼 시간을 마련해 주세요!",
      "NoActivitiesinGridLabel": "활동을 찾을 수 없습니다!",
      "CreateTournamentPageTitle": "토너먼트 만들기",
      "CreateTournamentSuccessLabel": "토너먼트를 만들었습니다.",
      "TournamentNameLabel": "토너먼트 이름",
      "TournamentNamePlaceHolderLabel": "토너먼트 이름(최대 255자)",
      "TournamentNameErrorLabel": "토너먼트 이름이 필요합니다.",
      "TournamentDescriptionLabel": "토너먼트 설명",
      "TournamentDescPlaceHolderLabel": "토너먼트 설명(최대 500자)",
      "SelectTeamsActionsLabel": "Teams 액션 선택:",
      "TeamsActionInfoToolTip": "아래의 사용 가능한 팀 작업에서 새 토너먼트에 포함할 작업을 선택하세요. 선택할 새 토너먼트 작업을 추가하려면 관리 도구에서 토너먼트 작업 관리를 방문하세요.",
      "ActionErrorLabel": "토너먼트를 만들려면 하나 이상의 작업을 선택하세요.",
      "CreateTournamentButton": "토너먼트 만들기",
      "DuplicateTournamentNameError": "토너먼트 이름이 이미 존재합니다. 토너먼트의 다른 이름을 입력하세요.",
      "CreateTournamentsButton": "토너먼트 만들기",
      "SingleTournamentLabel": "단일 토너먼트",
      "MultipleTournamentLabel": "여러 토너먼트",
      "MultiTournamentStep": "단계",
      "MultiTournamentStep1LinkLabel": "템플릿 다운로드",
      "MultiTournamentStep1Text": "샘플 파일 형식",
      "MultiTournamentStep2": "지침에 따라 토너먼트 세부 정보를 파일에 추가",
      "MultiTournamentStep3": "파일 업로드",
      "UploadFileButton": "파일 업로드",
      "RemoveFileLabel": "파일 제거",
      "ImportSpinnerMessage": "토너먼트를 만드는 중.....",
      "ErrorMsgTournamentList": "토너먼트 목록에 항목을 만드는 동안 오류가 발생했습니다. 데이터를 수정하고 다시 시도하세요.",
      "ErrorMsgActionsList": "작업 목록에서 항목을 만드는 동안 오류가 발생했습니다. 데이터를 수정하고 다시 시도하세요.",
      "ErrorMsgTournamentActionsList": "토너먼트 작업 목록에 항목을 만드는 동안 오류가 발생했습니다. 데이터를 수정하고 다시 시도하세요.",
      "LogMsgTournamentExists": "토너먼트 이후 건너뜀",
      "LogMsgTournamentExists1": "이미 있습니다.",
      "LogMsgDone": "토너먼트",
      "LogMsgDone1": "만들어졌습니다.",
      "LogMsgInvalidTournamentName": "유효한 토너먼트 이름이 없으므로 건너뛰었습니다.",
      "LogMsgInvalidTemplate": "올바른 템플릿이 아니므로 건너뛰었습니다.",
      "LogMsgMultipleTournaments": "토너먼트 이름이 두 개 이상 있으므로 건너뛰었습니다.",
      "LogMsgBlankSheet": "비어 있으므로 건너뛰었습니다.",
      "LogProgress": "진행률은 다음과 같습니다.",
      "ImportRule1": "템플릿의 열 머리글 수정 안 함",
      "ImportRule2": "템플릿의 열을 삭제하지 않음",
      "ImportRule3": "템플릿에 언급된 모든 필수(*) 열에 데이터 입력",
      "ImportRule4": "각 열이 템플릿에 언급된 문자 제한 및 형식을 따릅니다.",
      "ImportRule5": "제공된 샘플 데이터에 따라 각 시트에 1개의 토너먼트에 대한 데이터만 입력하세요.",
      "ImportRule6": "한 번에 10개의 토너먼트만 만들 수 있습니다.",
      "ImportRule7": "토너먼트 이름이 고유한지 확인하세요.",
      "TOTBreadcrumbLabel": "Teams 토너먼트",
      "EnableTOTSuccessMessage": "Teams 토너먼트를 사용하도록 설정했습니다. 계속하려면 앱을 새로 고치세요.",
      "EnableTOTSpinnerMessage": "이 프로세스를 완료하는 데 몇 분 정도 걸립니다. 완료된 성공적으로 완료된 메시지가 표시될 때까지 다른 곳으로 이동하지 마세요.",
      "TOTLeaderBoardPageTitle": "순위표",
      "TOTMyDashboardPageTitle": "내 대시보드",
      "ManageTournamentActionsToolTip": "토너먼트 액션 목록에 액세스하는 중",
      "ManageTournamentActionsLabel": "토너먼트 액션 관리",
      "ManageTournamentsLabel": "토너먼트 관리",
      "ManageAdminsToolTip": "관리 목록에 액세스하는 중",
      "ManageAdminsLabel": "관리자 관리",
      "QuickLinksLabel": "빠른 링크",
      "SpinnerListCreationMessage": "Teams 토너먼트 설정 중...",
      "ManageTournamentsPageTitle": "토너먼트 관리",
      "ManageToTLabel1": "한 번에 여러 토너먼트를 시작할 수 있습니다. 현재 진행 중인 토너먼트, 토너먼트 완료 기능 및 새 토너먼트 시작 기능은 아래를 참조하세요.",
      "ManageToTLabel2": "토너먼트가 시작되고 완료되면 다시 시작할 수 없습니다. 그러나 유사한 토너먼트를 완료하려는 경우 동일한 작업을 사용하여 새 토너먼트를 생성할 수 있습니다!",
      "EndTournamentDialogMessage": "토너먼트를 완료하시겠습니까?",
      "StartTournamentDialogMessage": "새 토너먼트를 시작하시겠습니까?",
      "ConfirmLabel": "확인",
      "YesButton": "예",
      "NoButton": "아니요",
      "ActiveTournamentLabel": "활성 토너먼트",
      "EndTournamentButton": "토너먼트 완료",
      "StartTournamentHeaderLabel": "토너먼트 시작",
      "NoTournamentMessage": "토너먼트를 찾을 수 없습니다. 나중에 다시 확인하세요.",
      "SelectTournamentMessage": "시작할 토너먼트를 하나 이상 선택하세요.",
      "SelectEndTournamentMessage": "완료할 토너먼트를 선택하세요.",
      "StartTournamentButton": "토너먼트 시작",
      "EndTournamentSuccessMessage": "토너먼트를 완료했습니다.",
      "EnableTournamentSuccessMessage": "토너먼트가 시작되었습니다.",
      "CompleteTournamentSpinnerMessage": "토너먼트 완료 중...",
      "EnableTournamentSpinnerMessage": "토너먼트를 사용하도록 설정하는 중...",
      "SearchActiveTournaments": "활성 토너먼트 검색",
      "SearchPendingTournaments": "시작할 토너먼트 검색",
      "SelectAllLabel": "모두 선택",
      "NoSearchResults": "검색과 일치하는 결과가 없습니다.",
      "NoActiveParticipantsMessage": "현재 활성 참가자가 없습니다. 가장 먼저 내 대시보드에 참여하고 활동을 기록해 보세요!",
      "NoActiveTournamentMessage": "현재 활성 토너먼트가 없습니다. 나중에 다시 확인하세요.",
      "TournamentLabel": "토너먼트",
      "DescriptionLabel": "설명",
      "NoActiveParticipantsErrorMessage": "현재 활성 참가자가 없습니다. 가장 먼저 참여하여 활동을 기록해 보세요. ",
      "PendingActionsLabel": "보류 중인 액션",
      "PendingActionsSuccessMessage": "이 토너먼트에는 더 이상 보류 중인 작업이 없습니다.",
      "SelectActionsErrorMessage": "계속하려면 액션을 하나 이상 선택하세요.",
      "FormSavingMessage": "세부 정보를 저장하는 중...",
      "CompletedActionsLabel": "완료된 액션",
      "RankLabel": "순위",
      "UserLabel": "사용자",
      "MyDashboardInfoIconMessage": "이 액션에 대해 자세히 알아보기",
      "SelectTournamentPlaceHolder": "토너먼트 선택",
      "MyTournamentsLabel": "내 토너먼트",
      "OrLabel": "또는",
      "MyTournamentsTooltip": "이미 참가한 활성 토너먼트",
      "PointsLabel": "점수",
      "TournamentRankLabel": "토너먼트 순위",
      "ParticipantsLabel": "참가자",
      "TournamentReportsPageTitle": "토너먼트 보고서",
      "TotalActivitiesLabel": "활동 합계",
      "TotalPointsLabel": "점수 합계",
      "TotalParticipantsLabel": "참가자 합계",
      "TotalPercentageCompletionLabel": "총 완료율(%)",
      "Top5ParticipantswithPointsLabel": "점수 포함 상위 5명 참가자",
      "Top5TournamentswithParticipantsLabel": "참가자 포함 상위 5개 토너먼트",
      "ParticipantsStatusLabel": "참가자 상태",
      "ParticipantsDetailsLabel": "참가자 세부 정보",
      "NameLabel": "이름",
      "PercentageTournamentCompletedLabel": "% 토너먼트 완료",
      "ActivitiesCompletedLabel": "작업 완료됨",
      "NoRecordsinGridLabel": "발견된 레코드가 없습니다!",
      "SearchPlaceholder": "참가자 이름으로 검색",
      "NoCompletedTournamentsMessage": "현재 완료된 토너먼트가 없습니다. 나중에 다시 확인해 주세요.",
      "ReportsDropdownInfoIconText": "보고서는 완료된 토너먼트에 대해서만 생성할 수 있습니다.",
      "RefreshIconInfoText": "새로 고침을 클릭하여 최신 데이터 보기"
    }

});