define([], function () {
  return {
    "AboutContentLabel": "foi criado com Especialistas organizacionais/Especialistas em Adoção em mente. Ouvindo da comunidade Microsoft 365 Champion, este aplicativo foi desenvolvido para fornecer uma plataforma para ajudar a criar e sustentar suas próprias comunidades. Comece com inspiração por meio da execução para ajudá-lo a alcançar mais em suas próprias comunidades!",
    "AboutHeaderLabel": "Sobre a",
    "AcceptButtonAriaDescription": "Ao clicar neste botão, você dará permissão à Web Part do Programa de Especialistas para atualizar sua foto de perfil em seu nome.",
    "AcceptButtonText": "Aceitar",
    "ActionErrorLabel": "Selecione pelo menos uma ação para criar um torneio.",
    "ActionGridHeader": "Ação",
    "ActiveTournamentLabel": "Torneios Ativos",
    "ActivitiesCompletedLabel": "Atividades Concluídas",
    "ActivitiesLabel": "Atividades",
    "AddEventLabel": "Adicionar Evento",
    "AdditionalResourcesContentLabel": "O Grupo de Atendimento ao Cliente do Microsoft Teams está focado em fornecer soluções como estas para inspirar e ajudar você a alcançar suas metas. Siga e ingresse por meio desses outros recursos para saber mais sobre nós e a comunidade:",
    "AdditionalResourcesHeaderLabel": "Recursos Adicionais:",
    "AddMemberLabel": "Adicionar Membro",
    "AddMemberPageTitle": "Adicionar Membro",
    "AddMembersToolTip": "Adicionar Membros Comece a adicionar as pessoas com as quais você colaborará em seu...",
    "AdminTasksLabel": "Tarefas Administrativas",
    "AdminToolsLabel": "Ferramentas do Administrador",
    "AllTime": "Toda Hora",
    "AppLogoToolTip": "Home",
    "ApplyButton": "Aplicar",
    "ApplyButtonAriaDescription": "Ao clicar neste botão, você dará permissão à Web Part do Programa de Especialistas para atualizar sua foto de perfil em seu nome.",
    "ApplyButtonText": "Aplicar imagem",
    "ApplySpinnerLabel": "Aplicando nova imagem de perfil à sua conta...",
    "ApproveButton": "Aprovar",
    "ApproveChampionSearchboxPlaceholder": "Pesquisar por Nome do Membro/Email",
    "AppTitleErrorLabel": "O Título do Aplicativo é obrigatório.",
    "AppTitleInfoIconText": "O título do aplicativo aparecerá na seção de cabeçalho e nas seções de trilha do aplicativo",
    "AppTitleLabel": "Título do Aplicativo",
    "AppTitlePlaceholderText": "Máximo de 30 Caracteres",
    "BackButton": "Voltar",
    "BadgeImageAlt": "Prêmio em forma de medalha com a letra C no meio que indica que eu sou parte do Programa de Especialistas",
    "BadgePointsTooltip": "Pontos necessários para desbloquear:",
    "BasicGroupName": "Nome do grupo",
    "BecomeChampionLabel": "Torne-se um Especialista",
    "BySpecialityPlaceHolder": "Selecionar por Especialidade",
    "ChampionActivitiesLabel": "Atividades de Especialista",
    "ChampionApprovedMessage": "Solicitações de Especialistas Aprovadas.",
    "ChampionLabel": "Especialista",
    "ChampionLeaderBoardLabel": "Classificação de especialistas",
    "ChampionListLabel": "Lista de Especialistas",
    "championRecordsFoundLabel": "Registros de campeões encontrados",
    "ChampionRejectedMessage": "Solicitações de Especialistas Rejeitadas.",
    "ChampionReportLabel": "Relatório dos Campeões",
    "ChampionReportToolTip": "Relatório dos Campeões",
    "ChampionRequestSubmitSuccessMessage": "Envio de solicitação de especialistas bem-sucedido",
    "ChampionsListPageTitle": "Lista de Especialistas",
    "ChampionsListToolTip": "Acessando a Lista de Especialistas",
    "ChampionsSelectedLabel": "Especialista(s) selecionado(s).",
    "ChampionSubmissionPendingLabel": "O envio dos especialistas está pendente",
    "ChatIconLabel": "Chat",
    "ClearButton": "Limpar",
    "CMPGitHubLinkLabel": "GitHub",
    "CMPSideBarChampionsLabel": "Especialistas",
    "CMPSideBarGlobalRankLabel": "Classificação Global",
    "CMPSideBarPointsLabel": "Pontos",
    "CompletedActionsLabel": "Ações Concluídas",
    "CompleteTournamentSpinnerMessage": "Completando o Torneio...",
    "ConfigSettingsSaved": "Configurações salvas.",
    "ConfirmLabel": "Confirmar",
    "CountLabel": "Contagem",
    "CountryGridHeader": "País/região",
    "CountValidationMessage": "A contagem deve estar entre 1 e 5",
    "CreateTournamentButton": "Criar Torneio",
    "CreateTournamentPageTitle": "Criar Torneio",
    "CreateTournamentsButton": "Crie Torneios",
    "CreateTournamentSuccessLabel": "Torneio criado com êxito.",
    "CurrentVersionLabel": "Versão atual:",
    "DashboardLabel": "Painel",
    "DateLabel": "Data",
    "DateofEventGridLabel": "Data do Evento",
    "DescriptionFieldLabel": "Campo de Descrição",
    "DescriptionLabel": "Descrição",
    "DigitalBadgeAppBannerAltText": "Membros da equipe da Microsoft participando de uma discussão",
    "DigitalBadgeLabel": "Selo Digital",
    "DigitalBadgePageTitle": "Selo Digital",
    "digitalBadgeProfileAriaLabel": "Abrir o aplicativo Web do Outlook em uma nova guia ou janela do navegador",
    "DigitalBadgeSubPageTitle": "Veja como seu selo digital ficará!",
    "DigitalBadgeSuccessMessage": "<strong>Parabéns!</strong> Você reivindicou com êxito seu selo digital e sua foto de perfil foi atualizada. Aguarde até 24 horas para ver a atualização refletida em todos os aplicativos do Microsoft 365 (incluindo o Teams).",
    "DigitalMembersToolTip": "Obtenha seu selo digital e aplique-o à sua imagem de perfil",
    "DocumentationLabel": "Documentação técnica da solução e visão geral da arquitetura sobre",
    "DownloadButtonAriaDescription": "Clique para baixar sua imagem de perfil atual",
    "DownloadButtonSecondaryText": "Baixar sua imagem de perfil atual",
    "DownloadButtonText": "Baixar",
    "DownloadedButtonSecondaryText": "A imagem de perfil baixada pode ser encontrada na pasta Downloads do dispositivo.",
    "DownloadedButtonText": "Baixado",
    "DownloadingButtonText": "Baixando...",
    "DrivingAdoptionLinkLabel": "Impulsionando a adoção na Microsoft Technical Community",
    "DuplicateTournamentNameError": "O nome do torneio já existe. Insira outro nome para o torneio.",
    "EmailIconLabel": "Enviar um Email",
    "EmailIDLabel": "ID de email",
    "EmailLabel": "Email",
    "EnableTOTLabel": "Habilitar o Torneio de equipes",
    "EnableTOTSpinnerMessage": "Este processo levará alguns minutos para ser concluído. Não saia até ver a mensagem concluída com êxito.",
    "EnableTOTSuccessMessage": "O Torneio de equipes foi habilitado com êxito. Atualize o aplicativo para continuar.",
    "EnableTOTToolTip": "Habilitar o Torneio de equipes",
    "EnableTournamentSpinnerMessage": "Habilitando o(s) Torneio(s)...",
    "EnableTournamentSuccessMessage": "Torneio(s) iniciado(s) com êxito.",
    "EndTournamentButton": "Torneio Concluído",
    "EndTournamentDialogMessage": "Tem certeza de que deseja concluir o torneio?",
    "EndTournamentSuccessMessage": "Torneio concluído com êxito.",
    "ErrorMsgActionsList": "Erro ao criar um item na lista Ações. Corrija os dados e tente novamente.",
    "ErrorMsgTournamentActionsList": "Ocorreu um erro ao criar um item na lista Ações de Torneio. Corrija os dados e tente novamente.",
    "ErrorMsgTournamentList": "Erro ao criar um item na lista Torneios. Corrija os dados e tente novamente.",
    "EventApprovalsEnableLabel": "Habilitar Aprovações de Evento de Especialista",
    "EventApprovedMessage": "Evento(s) de Especialista(s) Aprovado(s).",
    "EventChartLabel": "10 principais Eventos com Tipos de Evento",
    "EventLabel": "Evento",
    "EventRejectedMessage": "Evento(s) de Especialista(s) Rejeitado(s).",
    "EventsApprovalInfoIconTooltipContent": "Habilitar esta opção exigirá que os envios de eventos por campeão sejam aprovados por um administrador. Os pontos dos eventos serão concedidos somente após a aprovação.",
    "EventsListLabel": "Lista de Eventos",
    "EventsListToolTip": "Acessando a Lista de eventos",
    "EventsSelectedLabel": "Evento(s) Selecionado(s).",
    "EventsSubmissionSuccessMessage": "Evento(s) registrado(s) com êxito.",
    "EventsSubmitMessage": "Quando terminar de adicionar eventos, clique no botão Enviar para salvar.",
    "EventSubmissionPendingMessage": "Evento(s) enviado(s) para aprovação. Os pontos serão concedidos assim que o(s) evento(s) for(em) aprovado(s).",
    "EventTypeGridLabel": "Tipo",
    "EventTypeGridLabelPlaceHolder": "Selecionar o Tipo de Evento",
    "EventTypeLabel": "Tipo de Evento",
    "EventTypesHeading": "Tipo de Evento",
    "EventTypeValidationMessage": "Selecione o tipo de evento!",
    "FeedbackToolTip": "Comentários",
    "FilterbyDateLabel": "Filtrar por Data",
    "FirstNameLabel": "Primeiro Nome",
    "FocusAreaGridHeader": "Área de Foco",
    "FocusAreaLabel": "Área de Foco",
    "FocusAreaPlaceholder": "Selecionar a Área de Foco",
    "FormSavingMessage": "Salvando seus detalhes....",
    "FromLabel": "De",
    "GetStartedLabel": "Introdução",
    "GroupGridHeader": "Grupo",
    "HowtoGetDigitalBadgeText": "Como obter uma Selo de Especialista",
    "ImportRule1": "Não modificar os cabeçalhos de coluna no modelo",
    "ImportRule2": "Não excluir as colunas no modelo",
    "ImportRule3": "Insira os dados em todas as colunas obrigatórias (*) mencionadas no modelo",
    "ImportRule4": "Siga o limite de caracteres e o tipo mencionado no modelo para cada coluna",
    "ImportRule5": "Insira dados para apenas 1 torneio em cada planilha de acordo com os dados de exemplo fornecidos",
    "ImportRule6": "Somente 10 Torneios podem ser criados por vez",
    "ImportRule7": "Certifique-se de que o Nome do Torneio é único",
    "ImportSpinnerMessage": "Criando Torneios.......",
    "Last1Year": "Último 1 ano",
    "Last3Months": "Últimos Três Meses",
    "Last6Months": "Últimos Seis Meses",
    "LastMonth": "Mês Passado",
    "LastNameLabel": "Sobrenome",
    "LatestVersionLabel": "Versão Mais Recente:",
    "LoadingDigitalBadgeLabel": "Carregamento de quadro de selo digital",
    "LoadingSpinnerLabel": "Carregando...",
    "LogMsgBlankSheet": "Ignorado, pois está em branco.",
    "LogMsgDone": "Torneio",
    "LogMsgDone1": "criado.",
    "LogMsgInvalidTemplate": "Ignorado, pois não é um modelo válido.",
    "LogMsgInvalidTournamentName": "Ignorado, pois ele não tem um Nome de Torneio válido.",
    "LogMsgMultipleTournaments": "Ignorado, pois ele tem mais de um Nome de Torneio.",
    "LogMsgTournamentExists": "Ignorado, pois o torneio",
    "LogMsgTournamentExists1": "já existe.",
    "LogProgress": " Abaixo está o progresso:",
    "M365ChampionCommunityLinkLabel": "Comunidade de especialistas do Microsoft 365",
    "ManageAdminsLabel": "Gerenciar Administradores",
    "ManageAdminsToolTip": "Acessando a Lista de Administradores",
    "ManageAppLogoLabel": "Gerenciar o Logotipo do Aplicativo",
    "ManageAppLogoToolTip": "Gerenciar o Logotipo do Aplicativo",
    "ManageConfigSettingsLabel": "Gerenciar Configurações",
    "ManageDigitalBadgesLabel": "Gerenciar os Selos Digitais",
    "ManageDigitalBadgesToolTip": "Gerenciar os Selos Digitais",
    "ManageToTLabel1": "Vários Torneios podem ser iniciados por vez. Veja abaixo os Torneios atuais ativos, a capacidade de concluir o torneio, bem como a capacidade de iniciar um novo torneio.",
    "ManageToTLabel2": "Depois que um torneio for iniciado e concluído, ele não estará disponível para iniciar novamente; no entanto, você pode criar um novo torneio usando as mesmas ações se quiser concluir um torneio semelhante!",
    "ManageTournamentActionsLabel": "Gerenciar as Ações do Torneio",
    "ManageTournamentActionsToolTip": "Acessando a Lista de Ações do Torneio",
    "ManageTournamentsLabel": "Gerenciar Torneios",
    "ManageTournamentsPageTitle": "Gerenciar Torneios",
    "MeetupBody": "Reserve um tempo para discutir sua área especialista e aprender mais!",
    "MeetupSubject": "Reunião individual (Solicitação de Especialista)",
    "MonthAndDateLabel": "Mês e data",
    "MoreInfoToolTip": "Mais Informações",
    "MSAdoptionHubLinkLabel": "Centro de adoção da Microsoft",
    "MultipleBadgeMessage": "Selecione um selo na lista abaixo. O selo selecionado será aplicado na imagem do seu perfil.",
    "MultipleTournamentLabel": "Vários Torneios",
    "MultiTournamentStep": "Etapa",
    "MultiTournamentStep1LinkLabel": "Baixar Modelo",
    "MultiTournamentStep1Text": " de formato de arquivo de amostra",
    "MultiTournamentStep2": "Adicione detalhes do torneio ao arquivo seguindo as diretrizes",
    "MultiTournamentStep3": "Fazer upload do arquivo",
    "MyDashboardInfoIconMessage": "Saiba mais sobre essa ação",
    "MyRankLabel": "Minha Classificação",
    "MyTournamentsLabel": "Meus Torneios",
    "MyTournamentsTooltip": "Torneios ativos dos quais você já participou",
    "NameLabel": "Nome",
    "NearMePlaceHolder": "Selecionar Perto de Mim",
    "NoActiveParticipantsErrorMessage": "Não há participantes ativos no momento. Seja o primeiro a participar e registrar uma atividade de ",
    "NoActiveParticipantsMessage": "Não há participantes ativos no momento. Seja o primeiro a participar e registrar uma atividade em Meu Painel!",
    "NoActiveTournamentMessage": "Não há nenhum torneio ativo no momento. Verifique novamente mais tarde.",
    "NoActivitiesinGridLabel": "Nenhuma Atividade Encontrada!",
    "NoBadgeMessage": "Nenhum selo encontrado para você selecionar. Verifique com o Administrador de Aplicativos.",
    "NoButton": "Não",
    "NoChampionsMessage": "Nenhuma solicitação pendente no momento",
    "NoCompletedTournamentsMessage": "Não há nenhum torneio concluído no momento. Verifique novamente mais tarde.",
    "NoEventsFoundMessage": "Nenhum Evento encontrado!",
    "NoEventsMessage": "Não há eventos concluídos no momento. Verifique novamente mais tarde.",
    "NominateMemberLabel": "Nomear Membro",
    "NominateMemberPageTitle": "Nomear Membro",
    "NoPendingEventsLabel": "Nenhum evento pendente no momento.",
    "NoProfileImageAlt": "Silhueta de uma pessoa, indicando que nenhuma imagem de perfil está atualmente aplicada à sua conta",
    "NoProfileImageDescription": "Se você já associou uma foto ao seu perfil e ainda estiver vendo esta mensagem, sua foto pode ainda não estar disponível. Tente novamente mais tarde ou contate a <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>assistência técnica</a> se ela ainda não apareceu após 24 horas.",
    "NoRecordsIcon": "Ícone Sem Registros",
    "NoRecordsinGridLabel": "Nenhum Registro Encontrado!",
    "NoSearchResults": "Não há resultados correspondentes à sua pesquisa.",
    "NotesLabel": "Anotações",
    "NotesPlaceholder": "Máximo de 200 caracteres",
    "NoTournamentMessage": "Nenhum torneio encontrado. Verifique novamente mais tarde.",
    "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>Bem-vindo ao utilitário do selo digital</span>. Como parte de sua associação ao Programa de Especialistas, você pode ganhar um selo digital! Esse utilitário permitirá que você '<em>obtenha</em>' seu selo digital sobrepondo-o em cima de sua foto de perfil existente. Observe que isso atualizará sua foto de perfil em todo o Microsoft 365 (Exchange, Teams, SharePoint, etc.)",
    "OrLabel": "OU",
    "OverviewLabel": "Visão geral e Informações sobre nosso",
    "ParticipantsDetailsLabel": "Detalhes dos Participantes",
    "ParticipantsLabel": "Participantes",
    "ParticipantsStatusLabel": "Status dos participantes",
    "PendingActionsLabel": "Ações Pendentes",
    "PendingActionsSuccessMessage": "Não há mais ações pendentes neste torneio.",
    "PendingEventsSearchboxPlaceholder": "Pesquisar por Especialista/Email",
    "PeopleNameGridHeader": "Nome do Membro",
    "PeoplePickerPlaceholder": "Para Adicionar um membro, digite o nome do membro",
    "PercentageTournamentCompletedLabel": "% do Torneio Concluído",
    "PivotHeaderBySpeciality": "Por Especialidade",
    "PivotHeaderGlobal": "Global",
    "PivotHeaderNearMe": "Perto de Mim",
    "PointsLabel": "Pontos",
    "PreAcceptDisclaimer": "v<h2><span style='font-weight:bold;'>Bem-vindo ao utilitário Selo digital</span></h2>",
    "PreAcceptDisclaimer1": "Como parte de sua associação ao Programa de Campeões, você ganhou um selo digital! Este utilitário permitirá que você '<em>reivindique</em>' seu selo digital sobrepondo-o à sua imagem do perfil existente.",
    "PreAcceptDisclaimer2": "Observe que isso atualizará a imagem do seu perfil em todos os Microsoft 365 (Exchange, Teams, SharePoint etc).",
    "PreAcceptDisclaimer3": "Se desejar, <span style='font-weight:bold'>você terá a oportunidade de 'salvar' uma cópia da sua foto de perfil existente</span> sem a sobreposição do selo digital nas etapas seguintes. Clique em 'Aceitar' para continuar (você pode ver um pop-up aberto e solicitar a entrada).",
    "PreAcceptPageTitle": "Solicite seu selo digital!",
    "PreApplyDisclaimer": "Esta é uma visualização da sua nova foto de perfil, incluindo o selo digital. Se desejar baixar sua foto de perfil existente antes de aplicar o selo digital, clique no link '<strong>Baixar sua imagem de perfil atual</strong>'.",
    "PreApplyDisclaimer1": "Clicar em ‘Aplicar imagem’ atualizará sua imagem de perfil do Microsoft 365 com esta nova imagem. <strong>Observe que isso atualizará sua foto de perfil em todo o Microsoft 365 e não poderá ser revertido por meio desta página</strong>.",
    "PreApplyDisclaimer2": "Se quiser alterar a imagem de volta, você pode usar o <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' id='linkToChangeProfileImage'>aplicativo Web do Outlook</a>.",
    "ProcessingSpinnerLabel": "Processando...",
    "ProfileImageAlt": "Minha imagem de perfil usada no O365, no Teams, etc.",
    "PropertyPaneDescription": "Descrição",
    "QuickLinksLabel": "Links Rápidos",
    "RankLabel": "Classificar",
    "RecordEventLabel": "Registre o usuário do evento",
    "RecordsNotFound": "Registros não encontrados",
    "RefreshIconInfoText": "Clique em atualizar para ver os dados mais recentes",
    "RegionLabel": "Região",
    "RejectButton": "Rejeitar",
    "RemoveEventLabel": "Remover Evento",
    "RemoveFileLabel": "Remover Arquivo",
    "ReportsDropdownInfoIconText": "O relatório só pode ser gerado para Torneios concluídos.",
    "RequestToCallLabel": "Agendar uma sincronização",
    "SaveButton": "Salvar",
    "SearchActiveTournaments": "Pesquisar Torneios ativos",
    "SearchLabel": "Pesquisar Os Principais Campeões",
    "SearchPendingTournaments": "Pesquisar Torneios para começar",
    "SearchPlaceholder": "Pesquisar por Nome do Participante",
    "SelectActionsErrorMessage": "Selecione pelo menos uma ação para continuar.",
    "SelectaCustomDate": "Selecionar uma data personalizada",
    "SelectAll": "Selecionar Todos Especialistas",
    "SelectAllEvents": "Selecionar Todos os Eventos",
    "SelectAllLabel": "Selecionar Tudo",
    "SelectChampion": "Selecionar Especialista",
    "SelectDate": "Selecionar uma data",
    "SelectedFocusAreaLabel": "Área de foco selecionada",
    "SelectEndTournamentMessage": "Selecione um torneio para concluir.",
    "SelectEvent": "Selecionar Evento",
    "SelectTeamsActionsLabel": "Selecionar as Ações do Teams:",
    "SelectTournamentMessage": "Selecione pelo menos um torneio para começar.",
    "SelectTournamentPlaceHolder": "Selecionar Torneio",
    "ShowHideToggle": "Mostrar/Ocultar Campos da Lista de Membros",
    "ShowMoreLabel": "Mostrar Mais",
    "SingleTournamentLabel": "Torneio Único",
    "SpinnerListCreationMessage": "Configurando o Torneio de equipes...",
    "StartTournamentButton": "Iniciar Torneio(s)",
    "StartTournamentDialogMessage": "Tem certeza de que deseja iniciar o novo torneio?",
    "StartTournamentHeaderLabel": "Iniciar Torneio",
    "StatusGridHeader": "Status",
    "SubmitButton": "Enviar",
    "SuccessIcon": "Ícone de Êxito",
    "SupportToolTip": "Suporte",
    "TeamsActionInfoToolTip": "Selecione uma das ações da Equipe disponíveis abaixo para incluir no novo torneio. Para adicionar novas ações do torneio para escolher, visite Gerenciar Ações de Torneio nas Ferramentas de Administração.",
    "ToggleLabelForMemberListColumns": "Mostrar/Ocultar Campos da Lista de Membros",
    "ToggleView": "alternar",
    "ToLabel": "Para",
    "TooltipContentForMemberListFieldsHeading": "Mostrar/ocultar campos da lista de membros em todos os componentes do aplicativo sempre que aplicável.",
    "Top5ParticipantswithPointsLabel": "Os 5 Principais Participantes com Pontos",
    "Top5TournamentswithParticipantsLabel": "Os 5 Principais Torneios com Participantes",
    "TopChampionsLabel": "Principais Especialistas",
    "TotalActivitiesLabel": "Total de Atividades",
    "TotalChampionsLabel": "Total de Campeões",
    "TotalParticipantsLabel": "Total de Participantes",
    "TotalPercentageCompletionLabel": "% do Total da Conclusão",
    "TotalPointsLabel": "Total de Pontos",
    "TOTBreadcrumbLabel": "Torneio de equipes",
    "TOTLabel": "Torneio de equipes",
    "TOTLeaderBoardPageTitle": "Quadro de Líderes",
    "TOTMyDashboardPageTitle": "Meu Painel",
    "TournamentDescPlaceHolderLabel": "Descrição do torneio (Máximo 500 caracteres)",
    "TournamentDescriptionLabel": "Descrição do Torneio",
    "TournamentLabel": "Torneio",
    "TournamentNameErrorLabel": "O Nome do Torneio é obrigatório.",
    "TournamentNameLabel": "Nome do Torneio",
    "TournamentNamePlaceHolderLabel": "Nome do Torneio (Máximo de 255 caracteres)",
    "TournamentRankLabel": "Classificação do Torneio",
    "TournamentReportsPageTitle": "Relatório dos Torneios",
    "UnauthorizedText": "Você não está qualificado para o Programa de Selo de Especialista no momento",
    "UploadFileButton": "Carregar Arquivo",
    "UserAddedMessage": "Usuário Adicionado com Êxito!",
    "UserExistingMessage": "O Usuário Já É um Especialista!",
    "UserLabel": "Usuário",
    "UserNominatedMessage": "Usuário Indicado com Êxito!",
    "ViewActivitiesLabel": "Exibir atividades",
    "ViewDashBoardLabel": "Exibir Painel",
    "VisitLabel": "Visite as páginas da Plataforma de gerenciamento de especialistas para saber mais:",
    "WelcomeLabel": "Bem-vindo(a)",
    "YesButton": "Sim"
  }
});
