define([], function () {
  return {
  "PropertyPaneDescription": "Descrição",
  "BasicGroupName": "Nome do grupo",
  "DescriptionFieldLabel": "Campo de Descrição",
  "SaveButton": "Salvar",
  "BackButton": "Voltar",
  "GetStartedLabel": "Introdução",
  "AdminToolsLabel": "Ferramentas do Administrador",
  "ChampionLeaderBoardLabel": "Classificação de especialistas",
  "AddMemberLabel": "Adicionar Membro",
  "NominateMemberLabel": "Nomear Membro",
  "DigitalBadgeLabel": "Selo Digital",
  "TOTLabel": "Torneio de equipes",
  "ChampionListLabel": "Lista de Especialistas",
  "EventsListLabel": "Lista de Eventos",
  "AdminTasksLabel": "Tarefas Administrativas",
  "ManageDigitalBadgesLabel": "Gerenciar os Selos Digitais",
  "EnableTOTLabel": "Habilitar o Torneio de equipes",
  "AddMembersToolTip": "Adicionar Membros Comece a adicionar as pessoas com as quais você colaborará em seu...",
  "DigitalMembersToolTip": "Obtenha seu selo digital e aplique-o à sua imagem de perfil",
  "ChampionsListToolTip": "Acessando a Lista de Especialistas",
  "EventsListToolTip": "Acessando a Lista de eventos",
  "EnableTOTToolTip": "Habilitar o Torneio de equipes",
  "ManageDigitalBadgesToolTip": "Gerenciar os Selos Digitais",
  "WelcomeLabel": "Bem-vindo(a)",
  "ManageAppLogoLabel": "Gerenciar o Logotipo do Aplicativo",
  "ManageAppLogoToolTip": "Gerenciar o Logotipo do Aplicativo",
  "AppLogoToolTip": "Home",
  "MoreInfoToolTip": "Mais Informações",
  "SupportToolTip": "Suporte",
  "FeedbackToolTip": "Comentários",
  "AdditionalResourcesHeaderLabel": "Recursos Adicionais:",
  "AdditionalResourcesContentLabel": "O Grupo de Atendimento ao Cliente do Microsoft Teams está focado em fornecer soluções como estas para inspirar e ajudar você a alcançar suas metas. Siga e ingresse por meio desses outros recursos para saber mais sobre nós e a comunidade:",
  "M365ChampionCommunityLinkLabel": "Comunidade de especialistas do Microsoft 365",
  "DrivingAdoptionLinkLabel": "Impulsionando a adoção na Microsoft Technical Community",
  "CurrentVersionLabel": "Versão atual:",
  "LatestVersionLabel": "Versão Mais Recente:",
  "CMPGitHubLinkLabel": "GitHub",
  "VisitLabel": "Visite as páginas da Plataforma de gerenciamento de especialistas para saber mais:",
  "OverviewLabel": "Visão geral e Informações sobre nosso",
  "MSAdoptionHubLinkLabel": "Centro de adoção da Microsoft",
  "DocumentationLabel": "Documentação técnica da solução e visão geral da arquitetura sobre",
  "AddMemberPageTitle": "Adicionar Membro",
  "NominateMemberPageTitle": "Nomear Membro",
  "PeoplePickerPlaceholder": "Para Adicionar um membro, digite o nome do membro",
  "FocusAreaPlaceholder": "Selecionar a Área de Foco",
  "UserExistingMessage": "O Usuário Já É um Especialista!",
  "ChampionsListPageTitle": "Lista de Especialistas",
  "UserNominatedMessage": "Usuário Indicado com Êxito!",
  "UserAddedMessage": "Usuário Adicionado com Êxito!",
  "PeopleNameGridHeader": "Nome do Membro",
  "SelectChampion": "Selecionar Especialista",
  "SelectAll": "Selecionar Todos Especialistas",
  "FocusAreaGridHeader": "Área de Foco",
  "CountryGridHeader": "País/região",
  "RegionLabel": "Região",
  "StatusGridHeader": "Status",
  "ActionGridHeader": "Ação",
  "ApproveButton": "Aprovar",
  "RejectButton": "Rejeitar",
  "NoChampionsMessage": "Nenhuma solicitação pendente no momento",
  "ChampionApprovedMessage": "Solicitações de Especialistas Aprovadas.",
  "ChampionRejectedMessage": "Solicitações de Especialistas Rejeitadas.",
  "ProcessingSpinnerLabel": "Processando...",
  "DigitalBadgePageTitle": "Selo Digital",
  "LoadingSpinnerLabel": "Carregando...",
  "LoadingDigitalBadgeLabel": "Carregamento de quadro de selo digital",
  "DigitalBadgeAppBannerAltText": "Membros da equipe da Microsoft participando de uma discussão",
  "GroupGridHeader": "Grupo",
  "ShowHideToggle": "Mostrar/Ocultar Campos da Lista de Membros",
  "ToggleView": "alternar",
  "SelectedFocusAreaLabel": "Área de foco selecionada",
  "PreAcceptPageTitle": "Solicite seu selo digital!",
  "PreAcceptDisclaimer": "v<h2><span style='font-weight:bold;'>Bem-vindo ao utilitário Selo digital</span></h2>",
  "PreAcceptDisclaimer1": "Como parte de sua associação ao Programa de Campeões, você ganhou um selo digital! Este utilitário permitirá que você '<em>reivindique</em>' seu selo digital sobrepondo-o à sua imagem do perfil existente.",
  "PreAcceptDisclaimer2": "Observe que isso atualizará a imagem do seu perfil em todos os Microsoft 365 (Exchange, Teams, SharePoint etc).",
  "PreAcceptDisclaimer3": "Se desejar, <span style='font-weight:bold'>você terá a oportunidade de 'salvar' uma cópia da sua foto de perfil existente</span> sem a sobreposição do selo digital nas etapas seguintes. Clique em 'Aceitar' para continuar (você pode ver um pop-up aberto e solicitar a entrada).",
  "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>Bem-vindo ao utilitário do selo digital</span>. Como parte de sua associação ao Programa de Especialistas, você pode ganhar um selo digital! Esse utilitário permitirá que você '<em>obtenha</em>' seu selo digital sobrepondo-o em cima de sua foto de perfil existente. Observe que isso atualizará sua foto de perfil em todo o Microsoft 365 (Exchange, Teams, SharePoint, etc.)",
  "HowtoGetDigitalBadgeText": "Como obter uma Selo de Especialista",
  "MultipleBadgeMessage": "Selecione um selo na lista abaixo. O selo selecionado será aplicado na imagem do seu perfil.",
  "NoBadgeMessage": "Nenhum selo encontrado para você selecionar. Verifique com o Administrador de Aplicativos.",
  "DigitalBadgeSubPageTitle": "Veja como seu selo digital ficará!",
  "ProfileImageAlt": "Minha imagem de perfil usada no O365, no Teams, etc.",
  "BadgeImageAlt": "Prêmio em forma de medalha com a letra C no meio que indica que eu sou parte do Programa de Especialistas",
  "NoProfileImageAlt": "Silhueta de uma pessoa, indicando que nenhuma imagem de perfil está atualmente aplicada à sua conta",
  "ApplyButtonText": "Aplicar imagem",
  "ApplyButtonAriaDescription": "Ao clicar neste botão, você dará permissão à Web Part do Programa de Especialistas para atualizar sua foto de perfil em seu nome.",
  "ApplyButton": "Aplicar",
  "DownloadButtonText": "Baixar",
  "DownloadButtonAriaDescription": "Clique para baixar sua imagem de perfil atual",
  "DownloadingButtonText": "Baixando...",
  "DownloadedButtonText": "Baixado",
  "DownloadedButtonSecondaryText": "A imagem de perfil baixada pode ser encontrada na pasta Downloads do dispositivo.",
  "DownloadButtonSecondaryText": "Baixar sua imagem de perfil atual",
  "PreApplyDisclaimer": "Esta é uma visualização da sua nova foto de perfil, incluindo o selo digital. Se desejar baixar sua foto de perfil existente antes de aplicar o selo digital, clique no link '<strong>Baixar sua imagem de perfil atual</strong>'.",
  "PreApplyDisclaimer1": "Clicar em ‘Aplicar imagem’ atualizará sua imagem de perfil do Microsoft 365 com esta nova imagem. <strong>Observe que isso atualizará sua foto de perfil em todo o Microsoft 365 e não poderá ser revertido por meio desta página</strong>.",
  "PreApplyDisclaimer2": "Se quiser alterar a imagem de volta, você pode usar o <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' id='linkToChangeProfileImage'>aplicativo Web do Outlook</a>.",
  "NoProfileImageDescription": "Se você já associou uma foto ao seu perfil e ainda estiver vendo esta mensagem, sua foto pode ainda não estar disponível. Tente novamente mais tarde ou contate a <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>assistência técnica</a> se ela ainda não apareceu após 24 horas.",
  "AcceptButtonText": "Aceitar",
  "AcceptButtonAriaDescription": "Ao clicar neste botão, você dará permissão à Web Part do Programa de Especialistas para atualizar sua foto de perfil em seu nome.",
  "UnauthorizedText": "Você não está qualificado para o Programa de Selo de Especialista no momento",
  "ApplySpinnerLabel": "Aplicando nova imagem de perfil à sua conta...",
  "DigitalBadgeSuccessMessage": "<strong>Parabéns!</strong> Você reivindicou com êxito seu selo digital e sua foto de perfil foi atualizada. Aguarde até 24 horas para ver a atualização refletida em todos os aplicativos do Microsoft 365 (incluindo o Teams).",
  "BadgePointsTooltip": "Pontos necessários para desbloquear:",
  "CMPSideBarPointsLabel": "Pontos",
  "CMPSideBarGlobalRankLabel": "Classificação Global",
  "CMPSideBarChampionsLabel": "Especialistas",
  "FirstNameLabel": "Primeiro Nome",
  "LastNameLabel": "Sobrenome",
  "EmailIDLabel": "ID de email",
  "BecomeChampionLabel": "Torne-se um Especialista",
  "ChampionSubmissionPendingLabel": "O envio dos especialistas está pendente",
  "ChampionRequestSubmitSuccessMessage": "Envio de solicitação de especialistas bem-sucedido",
  "PivotHeaderGlobal": "Global",
  "PivotHeaderNearMe": "Perto de Mim",
  "PivotHeaderBySpeciality": "Por Especialidade",
  "NearMePlaceHolder": "Selecionar Perto de Mim",
  "BySpecialityPlaceHolder": "Selecionar por Especialidade",
  "TopChampionsLabel": "Principais Especialistas",
  "RecordsNotFound": "Registros não encontrados",
  "EventTypeLabel": "Tipo de Evento",
  "CountLabel": "Contagem",
  "MyRankLabel": "Minha Classificação",
  "SelectDate": "Selecionar uma data",
  "NotesPlaceholder": "Máximo de 200 caracteres",
  "EventSubmissionPendingMessage": "Evento(s) enviado(s) para aprovação. Os pontos serão concedidos assim que o(s) evento(s) for(em) aprovado(s).",
  "EventsSubmissionSuccessMessage": "Evento(s) registrado(s) com êxito.",
  "ViewDashBoardLabel": "Exibir Painel",
  "DateofEventGridLabel": "Data do Evento",
  "EventTypeGridLabel": "Tipo",
  "RecordEventLabel": "Registre o usuário do evento",
  "MonthAndDateLabel": "Mês e data",
  "EventTypeGridLabelPlaceHolder": "Selecionar o Tipo de Evento",
  "EventTypeValidationMessage": "Selecione o tipo de evento!",
  "CountValidationMessage": "A contagem deve estar entre 1 e 5",
  "EventsSubmitMessage": "Quando terminar de adicionar eventos, clique no botão Enviar para salvar.",
  "SubmitButton": "Enviar",
  "SearchLabel": "Pesquisar Os Principais Campeões",
  "ActivitiesLabel": "Atividades",
  "FocusAreaLabel": "Área de Foco",
  "ShowMoreLabel": "Mostrar Mais",
  "ViewActivitiesLabel": "Exibir atividades",
  "ChatIconLabel": "Chat",
  "RequestToCallLabel": "Agendar uma sincronização",
  "EmailIconLabel": "Enviar um Email",
  "MeetupSubject": "Reunião individual (Solicitação de Especialista)",
  "MeetupBody": "Reserve um tempo para discutir sua área especialista e aprender mais!",
  "NoActivitiesinGridLabel": "Nenhuma Atividade Encontrada!",
  "CreateTournamentPageTitle": "Criar Torneio",
  "CreateTournamentSuccessLabel": "Torneio criado com êxito.",
  "TournamentNameLabel": "Nome do Torneio",
  "TournamentNamePlaceHolderLabel": "Nome do Torneio (Máximo de 255 caracteres)",
  "TournamentNameErrorLabel": "O Nome do Torneio é obrigatório.",
  "TournamentDescriptionLabel": "Descrição do Torneio",
  "TournamentDescPlaceHolderLabel": "Descrição do torneio (Máximo 500 caracteres)",
  "SelectTeamsActionsLabel": "Selecionar as Ações do Teams:",
  "TeamsActionInfoToolTip": "Selecione uma das ações da Equipe disponíveis abaixo para incluir no novo torneio. Para adicionar novas ações do torneio para escolher, visite Gerenciar Ações de Torneio nas Ferramentas de Administração.",
  "ActionErrorLabel": "Selecione pelo menos uma ação para criar um torneio.",
  "CreateTournamentButton": "Criar Torneio",
  "DuplicateTournamentNameError": "O nome do torneio já existe. Insira outro nome para o torneio.",
  "CreateTournamentsButton": "Crie Torneios",
  "SingleTournamentLabel": "Torneio Único",
  "MultipleTournamentLabel": "Vários Torneios",
  "MultiTournamentStep": "Etapa",
  "MultiTournamentStep1LinkLabel": "Baixar Modelo",
  "MultiTournamentStep1Text": " de formato de arquivo de amostra",
  "MultiTournamentStep2": "Adicione detalhes do torneio ao arquivo seguindo as diretrizes",
  "MultiTournamentStep3": "Fazer upload do arquivo",
  "UploadFileButton": "Carregar Arquivo",
  "RemoveFileLabel": "Remover Arquivo",
  "ImportSpinnerMessage": "Criando Torneios.......",
  "ErrorMsgTournamentList": "Erro ao criar um item na lista Torneios. Corrija os dados e tente novamente.",
  "ErrorMsgActionsList": "Erro ao criar um item na lista Ações. Corrija os dados e tente novamente.",
  "ErrorMsgTournamentActionsList": "Ocorreu um erro ao criar um item na lista Ações de Torneio. Corrija os dados e tente novamente.",
  "LogMsgTournamentExists": "Ignorado, pois o torneio",
  "LogMsgTournamentExists1": "já existe.",
  "LogMsgDone": "Torneio",
  "LogMsgDone1": "criado.",
  "LogMsgInvalidTournamentName": "Ignorado, pois ele não tem um Nome de Torneio válido.",
  "LogMsgInvalidTemplate": "Ignorado, pois não é um modelo válido.",
  "LogMsgMultipleTournaments": "Ignorado, pois ele tem mais de um Nome de Torneio.",
  "LogMsgBlankSheet": "Ignorado, pois está em branco.",
  "LogProgress": " Abaixo está o progresso:",
  "ImportRule1": "Não modificar os cabeçalhos de coluna no modelo",
  "ImportRule2": "Não excluir as colunas no modelo",
  "ImportRule3": "Insira os dados em todas as colunas obrigatórias (*) mencionadas no modelo",
  "ImportRule4": "Siga o limite de caracteres e o tipo mencionado no modelo para cada coluna",
  "ImportRule5": "Insira dados para apenas 1 torneio em cada planilha de acordo com os dados de exemplo fornecidos",
  "ImportRule6": "Somente 10 Torneios podem ser criados por vez",
  "ImportRule7": "Certifique-se de que o Nome do Torneio é único",
  "TOTBreadcrumbLabel": "Torneio de equipes",
  "EnableTOTSuccessMessage": "O Torneio de equipes foi habilitado com êxito. Atualize o aplicativo para continuar.",
  "EnableTOTSpinnerMessage": "Este processo levará alguns minutos para ser concluído. Não saia até ver a mensagem concluída com êxito.",
  "TOTLeaderBoardPageTitle": "Quadro de Líderes",
  "TOTMyDashboardPageTitle": "Meu Painel",
  "ManageTournamentActionsToolTip": "Acessando a Lista de Ações do Torneio",
  "ManageTournamentActionsLabel": "Gerenciar as Ações do Torneio",
  "ManageTournamentsLabel": "Gerenciar Torneios",
  "ManageAdminsToolTip": "Acessando a Lista de Administradores",
  "ManageAdminsLabel": "Gerenciar Administradores",
  "QuickLinksLabel": "Links Rápidos",
  "SpinnerListCreationMessage": "Configurando o Torneio de equipes...",
  "ManageTournamentsPageTitle": "Gerenciar Torneios",
  "ManageToTLabel1": "Vários Torneios podem ser iniciados por vez. Veja abaixo os Torneios atuais ativos, a capacidade de concluir o torneio, bem como a capacidade de iniciar um novo torneio.",
  "ManageToTLabel2": "Depois que um torneio for iniciado e concluído, ele não estará disponível para iniciar novamente; no entanto, você pode criar um novo torneio usando as mesmas ações se quiser concluir um torneio semelhante!",
  "EndTournamentDialogMessage": "Tem certeza de que deseja concluir o torneio?",
  "StartTournamentDialogMessage": "Tem certeza de que deseja iniciar o novo torneio?",
  "ConfirmLabel": "Confirmar",
  "YesButton": "Sim",
  "NoButton": "Não",
  "ActiveTournamentLabel": "Torneios Ativos",
  "EndTournamentButton": "Torneio Concluído",
  "StartTournamentHeaderLabel": "Iniciar Torneio",
  "NoTournamentMessage": "Nenhum torneio encontrado. Verifique novamente mais tarde.",
  "SelectTournamentMessage": "Selecione pelo menos um torneio para começar.",
  "SelectEndTournamentMessage": "Selecione um torneio para concluir.",
  "StartTournamentButton": "Iniciar Torneio(s)",
  "EndTournamentSuccessMessage": "Torneio concluído com êxito.",
  "EnableTournamentSuccessMessage": "Torneio(s) iniciado(s) com êxito.",
  "CompleteTournamentSpinnerMessage": "Completando o Torneio...",
  "EnableTournamentSpinnerMessage": "Habilitando o(s) Torneio(s)...",
  "SearchActiveTournaments": "Pesquisar Torneios ativos",
  "SearchPendingTournaments": "Pesquisar Torneios para começar",
  "SelectAllLabel": "Selecionar Tudo",
  "NoSearchResults": "Não há resultados correspondentes à sua pesquisa.",
  "NoActiveParticipantsMessage": "Não há participantes ativos no momento. Seja o primeiro a participar e registrar uma atividade em Meu Painel!",
  "NoActiveTournamentMessage": "Não há nenhum torneio ativo no momento. Verifique novamente mais tarde.",
  "TournamentLabel": "Torneio",
  "DescriptionLabel": "Descrição",
  "NoActiveParticipantsErrorMessage": "Não há participantes ativos no momento. Seja o primeiro a participar e registrar uma atividade de ",
  "PendingActionsLabel": "Ações Pendentes",
  "PendingActionsSuccessMessage": "Não há mais ações pendentes neste torneio.",
  "SelectActionsErrorMessage": "Selecione pelo menos uma ação para continuar.",
  "FormSavingMessage": "Salvando seus detalhes....",
  "CompletedActionsLabel": "Ações Concluídas",
  "RankLabel": "Classificar",
  "UserLabel": "Usuário",
  "MyDashboardInfoIconMessage": "Saiba mais sobre essa ação",
  "SelectTournamentPlaceHolder": "Selecionar Torneio",
  "MyTournamentsLabel": "Meus Torneios",
  "OrLabel": "OU",
  "MyTournamentsTooltip": "Torneios ativos dos quais você já participou",
  "PointsLabel": "Pontos",
  "TournamentRankLabel": "Classificação do Torneio",
  "ParticipantsLabel": "Participantes",
  "TournamentReportsPageTitle": "Relatório dos Torneios",
  "TotalActivitiesLabel": "Total de Atividades",
  "TotalPointsLabel": "Total de Pontos",
  "TotalParticipantsLabel": "Total de Participantes",
  "TotalPercentageCompletionLabel": "% do Total da Conclusão",
  "Top5ParticipantswithPointsLabel": "Os 5 Principais Participantes com Pontos",
  "Top5TournamentswithParticipantsLabel": "Os 5 Principais Torneios com Participantes",
  "ParticipantsStatusLabel": "Status dos participantes",
  "ParticipantsDetailsLabel": "Detalhes dos Participantes",
  "NameLabel": "Nome",
  "PercentageTournamentCompletedLabel": "% do Torneio Concluído",
  "ActivitiesCompletedLabel": "Atividades Concluídas",
  "NoRecordsinGridLabel": "Nenhum Registro Encontrado!",
  "SearchPlaceholder": "Pesquisar por Nome do Participante",
  "NoCompletedTournamentsMessage": "Não há nenhum torneio concluído no momento. Verifique novamente mais tarde.",
  "ReportsDropdownInfoIconText": "O relatório só pode ser gerado para Torneios concluídos.",
  "RefreshIconInfoText": "Clique em atualizar para ver os dados mais recentes",
  "EventApprovedMessage": "Evento(s) de Especialista(s) Aprovado(s).",
  "EventRejectedMessage": "Evento(s) de Especialista(s) Rejeitado(s).",
  "SelectAllEvents": "Selecionar Todos os Eventos",
  "SelectEvent": "Selecionar Evento",
  "ChampionLabel": "Especialista",
  "EmailLabel": "Email",
  "EventLabel": "Evento",
  "DateLabel": "Data",
  "NotesLabel": "Anotações",
  "SuccessIcon": "Ícone de Êxito",
  "PendingEventsSearchboxPlaceholder": "Pesquisar por Especialista/Email",
  "NoRecordsIcon": "Ícone Sem Registros",
  "NoPendingEventsLabel": "Nenhum evento pendente no momento.",
  "ChampionActivitiesLabel": "Atividades de Especialista",
  "ManageConfigSettingsLabel": "Gerenciar Configurações",
  "ApproveChampionSearchboxPlaceholder": "Pesquisar por Nome do Membro/Email",
  "EventsApprovalInfoIconTooltipContent": "Habilitar esta opção exigirá que os envios de eventos por campeão sejam aprovados por um administrador. Os pontos dos eventos serão concedidos somente após a aprovação.",
  "ConfigSettingsSaved": "Configurações salvas.",
  "EventApprovalsEnableLabel": "Habilitar Aprovações de Evento de Especialista",
  "EventsSelectedLabel": "Evento(s) Selecionado(s).",
  "ChampionsSelectedLabel": "Especialista(s) selecionado(s).",
  "ToggleLabelForMemberListColumns": "Mostrar/Ocultar Campos da Lista de Membros",
  "TooltipContentForMemberListFieldsHeading": "Mostrar/ocultar campos da lista de membros em todos os componentes do aplicativo sempre que aplicável.",
  "ChampionReportLabel": "Relatório dos Campeões",
  "ChampionReportToolTip": "Relatório dos Campeões",
  "TotalChampionsLabel": "Total de Campeões",
  "ClearButton": "Limpar",
  "FilterbyDateLabel": "Filtrar por Data",
  "EventTypesHeading": "Tipo de Evento",
  "NoEventsMessage": "Não há eventos concluídos no momento. Verifique novamente mais tarde.",
  "NoEventsFoundMessage": "Nenhum Evento encontrado!",
  "AppTitleLabel": "Título do Aplicativo",
  "AppTitleErrorLabel": "O Título do Aplicativo é obrigatório.",
  "AppTitlePlaceholderText": "Máximo de 30 Caracteres",
  "AppTitleInfoIconText": "O título do aplicativo aparecerá na seção de cabeçalho e nas seções de trilha do aplicativo",
  "AboutContentLabel": "foi criado com Especialistas organizacionais/Especialistas em Adoção em mente. Ouvindo da comunidade Microsoft 365 Champion, este aplicativo foi desenvolvido para fornecer uma plataforma para ajudar a criar e sustentar suas próprias comunidades. Comece com inspiração por meio da execução para ajudá-lo a alcançar mais em suas próprias comunidades!",
  "AboutHeaderLabel": "Sobre a",
  "DashboardLabel": "Painel",
  "RemoveEventLabel": "Remover Evento",
  "AddEventLabel": "Adicionar Evento",
  "EventChartLabel": "10 principais Eventos com Tipos de Evento",
  "FromLabel": "De",
  "ToLabel": "Para",
  "AllTime": "Toda Hora",
  "LastMonth": "Mês Passado",
  "Last3Months": "Últimos Três Meses",
  "Last6Months": "Últimos Seis Meses",
  "Last1Year": "Último 1 ano",
  "SelectaCustomDate": "Selecionar uma data personalizada",
  "championRecordsFoundLabel": "Registros de campeões encontrados",
  "digitalBadgeProfileAriaLabel": "Abrir o aplicativo Web do Outlook em uma nova guia ou janela do navegador",
  "AddMemberAsAdminLabel": "Adicionar Membro como Administrador",
  "NoteValidationMessage": "As anotações não devem exceder 200 caracteres",
  "CloseInfoPopoverButton": "Fechar"
  }
});
