define([], function () {
    return {
      "PropertyPaneDescription": "Descrição",
      "BasicGroupName": "Nome do grupo",
      "DescriptionFieldLabel": "Campo de Descrição",
      "CMPBreadcrumbLabel": "Plataforma de Gerenciamento de Campeões",
      "SaveButton": "Salvar",
      "BackButton": "Voltar",
      "GetStartedLabel": "Introdução",
      "AdminToolsLabel": "Ferramentas do Administrador",
      "ChampionLeaderBoardLabel": "Placar de Líderes dos Campeões",
      "AddMemberLabel": "Adicionar Membro",
      "NominateMemberLabel": "Nomear Membro",
      "DigitalBadgeLabel": "Selo Digital",
      "TOTLabel": "Campeonato do Teams",
      "ChampionListLabel": "Lista de Campeões",
      "EventsListLabel": "Lista de Eventos",
      "EventsTrackListLabel": "Lista de Acompanhamento dos Eventos",
      "ManageApprovalsLabel": "Gerenciar Aprovações",
      "ManageDigitalBadgesLabel": "Gerenciar os Selos Digitais",
      "EnableTOTLabel": "Habilitar o Campeonato do Teams",
      "AddMembersToolTip": "Adicionar Membros Comece a adicionar as pessoas com as quais você colaborará em seu...",
      "DigitalMembersToolTip": "Obtenha seu selo digital e aplique-o à sua imagem de perfil",
      "ChampionsListToolTip": "Acessando a Lista de Campeões",
      "EventsListToolTip": "Acessando a Lista de eventos",
      "EventTrackListToolTip": "Acessando a Lista de Acompanhamento do Evento",
      "ManageApprovalToolTip": "Aprovar Campeão",
      "EnableTOTToolTip": "Habilitar o Campeonato do Teams",
      "ManageDigitalBadgesToolTip": "Gerenciar os Selos Digitais",
      "WelcomeLabel": "Bem-vindo(a)",
      "ManageAppLogoLabel": "Gerenciar o Logotipo do Aplicativo",
      "ManageAppLogoToolTip": "Gerenciar o Logotipo do Aplicativo",
      "AppHeaderTitleLabel": "Plataforma de Gerenciamento de Campeões",
      "AppLogoToolTip": "Home",
      "MoreInfoToolTip": "Mais Informações",
      "SupportToolTip": "Suporte",
      "FeedbackToolTip": "Comentários",
      "AboutHeaderLabel": "Sobre a Plataforma de Gerenciamento de Campeões (CMP):",
      "AboutContentLabel": "Nossa Plataforma de Gerenciamento de Campeão foi criada com Especialistas organizacionais/Especialistas de Adoção em mente. Ouvindo da comunidade Microsoft 365 Champion, este aplicativo foi desenvolvido para fornecer uma plataforma para ajudar a criar e sustentar suas próprias comunidades. Comece com inspiração por meio da execução para ajudá-lo a alcançar mais em suas próprias comunidades!",
      "AdditionalResourcesHeaderLabel": "Recursos Adicionais:",
      "AdditionalResourcesContentLabel": "O Grupo de Atendimento ao Cliente do Microsoft Teams está focado em fornecer soluções como estas para inspirar e ajudar você a alcançar suas metas. Siga e ingresse por meio desses outros recursos para saber mais sobre nós e a comunidade:",
      "M365ChampionCommunityLinkLabel": "Comunidade de Campeões do Microsoft 365",
      "DrivingAdoptionLinkLabel": "Impulsionando a adoção na Microsoft Technical Community",
      "CurrentVersionLabel": "Versão atual:",
      "LatestVersionLabel": "Versão Mais Recente:",
      "CMPGitHubLinkLabel": "GitHub",
      "VisitLabel": "Visite as páginas da Plataforma de Gerenciamento de Campeão para saber mais:",
      "OverviewLabel": "Visão geral e Informações sobre nosso",
      "MSAdoptionHubLinkLabel": "Hub de Adoção da Microsoft",
      "DocumentationLabel": "Documentação técnica da solução e visão geral da arquitetura sobre",
      "AddMemberPageTitle": "Adicionar Membro",
      "NominateMemberPageTitle": "Nomear Membro",
      "PeoplePickerPlaceholder": "Para Adicionar um membro, digite o nome do membro",
      "RegionPlaceholder": "Selecionar Região",
      "CountryPlaceholder": "Selecionar País/Região",
      "GroupPlaceholder": "Selecionar Grupo",
      "FocusAreaPlaceholder": "Selecionar a Área de Foco",
      "UserExistingMessage": "O Usuário Já É um Campeão!",
      "ChampionsListPageTitle": "Lista de Campeões",
      "UserNominatedMessage": "Usuário Indicado com Êxito!",
      "UserAddedMessage": "Usuário Adicionado com Êxito!",
      "PeopleNameGridHeader": "Nome do Membro",
      "Select": "Selecionar",
      "SelectAll": "Selecionar Tudo",
      "RegionGridHeader": "Região",
      "CountryGridHeader": "País/região",
      "GroupGridHeader": "Grupo",
      "FocusAreaGridHeader": "Área de Foco",
      "StatusGridHeader": "Status",
      "ManageApprovalsPageTitle": "Gerenciar Aprovações",
      "ActionGridHeader": "Ação",
      "ApproveButton": "Aprovar",
      "RejectButton": "Rejeitar",
      "NoChampionsMessage": "Nenhuma solicitação pendente no momento",
      "ChampionApprovedMessage": "Solicitação(ões) de Campeão Aprovada(s)!",
      "ChampionRejectedMessage": "Solicitação(ões) de Campeão Rejeitada(s)!",
      "ProcessingSpinnerLabel": "Processando...",
      "DigitalBadgePageTitle": "Selo Digital",
      "LoadingSpinnerLabel": "Carregando...",
      "DigitalBadgeAppBannerAltText": "Membros da equipe da Microsoft participando de uma discussão",
      "PreAcceptPageTitle": "Solicite seu selo digital!",
      "PreAcceptDisclaimer": "<span style='font-weight:bold;'>Bem-vindo ao utilitário do selo digital</span> <br/><br/> <span>Como parte de sua associação ao Programa Campeões, você ganhou um selo digital! Esse utilitário permitirá que você '<em>obtenha</em>' seu selo digital sobrepondo-o em cima de sua foto de perfil existente. <br/><br/> Observe que isso atualizará sua foto de perfil em todo o Microsoft 365 (Exchange, Teams, SharePoint, etc.).</span>",
      "PreAcceptDisclaimer2": "Se desejar, <span style='font-weight:bold;'>você terá a oportunidade de 'salvar' uma cópia da sua foto de perfil existente</span> sem a sobreposição do selo digital nas etapas seguintes. Clique em 'Aceitar' para continuar (você pode ver um pop-up aberto e solicitar a entrada).",
      "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>Bem-vindo ao utilitário do selo digital</span>. Como parte de sua associação ao Programa Campeões, você pode ganhar um selo digital! Esse utilitário permitirá que você '<em>obtenha</em>' seu selo digital sobrepondo-o em cima de sua foto de perfil existente. Observe que isso atualizará sua foto de perfil em todo o Microsoft 365 (Exchange, Teams, SharePoint, etc.)",
      "HowtoGetDigitalBadgeText": "Como obter uma Selo de Campeão",
      "MultipleBadgeMessage": "Selecione um selo na lista abaixo. O selo selecionado será aplicado na imagem do seu perfil.",
      "NoBadgeMessage": "Nenhum selo encontrado para você selecionar. Verifique com o Administrador de Aplicativos.",
      "DigitalBadgeSubPageTitle": "Veja como seu selo digital ficará!",
      "ProfileImageAlt": "Minha imagem de perfil usada no O365, no Teams, etc.",
      "BadgeImageAlt": "Prêmio em forma de medalha com a letra C no meio que indica que eu sou parte do Programa Dos Campeão",
      "NoProfileImageAlt": "Silhueta de uma pessoa, indicando que nenhuma imagem de perfil está atualmente aplicada à sua conta",
      "ApplyButtonText": "Aplicar imagem",
      "ApplyButtonAriaDescription": "Ao clicar neste botão, você dará permissão à Web Part do Programa Campeões para atualizar sua foto de perfil em seu nome.",
      "ApplyButton": "Aplicar",
      "DownloadButtonText": "Baixar",
      "DownloadButtonAriaDescription": "Clique para baixar sua imagem de perfil atual",
      "DownloadingButtonText": "Baixando...",
      "DownloadedButtonText": "Baixado",
      "DownloadedButtonSecondaryText": "A imagem de perfil baixada pode ser encontrada na pasta Downloads do dispositivo.",
      "DownloadButtonSecondaryText": "Baixar sua imagem de perfil atual",
      "PreApplyDisclaimer": "Esta é uma visualização da sua nova foto de perfil, incluindo o selo digital. Se desejar baixar sua foto de perfil existente antes de aplicar o selo digital, clique no link '<strong>Baixar sua imagem de perfil atual</strong>'.<br />",
      "PreApplyDisclaimer1": "<br />Clicar em \"Aplicar imagem\" atualizará sua imagem de perfil do Microsoft 365 com esta nova imagem. <strong>Observe que isso atualizará sua foto de perfil em todo o Microsoft 365 e não poderá ser revertido por meio desta página</strong>. <br/><br/>Se desejar alterar sua imagem de volta, você poderá usar o <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' aria-label='Open the Outlook web application in a new browser tab or window'>aplicativo da Web do Outlook</a>.",
      "NoProfileImageDescription": "Se você já associou uma foto ao seu perfil e ainda estiver vendo esta mensagem, sua foto pode ainda não estar disponível. Tente novamente mais tarde ou contate a <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>assistência técnica</a> se ela ainda não apareceu após 24 horas.",
      "AcceptButtonText": "Aceitar",
      "AcceptButtonAriaDescription": "Ao clicar neste botão, você dará permissão à Web Part do Programa Campeões para atualizar sua foto de perfil em seu nome.",
      "UnauthorizedText": "Você não está qualificado para o Programa de Selo de Campeão no momento",
      "ApplySpinnerLabel": "Aplicando nova imagem de perfil à sua conta...",
      "DigitalBadgeSuccessMessage": "<strong>Parabéns!</strong> Você reivindicou com êxito seu selo digital e sua foto de perfil foi atualizada. Aguarde até 24 horas para ver a atualização refletida em todos os aplicativos do Microsoft 365 (incluindo o Teams).",
      "CMPSideBarPointsLabel": "Pontos",
      "CMPSideBarGlobalRankLabel": "Classificação Global",
      "CMPSideBarChampionsLabel": "Campeões",
      "FirstNameLabel": "Primeiro Nome",
      "LastNameLabel": "Sobrenome",
      "EmailIDLabel": "ID de email",
      "BecomeChampionLabel": "Torne-se um Campeão",
      "ChampionSubmissionPendingLabel": "O envio dos campeões está pendente",
      "ChampionRequestSubmitSuccessMessage": "Envio de solicitação de campeão bem-sucedido",
      "PivotHeaderGlobal": "Global",
      "PivotHeaderNearMe": "Perto de Mim",
      "PivotHeaderBySpeciality": "Por Especialidade",
      "NearMePlaceHolder": "Selecionar Perto de Mim",
      "BySpecialityPlaceHolder": "Selecionar por Especialidade",
      "TopChampionsLabel": "Principais Campeões",
      "RecordsNotFound": "Registros não encontrados",
      "EventTypeLabel": "Tipo de Evento",
      "CountLabel": "Contagem",
      "MyRankLabel": "Minha Classificação",
      "ViewDashBoardLabel": "Exibir Painel",
      "DateofEventGridLabel": "Data do Evento",
      "EventTypeGridLabel": "Tipo",
      "RecordEventLabel": "Registre o usuário do evento",
      "MonthAndDateLabel": "Mês e data",
      "EventTypeGridLabelPlaceHolder": "Selecionar o Tipo de Evento",
      "EventTypeValidationMessage": "Selecione o tipo de evento!",
      "CountValidationMessage": "A contagem deve estar entre 1 e 5",
      "EventsSubmitMessage": "Quando terminar de adicionar eventos, clique no botão Enviar para salvar.",
      "SubmitButton": "Enviar",
      "SearchLabel": "Pesquisar",
      "ActivitiesLabel": "Atividades",
      "RegionLabel": "Região",
      "FocusAreaLabel": "Área de Foco",
      "ShowMoreLabel": "Mostrar Mais",
      "ViewActivitiesLabel": "Exibir atividades",
      "ChatIconLabel": "Chat",
      "RequestToCallLabel": "Solicitação para ligar",
      "EmailIconLabel": "Enviar um Email",
      "MeetupSubject": "Reunião individual (Solicitação de Campeão)",
      "MeetupBody": "Reserve um tempo para discutir sua área campeã e aprender mais!",
      "NoActivitiesinGridLabel": "Nenhuma Atividade Encontrada!",
      "CreateTournamentPageTitle": "Criar Campeonato",
      "CreateTournamentSuccessLabel": "Campeonato criado com êxito.",
      "TournamentNameLabel": "Nome do Campeonato",
      "TournamentNamePlaceHolderLabel": "Nome do Campeonato (Máximo de 255 caracteres)",
      "TournamentNameErrorLabel": "O Nome do Campeonato é obrigatório.",
      "TournamentDescriptionLabel": "Descrição do Campeonato",
      "TournamentDescPlaceHolderLabel": "Descrição do torneio (Máximo 500 caracteres)",
      "SelectTeamsActionsLabel": "Selecionar as Ações do Teams:",
      "TeamsActionInfoToolTip": "Selecione uma das ações do Teams disponíveis abaixo para incluir no novo campeonato. Para adicionar novas ações do campeonato para escolher, visite Gerenciar Ações de Campeonato nas Ferramentas de Administração.",
      "ActionErrorLabel": "Selecione pelo menos uma ação para criar um campeonato.",
      "CreateTournamentButton": "Criar Campeonato",
      "DuplicateTournamentNameError": "O nome do campeonato já existe. Insira outro nome para o campeonato.",
      "CreateTournamentsButton": "Crie Campeonatos",
      "SingleTournamentLabel": "Campeonato Único",
      "MultipleTournamentLabel": "Vários Campeonatos",
      "MultiTournamentStep": "Etapa",
      "MultiTournamentStep1LinkLabel": "Baixar Modelo",
      "MultiTournamentStep1Text": " de formato de arquivo de amostra",
      "MultiTournamentStep2": "Adicione detalhes do campeonato ao arquivo seguindo as diretrizes",
      "MultiTournamentStep3": "Fazer upload do arquivo",
      "UploadFileButton": "Carregar Arquivo",
      "RemoveFileLabel": "Remover Arquivo",
      "ImportSpinnerMessage": "Criando campeonatos.......",
      "ErrorMsgTournamentList": "Erro ao criar um item na lista Campeonatos. Corrija os dados e tente novamente.",
      "ErrorMsgActionsList": "Erro ao criar um item na lista Ações. Corrija os dados e tente novamente.",
      "ErrorMsgTournamentActionsList": "Ocorreu um erro ao criar um item na lista Ações de Campeonato. Corrija os dados e tente novamente.",
      "LogMsgTournamentExists": "Ignorado, pois o campeonato",
      "LogMsgTournamentExists1": "já existe.",
      "LogMsgDone": "Campeonato",
      "LogMsgDone1": "criado.",
      "LogMsgInvalidTournamentName": "Ignorado, pois ele não tem um Nome de Campeonato válido.",
      "LogMsgInvalidTemplate": "Ignorado, pois não é um modelo válido.",
      "LogMsgMultipleTournaments": "Ignorado, pois ele tem mais de um Nome de Campeonato.",
      "LogMsgBlankSheet": "Ignorado, pois está em branco.",
      "LogProgress": " Abaixo está o progresso:",
      "ImportRule1": "Não modificar os cabeçalhos de coluna no modelo",
      "ImportRule2": "Não excluir as colunas no modelo",
      "ImportRule3": "Insira os dados em todas as colunas obrigatórias (*) mencionadas no modelo",
      "ImportRule4": "Siga o limite de caracteres e o tipo mencionado no modelo para cada coluna",
      "ImportRule5": "Insira dados para apenas 1 campeonato em cada planilha de acordo com os dados de exemplo fornecidos",
      "ImportRule6": "Somente 10 campeonatos podem ser criados por vez",
      "ImportRule7": "Certifique-se de que o Nome do Campeonato é único",
      "TOTBreadcrumbLabel": "Campeonato do Teams",
      "EnableTOTSuccessMessage": "O campeonato do Teams foi habilitado com êxito. Atualize o aplicativo para continuar.",
      "EnableTOTSpinnerMessage": "Este processo levará alguns minutos para ser concluído. Não saia até ver a mensagem concluída com êxito.",
      "TOTLeaderBoardPageTitle": "Quadro de Líderes",
      "TOTMyDashboardPageTitle": "Meu Painel",
      "ManageTournamentActionsToolTip": "Acessando a Lista de Ações do Campeonato",
      "ManageTournamentActionsLabel": "Gerenciar as Ações do Campeonato",
      "ManageTournamentsLabel": "Gerenciar Campeonatos",
      "ManageAdminsToolTip": "Acessando a Lista de Administradores",
      "ManageAdminsLabel": "Gerenciar Administradores",
      "QuickLinksLabel": "Links Rápidos",
      "SpinnerListCreationMessage": "Configurando o Campeonato do Teams...",
      "ManageTournamentsPageTitle": "Gerenciar Campeonatos",
      "ManageToTLabel1": "Vários campeonatos podem ser iniciados por vez. Veja abaixo os campeonatos atuais ativos, a capacidade de concluir o campeonato, bem como a capacidade de iniciar um novo campeonato.",
      "ManageToTLabel2": "Depois que um campeonato for iniciado e concluído, ele não estará disponível para iniciar novamente; no entanto, você pode criar um novo campeonato usando as mesmas ações se quiser concluir um campeonato semelhante!",
      "EndTournamentDialogMessage": "Tem certeza de que deseja concluir o campeonato?",
      "StartTournamentDialogMessage": "Tem certeza de que deseja iniciar o novo campeonato?",
      "ConfirmLabel": "Confirmar",
      "YesButton": "Sim",
      "NoButton": "Não",
      "ActiveTournamentLabel": "Campeonatos Ativos",
      "EndTournamentButton": "Campeonato Concluído",
      "StartTournamentHeaderLabel": "Iniciar Campeonato",
      "NoTournamentMessage": "Nenhum campeonato encontrado. Verifique novamente mais tarde.",
      "SelectTournamentMessage": "Selecione pelo menos um campeonato para começar.",
      "SelectEndTournamentMessage": "Selecione um campeonato para concluir.",
      "StartTournamentButton": "Iniciar Campeonato(s)",
      "EndTournamentSuccessMessage": "Campeonato concluído com êxito.",
      "EnableTournamentSuccessMessage": "Torneio(s) iniciado(s) com êxito.",
      "CompleteTournamentSpinnerMessage": "Completando o Campeonato...",
      "EnableTournamentSpinnerMessage": "Habilitando o(s) Campeonato(s)...",
      "SearchActiveTournaments": "Pesquisar campeonatos ativos",
      "SearchPendingTournaments": "Pesquisar campeonatos para começar",
      "SelectAllLabel": "Selecionar Tudo",
      "NoSearchResults": "Não há resultados correspondentes à sua pesquisa.",
      "NoActiveParticipantsMessage": "Não há participantes ativos no momento. Seja o primeiro a participar e registrar uma atividade em Meu Painel!",
      "NoActiveTournamentMessage": "Não há nenhum campeonato ativo no momento. Verifique novamente mais tarde.",
      "TournamentLabel": "Campeonato",
      "DescriptionLabel": "Descrição",
      "NoActiveParticipantsErrorMessage": "Não há participantes ativos no momento. Seja o primeiro a participar e registrar uma atividade de ",
      "PendingActionsLabel": "Ações Pendentes",
      "PendingActionsSuccessMessage": "Não há mais ações pendentes neste campeonato.",
      "SelectActionsErrorMessage": "Selecione pelo menos uma ação para continuar.",
      "FormSavingMessage": "Salvando seus detalhes....",
      "CompletedActionsLabel": "Ações Concluídas",
      "RankLabel": "Classificar",
      "UserLabel": "Usuário",
      "MyDashboardInfoIconMessage": "Saiba mais sobre essa ação",
      "SelectTournamentPlaceHolder": "Selecionar Campeonato",
      "MyTournamentsLabel": "Meus Campeonatos",
      "OrLabel": "OU",
      "MyTournamentsTooltip": "Campeonatos ativos dos quais você já participou",
      "PointsLabel": "Pontos",
      "TournamentRankLabel": "Classificação do Campeonato",
      "ParticipantsLabel": "Participantes",
      "TournamentReportsPageTitle": "Relatório dos Campeonatos",
      "TotalActivitiesLabel": "Total de Atividades",
      "TotalPointsLabel": "Total de Pontos",
      "TotalParticipantsLabel": "Total de Participantes",
      "TotalPercentageCompletionLabel": "% do Total da Conclusão",
      "Top5ParticipantswithPointsLabel": "Os 5 Principais Participantes com Pontos",
      "Top5TournamentswithParticipantsLabel": "Os 5 Principais Campeonatos com Participantes",
      "ParticipantsStatusLabel": "Status dos participantes",
      "ParticipantsDetailsLabel": "Detalhes dos Participantes",
      "NameLabel": "Nome",
      "PercentageTournamentCompletedLabel": "% do Campeonato Concluído",
      "ActivitiesCompletedLabel": "Atividades Concluídas",
      "NoRecordsinGridLabel": "Nenhum Registro Encontrado!",
      "SearchPlaceholder": "Pesquisar por Nome do Participante",
      "NoCompletedTournamentsMessage": "Não há nenhum campeonato concluído no momento. Verifique novamente mais tarde.",
      "ReportsDropdownInfoIconText": "O relatório só pode ser gerado para campeonatos concluídos.",
      "RefreshIconInfoText": "Clique em atualizar para ver os dados mais recentes"
    }
});