define([], function () {
  return {
  "PropertyPaneDescription": "Описание",
  "BasicGroupName": "Имя группы",
  "DescriptionFieldLabel": "Поле описания",
  "SaveButton": "Сохранить",
  "BackButton": "Назад",
  "GetStartedLabel": "Начало работы",
  "AdminToolsLabel": "Средства администрирования",
  "ChampionLeaderBoardLabel": "Таблица лидеров среди чемпионов",
  "AddMemberLabel": "Добавить участника",
  "NominateMemberLabel": "Назначить участника",
  "DigitalBadgeLabel": "Цифровой значок",
  "TOTLabel": "Состязания команд",
  "ChampionListLabel": "Список чемпионов",
  "EventsListLabel": "Список событий",
  "AdminTasksLabel": "Задачи администрирования",
  "ManageDigitalBadgesLabel": "Управление цифровыми значками",
  "EnableTOTLabel": "Включить \"Состязания команд\"",
  "AddMembersToolTip": "Добавление участников Начните добавлять людей, с которыми вы будете сотрудничать в вашей...",
  "DigitalMembersToolTip": "Получите цифровой значок и примените его к изображению профиля",
  "ChampionsListToolTip": "Доступ к списку чемпионов",
  "EventsListToolTip": "Доступ к списку событий",
  "EnableTOTToolTip": "Включить \"Состязания команд\"",
  "ManageDigitalBadgesToolTip": "Управление цифровыми значками",
  "WelcomeLabel": "Добро пожаловать!",
  "ManageAppLogoLabel": "Управление логотипом приложения",
  "ManageAppLogoToolTip": "Управление логотипом приложения",
  "AppLogoToolTip": "Домашняя страница",
  "MoreInfoToolTip": "Дополнительные сведения",
  "SupportToolTip": "Поддержка",
  "FeedbackToolTip": "Обратная связь",
  "AdditionalResourcesHeaderLabel": "Дополнительные ресурсы:",
  "AdditionalResourcesContentLabel": "Группа поддержки клиентов Microsoft Teams занимается предоставлением таких решений, которые вдохновляют и помогают вам в достижении ваших целей. Следите за новостями и присоединяйтесь к этим другим ресурсам, чтобы узнать больше от нас и сообщества:",
  "M365ChampionCommunityLinkLabel": "Сообщество чемпионов Microsoft 365",
  "DrivingAdoptionLinkLabel": "Внедрение в Microsoft Technical Community",
  "CurrentVersionLabel": "Текущая версия:",
  "LatestVersionLabel": "Последняя версия:",
  "CMPGitHubLinkLabel": "GitHub",
  "VisitLabel": "Дополнительные сведения см. на страницах платформы управления чемпионами:",
  "OverviewLabel": "Обзор и информация о наших",
  "MSAdoptionHubLinkLabel": "Центр внедрения Microsoft",
  "DocumentationLabel": "Техническая документация решения и обзор архитектуры по",
  "AddMemberPageTitle": "Добавить участника",
  "NominateMemberPageTitle": "Назначить участника",
  "PeoplePickerPlaceholder": "Чтобы добавить участника, введите имя участника",
  "FocusAreaPlaceholder": "Выбор области фокусировки",
  "UserExistingMessage": "Пользователь уже является чемпионом!",
  "ChampionsListPageTitle": "Список чемпионов",
  "UserNominatedMessage": "Пользователь успешно назначен!",
  "UserAddedMessage": "Пользователь успешно добавлен!",
  "PeopleNameGridHeader": "Имя участника",
  "SelectChampion": "Выбрать чемпиона",
  "SelectAll": "Выбрать всех чемпионов",
  "FocusAreaGridHeader": "Область фокусировки",
  "CountryGridHeader": "Страна",
  "RegionLabel": "Регион",
  "StatusGridHeader": "Состояние",
  "ActionGridHeader": "Действие",
  "ApproveButton": "Утвердить",
  "RejectButton": "Отклонить",
  "NoChampionsMessage": "В данный момент нет ожидающих запросов",
  "ChampionApprovedMessage": "Запросы чемпионов одобрены.",
  "ChampionRejectedMessage": "Запросы чемпионов отклонены.",
  "ProcessingSpinnerLabel": "Обработка...",
  "DigitalBadgePageTitle": "Цифровой значок",
  "LoadingSpinnerLabel": "Загрузка...",
  "LoadingDigitalBadgeLabel": "Загрузка рамки цифрового значка",
  "DigitalBadgeAppBannerAltText": "Участники команды Майкрософт участвуют в обсуждении",
  "GroupGridHeader": "Группа",
  "ShowHideToggle": "Показать или скрыть поля списка участников",
  "ToggleView": "переключатель",
  "SelectedFocusAreaLabel": "Выбрана область фокусировки",
  "PreAcceptPageTitle": "Получите цифровой значок!",
  "PreAcceptDisclaimer": "<h2><span style='font-weight:bold;'>Добро пожаловать в служебную программу цифровых значков</span></h2>",
  "PreAcceptDisclaimer1": "В рамках участия в программе Champions вы заработали цифровой значок! Эта утилита позволит вам \"<em>заявить</em>\" свой цифровой значок, наложив его поверх существующего изображения профиля.",
  "PreAcceptDisclaimer2": "Обратите внимание, что это приведет к обновлению аватара во всех Microsoft 365 (Exchange, Teams, SharePoint и т. д.).",
  "PreAcceptDisclaimer3": "При желании <span style='font-weight:bold'>у вас будет возможность \"сохранить\" копию существующего изображения профиля</span> без наложения цифрового значка на последующих шагах. Щелкните \"Принять\", чтобы продолжить (вы можете увидеть всплывающее окно с предложением войти в систему).",
  "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>Вас приветствует служебная программа цифровых значков</span>. Участвуя в Программе чемпионов, вы можете зарабатывать цифровые значки! Эта служебная программа поможет вам <em>получить</em> цифровой значок, наложив его поверх вашего аватара. Обратите внимание, что ваш аватар изменится во всех продуктах Microsoft 365 (Exchange, Teams, SharePoint и т. д.).",
  "HowtoGetDigitalBadgeText": "Как получить значок чемпиона",
  "MultipleBadgeMessage": "Выберите значок из списка ниже. Выбранный значок будет применен к вашему аватару.",
  "NoBadgeMessage": "Не найдены значки для выбора. Обратитесь к администратору приложения.",
  "DigitalBadgeSubPageTitle": "Вот как будет выглядеть ваш цифровой значок!",
  "ProfileImageAlt": "Мой профиль, используемый в Office 365, Teams и т. д.",
  "BadgeImageAlt": "Награда в виде медали с буквой С посередине, означающей, что я участвую в Программе чемпионов",
  "NoProfileImageAlt": "Силуэт человека, означающий, что изображение профиля в настоящее время не применяется к вашей учетной записи.",
  "ApplyButtonText": "Применить изображение",
  "ApplyButtonAriaDescription": "Нажимая эту кнопку, вы даете веб-части Программы чемпионов разрешение на обновление изображения вашего профиля от вашего имени.",
  "ApplyButton": "Применить",
  "DownloadButtonText": "Скачать",
  "DownloadButtonAriaDescription": "Щелкните, чтобы скачать текущее изображение профиля",
  "DownloadingButtonText": "Скачивание…",
  "DownloadedButtonText": "Скачано",
  "DownloadedButtonSecondaryText": "Скачанные изображения профиля можно найти в папке \"Загрузки\" вашего устройства.",
  "DownloadButtonSecondaryText": "Скачать текущее изображение профиля",
  "PreApplyDisclaimer": "Это предварительный просмотр вашего нового изображения профиля, включая цифровой значок. Если вы хотите скачать существующее изображение профиля перед применением цифрового значка, щелкните ссылку \"<strong>Загрузить текущее изображение профиля</strong>\".",
  "PreApplyDisclaimer1": "Щелкнув \"Применить изображение\" вы обновите изображение профиля Microsoft 365 этим новым изображением. <strong>Обратите внимание, что изображение профиля будет обновлено во всех Microsoft 365, и это нельзя будет отменить на этой странице</strong>.",
  "PreApplyDisclaimer2": "Если вы хотите вернуть свое изображение, вы можете использовать <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' id='linkToChangeProfileImage'>веб-приложение Outlook</a>.",
  "NoProfileImageDescription": "Если вы уже связали изображение со своим профилем и все еще видите это сообщение, возможно, ваше изображение еще недоступно. Повторите попытку позже или свяжитесь с <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>справочная служба</a>, если она по-прежнему не отображается через 24 часа.",
  "AcceptButtonText": "Принять",
  "AcceptButtonAriaDescription": "Нажимая эту кнопку, вы даете веб-части Программы чемпионов разрешение на обновление изображения вашего профиля от вашего имени.",
  "UnauthorizedText": "В настоящее время вы не соответствуете требованиям для участия в программе \"Значок чемпиона\".",
  "ApplySpinnerLabel": "Применение нового образа профиля к вашей учетной записи...",
  "DigitalBadgeSuccessMessage": "<strong>Поздравляем!</strong> Вы успешно запросили цифровой значок, и ваш аватар обновлен. Подождите до 24 часов, чтобы увидеть обновление, отраженное во всех приложениях Microsoft 365 (включая Teams).",
  "BadgePointsTooltip": "Количество баллов, необходимое для разблокировки:",
  "CMPSideBarPointsLabel": "Баллы",
  "CMPSideBarGlobalRankLabel": "Глобальный рейтинг",
  "CMPSideBarChampionsLabel": "Чемпионы",
  "FirstNameLabel": "Имя",
  "LastNameLabel": "Фамилия",
  "EmailIDLabel": "ИД электронной почты",
  "BecomeChampionLabel": "Станьте чемпионом",
  "ChampionSubmissionPendingLabel": "Запрос чемпиона в работе",
  "ChampionRequestSubmitSuccessMessage": "Запрос чемпиона успешно отправлен",
  "PivotHeaderGlobal": "Глобально",
  "PivotHeaderNearMe": "Рядом со мной",
  "PivotHeaderBySpeciality": "По специализации",
  "NearMePlaceHolder": "Выбрать рядом со мной",
  "BySpecialityPlaceHolder": "Выбрать по специализации",
  "TopChampionsLabel": "Лучшие чемпионы",
  "RecordsNotFound": "Записи не найдены",
  "EventTypeLabel": "Тип события",
  "CountLabel": "Количество",
  "MyRankLabel": "Мой рейтинг",
  "SelectDate": "Выберите дату",
  "NotesPlaceholder": "Не более 200 символов",
  "EventSubmissionPendingMessage": "События отправлены на утверждение. Баллы будут присвоены после утверждения событий.",
  "EventsSubmissionSuccessMessage": "События успешно записаны.",
  "ViewDashBoardLabel": "Просмотр панели мониторинга",
  "DateofEventGridLabel": "Дата события",
  "EventTypeGridLabel": "Тип",
  "RecordEventLabel": "Записать событие",
  "MonthAndDateLabel": "Месяц и день",
  "EventTypeGridLabelPlaceHolder": "Выберите тип события",
  "EventTypeValidationMessage": "Выберите тип события",
  "CountValidationMessage": "Количество должно быть от 1 до 5",
  "EventsSubmitMessage": "По завершении добавления событий нажмите кнопку \"Отправить\", чтобы сохранить.",
  "SubmitButton": "Отправить",
  "SearchLabel": "Поиск лучших чемпионов",
  "ActivitiesLabel": "Действия",
  "FocusAreaLabel": "Область фокусировки",
  "ShowMoreLabel": "Показать еще",
  "ViewActivitiesLabel": "Просмотреть действия",
  "ChatIconLabel": "Чат",
  "RequestToCallLabel": "Запланировать синхронизацию",
  "EmailIconLabel": "Отправить сообщение электронной почты",
  "MeetupSubject": "1:1 (Запрос чемпиона)",
  "MeetupBody": "Выделите время, чтобы обсудить вашу область чемпиона и узнать больше!",
  "NoActivitiesinGridLabel": "Действия не найдены!",
  "CreateTournamentPageTitle": "Создать турнир",
  "CreateTournamentSuccessLabel": "Турнир успешно создан.",
  "TournamentNameLabel": "Название турнира",
  "TournamentNamePlaceHolderLabel": "Название турнира (максимум 255 символов)",
  "TournamentNameErrorLabel": "Необходимо указать название турнира.",
  "TournamentDescriptionLabel": "Описание турнира",
  "TournamentDescPlaceHolderLabel": "Описание турнира (не более 500 символов)",
  "SelectTeamsActionsLabel": "Выберите действия Teams:",
  "TeamsActionInfoToolTip": "Выберите из доступных ниже действий команд, чтобы включить их в новый турнир. Чтобы добавить для выбора новые турнирные действия, перейдите в раздел \"Управление действиями турнира\" в Инструментах администратора.",
  "ActionErrorLabel": "Выберите хотя бы одно действие, чтобы создать турнир.",
  "CreateTournamentButton": "Создать турнир",
  "DuplicateTournamentNameError": "Имя турнира уже существует. Введите другое имя турнира.",
  "CreateTournamentsButton": "Создание турниров",
  "SingleTournamentLabel": "Одиночный турнир",
  "MultipleTournamentLabel": "Множественные турниры",
  "MultiTournamentStep": "Шаг",
  "MultiTournamentStep1LinkLabel": "Скачать шаблон",
  "MultiTournamentStep1Text": " примера формата файла",
  "MultiTournamentStep2": "Добавьте сведения о турнире в файл, выполнив инструкции",
  "MultiTournamentStep3": "Выгрузить файл",
  "UploadFileButton": "Выгрузить файл",
  "RemoveFileLabel": "Удалить файл",
  "ImportSpinnerMessage": "Создание турниров...",
  "ErrorMsgTournamentList": "Произошла ошибка при создании элемента в списке турниров. Исправьте данные и повторите попытку.",
  "ErrorMsgActionsList": "Произошла ошибка при создании элемента в списке действий. Исправьте данные и повторите попытку.",
  "ErrorMsgTournamentActionsList": "Произошла ошибка при создании элемента в списке действий турнира. Исправьте данные и повторите попытку.",
  "LogMsgTournamentExists": "Пропущено, так как турнир",
  "LogMsgTournamentExists1": "уже существует.",
  "LogMsgDone": "Турнир",
  "LogMsgDone1": "создан.",
  "LogMsgInvalidTournamentName": "Пропущено, так как у него нет допустимого имени турнира.",
  "LogMsgInvalidTemplate": "Пропущено, так как он не является допустимым шаблоном.",
  "LogMsgMultipleTournaments": "Пропущено, так как оно содержит более одного имени турнира.",
  "LogMsgBlankSheet": "Пропущено, так как оно пустое.",
  "LogProgress": " Ниже приведен ход выполнения:",
  "ImportRule1": "Не изменять заголовки столбцов в шаблоне",
  "ImportRule2": "Не удалять столбцы в шаблоне",
  "ImportRule3": "Введите данные во всех обязательных (*) столбцах, упомянутых в шаблоне",
  "ImportRule4": "Соблюдайте лимит символов и введите указанные в шаблоне для каждого столбца.",
  "ImportRule5": "Введите данные только для 1 турнира на каждом листе согласно представленному образцу данных",
  "ImportRule6": "Одновременно можно создать только 10 турниров",
  "ImportRule7": "Убедитесь, что название турнира уникально",
  "TOTBreadcrumbLabel": "Состязания команд",
  "EnableTOTSuccessMessage": "\"Состязания команд\" включено. Обновите приложение, чтобы продолжить.",
  "EnableTOTSpinnerMessage": "Этот процесс займет несколько минут. Пожалуйста, не уходите, пока не увидите сообщение об успешном завершении.",
  "TOTLeaderBoardPageTitle": "Доска лидеров",
  "TOTMyDashboardPageTitle": "Моя панель мониторинга",
  "ManageTournamentActionsToolTip": "Доступ к списку действий турнира",
  "ManageTournamentActionsLabel": "Управление действиями турнира",
  "ManageTournamentsLabel": "Управление турнирами",
  "ManageAdminsToolTip": "Доступ к списку администраторов",
  "ManageAdminsLabel": "Управление администраторами",
  "QuickLinksLabel": "Быстрые ссылки",
  "SpinnerListCreationMessage": "Настройка \"Состязания команд\"...",
  "ManageTournamentsPageTitle": "Управление турнирами",
  "ManageToTLabel1": "Одновременно можно начать несколько турниров. Ниже отображаются активные турниры, возможность завершить турнир, а также возможность начать новый турнир.",
  "ManageToTLabel2": "После начала и завершения турнира он будет недоступен для повторного запуска; однако если вы хотите завершить похожий турнир, то можете создать новый, выполнив те же действия.",
  "EndTournamentDialogMessage": "Вы действительно хотите завершить турнир?",
  "StartTournamentDialogMessage": "Действительно начать новые турниры?",
  "ConfirmLabel": "Подтвердить",
  "YesButton": "Да",
  "NoButton": "Нет",
  "ActiveTournamentLabel": "Активные турниры",
  "EndTournamentButton": "Завершить турнир",
  "StartTournamentHeaderLabel": "Начать турнир",
  "NoTournamentMessage": "Турниры не найдены. Вернитесь сюда позже.",
  "SelectTournamentMessage": "Выберите хотя бы один турнир, чтобы начать.",
  "SelectEndTournamentMessage": "Выберите турнир для завершения.",
  "StartTournamentButton": "Запустить турниры",
  "EndTournamentSuccessMessage": "Турнир успешно завершен.",
  "EnableTournamentSuccessMessage": "Турниры успешно запущены.",
  "CompleteTournamentSpinnerMessage": "Завершение турнира...",
  "EnableTournamentSpinnerMessage": "Включение турниров...",
  "SearchActiveTournaments": "Поиск активных турниров",
  "SearchPendingTournaments": "Поиск турниров для начала",
  "SelectAllLabel": "Выбрать все",
  "NoSearchResults": "Нет результатов, соответствующих вашему запросу.",
  "NoActiveParticipantsMessage": "На данный момент активных участников нет. Будьте первым, кто примет участие и зарегистрирует активность в Личном кабинете!",
  "NoActiveTournamentMessage": "В данный момент нет активных турниров. Вернитесь сюда позже.",
  "TournamentLabel": "Турнир",
  "DescriptionLabel": "Описание",
  "NoActiveParticipantsErrorMessage": "На данный момент активных участников нет. Будьте первым, кто примет участие и зарегистрирует активность от ",
  "PendingActionsLabel": "Ожидающие выполнения действия",
  "PendingActionsSuccessMessage": "В этом турнире больше нет ожидающих выполнения действий.",
  "SelectActionsErrorMessage": "Выберите хотя бы одно действие, чтобы продолжить.",
  "FormSavingMessage": "Сохранение сведений....",
  "CompletedActionsLabel": "Завершенные действия",
  "RankLabel": "Рейтинг",
  "UserLabel": "Пользователь",
  "MyDashboardInfoIconMessage": "Подробнее об этом действии",
  "SelectTournamentPlaceHolder": "Выбор турнира",
  "MyTournamentsLabel": "Мои турниры",
  "OrLabel": "ИЛИ",
  "MyTournamentsTooltip": "Активные турниры, в которых вы уже участвовали",
  "PointsLabel": "Баллы",
  "TournamentRankLabel": "Рейтинг турнира",
  "ParticipantsLabel": "Участники",
  "TournamentReportsPageTitle": "Отчет о турнирах",
  "TotalActivitiesLabel": "Всего действий",
  "TotalPointsLabel": "Сумма баллов",
  "TotalParticipantsLabel": "Всего участников",
  "TotalPercentageCompletionLabel": "% от общего завершения",
  "Top5ParticipantswithPointsLabel": "5 лучших участников с баллами",
  "Top5TournamentswithParticipantsLabel": "Пять лучших турниров с участниками",
  "ParticipantsStatusLabel": "Состояние участников",
  "ParticipantsDetailsLabel": "Сведения об участниках",
  "NameLabel": "Имя",
  "PercentageTournamentCompletedLabel": "% турнира завершено",
  "ActivitiesCompletedLabel": "Действия завершены",
  "NoRecordsinGridLabel": "Записи не найдены!",
  "SearchPlaceholder": "Поиск по имени участника",
  "NoCompletedTournamentsMessage": "В данный момент нет завершенных турниров. Вернитесь сюда позже.",
  "ReportsDropdownInfoIconText": "Отчет можно создать только для завершенных турниров.",
  "RefreshIconInfoText": "Нажмите кнопку \"Обновить\", чтобы просмотреть последние данные",
  "EventApprovedMessage": "Событие(я) чемпиона утверждены.",
  "EventRejectedMessage": "Событие(я) чемпиона отклонены.",
  "SelectAllEvents": "Выбрать все события",
  "SelectEvent": "Выберите событие",
  "ChampionLabel": "Чемпион",
  "EmailLabel": "Электронная почта",
  "EventLabel": "Событие",
  "DateLabel": "Дата",
  "NotesLabel": "Заметки",
  "SuccessIcon": "Значок успеха",
  "PendingEventsSearchboxPlaceholder": "Поиск по имени или по адресу электронной почты чемпиона",
  "NoRecordsIcon": "Записи не найдены",
  "NoPendingEventsLabel": "В данный момент нет событий в ожидании.",
  "ChampionActivitiesLabel": "Действия с чемпионом",
  "ManageConfigSettingsLabel": "Управление параметрами конфигурации",
  "ApproveChampionSearchboxPlaceholder": "Поиск по имени или по адресу электронной почты участника",
  "EventsApprovalInfoIconTooltipContent": "Включение этого параметра потребует утверждения администратором заявок на события, отправленные чемпионами. Баллы за события будут начисляться только после утверждения.",
  "ConfigSettingsSaved": "Параметры конфигурации сохранены.",
  "EventApprovalsEnableLabel": "Разрешить утверждение событий чемпиона",
  "EventsSelectedLabel": "Выбраны события.",
  "ChampionsSelectedLabel": "Выбраны чемпионы.",
  "ToggleLabelForMemberListColumns": "Показать или скрыть поля списка участников",
  "TooltipContentForMemberListFieldsHeading": "Показать или скрыть поля списка участников во всех компонентах приложения, где это возможно.",
  "ChampionReportLabel": "Отчет Champions",
  "ChampionReportToolTip": "Отчет Champions",
  "TotalChampionsLabel": "Все чемпионы",
  "ClearButton": "Очистить",
  "FilterbyDateLabel": "Фильтр по дате",
  "EventTypesHeading": "Типы событий",
  "NoEventsMessage": "В данный момент нет завершенных событий. Вернитесь сюда позже.",
  "NoEventsFoundMessage": "События не найдены!",
  "AppTitleLabel": "Название приложения",
  "AppTitleErrorLabel": "Требуется название приложения.",
  "AppTitlePlaceholderText": "Не более 30 символов",
  "AppTitleInfoIconText": "Название приложения будет отображаться в разделе заголовка и разделах навигации приложения",
  "AboutContentLabel": "создано с помощью менеджеров организации и специалистов по внедрению. По отзывам Сообщества чемпионов Microsoft 365, это приложение было разработано, чтобы предоставить платформу для создания и поддержки ваших собственных сообществ. Начиная с вдохновения и заканчивая исполнением, мы помогаем вам достичь большего в ваших собственных сообществах!",
  "AboutHeaderLabel": "Сведения о",
  "DashboardLabel": "Панель мониторинга",
  "RemoveEventLabel": "Удалить событие",
  "AddEventLabel": "Добавить событие",
  "EventChartLabel": "10 основных событий с типами событий",
  "FromLabel": "С",
  "ToLabel": "До",
  "AllTime": "Все время",
  "LastMonth": "Прошлый месяц",
  "Last3Months": "Последние 3 месяца",
  "Last6Months": "Последние 6 месяцев",
  "Last1Year": "Последний год",
  "SelectaCustomDate": "Выбрать настраиваемую дату",
  "championRecordsFoundLabel": "Найдены записи чемпиона",
  "digitalBadgeProfileAriaLabel": "Открыть веб-приложение Outlook в новой вкладке или окне браузера",
  "AddMemberAsAdminLabel": "Добавить участника в качестве администратора",
  "NoteValidationMessage": "Длина заметок не должна превышать 200 символов",
  "CloseInfoPopoverButton": "Закрыть"
  }
});
