define([], function () {
  return {
    "AboutContentLabel": "Наша Платформа управления чемпионами была создана с помощью менеджеров организации и специалистов по внедрению. По отзывам Сообщества чемпионов Microsoft 365, это приложение было разработано, чтобы предоставить платформу для создания и поддержки ваших собственных сообществ. Начиная с вдохновения и заканчивая исполнением, мы помогаем вам достичь большего в ваших собственных сообществах!",
    "AboutHeaderLabel": "О платформе управления чемпионами:",
    "AcceptButtonAriaDescription": "Нажимая эту кнопку, вы даете веб-части Программы чемпионов разрешение на обновление изображения вашего профиля от вашего имени.",
    "AcceptButtonText": "Принять",
    "ActionErrorLabel": "Выберите хотя бы одно действие, чтобы создать турнир.",
    "ActionGridHeader": "Действие",
    "ActiveTournamentLabel": "Активные турниры",
    "ActivitiesCompletedLabel": "Действия завершены",
    "ActivitiesLabel": "Действия",
    "AdditionalResourcesContentLabel": "Группа поддержки клиентов Microsoft Teams занимается предоставлением таких решений, которые вдохновляют и помогают вам в достижении ваших целей. Следите за новостями и присоединяйтесь к этим другим ресурсам, чтобы узнать больше от нас и сообщества:",
    "AdditionalResourcesHeaderLabel": "Дополнительные ресурсы:",
    "AddMemberLabel": "Добавить участника",
    "AddMemberPageTitle": "Добавить участника",
    "AddMembersToolTip": "Добавление участников Начните добавлять людей, с которыми вы будете сотрудничать в вашей...",
    "AdminTasksLabel": "Задачи администрирования",
    "AdminToolsLabel": "Средства администрирования",
    "AppHeaderTitleLabel": "Платформа управления чемпионами",
    "AppLogoToolTip": "Домашняя страница",
    "ApplyButton": "Применить",
    "ApplyButtonAriaDescription": "Нажимая эту кнопку, вы даете веб-части Программы чемпионов разрешение на обновление изображения вашего профиля от вашего имени.",
    "ApplyButtonText": "Применить изображение",
    "ApplySpinnerLabel": "Применение нового образа профиля к вашей учетной записи...",
    "ApproveButton": "Утвердить",
    "ApproveChampionSearchboxPlaceholder": "Поиск по имени или по адресу электронной почты участника",
    "BackButton": "Назад",
    "BadgeImageAlt": "Награда в виде медали с буквой С посередине, означающей, что я участвую в Программе чемпионов",
    "BadgePointsTooltip": "Количество баллов, необходимое для разблокировки:",
    "BasicGroupName": "Имя группы",
    "BecomeChampionLabel": "Станьте чемпионом",
    "BySpecialityPlaceHolder": "Выбрать по специализации",
    "ChampionActivitiesLabel": "Действия с чемпионом",
    "ChampionApprovedMessage": "Запросы чемпионов одобрены.",
    "ChampionLabel": "Чемпион",
    "ChampionLeaderBoardLabel": "Таблица лидеров среди чемпионов",
    "ChampionListLabel": "Список чемпионов",
    "ChampionRejectedMessage": "Запросы чемпионов отклонены.",
    "ChampionRequestSubmitSuccessMessage": "Запрос чемпиона успешно отправлен",
    "ChampionsListPageTitle": "Список чемпионов",
    "ChampionsListToolTip": "Доступ к списку чемпионов",
    "ChampionsSelectedLabel": "Выбраны чемпионы.",
    "ChampionSubmissionPendingLabel": "Запрос чемпиона в работе",
    "ChatIconLabel": "Чат",
    "CMPBreadcrumbLabel": "Платформа управления чемпионами",
    "CMPGitHubLinkLabel": "GitHub",
    "CMPSideBarChampionsLabel": "Чемпионы",
    "CMPSideBarGlobalRankLabel": "Глобальный рейтинг",
    "CMPSideBarPointsLabel": "Баллы",
    "CompletedActionsLabel": "Завершенные действия",
    "CompleteTournamentSpinnerMessage": "Завершение турнира...",
    "ConfigSettingsSaved": "Параметры конфигурации сохранены.",
    "ConfirmLabel": "Подтвердить",
    "CountLabel": "Количество",
    "CountryGridHeader": "Страна",
    "CountryPlaceholder": "Выберите страну",
    "CountValidationMessage": "Количество должно быть от 1 до 5",
    "CreateTournamentButton": "Создать турнир",
    "CreateTournamentPageTitle": "Создать турнир",
    "CreateTournamentsButton": "Создание турниров",
    "CreateTournamentSuccessLabel": "Турнир успешно создан.",
    "CurrentVersionLabel": "Текущая версия:",
    "DateLabel": "Дата",
    "DateofEventGridLabel": "Дата события",
    "DescriptionFieldLabel": "Поле описания",
    "DescriptionLabel": "Описание",
    "DigitalBadgeAppBannerAltText": "Участники команды Майкрософт участвуют в обсуждении",
    "DigitalBadgeLabel": "Цифровой значок",
    "DigitalBadgePageTitle": "Цифровой значок",
    "DigitalBadgeSubPageTitle": "Вот как будет выглядеть ваш цифровой значок!",
    "DigitalBadgeSuccessMessage": "<strong>Поздравляем!</strong> Вы успешно запросили цифровой значок, и ваш аватар обновлен. Подождите до 24 часов, чтобы увидеть обновление, отраженное во всех приложениях Microsoft 365 (включая Teams).",
    "DigitalMembersToolTip": "Получите цифровой значок и примените его к изображению профиля",
    "DocumentationLabel": "Техническая документация решения и обзор архитектуры по",
    "DownloadButtonAriaDescription": "Щелкните, чтобы скачать текущее изображение профиля",
    "DownloadButtonSecondaryText": "Скачать текущее изображение профиля",
    "DownloadButtonText": "Скачать",
    "DownloadedButtonSecondaryText": "Скачанные изображения профиля можно найти в папке \"Загрузки\" вашего устройства.",
    "DownloadedButtonText": "Скачано",
    "DownloadingButtonText": "Скачивание…",
    "DrivingAdoptionLinkLabel": "Внедрение в Microsoft Technical Community",
    "DuplicateTournamentNameError": "Имя турнира уже существует. Введите другое имя турнира.",
    "EmailIconLabel": "Отправить сообщение электронной почты",
    "EmailIDLabel": "ИД электронной почты",
    "EmailLabel": "Электронная почта",
    "EnableTOTLabel": "Включить \"Состязания команд\"",
    "EnableTOTSpinnerMessage": "Этот процесс займет несколько минут. Пожалуйста, не уходите, пока не увидите сообщение об успешном завершении.",
    "EnableTOTSuccessMessage": "\"Состязания команд\" включено. Обновите приложение, чтобы продолжить.",
    "EnableTOTToolTip": "Включить \"Состязания команд\"",
    "EnableTournamentSpinnerMessage": "Включение турниров...",
    "EnableTournamentSuccessMessage": "Турниры успешно запущены.",
    "EndTournamentButton": "Завершить турнир",
    "EndTournamentDialogMessage": "Вы действительно хотите завершить турнир?",
    "EndTournamentSuccessMessage": "Турнир успешно завершен.",
    "ErrorMsgActionsList": "Произошла ошибка при создании элемента в списке действий. Исправьте данные и повторите попытку.",
    "ErrorMsgTournamentActionsList": "Произошла ошибка при создании элемента в списке действий турнира. Исправьте данные и повторите попытку.",
    "ErrorMsgTournamentList": "Произошла ошибка при создании элемента в списке турниров. Исправьте данные и повторите попытку.",
    "EventApprovalsEnableLabel": "Разрешить утверждение событий чемпиона",
    "EventApprovedMessage": "Событие(я) чемпиона утверждены.",
    "EventLabel": "Событие",
    "EventRejectedMessage": "Событие(я) чемпиона отклонены.",
    "EventsApprovalInfoIconTooltipContent": "Включение этого параметра потребует утверждения администратором заявок на события, отправленные чемпионами. Баллы за события будут начисляться только после утверждения.",
    "EventsListLabel": "Список событий",
    "EventsListToolTip": "Доступ к списку событий",
    "EventsSelectedLabel": "Выбраны события.",
    "EventsSubmissionSuccessMessage": "События успешно записаны.",
    "EventsSubmitMessage": "По завершении добавления событий нажмите кнопку \"Отправить\", чтобы сохранить.",
    "EventsTrackListLabel": "Список отслеживания событий",
    "EventSubmissionPendingMessage": "События отправлены на утверждение. Баллы будут присвоены после утверждения событий.",
    "EventTrackListToolTip": "Доступ к списку отслеживания событий",
    "EventTypeGridLabel": "Тип",
    "EventTypeGridLabelPlaceHolder": "Выберите тип события",
    "EventTypeLabel": "Тип события",
    "EventTypeValidationMessage": "Выберите тип события",
    "FeedbackToolTip": "Обратная связь",
    "FirstNameLabel": "Имя",
    "FocusAreaGridHeader": "Область фокусировки",
    "FocusAreaLabel": "Область фокусировки",
    "FocusAreaPlaceholder": "Выбор области фокусировки",
    "FormSavingMessage": "Сохранение сведений....",
    "GetStartedLabel": "Начало работы",
    "GroupGridHeader": "Группа",
    "GroupPlaceholder": "Выберите группу",
    "HowtoGetDigitalBadgeText": "Как получить значок чемпиона",
    "ImportRule1": "Не изменять заголовки столбцов в шаблоне",
    "ImportRule2": "Не удалять столбцы в шаблоне",
    "ImportRule3": "Введите данные во всех обязательных (*) столбцах, упомянутых в шаблоне",
    "ImportRule4": "Соблюдайте лимит символов и введите указанные в шаблоне для каждого столбца.",
    "ImportRule5": "Введите данные только для 1 турнира на каждом листе согласно представленному образцу данных",
    "ImportRule6": "Одновременно можно создать только 10 турниров",
    "ImportRule7": "Убедитесь, что название турнира уникально",
    "ImportSpinnerMessage": "Создание турниров...",
    "LastNameLabel": "Фамилия",
    "LatestVersionLabel": "Последняя версия:",
    "LoadingSpinnerLabel": "Загрузка...",
    "LogMsgBlankSheet": "Пропущено, так как оно пустое.",
    "LogMsgDone": "Турнир",
    "LogMsgDone1": "создан.",
    "LogMsgInvalidTemplate": "Пропущено, так как он не является допустимым шаблоном.",
    "LogMsgInvalidTournamentName": "Пропущено, так как у него нет допустимого имени турнира.",
    "LogMsgMultipleTournaments": "Пропущено, так как оно содержит более одного имени турнира.",
    "LogMsgTournamentExists": "Пропущено, так как турнир",
    "LogMsgTournamentExists1": "уже существует.",
    "LogProgress": " Ниже приведен ход выполнения:",
    "M365ChampionCommunityLinkLabel": "Сообщество чемпионов Microsoft 365",
    "ManageAdminsLabel": "Управление администраторами",
    "ManageAdminsToolTip": "Доступ к списку администраторов",
    "ManageAppLogoLabel": "Управление логотипом приложения",
    "ManageAppLogoToolTip": "Управление логотипом приложения",
    "ManageConfigSettingsLabel": "Управление параметрами конфигурации",
    "ManageDigitalBadgesLabel": "Управление цифровыми значками",
    "ManageDigitalBadgesToolTip": "Управление цифровыми значками",
    "ManageToTLabel1": "Одновременно можно начать несколько турниров. Ниже отображаются активные турниры, возможность завершить турнир, а также возможность начать новый турнир.",
    "ManageToTLabel2": "После начала и завершения турнира он будет недоступен для повторного запуска; однако если вы хотите завершить похожий турнир, то можете создать новый, выполнив те же действия.",
    "ManageTournamentActionsLabel": "Управление действиями турнира",
    "ManageTournamentActionsToolTip": "Доступ к списку действий турнира",
    "ManageTournamentsLabel": "Управление турнирами",
    "ManageTournamentsPageTitle": "Управление турнирами",
    "MeetupBody": "Выделите время, чтобы обсудить вашу область чемпиона и узнать больше!",
    "MeetupSubject": "1:1 (Запрос чемпиона)",
    "MonthAndDateLabel": "Месяц и день",
    "MoreInfoToolTip": "Дополнительные сведения",
    "MSAdoptionHubLinkLabel": "Центр внедрения Microsoft",
    "MultipleBadgeMessage": "Выберите значок из списка ниже. Выбранный значок будет применен к вашему аватару.",
    "MultipleTournamentLabel": "Множественные турниры",
    "MultiTournamentStep": "Шаг",
    "MultiTournamentStep1LinkLabel": "Скачать шаблон",
    "MultiTournamentStep1Text": " примера формата файла",
    "MultiTournamentStep2": "Добавьте сведения о турнире в файл, выполнив инструкции",
    "MultiTournamentStep3": "Выгрузить файл",
    "MyDashboardInfoIconMessage": "Подробнее об этом действии",
    "MyRankLabel": "Мой рейтинг",
    "MyTournamentsLabel": "Мои турниры",
    "MyTournamentsTooltip": "Активные турниры, в которых вы уже участвовали",
    "NameLabel": "Имя",
    "NearMePlaceHolder": "Выбрать рядом со мной",
    "NoActiveParticipantsErrorMessage": "На данный момент активных участников нет. Будьте первым, кто примет участие и зарегистрирует активность от ",
    "NoActiveParticipantsMessage": "На данный момент активных участников нет. Будьте первым, кто примет участие и зарегистрирует активность в Личном кабинете!",
    "NoActiveTournamentMessage": "В данный момент нет активных турниров. Вернитесь сюда позже.",
    "NoActivitiesinGridLabel": "Действия не найдены!",
    "NoBadgeMessage": "Не найдены значки для выбора. Обратитесь к администратору приложения.",
    "NoButton": "Нет",
    "NoChampionsMessage": "В данный момент нет ожидающих запросов",
    "NoCompletedTournamentsMessage": "В данный момент нет завершенных турниров. Вернитесь сюда позже.",
    "NominateMemberLabel": "Назначить участника",
    "NominateMemberPageTitle": "Назначить участника",
    "NoPendingEventsLabel": "В данный момент нет событий в ожидании.",
    "NoProfileImageAlt": "Силуэт человека, означающий, что изображение профиля в настоящее время не применяется к вашей учетной записи.",
    "NoProfileImageDescription": "Если вы уже связали изображение со своим профилем и все еще видите это сообщение, возможно, ваше изображение еще недоступно. Повторите попытку позже или свяжитесь с <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>справочная служба</a>, если она по-прежнему не отображается через 24 часа.",
    "NoRecordsIcon": "Записи не найдены",
    "NoRecordsinGridLabel": "Записи не найдены!",
    "NoSearchResults": "Нет результатов, соответствующих вашему запросу.",
    "NotesLabel": "Заметки",
    "NotesPlaceholder": "Не более 200 символов",
    "NoTournamentMessage": "Турниры не найдены. Вернитесь сюда позже.",
    "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>Вас приветствует служебная программа цифровых значков</span>. Участвуя в Программе чемпионов, вы можете зарабатывать цифровые значки! Эта служебная программа поможет вам <em>получить</em> цифровой значок, наложив его поверх вашего аватара. Обратите внимание, что ваш аватар изменится во всех продуктах Microsoft 365 (Exchange, Teams, SharePoint и т. д.).",
    "OrLabel": "ИЛИ",
    "OverviewLabel": "Обзор и информация о наших",
    "ParticipantsDetailsLabel": "Сведения об участниках",
    "ParticipantsLabel": "Участники",
    "ParticipantsStatusLabel": "Состояние участников",
    "PendingActionsLabel": "Ожидающие выполнения действия",
    "PendingActionsSuccessMessage": "В этом турнире больше нет ожидающих выполнения действий.",
    "PendingEventsSearchboxPlaceholder": "Поиск по имени или по адресу электронной почты чемпиона",
    "PeopleNameGridHeader": "Имя участника",
    "PeoplePickerPlaceholder": "Чтобы добавить участника, введите имя участника",
    "PercentageTournamentCompletedLabel": "% турнира завершено",
    "PivotHeaderBySpeciality": "По специализации",
    "PivotHeaderGlobal": "Глобально",
    "PivotHeaderNearMe": "Рядом со мной",
    "PointsLabel": "Баллы",
    "PreAcceptDisclaimer": "<span style='font-weight:bold;'>Вас приветствует служебная программа цифровых значков</span> <br/><br/> <span>Вы заработали цифровой значок, участвуя в Программе чемпионов! Эта служебная программа поможет вам <em>получить</em> цифровой значок, наложив его поверх вашего аватара. <br/><br/> Обратите внимание, что ваш аватар изменится во всех продуктах Microsoft 365 (Exchange, Teams, SharePoint и т. д.).</span>",
    "PreAcceptDisclaimer2": "При желании <span style='font-weight:bold;'>у вас будет возможность \"сохранить\" копию существующего изображения профиля</span> без наложения цифрового значка на последующих шагах. Нажмите \"Принять\", чтобы продолжить (вы можете увидеть всплывающее окно с запросом на вход).",
    "PreAcceptPageTitle": "Получите цифровой значок!",
    "PreApplyDisclaimer": "Это предварительный просмотр вашего нового изображения профиля, включая цифровой значок. Если вы хотите загрузить существующее изображение профиля перед применением цифрового значка, нажмите ссылку <strong>Загрузить текущее изображение профиля</strong>.<br />",
    "PreApplyDisclaimer1": "<br />Нажатие «Применить изображение» заменит изображение вашего профиля Microsoft 365 новым изображением. <strong>Обратите внимание, что при этом изображение вашего профиля будет обновлено во всех приложениях Microsoft 365, и его нельзя отменить на этой странице</strong>. <br/><br/>Если вы хотите вернуть свое изображение обратно, вы можете использовать <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank ' aria-label='Откройте веб-приложение Outlook в новой вкладке или окне браузера'>Веб-приложение Outlook</a>.",
    "ProcessingSpinnerLabel": "Обработка...",
    "ProfileImageAlt": "Мой профиль, используемый в Office 365, Teams и т. д.",
    "PropertyPaneDescription": "Описание",
    "QuickLinksLabel": "Быстрые ссылки",
    "RankLabel": "Рейтинг",
    "RecordEventLabel": "Записать событие",
    "RecordsNotFound": "Записи не найдены",
    "RefreshIconInfoText": "Нажмите кнопку \"Обновить\", чтобы просмотреть последние данные",
    "RegionGridHeader": "Регион",
    "RegionLabel": "Регион",
    "RegionPlaceholder": "Выберите регион",
    "RejectButton": "Отклонить",
    "RemoveFileLabel": "Удалить файл",
    "ReportsDropdownInfoIconText": "Отчет можно создать только для завершенных турниров.",
    "RequestToCallLabel": "Запрос на звонок",
    "SaveButton": "Сохранить",
    "SearchActiveTournaments": "Поиск активных турниров",
    "SearchLabel": "Поиск",
    "SearchPendingTournaments": "Поиск турниров для начала",
    "SearchPlaceholder": "Поиск по имени участника",
    "SelectActionsErrorMessage": "Выберите хотя бы одно действие, чтобы продолжить.",
    "SelectAll": "Выбрать всех чемпионов",
    "SelectAllEvents": "Выбрать все события",
    "SelectAllLabel": "Выбрать все",
    "SelectChampion": "Выбрать чемпиона",
    "SelectDate": "Выберите дату",
    "SelectEndTournamentMessage": "Выберите турнир для завершения.",
    "SelectEvent": "Выберите событие",
    "SelectTeamsActionsLabel": "Выберите действия Teams:",
    "SelectTournamentMessage": "Выберите хотя бы один турнир, чтобы начать.",
    "SelectTournamentPlaceHolder": "Выбор турнира",
    "ShowMoreLabel": "Показать еще",
    "SingleTournamentLabel": "Одиночный турнир",
    "SpinnerListCreationMessage": "Настройка \"Состязания команд\"...",
    "StartTournamentButton": "Запустить турниры",
    "StartTournamentDialogMessage": "Действительно начать новые турниры?",
    "StartTournamentHeaderLabel": "Начать турнир",
    "StatusGridHeader": "Состояние",
    "SubmitButton": "Отправить",
    "SuccessIcon": "Значок успеха",
    "SupportToolTip": "Поддержка",
    "TeamsActionInfoToolTip": "Выберите из доступных ниже действий команд, чтобы включить их в новый турнир. Чтобы добавить для выбора новые турнирные действия, перейдите в раздел \"Управление действиями турнира\" в Инструментах администратора.",
    "ToggleLabelForMemberListColumns": "Показать или скрыть поля списка участников",
    "TooltipContentForMemberListFieldsHeading": "Показать или скрыть поля списка участников во всех компонентах приложения, где это возможно.",
    "Top5ParticipantswithPointsLabel": "5 лучших участников с баллами",
    "Top5TournamentswithParticipantsLabel": "Пять лучших турниров с участниками",
    "TopChampionsLabel": "Лучшие чемпионы",
    "TotalActivitiesLabel": "Всего действий",
    "TotalParticipantsLabel": "Всего участников",
    "TotalPercentageCompletionLabel": "% от общего завершения",
    "TotalPointsLabel": "Сумма баллов",
    "TOTBreadcrumbLabel": "Состязания команд",
    "TOTLabel": "Состязания команд",
    "TOTLeaderBoardPageTitle": "Доска лидеров",
    "TOTMyDashboardPageTitle": "Моя панель мониторинга",
    "TournamentDescPlaceHolderLabel": "Описание турнира (не более 500 символов)",
    "TournamentDescriptionLabel": "Описание турнира",
    "TournamentLabel": "Турнир",
    "TournamentNameErrorLabel": "Необходимо указать название турнира.",
    "TournamentNameLabel": "Название турнира",
    "TournamentNamePlaceHolderLabel": "Название турнира (максимум 255 символов)",
    "TournamentRankLabel": "Рейтинг турнира",
    "TournamentReportsPageTitle": "Отчет о турнирах",
    "UnauthorizedText": "В настоящее время вы не соответствуете требованиям для участия в программе \"Значок чемпиона\".",
    "UploadFileButton": "Выгрузить файл",
    "UserAddedMessage": "Пользователь успешно добавлен!",
    "UserExistingMessage": "Пользователь уже является чемпионом!",
    "UserLabel": "Пользователь",
    "UserNominatedMessage": "Пользователь успешно назначен!",
    "ViewActivitiesLabel": "Просмотреть действия",
    "ViewDashBoardLabel": "Просмотр панели мониторинга",
    "VisitLabel": "Дополнительные сведения см. на страницах платформы управления чемпионами:",
    "WelcomeLabel": "Добро пожаловать!",
    "YesButton": "Да",
  }
});