define([], function () {
  return {
    "AboutContentLabel": "我们的拥护者管理平台是在组织拥护者/采用专家的考虑下创建的。从 Microsoft 365 拥护者社区了解到，此应用旨在提供一个平台来帮助创建和维护你自己的社区。通过执行帮助你在自己的社区中实现更多目标，从灵感入手!",
    "AboutHeaderLabel": "关于拥护者管理平台(CMP):",
    "AcceptButtonAriaDescription": "通过单击此按钮，你将授予拥护者计划 Web 部件代表你更新个人资料图片的权限。",
    "AcceptButtonText": "接受",
    "ActionErrorLabel": "选择至少一个操作以创建锦标赛。",
    "ActionGridHeader": "操作",
    "ActiveTournamentLabel": "活跃的锦标赛",
    "ActivitiesCompletedLabel": "活动已完成",
    "ActivitiesLabel": "活动",
    "AdditionalResourcesContentLabel": "Microsoft Teams 客户宣传组专注于提供此类解决方案，以激励和帮助你实现目标。关注并加入这些其他资源，向我们和社区了解详细信息:",
    "AdditionalResourcesHeaderLabel": "附加资源:",
    "AddMemberLabel": "添加成员",
    "AddMemberPageTitle": "添加成员",
    "AddMembersToolTip": "添加成员开始添加你将在其中协作的人员...",
    "AdminTasksLabel": "管理任务",
    "AdminToolsLabel": "管理工具",
    "AppHeaderTitleLabel": "拥护者管理平台",
    "AppLogoToolTip": "主页",
    "ApplyButton": "应用",
    "ApplyButtonAriaDescription": "通过单击此按钮，你将授予拥护者计划 Web 部件代表你更新个人资料图片的权限。",
    "ApplyButtonText": "应用映像",
    "ApplySpinnerLabel": "正在将新的配置文件映像应用到你的帐户...",
    "ApproveButton": "批准",
    "ApproveChampionSearchboxPlaceholder": "按成员名称/电子邮件搜索",
    "BackButton": "返回",
    "BadgeImageAlt": "中间有字母 C 的奖牌形奖，表示我是拥护者计划的一员",
    "BadgePointsTooltip": "解锁所需的积分:",
    "BasicGroupName": "组名称",
    "BecomeChampionLabel": "成为拥护者",
    "BySpecialityPlaceHolder": "按专业选择",
    "ChampionActivitiesLabel": "拥护者活动",
    "ChampionApprovedMessage": "已批准拥护者请求。",
    "ChampionLabel": "拥护者",
    "ChampionLeaderBoardLabel": "拥护者排行榜",
    "ChampionListLabel": "拥护者列表",
    "ChampionRejectedMessage": "已拒绝拥护者请求。",
    "ChampionRequestSubmitSuccessMessage": "拥护者请求提交成功",
    "ChampionsListPageTitle": "拥护者列表",
    "ChampionsListToolTip": "访问拥护者列表",
    "ChampionsSelectedLabel": "已选择一个或多个拥护者。",
    "ChampionSubmissionPendingLabel": "拥护者提交暂停",
    "ChatIconLabel": "聊天",
    "CMPBreadcrumbLabel": "拥护者管理平台",
    "CMPGitHubLinkLabel": "GitHub",
    "CMPSideBarChampionsLabel": "拥护者",
    "CMPSideBarGlobalRankLabel": "全局排名",
    "CMPSideBarPointsLabel": "得分",
    "CompletedActionsLabel": "已完成的操作",
    "CompleteTournamentSpinnerMessage": "正在完成锦标赛...",
    "ConfigSettingsSaved": "已保存配置设置。",
    "ConfirmLabel": "确认",
    "CountLabel": "计数",
    "CountryGridHeader": "国家/地区",
    "CountryPlaceholder": "选择国家/地区",
    "CountValidationMessage": "计数应介于 1 和 5 之间",
    "CreateTournamentButton": "创建锦标赛",
    "CreateTournamentPageTitle": "创建锦标赛",
    "CreateTournamentsButton": "创建锦标赛",
    "CreateTournamentSuccessLabel": "已成功创建锦标赛。",
    "CurrentVersionLabel": "当前版本:",
    "DateLabel": "日期",
    "DateofEventGridLabel": "事件日期",
    "DescriptionFieldLabel": "描述字段",
    "DescriptionLabel": "说明",
    "DigitalBadgeAppBannerAltText": "参与讨论的 Microsoft 团队成员",
    "DigitalBadgeLabel": "数字徽章",
    "DigitalBadgePageTitle": "数字徽章",
    "DigitalBadgeSubPageTitle": "下面是数字徽章的外观!",
    "DigitalBadgeSuccessMessage": "<strong>恭喜!</strong> 你已成功申请数字徽章，并且你的个人资料图片已更新。请最多允许 24 小时查看所有 Microsoft 365 应用程序(包括 Teams)中反映的更新。",
    "DigitalMembersToolTip": "获取数字徽章并将其应用于个人资料图像",
    "DocumentationLabel": "解决方案技术文档和体系结构概述",
    "DownloadButtonAriaDescription": "单击以下载当前个人资料图像",
    "DownloadButtonSecondaryText": "下载当前个人资料图像",
    "DownloadButtonText": "下载",
    "DownloadedButtonSecondaryText": "可在设备的“下载”文件夹中找到已下载的配置文件图像。",
    "DownloadedButtonText": "已下载",
    "DownloadingButtonText": "正在下载...",
    "DrivingAdoptionLinkLabel": "推动 Microsoft 技术社区采用",
    "DuplicateTournamentNameError": "锦标赛名称已存在。请为锦标赛输入另一个名称。",
    "EmailIconLabel": "发送电子邮件",
    "EmailIDLabel": "电子邮件 Id",
    "EmailLabel": "电子邮件",
    "EnableTOTLabel": "启用团队锦标赛",
    "EnableTOTSpinnerMessage": "此过程需要一些时间才能完成。在看到成功完成的消息之前，请不要离开。",
    "EnableTOTSuccessMessage": "已成功启用团队锦标赛。请刷新应用以继续。",
    "EnableTOTToolTip": "启用团队锦标赛",
    "EnableTournamentSpinnerMessage": "正在启用锦标赛...",
    "EnableTournamentSuccessMessage": "锦标赛已成功启动。",
    "EndTournamentButton": "完成锦标赛",
    "EndTournamentDialogMessage": "是否确定要完成锦标赛?",
    "EndTournamentSuccessMessage": "锦标赛已成功完成。",
    "ErrorMsgActionsList": "在“操作”列表中创建项时出错。请更正数据，然后重试。",
    "ErrorMsgTournamentActionsList": "在锦标赛操作列表中创建项目时出错。请更正数据，然后重试。",
    "ErrorMsgTournamentList": "在“锦标赛”列表中创建项目时出错。请更正数据，然后重试。",
    "EventApprovalsEnableLabel": "批准拥护者活动",
    "EventApprovedMessage": "已批准拥护者活动。",
    "EventLabel": "活动",
    "EventRejectedMessage": "已拒绝拥护者活动。",
    "EventsApprovalInfoIconTooltipContent": "启用此选项将要求管理员批准拥护者提交的活动。只有在批准后，才会奖励活动积分。",
    "EventsListLabel": "事件列表",
    "EventsListToolTip": "访问事件列表",
    "EventsSelectedLabel": "已选择活动。",
    "EventsSubmissionSuccessMessage": "已成功记录事件。",
    "EventsSubmitMessage": "添加完事件后，请单击“提交”按钮进行保存。",
    "EventsTrackListLabel": "事件跟踪列表",
    "EventSubmissionPendingMessage": "已提交事件以供审批。一旦事件获得批准，将授予积分。",
    "EventTrackListToolTip": "访问事件跟踪列表",
    "EventTypeGridLabel": "类型",
    "EventTypeGridLabelPlaceHolder": "选择事件类型",
    "EventTypeLabel": "活动类型",
    "EventTypeValidationMessage": "请选择事件类型!",
    "FeedbackToolTip": "反馈",
    "FirstNameLabel": "名字",
    "FocusAreaGridHeader": "焦点区域",
    "FocusAreaLabel": "焦点区域",
    "FocusAreaPlaceholder": "选择焦点区域",
    "FormSavingMessage": "正在保存你的详细信息......",
    "GetStartedLabel": "开始使用",
    "GroupGridHeader": "组",
    "GroupPlaceholder": "选择组",
    "HowtoGetDigitalBadgeText": "如何获取拥护者徽章",
    "ImportRule1": "不修改模板中的列标题",
    "ImportRule2": "不要删除模板中的列",
    "ImportRule3": "在模板中提到的所有必需(*)列中输入数据",
    "ImportRule4": "遵循每个列的模板中提到的字符限制和类型",
    "ImportRule5": "根据提供的示例数据，在每个工作表中仅输入 1 个锦标赛的数据",
    "ImportRule6": "一次只能创建 10 个锦标赛",
    "ImportRule7": "确保锦标赛名称是唯一的",
    "ImportSpinnerMessage": "正在创建锦标赛...",
    "LastNameLabel": "姓氏",
    "LatestVersionLabel": "最新版本:",
    "LoadingSpinnerLabel": "正在加载…",
    "LogMsgBlankSheet": "已跳过，因为它为空。",
    "LogMsgDone": "锦标赛",
    "LogMsgDone1": "已创建。",
    "LogMsgInvalidTemplate": "已跳过，因为它不是有效的模板。",
    "LogMsgInvalidTournamentName": "已跳过，因为它没有有效的锦标赛名称。",
    "LogMsgMultipleTournaments": "已跳过，因为它具有多个锦标赛名称。",
    "LogMsgTournamentExists": "已跳过，因为锦标赛已存在",
    "LogMsgTournamentExists1": "已存在。",
    "LogProgress": "下面是进度:",
    "M365ChampionCommunityLinkLabel": "Microsoft 365 拥护者社区",
    "ManageAdminsLabel": "管理管理员",
    "ManageAdminsToolTip": "访问管理员列表",
    "ManageAppLogoLabel": "管理应用徽标",
    "ManageAppLogoToolTip": "管理应用徽标",
    "ManageConfigSettingsLabel": "管理配置设置",
    "ManageDigitalBadgesLabel": "管理数字徽章",
    "ManageDigitalBadgesToolTip": "管理数字徽章",
    "ManageToTLabel1": "一次可以启动多个锦标赛。请参阅以下内容，了解当前活动锦标赛、完成锦标赛的能力以及启动新锦标赛的功能。",
    "ManageToTLabel2": "锦标赛启动并完成后，将无法重新开始;但是，如果要完成类似的锦标赛，可以使用相同的操作创建新锦标赛!",
    "ManageTournamentActionsLabel": "管理锦标赛操作",
    "ManageTournamentActionsToolTip": "访问锦标赛操作列表",
    "ManageTournamentsLabel": "管理锦标赛",
    "ManageTournamentsPageTitle": "管理锦标赛",
    "MeetupBody": "留出时间讨论你的拥护者区域并了解详细信息!",
    "MeetupSubject": "1:1 (拥护者请求)",
    "MonthAndDateLabel": "月份和日期",
    "MoreInfoToolTip": "详细信息",
    "MSAdoptionHubLinkLabel": "Microsoft 采用中心",
    "MultipleBadgeMessage": "从下面的列表中选择徽章。所选徽章将应用于你的个人资料图片。",
    "MultipleTournamentLabel": "多个锦标赛",
    "MultiTournamentStep": "步骤",
    "MultiTournamentStep1LinkLabel": "下载模板",
    "MultiTournamentStep1Text": "示例文件格式",
    "MultiTournamentStep2": "按照以下准则将锦标赛详细信息添加到文件",
    "MultiTournamentStep3": "上载文件",
    "MyDashboardInfoIconMessage": "了解有关此操作的详细信息",
    "MyRankLabel": "我的排名",
    "MyTournamentsLabel": "我的锦标赛",
    "MyTournamentsTooltip": "你已参与的活动锦标赛",
    "NameLabel": "名称",
    "NearMePlaceHolder": "选择“附近”",
    "NoActiveParticipantsErrorMessage": "目前没有活动参与者。成为第一个参与和记录活动的人",
    "NoActiveParticipantsMessage": "目前没有活动参与者。成为第一个从“我的仪表板”参与和记录活动的人!",
    "NoActiveTournamentMessage": "当前没有活动的锦标赛。请稍后返回查看。",
    "NoActivitiesinGridLabel": "未找到任何活动!",
    "NoBadgeMessage": "找不到可供你选择的锁屏提醒。请咨询应用管理员。",
    "NoButton": "否",
    "NoChampionsMessage": "目前没有挂起的请求",
    "NoCompletedTournamentsMessage": "目前没有已完成的锦标赛。请稍后返回查看。",
    "NominateMemberLabel": "提名成员",
    "NominateMemberPageTitle": "提名成员",
    "NoPendingEventsLabel": "目前没有挂起的活动。",
    "NoProfileImageAlt": "人员的剪影，表示当前未将个人资料图像应用于你的帐户",
    "NoProfileImageDescription": "如果已将图片与个人资料相关联，并且仍然看到此消息，则图片可能尚不可用。请稍后重试，如果 24 小时后仍未显示，请联系 <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>支持人员</a>。",
    "NoRecordsIcon": "无记录图标",
    "NoRecordsinGridLabel": "找不到记录!",
    "NoSearchResults": "没有匹配搜索的结果。",
    "NotesLabel": "笔记",
    "NotesPlaceholder": "最多 200 个字符",
    "NoTournamentMessage": "未找到锦标赛。请稍后再试。",
    "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>欢迎使用数字徽章实用工具</span> 作为拥护者计划的一部分，你可获得数字徽章! 此实用工具将通过将数字徽章叠加到现有个人资料图片的顶部，使你能够“<em>声明</em>”。请注意，这将更新所有 Microsoft 365 (Exchange、Teams、SharePoint 等)的个人资料图片。",
    "OrLabel": "或",
    "OverviewLabel": "概述和有关我们的信息",
    "ParticipantsDetailsLabel": "参与者详细信息",
    "ParticipantsLabel": "参与者",
    "ParticipantsStatusLabel": "参与者状态",
    "PendingActionsLabel": "挂起的操作",
    "PendingActionsSuccessMessage": "此锦标赛中没有其他暂停的操作。",
    "PendingEventsSearchboxPlaceholder": "按拥护者/电子邮件搜索",
    "PeopleNameGridHeader": "成员姓名",
    "PeoplePickerPlaceholder": "若要添加成员，请键入成员名称",
    "PercentageTournamentCompletedLabel": "锦标赛已完成百分比",
    "PivotHeaderBySpeciality": "按专业",
    "PivotHeaderGlobal": "全局",
    "PivotHeaderNearMe": "我的附近",
    "PointsLabel": "得分",
    "PreAcceptDisclaimer": "<span style='font-weight:bold;'>欢迎使用数字徽章实用工具</span> <br/><br/> <span>作为拥护者计划的一部分，你获得了数字徽章! 此实用工具将通过将数字徽章叠加到现有个人资料图片的顶部，使你能够“<em>声明</em>”。<br/><br/> 请注意，这将更新所有 Microsoft 365 (Exchange、Teams、SharePoint 等)的个人资料图片。</span>",
    "PreAcceptDisclaimer2": "如果需要，<span style='font-weight:bold;'>你将有机会“保存”现有个人资料图片的副本</span> 后续步骤中没有数字徽章覆盖。请单击“接受”以继续(可能会看到弹出窗口打开并提示登录)。",
    "PreAcceptPageTitle": "申请数字徽章!",
    "PreApplyDisclaimer": "这是新个人资料图片(包括数字徽章)的预览版。如果希望在应用数字徽章之前下载现有个人资料图片，请单击“<strong>下载当前个人资料图像</strong>”链接。<br />",
    "PreApplyDisclaimer1": "<br />单击“应用图像”将使用此新图像更新 Microsoft 365 个人资料图片。<strong>请注意，这将更新所有 Microsoft 365 的个人资料图片，并且无法通过此页面恢复</strong>。<br/><br/>如果你想要重新更改图片， 可以使用 <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' aria-label='在新的浏览器选项卡或窗口中打开 Outlook Web 应用程序'>Outlook Web 应用程序</a>。",
    "ProcessingSpinnerLabel": "正在处理...",
    "ProfileImageAlt": "我的个人资料在 O365、Teams 等中使用的图像",
    "PropertyPaneDescription": "说明",
    "QuickLinksLabel": "快速链接",
    "RankLabel": "排序",
    "RecordEventLabel": "记录事件",
    "RecordsNotFound": "未找到记录",
    "RefreshIconInfoText": "单击“刷新”以查看最新数据",
    "RegionGridHeader": "区域",
    "RegionLabel": "区域",
    "RegionPlaceholder": "选择区域",
    "RejectButton": "拒绝",
    "RemoveFileLabel": "删除文件",
    "ReportsDropdownInfoIconText": "只能为已完成的锦标赛生成报告。",
    "RequestToCallLabel": "请求呼叫",
    "SaveButton": "保存",
    "SearchActiveTournaments": "搜索活跃的锦标赛",
    "SearchLabel": "搜索",
    "SearchPendingTournaments": "搜索锦标赛以开始",
    "SearchPlaceholder": "按参与者姓名搜索",
    "SelectActionsErrorMessage": "至少选择一个操作以继续。",
    "SelectAll": "选择所有拥护者",
    "SelectAllEvents": "选择所有活动",
    "SelectAllLabel": "全选",
    "SelectChampion": "选择拥护者",
    "SelectDate": "选择日期",
    "SelectEndTournamentMessage": "选择要完成的锦标赛。",
    "SelectEvent": "选择活动",
    "SelectTeamsActionsLabel": "选择 Teams 操作:",
    "SelectTournamentMessage": "至少选择一个锦标赛开始。",
    "SelectTournamentPlaceHolder": "选择锦标赛",
    "ShowMoreLabel": "显示更多",
    "SingleTournamentLabel": "单个锦标赛",
    "SpinnerListCreationMessage": "正在设置团队锦标赛...",
    "StartTournamentButton": "开始锦标赛",
    "StartTournamentDialogMessage": "是否确定要开始新的锦标赛?",
    "StartTournamentHeaderLabel": "开始锦标赛",
    "StatusGridHeader": "状态",
    "SubmitButton": "提交",
    "SuccessIcon": "“成功”图标",
    "SupportToolTip": "支持",
    "TeamsActionInfoToolTip": "从以下可用 Teams 操作中进行选择，以包含在新锦标赛中。若要添加要选择的新锦标赛操作，请访问管理工具中的“管理锦标赛操作”。",
    "ToggleLabelForMemberListColumns": "显示/隐藏成员列表字段",
    "TooltipContentForMemberListFieldsHeading": "在适用的任何位置显示/隐藏应用所有组件中的成员列表字段。",
    "Top5ParticipantswithPointsLabel": "分数排名前 5 的参与者",
    "Top5TournamentswithParticipantsLabel": "与参与者一起参加的前 5 项锦标赛",
    "TopChampionsLabel": "排名靠前的拥护者",
    "TotalActivitiesLabel": "总活动",
    "TotalParticipantsLabel": "参与者总计",
    "TotalPercentageCompletionLabel": "完成总量的百分比",
    "TotalPointsLabel": "总得分",
    "TOTBreadcrumbLabel": "团队锦标赛",
    "TOTLabel": "团队锦标赛",
    "TOTLeaderBoardPageTitle": "排行榜",
    "TOTMyDashboardPageTitle": "我的仪表板",
    "TournamentDescPlaceHolderLabel": "锦标赛说明(最多 500 个字符)",
    "TournamentDescriptionLabel": "锦标赛说明",
    "TournamentLabel": "锦标赛",
    "TournamentNameErrorLabel": "锦标赛名称是必需的。",
    "TournamentNameLabel": "锦标赛名称",
    "TournamentNamePlaceHolderLabel": "锦标赛名称(最多 255 个字符)",
    "TournamentRankLabel": "锦标赛排名",
    "TournamentReportsPageTitle": "锦标赛报告",
    "UnauthorizedText": "你目前没有资格参加拥护者徽章计划",
    "UploadFileButton": "上传文件",
    "UserAddedMessage": "已成功添加用户!",
    "UserExistingMessage": "用户已是拥护者!",
    "UserLabel": "用户",
    "UserNominatedMessage": "已成功提名用户!",
    "ViewActivitiesLabel": "查看活动",
    "ViewDashBoardLabel": "查看仪表板",
    "VisitLabel": "访问“拥护者管理平台”页面以了解详细信息:",
    "WelcomeLabel": "欢迎",
    "YesButton": "是",
  }
});