define([], function () {
    return {
      "PropertyPaneDescription": "说明",
      "BasicGroupName": "组名称",
      "DescriptionFieldLabel": "描述字段",
      "CMPBreadcrumbLabel": "支持者管理平台",
      "SaveButton": "保存",
      "BackButton": "返回",
      "GetStartedLabel": "开始使用",
      "AdminToolsLabel": "管理工具",
      "ChampionLeaderBoardLabel": "拥护者排行榜",
      "AddMemberLabel": "添加成员",
      "NominateMemberLabel": "提名成员",
      "DigitalBadgeLabel": "数字徽章",
      "TOTLabel": "Teams 锦标赛",
      "ChampionListLabel": "支持者列表",
      "EventsListLabel": "事件列表",
      "EventsTrackListLabel": "事件跟踪列表",
      "ManageApprovalsLabel": "管理审批",
      "ManageDigitalBadgesLabel": "管理数字徽章",
      "EnableTOTLabel": "启用 Teams 锦标赛",
      "AddMembersToolTip": "添加成员开始添加你将在其中协作的人员...",
      "DigitalMembersToolTip": "获取数字徽章并将其应用于个人资料图像",
      "ChampionsListToolTip": "访问支持者列表",
      "EventsListToolTip": "访问事件列表",
      "EventTrackListToolTip": "访问事件跟踪列表",
      "ManageApprovalToolTip": "批准支持者",
      "EnableTOTToolTip": "启用 Teams 锦标赛",
      "ManageDigitalBadgesToolTip": "管理数字徽章",
      "WelcomeLabel": "欢迎",
      "ManageAppLogoLabel": "管理应用徽标",
      "ManageAppLogoToolTip": "管理应用徽标",
      "AppHeaderTitleLabel": "支持者管理平台",
      "AppLogoToolTip": "主页",
      "MoreInfoToolTip": "详细信息",
      "SupportToolTip": "支持",
      "FeedbackToolTip": "反馈",
      "AboutHeaderLabel": "关于冠军管理平台(CMP):",
      "AboutContentLabel": "我们的支持者管理平台是在组织支持者/采用专家的考虑下创建的。从 Microsoft 365 支持者社区了解到，此应用旨在提供一个平台来帮助创建和维护你自己的社区。通过执行帮助你在自己的社区中实现更多目标，从灵感入手!",
      "AdditionalResourcesHeaderLabel": "附加资源:",
      "AdditionalResourcesContentLabel": "Microsoft Teams 客户宣传组专注于提供此类解决方案，以激励和帮助你实现目标。关注并加入这些其他资源，向我们和社区了解详细信息:",
      "M365ChampionCommunityLinkLabel": "Microsoft 365 支持者社区",
      "DrivingAdoptionLinkLabel": "推动 Microsoft 技术社区采用",
      "CurrentVersionLabel": "当前版本:",
      "LatestVersionLabel": "最新版本:",
      "CMPGitHubLinkLabel": "GitHub",
      "VisitLabel": "访问“拥护者管理平台”页面以了解详细信息:",
      "OverviewLabel": "概述和有关我们的信息",
      "MSAdoptionHubLinkLabel": "Microsoft 采用中心",
      "DocumentationLabel": "解决方案技术文档和体系结构概述",
      "AddMemberPageTitle": "添加成员",
      "NominateMemberPageTitle": "提名成员",
      "PeoplePickerPlaceholder": "若要添加成员，请键入成员名称",
      "RegionPlaceholder": "选择区域",
      "CountryPlaceholder": "选择国家/地区",
      "GroupPlaceholder": "选择组",
      "FocusAreaPlaceholder": "选择焦点区域",
      "UserExistingMessage": "用户已是拥护者!",
      "ChampionsListPageTitle": "支持者列表",
      "UserNominatedMessage": "已成功提名用户!",
      "UserAddedMessage": "已成功添加用户!",
      "PeopleNameGridHeader": "成员姓名",
      "Select": "选择",
      "SelectAll": "全选",
      "RegionGridHeader": "区域",
      "CountryGridHeader": "国家/地区",
      "GroupGridHeader": "组",
      "FocusAreaGridHeader": "焦点区域",
      "StatusGridHeader": "状态",
      "ManageApprovalsPageTitle": "管理审批",
      "ActionGridHeader": "操作",
      "ApproveButton": "批准",
      "RejectButton": "拒绝",
      "NoChampionsMessage": "目前没有挂起的请求",
      "ChampionApprovedMessage": "批准支持者请求！",
      "ChampionRejectedMessage": "拒绝支持者拒绝！",
      "ProcessingSpinnerLabel": "正在处理...",
      "DigitalBadgePageTitle": "数字徽章",
      "LoadingSpinnerLabel": "正在加载…",
      "DigitalBadgeAppBannerAltText": "参与讨论的 Microsoft 团队成员",
      "PreAcceptPageTitle": "申请数字徽章!",
      "PreAcceptDisclaimer": "<span style='font-weight:bold;'>欢迎使用数字徽章实用工具</span> <br/><br/> <span>作为支持者计划的一部分，你获得了数字徽章! 此实用工具将通过将数字徽章叠加到现有个人资料图片的顶部，使你能够“<em>声明</em>”。<br/><br/> 请注意，这将更新所有 Microsoft 365 (Exchange、Teams、SharePoint 等)的个人资料图片。</span>",
      "PreAcceptDisclaimer2": "如果需要，<span style='font-weight:bold;'>你将有机会“保存”现有个人资料图片的副本</span> 后续步骤中没有数字徽章覆盖。请单击“接受”以继续(可能会看到弹出窗口打开并提示登录)。",
      "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>欢迎使用数字徽章实用工具</span> 作为支持者计划的一部分，你可获得数字徽章! 此实用工具将通过将数字徽章叠加到现有个人资料图片的顶部，使你能够“<em>声明</em>”。请注意，这将更新所有 Microsoft 365 (Exchange、Teams、SharePoint 等)的个人资料图片。",
      "HowtoGetDigitalBadgeText": "如何获取拥护者徽章",
      "MultipleBadgeMessage": "从下面的列表中选择徽章。所选徽章将应用于你的个人资料图片。",
      "NoBadgeMessage": "找不到可供你选择的锁屏提醒。请咨询应用管理员。",
      "DigitalBadgeSubPageTitle": "下面是数字徽章的外观!",
      "ProfileImageAlt": "我的个人资料在 O365、Teams 等中使用的图像",
      "BadgeImageAlt": "中间有字母 C 的奖牌形奖，表示我是拥护者计划的一员",
      "NoProfileImageAlt": "人员的剪影，表示当前未将个人资料图像应用于你的帐户",
      "ApplyButtonText": "应用映像",
      "ApplyButtonAriaDescription": "通过单击此按钮，你将授予支持者计划 Web 部件代表你更新个人资料图片的权限。",
      "ApplyButton": "应用",
      "DownloadButtonText": "下载",
      "DownloadButtonAriaDescription": "单击以下载当前个人资料图像",
      "DownloadingButtonText": "正在下载...",
      "DownloadedButtonText": "已下载",
      "DownloadedButtonSecondaryText": "可在设备的“下载”文件夹中找到已下载的配置文件图像。",
      "DownloadButtonSecondaryText": "下载当前个人资料图像",
      "PreApplyDisclaimer": "这是新个人资料图片(包括数字徽章)的预览版。如果希望在应用数字徽章之前下载现有个人资料图片，请单击“<strong>下载当前个人资料图像</strong>”链接。<br />",
      "PreApplyDisclaimer1": "<br />单击“应用图像”将使用此新图像更新 Microsoft 365 个人资料图片。<strong>请注意，这将更新所有 Microsoft 365 的个人资料图片，并且无法通过此页面恢复</strong>。<br/><br/>如果你想要重新更改图片， 可以使用 <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' aria-label='在新的浏览器选项卡或窗口中打开 Outlook Web 应用程序'>Outlook Web 应用程序</a>。",
      "NoProfileImageDescription": "如果已将图片与个人资料相关联，并且仍然看到此消息，则图片可能尚不可用。请稍后重试，如果 24 小时后仍未显示，请联系 <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>支持人员</a>。",
      "AcceptButtonText": "接受",
      "AcceptButtonAriaDescription": "通过单击此按钮，你将授予支持者计划 Web 部件代表你更新个人资料图片的权限。",
      "UnauthorizedText": "你目前没有资格参加拥护者徽章计划",
      "ApplySpinnerLabel": "正在将新的配置文件映像应用到你的帐户...",
      "DigitalBadgeSuccessMessage": "<strong>恭喜!</strong> 你已成功申请数字徽章，并且你的个人资料图片已更新。请最多允许 24 小时查看所有 Microsoft 365 应用程序(包括 Teams)中反映的更新。",
      "CMPSideBarPointsLabel": "得分",
      "CMPSideBarGlobalRankLabel": "全局排名",
      "CMPSideBarChampionsLabel": "拥护者冠军",
      "FirstNameLabel": "名字",
      "LastNameLabel": "姓氏",
      "EmailIDLabel": "电子邮件 Id",
      "BecomeChampionLabel": "成为拥护者",
      "ChampionSubmissionPendingLabel": "支持者提交挂起",
      "ChampionRequestSubmitSuccessMessage": "支持者请求提交成功",
      "PivotHeaderGlobal": "全局",
      "PivotHeaderNearMe": "我的附近",
      "PivotHeaderBySpeciality": "按专业",
      "NearMePlaceHolder": "选择“附近”",
      "BySpecialityPlaceHolder": "按专业选择",
      "TopChampionsLabel": "顶级拥护者",
      "RecordsNotFound": "未找到记录",
      "EventTypeLabel": "活动类型",
      "CountLabel": "计数",
      "MyRankLabel": "我的排名",
      "ViewDashBoardLabel": "查看仪表板",
      "DateofEventGridLabel": "事件日期",
      "EventTypeGridLabel": "类型",
      "RecordEventLabel": "记录事件",
      "MonthAndDateLabel": "月份和日期",
      "EventTypeGridLabelPlaceHolder": "选择事件类型",
      "EventTypeValidationMessage": "请选择事件类型!",
      "CountValidationMessage": "计数应介于 1 和 5 之间",
      "EventsSubmitMessage": "添加完事件后，请单击“提交”按钮进行保存。",
      "SubmitButton": "提交",
      "SearchLabel": "搜索",
      "ActivitiesLabel": "活动",
      "RegionLabel": "区域",
      "FocusAreaLabel": "焦点区域",
      "ShowMoreLabel": "显示更多",
      "ViewActivitiesLabel": "查看活动",
      "ChatIconLabel": "聊天",
      "RequestToCallLabel": "请求呼叫",
      "EmailIconLabel": "发送电子邮件",
      "MeetupSubject": "1:1 (拥护者请求)",
      "MeetupBody": "留出时间讨论你的拥护者区域并了解详细信息!",
      "NoActivitiesinGridLabel": "未找到任何活动!",
      "CreateTournamentPageTitle": "创建锦标赛",
      "CreateTournamentSuccessLabel": "已成功创建锦标赛。",
      "TournamentNameLabel": "锦标赛名称",
      "TournamentNamePlaceHolderLabel": "锦标赛名称(最多 255 个字符)",
      "TournamentNameErrorLabel": "锦标赛名称是必需的。",
      "TournamentDescriptionLabel": "锦标赛说明",
      "TournamentDescPlaceHolderLabel": "锦标赛说明(最多 500 个字符)",
      "SelectTeamsActionsLabel": "选择 Teams 操作:",
      "TeamsActionInfoToolTip": "从以下可用 Teams 操作中进行选择，以包含在新锦标赛中。若要添加要选择的新锦标赛操作，请访问管理工具中的“管理锦标赛操作”。",
      "ActionErrorLabel": "选择至少一个操作以创建锦标赛。",
      "CreateTournamentButton": "创建锦标赛",
      "DuplicateTournamentNameError": "锦标赛名称已存在。请为锦标赛输入另一个名称。",
      "CreateTournamentsButton": "创建锦标赛",
      "SingleTournamentLabel": "单个锦标赛",
      "MultipleTournamentLabel": "多个锦标赛",
      "MultiTournamentStep": "步骤",
      "MultiTournamentStep1LinkLabel": "下载模板",
      "MultiTournamentStep1Text": "示例文件格式",
      "MultiTournamentStep2": "按照以下准则将锦标赛详细信息添加到文件",
      "MultiTournamentStep3": "上载文件",
      "UploadFileButton": "上传文件",
      "RemoveFileLabel": "删除文件",
      "ImportSpinnerMessage": "正在创建锦标赛......",
      "ErrorMsgTournamentList": "在“锦标赛”列表中创建项目时出错。请更正数据，然后重试。",
      "ErrorMsgActionsList": "在“操作”列表中创建项时出错。请更正数据，然后重试。",
      "ErrorMsgTournamentActionsList": "在锦标赛操作列表中创建项目时出错。请更正数据，然后重试。",
      "LogMsgTournamentExists": "已跳过，因为锦标赛已存在",
      "LogMsgTournamentExists1": "已存在。",
      "LogMsgDone": "锦标赛",
      "LogMsgDone1": "已创建。",
      "LogMsgInvalidTournamentName": "已跳过，因为它没有有效的锦标赛名称。",
      "LogMsgInvalidTemplate": "已跳过，因为它不是有效的模板。",
      "LogMsgMultipleTournaments": "已跳过，因为它具有多个锦标赛名称。",
      "LogMsgBlankSheet": "已跳过，因为它为空。",
      "LogProgress": "下面是进度:",
      "ImportRule1": "不修改模板中的列标题",
      "ImportRule2": "不要删除模板中的列",
      "ImportRule3": "在模板中提到的所有必需(*)列中输入数据",
      "ImportRule4": "遵循每个列的模板中提到的字符限制和类型",
      "ImportRule5": "根据提供的示例数据，在每个工作表中仅输入 1 个锦标赛的数据",
      "ImportRule6": "一次只能创建 10 个锦标赛",
      "ImportRule7": "确保锦标赛名称是唯一的",
      "TOTBreadcrumbLabel": "Teams 锦标赛",
      "EnableTOTSuccessMessage": "已成功启用 Teams 锦标赛。请刷新应用以继续。",
      "EnableTOTSpinnerMessage": "此过程需要一些时间才能完成。在看到成功完成的消息之前，请不要离开。",
      "TOTLeaderBoardPageTitle": "排行榜",
      "TOTMyDashboardPageTitle": "我的仪表板",
      "ManageTournamentActionsToolTip": "访问锦标赛操作列表",
      "ManageTournamentActionsLabel": "管理锦标赛操作",
      "ManageTournamentsLabel": "管理锦标赛",
      "ManageAdminsToolTip": "访问管理员列表",
      "ManageAdminsLabel": "管理管理员",
      "QuickLinksLabel": "快速链接",
      "SpinnerListCreationMessage": "正在设置 Teams 锦标赛...",
      "ManageTournamentsPageTitle": "管理锦标赛",
      "ManageToTLabel1": "一次可以启动多个锦标赛。请参阅以下内容，了解当前活动锦标赛、完成锦标赛的能力以及启动新锦标赛的功能。",
      "ManageToTLabel2": "锦标赛启动并完成后，将无法重新开始;但是，如果要完成类似的锦标赛，可以使用相同的操作创建新锦标赛!",
      "EndTournamentDialogMessage": "是否确定要完成锦标赛?",
      "StartTournamentDialogMessage": "是否确定要开始新的锦标赛?",
      "ConfirmLabel": "确认",
      "YesButton": "是",
      "NoButton": "否",
      "ActiveTournamentLabel": "活跃的锦标赛",
      "EndTournamentButton": "完成锦标赛",
      "StartTournamentHeaderLabel": "开始锦标赛",
      "NoTournamentMessage": "未找到锦标赛。请稍后再试。",
      "SelectTournamentMessage": "至少选择一个锦标赛开始。",
      "SelectEndTournamentMessage": "选择要完成的锦标赛。",
      "StartTournamentButton": "开始锦标赛",
      "EndTournamentSuccessMessage": "锦标赛已成功完成。",
      "EnableTournamentSuccessMessage": "锦标赛已成功启动。",
      "CompleteTournamentSpinnerMessage": "正在完成锦标赛...",
      "EnableTournamentSpinnerMessage": "正在启用锦标赛(的)...",
      "SearchActiveTournaments": "搜索活跃的锦标赛",
      "SearchPendingTournaments": "搜索锦标赛以开始",
      "SelectAllLabel": "全选",
      "NoSearchResults": "没有匹配搜索的结果。",
      "NoActiveParticipantsMessage": "目前没有活动参与者。成为第一个从“我的仪表板”参与和记录活动的人!",
      "NoActiveTournamentMessage": "当前没有活动的锦标赛。请稍后返回查看。",
      "TournamentLabel": "锦标赛",
      "DescriptionLabel": "说明",
      "NoActiveParticipantsErrorMessage": "目前没有活动参与者。成为第一个参与和记录活动的人",
      "PendingActionsLabel": "挂起的操作",
      "PendingActionsSuccessMessage": "此锦标赛中没有其他挂起的操作。",
      "SelectActionsErrorMessage": "至少选择一个操作以继续。",
      "FormSavingMessage": "正在保存你的详细信息......",
      "CompletedActionsLabel": "已完成的操作",
      "RankLabel": "排序",
      "UserLabel": "用户",
      "MyDashboardInfoIconMessage": "了解有关此操作的详细信息",
      "SelectTournamentPlaceHolder": "选择锦标赛",
      "MyTournamentsLabel": "我的锦标赛",
      "OrLabel": "或",
      "MyTournamentsTooltip": "你已参与的活动锦标赛",
      "PointsLabel": "得分",
      "TournamentRankLabel": "锦标赛排名",
      "ParticipantsLabel": "参与者",
      "TournamentReportsPageTitle": "锦标赛报告",
      "TotalActivitiesLabel": "总活动",
      "TotalPointsLabel": "总得分",
      "TotalParticipantsLabel": "参与者总计",
      "TotalPercentageCompletionLabel": "完成总量的百分比",
      "Top5ParticipantswithPointsLabel": "分数排名前 5 的参与者",
      "Top5TournamentswithParticipantsLabel": "与参与者一起参加的前 5 项锦标赛",
      "ParticipantsStatusLabel": "参与者状态",
      "ParticipantsDetailsLabel": "参与者详细信息",
      "NameLabel": "名称",
      "PercentageTournamentCompletedLabel": "锦标赛已完成百分比",
      "ActivitiesCompletedLabel": "活动已完成",
      "NoRecordsinGridLabel": "找不到记录!",
      "SearchPlaceholder": "按参与者姓名搜索",
      "NoCompletedTournamentsMessage": "目前没有已完成的锦标赛。请稍后返回查看。",
      "ReportsDropdownInfoIconText": "只能为已完成的锦标赛生成报告。",
      "RefreshIconInfoText": "单击“刷新”以查看最新数据"
    }

});