define([], function () {
  return {
    "AboutContentLabel": "我們的擁護者管理平台由組織擁護者/採用專家所建立。從 Microsoft 365 擁護者社群得知，此應用程式是開發來提供平臺，協助建立及維持您自己的社群。從靈感開始，透過執行來協助您在您自己的社群中達成更多目標!",
    "AboutHeaderLabel": "關於擁護者管理平台 (CMP):",
    "AcceptButtonAriaDescription": "按一下此按鈕，即表示您授與擁護者計畫網頁元件許可權，以代表您更新您的個人資料圖片。",
    "AcceptButtonText": "接受",
    "ActionErrorLabel": "請至少選取一個動作來建立競賽。",
    "ActionGridHeader": "動作",
    "ActiveTournamentLabel": "進行中的競賽",
    "ActivitiesCompletedLabel": "已完成的活動",
    "ActivitiesLabel": "活動",
    "AdditionalResourcesContentLabel": "Microsoft Teams 客戶參與群組著重于提供這類解決方案，以激勵並協助您達成目標。透過這些其他資源關注並加入，以深入瞭解我們與社群:",
    "AdditionalResourcesHeaderLabel": "其他資源:",
    "AddMemberLabel": "新增成員",
    "AddMemberPageTitle": "新增成員",
    "AddMembersToolTip": "新增成員開始新增您將在您中共同作業的人員...",
    "AdminTasksLabel": "系統管理工作",
    "AdminToolsLabel": "系統管理工具",
    "AppHeaderTitleLabel": "擁護者管理平台",
    "AppLogoToolTip": "首頁",
    "ApplyButton": "套用",
    "ApplyButtonAriaDescription": "按一下此按鈕，即表示您授與擁護者計畫網頁元件許可權，以代表您更新您的個人資料圖片。",
    "ApplyButtonText": "套用影像",
    "ApplySpinnerLabel": "正在將新的設定檔影像套用至您的帳戶...",
    "ApproveButton": "核准",
    "ApproveChampionSearchboxPlaceholder": "依成員名稱/郵件搜尋",
    "BackButton": "返回",
    "BadgeImageAlt": "獎牌形狀獎項與字母 C 在中間表示我是擁護者計畫的一份子",
    "BadgePointsTooltip": "解除鎖定所需的點數:",
    "BasicGroupName": "群組名稱",
    "BecomeChampionLabel": "成為擁護者",
    "BySpecialityPlaceHolder": "依特殊專案選取",
    "ChampionActivitiesLabel": "擁護者活動",
    "ChampionApprovedMessage": "已核准擁護者要求。",
    "ChampionLabel": "擁護者",
    "ChampionLeaderBoardLabel": "擁護者排行榜",
    "ChampionListLabel": "擁護者清單",
    "ChampionRejectedMessage": "已拒絕擁護者要求。",
    "ChampionRequestSubmitSuccessMessage": "成功提交擁護者要求",
    "ChampionsListPageTitle": "擁護者清單",
    "ChampionsListToolTip": "正在存取擁護者清單",
    "ChampionsSelectedLabel": "已選取擁護者。",
    "ChampionSubmissionPendingLabel": "擁護者提交擱置中",
    "ChatIconLabel": "聊天",
    "CMPBreadcrumbLabel": "擁護者管理平台",
    "CMPGitHubLinkLabel": "GitHub",
    "CMPSideBarChampionsLabel": "擁護者",
    "CMPSideBarGlobalRankLabel": "全域排名",
    "CMPSideBarPointsLabel": "點數",
    "CompletedActionsLabel": "已完成的動作",
    "CompleteTournamentSpinnerMessage": "正在完成競賽...",
    "ConfigSettingsSaved": "已儲存設定。",
    "ConfirmLabel": "確認",
    "CountLabel": "計數",
    "CountryGridHeader": "國家/地區",
    "CountryPlaceholder": "選取國家/地區",
    "CountValidationMessage": "計數應介於 1 到 5 之間",
    "CreateTournamentButton": "建立競賽",
    "CreateTournamentPageTitle": "建立競賽",
    "CreateTournamentsButton": "建立競賽",
    "CreateTournamentSuccessLabel": "已成功建立競賽。",
    "CurrentVersionLabel": "目前版本:",
    "DateLabel": "日期",
    "DateofEventGridLabel": "事件日期",
    "DescriptionFieldLabel": "描述欄位",
    "DescriptionLabel": "描述",
    "DigitalBadgeAppBannerAltText": "參與討論的 Microsoft 小組成員",
    "DigitalBadgeLabel": "數位徽章",
    "DigitalBadgePageTitle": "數位徽章",
    "DigitalBadgeSubPageTitle": "以下是您的數位徽章外觀!",
    "DigitalBadgeSuccessMessage": "<strong>恭喜!</strong>您已成功領取您的數位徽章，且您的個人資料圖片已更新。請允許最多 24 小時查看反映在所有 Microsoft 365 應用程式的更新 (包括 Teams)。",
    "DigitalMembersToolTip": "取得您的數位徽章，並將之套用至您的個人資料影像",
    "DocumentationLabel": "解決方案技術檔與架構概觀:",
    "DownloadButtonAriaDescription": "按一下以下載您目前的設定檔影像",
    "DownloadButtonSecondaryText": "下載您目前的設定檔影像",
    "DownloadButtonText": "下載",
    "DownloadedButtonSecondaryText": "您可以在裝置的 [下載] 資料夾中找到您下載的設定檔影像。",
    "DownloadedButtonText": "已下載",
    "DownloadingButtonText": "正在下載...",
    "DrivingAdoptionLinkLabel": "在 Microsoft 技術社群上推動採用",
    "DuplicateTournamentNameError": "該競賽名稱已存在。請輸入另一個競賽名稱。",
    "EmailIconLabel": "傳送電子郵件",
    "EmailIDLabel": "電子郵件識別碼",
    "EmailLabel": "電子郵件",
    "EnableTOTLabel": "啟用團隊競賽",
    "EnableTOTSpinnerMessage": "此程式需要一些時間才能完成。在您看到成功完成的訊息之前，請勿離開。",
    "EnableTOTSuccessMessage": "已成功啟用團隊競賽。請重新整理應用程式以繼續。",
    "EnableTOTToolTip": "啟用團隊競賽",
    "EnableTournamentSpinnerMessage": "正在啟用競賽...",
    "EnableTournamentSuccessMessage": "競賽已成功開始。",
    "EndTournamentButton": "完成競賽",
    "EndTournamentDialogMessage": "您確定要完成競賽嗎?",
    "EndTournamentSuccessMessage": "已成功完成競賽。",
    "ErrorMsgActionsList": "在 [動作] 清單中建立專案時發生錯誤。請更正資料，然後再試一次。",
    "ErrorMsgTournamentActionsList": "在競賽動作清單中建立專案時發生錯誤。請更正資料，然後再試一次。",
    "ErrorMsgTournamentList": "在 [競賽] 清單中建立專案時發生錯誤。請更正資料，然後再試一次。",
    "EventApprovalsEnableLabel": "啟擁護者事件核准",
    "EventApprovedMessage": "擁護者事件已核准。",
    "EventLabel": "事件",
    "EventRejectedMessage": "已拒絕擁護者事件。",
    "EventsApprovalInfoIconTooltipContent": "啟用此選項會要求系統管理員核准由擁護者提交的事件。事件的點數只會在核准後頒發。",
    "EventsListLabel": "事件清單",
    "EventsListToolTip": "正在存取事件清單",
    "EventsSelectedLabel": "已選取事件。",
    "EventsSubmissionSuccessMessage": "已成功記錄事件。",
    "EventsSubmitMessage": "當您完成新增事件時，請按一下 [提交] 按鈕以儲存。",
    "EventsTrackListLabel": "事件追蹤清單",
    "EventSubmissionPendingMessage": "已提交要核准的事件。一旦事件核准後，就可獲得點數。",
    "EventTrackListToolTip": "正在存取事件追蹤清單",
    "EventTypeGridLabel": "類型",
    "EventTypeGridLabelPlaceHolder": "選取事件種類",
    "EventTypeLabel": "活動類型",
    "EventTypeValidationMessage": "請選取事件類型!",
    "FeedbackToolTip": "意見反應",
    "FirstNameLabel": "名字",
    "FocusAreaGridHeader": "焦點區域",
    "FocusAreaLabel": "焦點區域",
    "FocusAreaPlaceholder": "選取焦點區域",
    "FormSavingMessage": "正在儲存您的詳細資料。...",
    "GetStartedLabel": "開始",
    "GroupGridHeader": "群組",
    "GroupPlaceholder": "選取群組",
    "HowtoGetDigitalBadgeText": "如何取得擁護者徽章",
    "ImportRule1": "請勿修改範本中的資料行標頭",
    "ImportRule2": "不要刪除範本中的欄",
    "ImportRule3": "在範本中提及的所有必要 (*) 欄位中輸入資料",
    "ImportRule4": "遵循每個欄範本中所提及的字元限制和類型",
    "ImportRule5": "根據提供的範例資料，在每張工作表中只輸入 1 個競賽的資料",
    "ImportRule6": "一次只能建立 10 場競賽",
    "ImportRule7": "請確認競賽名稱獨一無二",
    "ImportSpinnerMessage": "正在建立競賽.....",
    "LastNameLabel": "姓氏",
    "LatestVersionLabel": "最新版本:",
    "LoadingSpinnerLabel": "正在載入...",
    "LogMsgBlankSheet": "已略過，因為它是空白。",
    "LogMsgDone": "競賽",
    "LogMsgDone1": "已建立。",
    "LogMsgInvalidTemplate": "已略過，因為它不是有效的範本。",
    "LogMsgInvalidTournamentName": "已略過，因為它沒有有效的競賽名稱。",
    "LogMsgMultipleTournaments": "已略過，因為它有一個以上的競賽名稱。",
    "LogMsgTournamentExists": "已略過，因為競賽",
    "LogMsgTournamentExists1": "已經存在。",
    "LogProgress": "以下是進度:",
    "M365ChampionCommunityLinkLabel": "Microsoft 365 擁護者社群",
    "ManageAdminsLabel": "管理系統管理員",
    "ManageAdminsToolTip": "正在存取管理員清單",
    "ManageAppLogoLabel": "管理應用程式標誌",
    "ManageAppLogoToolTip": "管理應用程式標誌",
    "ManageConfigSettingsLabel": "管理組態設定",
    "ManageDigitalBadgesLabel": "管理數位徽章",
    "ManageDigitalBadgesToolTip": "管理數位徽章",
    "ManageToTLabel1": "一次可以開始多項競賽。請參閱下方，瞭解目前進行中的競賽、完成競賽的能力，以及開始新競賽的功能。",
    "ManageToTLabel2": "一旦競賽開始並完成之後，將無法再次開始；不過，如果您想要完成類似的競賽，可以使用相同的動作來建立新競賽!",
    "ManageTournamentActionsLabel": "管理競賽動作",
    "ManageTournamentActionsToolTip": "正在存取競賽動作清單",
    "ManageTournamentsLabel": "管理競賽",
    "ManageTournamentsPageTitle": "管理競賽",
    "MeetupBody": "設定稍後再討論您的擁護者區域並深入瞭解!",
    "MeetupSubject": "1:1 (擁護者要求)",
    "MonthAndDateLabel": "月份與日期",
    "MoreInfoToolTip": "其他資訊",
    "MSAdoptionHubLinkLabel": "Microsoft 採用中樞",
    "MultipleBadgeMessage": "從下列清單選取徽章。選取的徽章將套用至您的個人資料圖片。",
    "MultipleTournamentLabel": "多場競賽",
    "MultiTournamentStep": "步驟",
    "MultiTournamentStep1LinkLabel": "下載範本",
    "MultiTournamentStep1Text": "的範例檔案格式",
    "MultiTournamentStep2": "依下列指導方針將競賽詳細資料新增至檔案",
    "MultiTournamentStep3": "上傳檔案",
    "MyDashboardInfoIconMessage": "尋找這個動作的其他資訊",
    "MyRankLabel": "我的排名",
    "MyTournamentsLabel": "我的競賽",
    "MyTournamentsTooltip": "您已參與的進行中競賽",
    "NameLabel": "名稱",
    "NearMePlaceHolder": "在我附近選取",
    "NoActiveParticipantsErrorMessage": "目前沒有作用中的參與者。成為第一個參與活動並從下列來源記錄活動的人 ",
    "NoActiveParticipantsMessage": "目前沒有任何作用中的參與者。成為第一個從 [我的儀表板] 參與並記錄活動的人!",
    "NoActiveTournamentMessage": "目前沒有進行中的競賽。請稍後再回來查看。",
    "NoActivitiesinGridLabel": "找不到任何活動!",
    "NoBadgeMessage": "找不到可供您選取的徽章。請洽詢您的應用程式管理員。",
    "NoButton": "否",
    "NoChampionsMessage": "目前沒有擱置的要求",
    "NoCompletedTournamentsMessage": "目前沒有完成的競賽。請稍後再回來查看。",
    "NominateMemberLabel": "提名成員",
    "NominateMemberPageTitle": "提名成員",
    "NoPendingEventsLabel": "目前沒有擱置中事件。",
    "NoProfileImageAlt": "人員的剪影，表示目前沒有設定檔影像套用到您的帳戶",
    "NoProfileImageDescription": "如果您已經將圖片與您的個人資料建立關聯，但您仍然看到此訊息，您的圖片可能還無法使用。請稍後再試一次，如果 24 小時之後仍未顯示，請連絡 <a class='constAnchor' href='https://microsoft.service-now.com/' target='_blank' aria-description='Open the Outlook web application in a new browser tab or window'>服務台</a>。",
    "NoRecordsIcon": "沒有記錄圖示",
    "NoRecordsinGridLabel": "找不到記錄!",
    "NoSearchResults": "沒有任何結果符合您的搜尋。",
    "NotesLabel": "記事",
    "NotesPlaceholder": "最多 200 個字元",
    "NoTournamentMessage": "找不到任何競賽。請稍後再回來查看。",
    "NotQualifiedPreAcceptDisclaimer": "<span style='font-weight:bold;'>歡迎使用數位徽章公用程式</span>。作為您擁護者計畫的成員資格的一部分，您可獲得數位徽章! 此公用程式可讓您藉由「宣告」<em></em>的方式，將數位徽章重疊於現有的個人資料圖片上。請注意，這將會更新您所有 Microsoft 365 產品 (Exchange、Teams、SharePoint 等) 中的個人資料圖片。",
    "OrLabel": "或",
    "OverviewLabel": "我們的概觀與資訊",
    "ParticipantsDetailsLabel": "參與者詳細資料",
    "ParticipantsLabel": "參與者",
    "ParticipantsStatusLabel": "參與者狀態",
    "PendingActionsLabel": "待完成動作",
    "PendingActionsSuccessMessage": "此競賽沒有其他擱置中的動作。",
    "PendingEventsSearchboxPlaceholder": "依擁護者/郵件搜尋",
    "PeopleNameGridHeader": "成員名稱",
    "PeoplePickerPlaceholder": "若要新增成員，請輸入成員名稱",
    "PercentageTournamentCompletedLabel": "% 競賽已完成",
    "PivotHeaderBySpeciality": "根據專案",
    "PivotHeaderGlobal": "全域",
    "PivotHeaderNearMe": "在我附近",
    "PointsLabel": "點數",
    "PreAcceptDisclaimer": "<span style='font-weight:bold;'>歡迎使用數位徽章公用程式</span> <br/><br/><span>作為您擁護者計畫的成員資格的一部分，您已獲得數位徽章! 此公用程式可讓您藉由「宣告」<em></em>的方式，將數位徽章重疊於現有的個人資料圖片上。<br/><br/> 請注意，這將會更新您所有 Microsoft 365 產品 (Exchange、Teams、SharePoint 等) 中的個人資料圖片。</span>",
    "PreAcceptDisclaimer2": "如有需要，<span style='font-weight:bold;'>您將有機會「儲存」您現有的個人資料圖片複本</span>而不會在後續步驟中重迭數位徽章。請按一下 [接受] 以繼續 (您可能會看到快顯視窗開啟，並提示您) 登入。",
    "PreAcceptPageTitle": "領取您的數位徽章!",
    "PreApplyDisclaimer": "這是新個人資料圖片的預覽，包括數位徽章。若要在套用數位徽章前下載現有的個人資料圖片，請按一下 [<strong>下載您目前的設定檔影像</strong>] 連結。<br />",
    "PreApplyDisclaimer1": "<br />按一下 [套用影像] 將會使用此新影像更新您的 Microsoft 365 設定檔圖片。<strong>請注意，這將會更新您在所有 Microsoft 365 的個人資料圖片，而且無法透過此頁面</strong>還原 <br/><br/>如果您想要變更圖片，您可以使用 <a class='constAnchor' href='https://outlook.office365.com/owa/' target='_blank' aria-label='Open the Outlook web application in a new browser tab or window'> Outlook Web 應用程式</a>。",
    "ProcessingSpinnerLabel": "處理中...",
    "ProfileImageAlt": "我的設定檔使用於 O365、Teams 等的影像",
    "PropertyPaneDescription": "描述",
    "QuickLinksLabel": "快速連結",
    "RankLabel": "排名",
    "RecordEventLabel": "記錄事件",
    "RecordsNotFound": "找不到記錄",
    "RefreshIconInfoText": "按一下 [重新整理] 以查看最新資料",
    "RegionGridHeader": "地區",
    "RegionLabel": "地區",
    "RegionPlaceholder": "選取區域",
    "RejectButton": "拒絕",
    "RemoveFileLabel": "移除檔案",
    "ReportsDropdownInfoIconText": "只能為已完成的競賽產生報告。",
    "RequestToCallLabel": "請求通話",
    "SaveButton": "儲存",
    "SearchActiveTournaments": "搜尋進行中的競賽",
    "SearchLabel": "搜尋",
    "SearchPendingTournaments": "搜尋競賽以開始",
    "SearchPlaceholder": "依參與者名稱搜尋",
    "SelectActionsErrorMessage": "請至少選取一個動作以繼續。",
    "SelectAll": "選取所有擁護者",
    "SelectAllEvents": "選取所有活動",
    "SelectAllLabel": "全選",
    "SelectChampion": "選取擁護者",
    "SelectDate": "選取日期",
    "SelectEndTournamentMessage": "選取要完成的競賽。",
    "SelectEvent": "選取事件",
    "SelectTeamsActionsLabel": "選取 Teams 動作:",
    "SelectTournamentMessage": "至少選取一個競賽以開始。",
    "SelectTournamentPlaceHolder": "選取競賽",
    "ShowMoreLabel": "顯示更多",
    "SingleTournamentLabel": "單一競賽",
    "SpinnerListCreationMessage": "正在設定團隊競賽...",
    "StartTournamentButton": "開始競賽",
    "StartTournamentDialogMessage": "您確定要開始新的競賽嗎?",
    "StartTournamentHeaderLabel": "開始競賽",
    "StatusGridHeader": "狀態",
    "SubmitButton": "提交",
    "SuccessIcon": "成功圖示",
    "SupportToolTip": "支援",
    "TeamsActionInfoToolTip": "從下列可用的 Teams 動作中選取要包含在新競賽中的動作。若要新增要選擇的競賽動作，請前往 [管理員工具] 中的 [管理競賽動作]。",
    "ToggleLabelForMemberListColumns": "顯示/隱藏成員清單欄位",
    "TooltipContentForMemberListFieldsHeading": "在適用的地方顯示/隱藏應用程式所有元件的成員清單欄位。",
    "Top5ParticipantswithPointsLabel": "前 5 位有點數的參與者",
    "Top5TournamentswithParticipantsLabel": "有參與者的前 5 場競賽",
    "TopChampionsLabel": "熱門擁護者",
    "TotalActivitiesLabel": "活動總數",
    "TotalParticipantsLabel": "參與者總計",
    "TotalPercentageCompletionLabel": "總完成百分比的",
    "TotalPointsLabel": "總點數",
    "TOTBreadcrumbLabel": "團隊競賽",
    "TOTLabel": "團隊競賽",
    "TOTLeaderBoardPageTitle": "排行榜",
    "TOTMyDashboardPageTitle": "我的儀表板",
    "TournamentDescPlaceHolderLabel": "競賽描述: (最多 500 個字元)",
    "TournamentDescriptionLabel": "競賽說明",
    "TournamentLabel": "競賽",
    "TournamentNameErrorLabel": "競賽名稱是必要資訊。",
    "TournamentNameLabel": "競賽名稱",
    "TournamentNamePlaceHolderLabel": "競賽名稱 (最多 255 個字元)",
    "TournamentRankLabel": "競賽排名",
    "TournamentReportsPageTitle": "競賽報告",
    "UnauthorizedText": "您目前不符合擁護者徽章計畫的資格",
    "UploadFileButton": "上傳檔案",
    "UserAddedMessage": "已成功新增使用者!",
    "UserExistingMessage": "使用者已經是擁護者!",
    "UserLabel": "使用者",
    "UserNominatedMessage": "已成功提名使用者!",
    "ViewActivitiesLabel": "查看活動",
    "ViewDashBoardLabel": "檢視 [儀表板]",
    "VisitLabel": "請造訪 [擁護者管理平台] 頁面以深入瞭解:",
    "WelcomeLabel": "歡迎",
    "YesButton": "是",
  }
});